/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import ArkLib.Data.CodingTheory.GMMDS.LovettCoordMerge
import ArkLib.Data.CodingTheory.GMMDS.LovettMergeIdentity
import ArkLib.Data.CodingTheory.GMMDS.LovettUnion
import ArkLib.Data.CodingTheory.GMMDS.LovettLemma25

/-!
# Lovett's GM-MDS proof: the merge-branch assembly (#389)

This file assembles the coordinate-merge construction (`LovettCoordMerge`) and the merge
substitution collapse identity (`LovettMergeIdentity`) towards the merge branch of Lovett's
Lemma 2.5 (arXiv:1803.02523, p.9).

## The two cleanly-discharged facts

* `collapseVec_vAbs` — the *in-place* collapse `collapseVec j v` (over `Fin n`, used by the
  substitution `substVarP`) preserves total weight: `|collapseVec j v| = |v|`, **provided** the
  merge candidate zeros `j` and `last` (`v(j) = v(last) = 0` for the candidate vector), or more
  generally always: relocating `v(last)` onto `j` and zeroing `last` keeps the sum.
* `mergeVec_vAbs_eq_collapseVec_vAbs` — the two merge encodings (the `Fin (n−1)`-side `mergeVec`
  and the `Fin n`-side `collapseVec`) carry the **same weight**, so the family block sizes
  `k − |vᵢ|` agree between `V` and the merged system; the merge does not change the induction
  measure `d` per block.

## The remaining residual

The full merge contradiction additionally needs two ingredients **not** discharged here:

1. the reindexing algebra-isomorphism `MvPolynomial (Fin (n−1)) F ≃ₐ[F] R'` onto the subalgebra
   generated by `{a_c : c ≠ last}`, transporting `pFamUnion (mergeSys j V) k` (over `Fin (n−1)`,
   independent by the `n−1` IH `IHn`) to the `substVarP`-image of `pFamUnion V k` (over `Fin n`);
2. the **common-factor-free dependence minimization** (minimize total degree of the dependence
   coefficients; any shared `(a_j − a_last)` factor divides out — `sub_X_dvd_of_subst_eq_zero` —
   contradicting minimality).

These are isolated as the precise, machine-checked-satisfiable residual `MergeContradiction`
below; everything else needed (the construction, weight preservation, the collapse identity, the
divisibility kernel) is landed and axiom-clean.

Issue #389.
-/

open Finset Polynomial

namespace ArkLib.GMMDS

variable {F : Type*} [Field F] {n m : ℕ}

/-- **The in-place collapse preserves total weight.**  `|collapseVec j v| = |v|` whenever
`j ≠ last`: the value `v(last)` is relocated onto coordinate `j` and `last` is zeroed; the total
is unchanged. -/
theorem collapseVec_vAbs {n : ℕ} (hn : 1 ≤ n) (j : Fin n) (hjl : j ≠ lastCoord n hn)
    (v : Fin n → ℕ) :
    vAbs (collapseVec hn j v) = vAbs v := by
  classical
  set l := lastCoord n hn with hldef
  unfold vAbs collapseVec
  -- split off {j, l}
  have hsub : ({j, l} : Finset (Fin n)) ⊆ Finset.univ := Finset.subset_univ _
  rw [← Finset.sum_sdiff hsub, ← Finset.sum_sdiff (f := v) hsub]
  congr 1
  · -- complement: each term equals v c
    apply Finset.sum_congr rfl
    intro c hc
    rw [Finset.mem_sdiff, Finset.mem_insert, Finset.mem_singleton] at hc
    obtain ⟨-, hc2⟩ := hc
    push_neg at hc2
    obtain ⟨hcj, hcl⟩ := hc2
    rw [if_neg (hldef ▸ hcl), if_neg hcj]
  · -- on {j, l}: (v j + v l) + 0 = v j + v l
    rw [Finset.sum_pair hjl, Finset.sum_pair hjl]
    rw [if_neg hjl, if_pos rfl, if_pos rfl, add_zero]

/-- **The two merge encodings carry the same weight.**  The `Fin (n−1)`-side `mergeVec` and the
`Fin n`-side `collapseVec` agree on total weight (both equal `|v|`), for `n ≥ 2` and an interior
`j < n−1`.  Hence the per-block sizes `k − |vᵢ|` agree between `V` and the merged system. -/
theorem mergeVec_vAbs_eq_collapseVec_vAbs {n : ℕ} (hn2 : 2 ≤ n) (j : Fin n)
    (hjlt : (j : ℕ) < n - 1) (v : Fin n → ℕ) :
    vAbs (mergeVec (by omega : 1 ≤ n) j v)
      = vAbs (collapseVec (by omega : 1 ≤ n) j v) := by
  have hjl : j ≠ lastCoord n (by omega) := by
    intro h; rw [h] at hjlt; simp only [lastCoord] at hjlt; omega
  rw [mergeVec_vAbs hn2 j hjlt, collapseVec_vAbs (by omega) j hjl]

/-- **The merged system is again `V*(k)` on the cleanly-provable clauses.**  `mergeSys` preserves
weight bound (i) and shape (iii); clause (ii) is the content of `MergeContradiction`'s residual
(it needs Lovett's Lemma 2.4 tight-classification).  This records the two automatic clauses. -/
theorem mergeSys_weight_shape {n m : ℕ} (hn2 : 2 ≤ n) (j : Fin n) (hjlt : (j : ℕ) < n - 1)
    {V : Fin m → (Fin n → ℕ)} {k : ℕ} (hV : IsVStar V k) :
    (∀ i, vAbs (mergeSys (by omega : 1 ≤ n) j V i) ≤ k - 1) ∧
      (∀ i, ∀ t : Fin (n - 1), (t : ℕ) < (n - 1) - 1 →
        mergeSys (by omega : 1 ≤ n) j V i t ≤ 1) := by
  refine ⟨?_, ?_⟩
  · intro i
    rw [mergeSys, mergeVec_vAbs hn2 j hjlt]
    exact hV.weight_le i
  · intro i t ht
    exact mergeVec_shape hn2 j hjlt (V i) (fun l hl => hV.shape i l hl) t ht

/-- **The merge-branch contradiction residual.**  The remaining mathematical content of the merge
branch of Lovett's Lemma 2.5, after the construction (`mergeSys`), weight preservation
(`mergeVec_vAbs`), shape preservation (`mergeVec_shape`), and the collapse identity
(`substVarP_pVanish`) are all in hand:

given a primitive `V*(k)` system with a merge candidate `(i*, j*)` and both minimal-counterexample
IHs, the witness `(1,…,1,0)` exists.

This is what remains to discharge to obtain the unconditional `MergeBranchImpossible` (hence full
`LovettThm17`).  Its two genuine sub-ingredients are (1) the `MvPolynomial (Fin (n−1)) ≅ subring`
reindexing isomorphism transporting the `n−1`-IH independence of `mergeSys` to the `substVarP`
image, and (2) the common-factor-free dependence minimization closed by `sub_X_dvd_of_subst_eq_zero`.

It is **definitionally equal** to `MergeBranchImpossible`; recording it here documents the precise
residual and lets the assembled substrate be checked against it. -/
def MergeContradiction (F : Type*) [Field F] : Prop := MergeBranchImpossible F

/-- `MergeContradiction` is interchangeable with `MergeBranchImpossible` (definitional). -/
theorem mergeBranchImpossible_iff_mergeContradiction :
    MergeContradiction F ↔ MergeBranchImpossible F := Iff.rfl

/-- **Non-vacuity** of `MergeContradiction`'s conclusion (it is satisfiable, not contradictory):
on the concrete `LovettWitnessCounterexample` system the witness is present, exactly as for
`MergeBranchImpossible` (`mergeBranchImpossible_conclusion_cexV`). -/
theorem mergeContradiction_conclusion_cexV
    (i : Fin 2) (j : Fin 2) (hjlt : (j : ℕ) < 2 - 1)
    (hj0 : cexV i j = 0) (hlast : cexV i (lastCoord 2 (by norm_num)) = 0) :
    ∃ i₀, cexV i₀ = oneVec 2 (by norm_num) :=
  mergeBranchImpossible_conclusion_cexV i j hjlt hj0 hlast

end ArkLib.GMMDS

-- Axiom audit (expected: propext, Classical.choice, Quot.sound only)
#print axioms ArkLib.GMMDS.collapseVec_vAbs
#print axioms ArkLib.GMMDS.mergeVec_vAbs_eq_collapseVec_vAbs
#print axioms ArkLib.GMMDS.mergeSys_weight_shape
#print axioms ArkLib.GMMDS.mergeContradiction_conclusion_cexV
