/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import ArkLib.Data.CodingTheory.GMMDS.LovettMeetReplace
import ArkLib.Data.CodingTheory.GMMDS.LovettPolynomial
import ArkLib.Data.CodingTheory.GMMDS.LovettUnion

/-!
# Lovett's GM-MDS proof: the algebraic finish of Lemma 2.4 (#389)

The combinatorial layer of Lovett's Lemma 2.4 (arXiv:1803.02523, p.8) is fully discharged in
[[LovettMeetReplace]]: given a `V*(k)` system `V` and a **tight** index set `I` with `1 < |I| < m`,
the meet-replacement system `replaceMeetFin V I hI` is again `V*(k)`
(`replaceMeetFin_isVStar`), has the **same** induction measure `d` (`lovettD_replaceMeet`) and
**fewer** vectors (`replaceMeet_card`), so the master frame's `m`-induction hypothesis applies and
gives `P(k, V')` linearly independent.

This file records the **load-bearing divisibility fact** for the remaining algebraic finish — that
the meet vanishing polynomial divides every member's vanishing polynomial — and states the precise
residual that closes Lemma 2.4 (the equal-span / equal-cardinality transfer over `F(a)`).

## The divisibility direction (verified)

`v_I = ⋀_{i∈I} vᵢ ≤ vᵢ` coordinate-wise (`vMeet_le_mem`), hence `pVanish v_I ∣ pVanish vᵢ`
(`pVanish_dvd_of_le`).  This is exactly the direction Lovett uses: every `I`-block family element
`pFam vᵢ e` is a multiple of `pVanish v_I`, so it lies in the span of the single meet block
`{pVanish v_I · xᵉ}` — the inclusion that, together with equal cardinality and the `m`-IH
independence of `P(k, V')`, forces span equality and hence `P(k, V)` independent.

Issue #389.
-/

open Polynomial Finset

namespace ArkLib.GMMDS

variable {F : Type*} [Field F] {n : ℕ}

/-- **Coordinate-wise domination lifts to divisibility of vanishing polynomials.**  If `v ≤ w`
coordinate-wise, then `pVanish v ∣ pVanish w` (each factor `(x − aⱼ)^{v j}` divides
`(x − aⱼ)^{w j}`). -/
theorem pVanish_dvd_of_le {v w : Fin n → ℕ} (hle : ∀ j, v j ≤ w j) :
    pVanish (F := F) v ∣ pVanish (F := F) w := by
  classical
  rw [pVanish, pVanish]
  exact Finset.prod_dvd_prod_of_dvd _ _ (fun j _ => pow_dvd_pow _ (hle j))

/-- **The meet vanishing polynomial divides each member's vanishing polynomial.**  For the tight
meet-replacement of Lemma 2.4: `pVanish (⋀_{i∈I} vᵢ) ∣ pVanish vᵢ` for every `i ∈ I`. -/
theorem pVanish_vMeet_dvd_mem {m : ℕ} {V : Fin m → (Fin n → ℕ)} {I : Finset (Fin m)}
    (hI : I.Nonempty) {i : Fin m} (hi : i ∈ I) :
    pVanish (F := F) (vMeet V I hI) ∣ pVanish (F := F) (V i) :=
  pVanish_dvd_of_le (fun l => vMeet_le_mem hI hi l)

/-- **The meet vanishing polynomial divides each `I`-block family element.**  Hence every
`I`-block element `pFam vᵢ e` lies in the principal ideal generated by `pVanish v_I` — the
inclusion underlying the span equality of Lemma 2.4. -/
theorem pVanish_vMeet_dvd_pFam_mem {m : ℕ} {V : Fin m → (Fin n → ℕ)} {I : Finset (Fin m)}
    (hI : I.Nonempty) {i : Fin m} (hi : i ∈ I) (e : ℕ) :
    pVanish (F := F) (vMeet V I hI) ∣ pFam (F := F) (V i) e := by
  unfold pFam
  exact Dvd.dvd.mul_right (pVanish_vMeet_dvd_mem hI hi) _

/-! ## The independence of the meet-replacement system from the `m`-IH

Everything Lovett's Lemma 2.4 needs *except* the final equal-span transfer is now in place.  The
following lemma packages the application of the master frame's `m`-induction hypothesis to the
meet-replacement system: under tightness it has equal measure `d` and strictly fewer vectors, so
the `m`-IH directly yields its independence. -/

/-- **The meet-replacement system is independent, from the `m`-IH.**  For a tight `I` with
`|I| > 1`, the `m`-induction hypothesis (equal measure `d`, fewer vectors) applies to
`replaceMeetFin V I hI`, giving `P(k, V')` linearly independent. -/
theorem lovettHolds_replaceMeetFin {m : ℕ} {V : Fin m → (Fin n → ℕ)} {k : ℕ}
    {I : Finset (Fin m)} (hI : I.Nonempty) (hk : 1 ≤ k) (hV : IsVStar V k)
    (htight : tightConstraint V k I hI) (hIcard : 1 < I.card)
    (IHm : ∀ {m' : ℕ} (V' : Fin m' → (Fin n → ℕ)),
      lovettD V' k = lovettD V k → m' < m → IsVStar V' k → LovettHolds F V' k) :
    LovettHolds F (replaceMeetFin V I hI) k := by
  have hcard : (m - I.card) + 1 < m := by
    have hle : I.card ≤ m := by
      have := Finset.card_le_univ I; simpa [Fintype.card_fin] using this
    omega
  exact IHm (replaceMeetFin V I hI)
    (lovettD_replaceMeet hI htight) hcard
    (replaceMeetFin_isVStar hI hk hV htight)

/-- **The equal-span transfer residual of Lemma 2.4** (the algebraic finish, paper p.8–9).

After the combinatorial layer (`replaceMeetFin_isVStar`, `lovettD_replaceMeet`) and the `m`-IH
independence of the replacement system (`lovettHolds_replaceMeetFin`), the only remaining content
of Lemma 2.4 is the **basis-counting transfer**: `P(k,V)` and `P(k,V')` span the same `F(a)`-space
(every `I`-block element is a `pVanish v_I`-multiple — `pVanish_vMeet_dvd_pFam_mem` — and the
single meet block spans *all* degree-`<k` multiples of `pVanish v_I`, as in
[[LovettBlockSpan]]), and they have equal cardinality (`lovettD_replaceMeet`), so
`linearIndependent_of_span_eq_card` (over `F(a)` via `linearIndependent_fractionField_iff`)
transfers independence from `V'` to `V`.

This residual is stated as the transfer arrow.  It is TRUE (it is Lovett's argument), and
non-vacuous: its hypothesis is discharged by `lovettHolds_replaceMeetFin`. -/
def Lemma24SpanTransfer (F : Type*) [Field F] : Prop :=
  ∀ {n m : ℕ} (V : Fin m → (Fin n → ℕ)) (k : ℕ) (I : Finset (Fin m)) (hI : I.Nonempty),
    1 ≤ k → IsVStar V k → tightConstraint V k I hI → 1 < I.card → I.card < m →
    LovettHolds F (replaceMeetFin V I hI) k →
    LovettHolds F V k

/-- **Lemma 2.4, modulo the span-transfer residual.**  Given the transfer arrow, a tight
`1 < |I| < m` set makes `V` itself independent (its replacement is independent by the `m`-IH).
This is the exact form consumed by the merge-branch clause-(ii) verification. -/
theorem lovettHolds_of_tight_of_spanTransfer {m : ℕ} {V : Fin m → (Fin n → ℕ)} {k : ℕ}
    {I : Finset (Fin m)} (hI : I.Nonempty) (hk : 1 ≤ k) (hV : IsVStar V k)
    (htight : tightConstraint V k I hI) (hlo : 1 < I.card) (hhi : I.card < m)
    (IHm : ∀ {m' : ℕ} (V' : Fin m' → (Fin n → ℕ)),
      lovettD V' k = lovettD V k → m' < m → IsVStar V' k → LovettHolds F V' k)
    (htransfer : Lemma24SpanTransfer F) :
    LovettHolds F V k :=
  htransfer V k I hI hk hV htight hlo hhi
    (lovettHolds_replaceMeetFin hI hk hV htight hlo IHm)

end ArkLib.GMMDS

-- Axiom audit (expected: propext, Classical.choice, Quot.sound only)
#print axioms ArkLib.GMMDS.pVanish_dvd_of_le
#print axioms ArkLib.GMMDS.pVanish_vMeet_dvd_mem
#print axioms ArkLib.GMMDS.pVanish_vMeet_dvd_pFam_mem
#print axioms ArkLib.GMMDS.lovettHolds_replaceMeetFin
#print axioms ArkLib.GMMDS.lovettHolds_of_tight_of_spanTransfer
