#!/usr/bin/env python3
"""
probe_dsj_worstdir_orbit_groundtruth  (#444)

DECISIVE attack on (A5)+(J): is the claimed worst direction (n/4, 5n/8) really
a UNIQUE dilation orbit of size 8 that maximizes the complete-homogeneous (h)
readout, and does evaluating the over-determined far-line incidence ON THAT ONE
ORBIT (cheap: orbit size 8, even at n=128) reproduce the GPU fit
    s*(n) = n/2 + 1 - 2*(log2 n - 3)
or does it instead reproduce the PLAIN Johnson agreement n/2 with NO -2*depth
defect (which would refute (D) as a real mechanism and confirm the prior audit
that the defect is a 3-point overfit artifact)?

The prior probes (overfit/robustness/audit) established:
  - the "PERFECT n=8..32" fit is 3 points on a ~3-param model => no predictive power;
  - the -2*depth defect is circular (defect DEFINED as -2(mu-3));
  - delta*->1/2 is automatic for ANY leading-term-n/2 model => not evidence for mech;
  - R3 = open Paley wall.

What is MISSING and what THIS probe adds: an INDEPENDENT, mechanism-driven count.
If (A5) is right, the worst direction is structurally special and we can compute
its incidence directly without C(n,s) exhaustion -- giving a 4th and 5th data
point (n=64,128) that the GPU could NOT reach. That breaks the overfit tie.

MODEL of the over-determined far-line incidence (cyclotomic / char-0 faithful):
  Domain D = mu_n = {zeta^i : i in Z_n}, zeta = exp(2pi i/n), n=2^mu, rho=1/4, k=rho*n.
  A "far line" in direction (a,b) (a,b in Z_n) is the set of evaluation patterns
  whose agreement with a degree-<k codeword is governed by how many domain points
  x satisfy a structural congruence x^a == c * x^b type relation -- equivalently,
  the over-determined incidence I(a,b; s) counts domain points lying on the
  intersection of the far line with the Johnson ball boundary, which in the
  cyclotomic model reduces to counting i in Z_n with
       (a*i mod n, b*i mod n) hitting a fixed residue window of width ~ agreement.
  The h-readout (complete homogeneous) for direction (a,b) is the number of
  i in Z_n such that {a*i mod n} and {b*i mod n} are SIMULTANEOUSLY small
  (in the 2-adic stalling sense). We use the standard surrogate: the incidence
  of (a,b) is the size of the additive-energy support
       supp(a,b) = { i in Z_n : gcd-weighted 2-adic valuation of (a i, b i) high }.

  This surrogate is the SAME one the in-tree LamLeungTwoPower / overdet probes use:
  the worst direction maximizes the count of i with v2(a*i mod n)+v2(b*i mod n)
  large. We compute it EXACTLY (integer arithmetic, char-0) and find the max,
  the argmax direction(s), and the orbit size, then read off the crossing s*.

HONESTY: this is a SURROGATE incidence, not the GPU engine. We state explicitly
whether the surrogate reproduces the fit. If it does NOT reproduce -2*depth, that
is evidence the defect is not intrinsic to the worst-direction mechanism (A5/D).
DO NOT git commit.
"""
import math
from collections import Counter

def v2(x):
    """2-adic valuation of nonzero residue; v2(0)=infinity-ish -> return large."""
    if x == 0:
        return 99
    v = 0
    while x % 2 == 0:
        x //= 2; v += 1
    return v

def overdet_incidence(n, a, b):
    """
    Char-0 EXACT surrogate for over-determined far-line incidence in direction (a,b)
    on mu_n. Count weighted by simultaneous 2-adic alignment of (a*i, b*i) mod n.
    Returns the agreement count = #{i in Z_n : a*i and b*i both lie in the
    2-power-aligned coset}, i.e. the maximal coset-saturation block size.
    We measure the LARGEST block of i for which (a*i mod n, b*i mod n) repeats a
    structural value, which is the genuine over-determined incidence (#domain pts
    on the worst line) per coset-saturation lemma.
    """
    # The over-determined incidence on a line in dir (a,b) = max over residues
    # (r,s) of #{i : a*i = r, b*i = s mod n}. But that is just the size of the
    # kernel of i -> (a*i, b*i), which is n/lcm-structure. To capture the JOHNSON
    # ball (agreement), we instead count i within the agreement window: how many
    # domain points the codeword+line agree on. Use the additive-character energy:
    #   I(a,b) proportional to max_t #{i : a*i ≡ t (mod n) within band}.
    # Concretely the saturation block in direction (a,b) is n / |<a,b>| where
    # <a,b> is the subgroup of Z_n generated by gcd(a,b,n)... we compute the
    # actual fiber sizes.
    fibers = Counter()
    for i in range(n):
        fibers[((a*i) % n, (b*i) % n)] += 1
    return max(fibers.values())

def h_readout(n, a, b):
    """Complete-homogeneous readout strength: sum over i of 2-adic alignment of
    a*i and b*i. Larger = direction stalls more on the 2-adic locus."""
    tot = 0
    for i in range(1, n):
        tot += min(v2((a*i) % n) if (a*i) % n else 99,
                   v2((b*i) % n) if (b*i) % n else 99)
    return tot

def fit_sstar(n):
    mu = int(round(math.log2(n)))
    return n//2 + 1 - 2*(mu - 3)

print("="*86)
print("PART 1: Is (n/4, 5n/8) the UNIQUE h-readout maximizer, orbit size 8? (A5 test)")
print("="*86)
print(f"{'n':>5} {'claimed dir':>14} {'h(claimed)':>11} {'h_max':>7} {'#argmax':>8} "
      f"{'claimed is max?':>16}")
for mu in range(3, 8):
    n = 2**mu
    a0, b0 = n//4, (5*n)//8
    # 5n/8 integer only when n divisible by 8 -> n>=8 ok
    hc = h_readout(n, a0, b0)
    best = -1; argmax = []
    for a in range(n):
        for b in range(n):
            h = h_readout(n, a, b)
            if h > best:
                best = h; argmax = [(a,b)]
            elif h == best:
                argmax.append((a,b))
    is_max = (best == hc)
    print(f"{n:>5} {f'({a0},{b0})':>14} {hc:>11} {best:>7} {len(argmax):>8} {str(is_max):>16}")

print()
print("="*86)
print("PART 2: over-det incidence on claimed worst dir vs budget n; crossing vs fit s*")
print("="*86)
print(f"{'n':>5} {'I(n/4,5n/8)':>12} {'budget n':>9} {'I/n':>7} {'fit s*':>7} "
      f"{'johnson n/2':>11}")
for mu in range(3, 9):
    n = 2**mu
    a0, b0 = n//4, (5*n)//8
    I = overdet_incidence(n, a0, b0)
    print(f"{n:>5} {I:>12} {n:>9} {I/n:>7.3f} {fit_sstar(n):>7} {n//2:>11}")

print()
print("="*86)
print("PART 3: orbit size of (n/4,5n/8) under dilation i->c*i (units of Z_n)")
print("="*86)
print(f"{'n':>5} {'dilation-orbit size':>20} {'claimed=8?':>11}")
for mu in range(3, 9):
    n = 2**mu
    a0, b0 = n//4, (5*n)//8
    orbit = set()
    for c in range(1, n):
        if math.gcd(c, n) == 1:
            orbit.add(((a0*c) % n, (b0*c) % n))
    print(f"{n:>5} {len(orbit):>20} {str(len(orbit)==8):>11}")

print()
print("="*86)
print("VERDICT")
print("="*86)
print("Read off above: (i) does the claimed dir maximize the h-readout uniquely up")
print("to an orbit of size 8?  (ii) does the over-det incidence on it cross budget n")
print("at the fit s* (=n/2+1-2*depth) or at plain Johnson n/2?  If the surrogate gives")
print("I = n/2 + O(1) with NO depth-growing -2*log2 n term, the surrogate does NOT")
print("encode the defect => the -2*depth is either (a) a true GPU effect this surrogate")
print("misses, or (b) the 3-point overfit artifact the prior audit already flagged.")
print("Either way the burden is GPU n=64/128, which is the unresolved empirical gate.")
