#!/usr/bin/env python3
"""Falsify-first probe for the f-level slice product count (issue #232, O95 capstone).

Lean defs (FoldPolynomialSlices.lean):
  evenSlice f = contract 2 (f + f.comp(-X))        -> coeff i = 2*c_{2i}
  oddSlice  f = contract 2 (divX (f - f.comp(-X))) -> coeff i = 2*c_{2i+1}

Checks (exact integer arithmetic over GF(q), exit 0 iff all pass):
  (i)   slice coefficient law matches the Lean defs;
  (ii)  q in {5,13,17}, k=2m in {2,4,6}: f -> (evenSlice f, oddSlice f) is a
        bijection {deg<2m} -> {deg<m} x {deg<m};
  (iii) sample loci Z, |Z| <= m: #{f deg<2m : both slices vanish on Z} == q^(2m-2|Z|);
  (iv)  union-bound sanity on the order-8 subgroup D of GF(17)^*: every f with
        wt_D(f) <= w has a dead locus Z subset of D^2 with |Z| >= |D^2| - w and both
        slices vanishing on Z, and #{f deg<2m : wt <= w} <= C(|D2|, |D2|-w) * q^(2m-2(|D2|-w)).
"""
import itertools
import math
import sys

FAILS = 0


def fail(msg):
    global FAILS
    FAILS += 1
    print("FAIL:", msg)


def poly_eval(coeffs, x, q):
    acc = 0
    for c in reversed(coeffs):
        acc = (acc * x + c) % q
    return acc


def even_slice(coeffs, q):
    # coeff i of evenSlice = 2*c_{2i}  (contract 2 of f + f(-X))
    return [(2 * coeffs[i]) % q for i in range(0, len(coeffs), 2)]


def odd_slice(coeffs, q):
    # coeff i of oddSlice = 2*c_{2i+1} (contract 2 of divX(f - f(-X)))
    return [(2 * coeffs[i]) % q for i in range(1, len(coeffs), 2)]


def slices_direct(coeffs, q):
    """Compute slices straight from the Lean definitions (poly ops), to cross-check."""
    n = len(coeffs)
    f_negx = [(c * pow(-1, i, q)) % q for i, c in enumerate(coeffs)]
    s = [(coeffs[i] + f_negx[i]) % q for i in range(n)]           # f + f(-X)
    d = [(coeffs[i] - f_negx[i]) % q for i in range(n)]           # f - f(-X)
    dx = d[1:] if len(d) > 1 else []                               # divX
    ev = [s[i] for i in range(0, n, 2)]                            # contract 2
    od = [dx[i] for i in range(0, len(dx), 2)]
    return ev, od


def pad(v, n):
    return list(v) + [0] * (n - len(v))


# ---------- (i) coefficient law ----------
for q in (5, 13, 17):
    for trial_coeffs in itertools.islice(itertools.product(range(q), repeat=5), 0, q ** 5, max(1, q ** 5 // 200)):
        coeffs = list(trial_coeffs)
        ev1, od1 = even_slice(coeffs, q), odd_slice(coeffs, q)
        ev2, od2 = slices_direct(coeffs, q)
        m = max(len(ev1), len(ev2), len(od1), len(od2))
        if pad(ev1, m) != pad(ev2, m) or pad(od1, m) != pad(od2, m):
            fail(f"(i) coeff law mismatch q={q} coeffs={coeffs}: {ev1},{od1} vs {ev2},{od2}")
            break
print("(i) slice coefficient law: OK" if FAILS == 0 else "(i) FAILED")

# ---------- (ii) bijection and (iii) locus counts ----------
for q in (5, 13, 17):
    for m in (1, 2, 3):
        k = 2 * m
        if q ** k > 600000:  # keep exhaustive enumeration tractable
            continue
        seen = {}
        bij_ok = True
        for coeffs in itertools.product(range(q), repeat=k):
            key = (tuple(pad(even_slice(coeffs, q), m)), tuple(pad(odd_slice(coeffs, q), m)))
            if key in seen:
                fail(f"(ii) not injective q={q} m={m}: {coeffs} vs {seen[key]}")
                bij_ok = False
                break
            seen[key] = coeffs
        if bij_ok and len(seen) != q ** k:
            fail(f"(ii) not surjective q={q} m={m}: image size {len(seen)} != {q ** k}")
        if bij_ok:
            # surjectivity: image size q^k = (q^m)^2 = |target| forces onto
            pass

        # (iii) loci: subsets of small point sets, |Z| <= m
        pts = list(range(min(q, 4)))
        for zsize in range(0, m + 1):
            for Z in itertools.combinations(pts, zsize):
                count = 0
                for coeffs in itertools.product(range(q), repeat=k):
                    ev, od = even_slice(coeffs, q), odd_slice(coeffs, q)
                    if all(poly_eval(ev, z, q) == 0 for z in Z) and \
                       all(poly_eval(od, z, q) == 0 for z in Z):
                        count += 1
                want = q ** (k - 2 * zsize)
                if count != want:
                    fail(f"(iii) q={q} m={m} Z={Z}: count {count} != {want}")
print("(ii)+(iii) bijection and locus counts: OK" if FAILS == 0 else "(ii)/(iii) FAILED")

# ---------- (iv) union-bound sanity over GF(17), order-8 subgroup ----------
q = 17
g = 3  # generator of GF(17)^*; order-8 subgroup generated by g^2 = 9
D = sorted({pow(9, i, q) for i in range(8)})
assert len(D) == 8 and all((q - x) % q in D for x in D) and 0 not in D
D2 = sorted({(x * x) % q for x in D})
nD2 = len(D2)  # 4

for m in (2, 3):
    k = 2 * m
    wt_count = {}  # w -> #{f : wt_D(f) <= w}
    for coeffs in itertools.product(range(q), repeat=k):
        wt = sum(1 for x in D if poly_eval(coeffs, x, q) != 0)
        # dead-locus structure check: Z = {y in D2 : both slices vanish at y}
        ev, od = even_slice(coeffs, q), odd_slice(coeffs, q)
        dead = [y for y in D2 if poly_eval(ev, y, q) == 0 and poly_eval(od, y, q) == 0]
        if len(dead) < nD2 - wt:
            fail(f"(iv) structure q=17 m={m} coeffs={coeffs}: |dead|={len(dead)} < {nD2 - wt}")
        for w in range(wt, nD2 + 1):
            wt_count[w] = wt_count.get(w, 0) + 1
    for w in range(0, nD2 + 1):
        z0 = nD2 - w
        if z0 > m:
            continue  # bound only claimed for z0 <= m
        have = wt_count.get(w, 0)
        bound = math.comb(nD2, z0) * q ** (k - 2 * z0)
        if have > bound:
            fail(f"(iv) union bound q=17 m={m} w={w}: {have} > {bound}")
print("(iv) union-bound sanity: OK" if FAILS == 0 else "(iv) FAILED")

print("RESULT:", "ALL CHECKS PASS" if FAILS == 0 else f"{FAILS} FAILURES")
sys.exit(0 if FAILS == 0 else 1)
