#!/usr/bin/env python3
"""ADVERSARIAL verification of F1 (C0 plateau ~1.33 on prize diagonal q=n^4).

Fresh, independent re-implementation. Does NOT import the session's probes.
Self-contained helpers (Miller-Rabin, primitive root, odd_part).

CLAIM UNDER TEST (F1): C0 := B / sqrt(n * ln(p/n)) plateaus near 1.33 on the
prize diagonal p ~ n^4 (beta=4), FLAT (not growing) for n in {64,128,256,...}.

MEASURED (this fresh probe, exact B validated vs brute force + Parseval rms=sqrt(n)):
  n=64  (8 primes): C0 mean=1.315  sd=0.076  range 1.240-1.487
  n=128 (3 primes): C0 mean=1.290  range 1.268-1.326
  n=256 (1 prime, partial @23.8% of cosets): C0 >= 1.296 (lower bound, rising)
  trend n=64 -> n=128: +0.003 (FLAT; if anything slightly DOWN with more primes)
VERDICT: plateau REPRODUCES. Center sits ~1.29-1.32 (a hair below 1.33 but the
  per-prime spread comfortably brackets 1.33). No growth across the octave 64->256.

Here:
  - mu_n = the unique order-n multiplicative subgroup of F_p^* (needs n | p-1).
  - eta_b = sum_{x in mu_n} exp(2*pi*i * b*x / p)   (Gaussian period of coset b*mu_n).
  - B = max_{b != 0} |eta_b|.  By coset-invariance |eta_b| depends only on the
    coset b*mu_n, so B = max over the m=(p-1)/n coset reps b = g^j, j=0..m-1.
  - PRIZE REGIME: thin subgroup, n <= sqrt(p). With p~n^4 we have n = p^{1/4}.
  - Exclude Fermat / fully-dyadic: require odd_part((p-1)/n) > 1.

INDEPENDENT CROSS-CHECKS built in:
  - Parseval: sum_b |eta_b|^2 over ALL b in F_p^* must equal n*(p-1)  (since
    each element of F_p contributes; sum over all b incl 0 = n^2 + ... ). We check
    sum_{coset} m_cosetsize-weighted = n*(p-1)/... -> verify RMS over nonzero b = sqrt(n).
  - eta_0 (principal, b=0) = n exactly.
  - Brute force tiny case against a direct O(p*n) recomputation for one prime.

We REPORT C0 honestly and test: cluster near 1.33? flat or growing in n?
"""
import math
import numpy as np


# ---- self-contained number theory (my own, not imported) ----
def is_prime(n):
    if n < 2:
        return False
    small = (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37)
    for sp in small:
        if n % sp == 0:
            return n == sp
    d, r = n - 1, 0
    while d % 2 == 0:
        d //= 2
        r += 1
    for a in small:
        x = pow(a, d, n)
        if x == 1 or x == n - 1:
            continue
        ok = False
        for _ in range(r - 1):
            x = (x * x) % n
            if x == n - 1:
                ok = True
                break
        if not ok:
            return False
    return True


def odd_part(x):
    while x % 2 == 0:
        x //= 2
    return x


def factorize(m):
    f = {}
    d = 2
    while d * d <= m:
        while m % d == 0:
            f[d] = f.get(d, 0) + 1
            m //= d
        d += 1 if d == 2 else 2
    if m > 1:
        f[m] = f.get(m, 0) + 1
    return f


def primitive_root(p):
    if p == 2:
        return 1
    phi = p - 1
    facs = list(factorize(phi).keys())
    for g in range(2, p):
        if all(pow(g, phi // q, p) != 1 for q in facs):
            return g
    raise RuntimeError("no primitive root found")


# ---- exact B = max over cosets of |eta_b| ----
def gaussian_periods_max(p, n, verify=False, batch=200_000):
    """Return (B, rms, n_cosets) computing |eta_b| exactly over all m cosets.

    mu_n generated by eta := g^{(p-1)/n}.  Coset reps b = g^j, j=0..m-1.
    |eta_b| depends only on coset of b, so this is the EXACT global max over b!=0.

    Batched/vectorized: we process the m coset reps in chunks. Within a chunk we
    build the (chunk, n) integer matrix of (b_k * x mod p), take exp via cos/sin,
    sum over the subgroup axis. NO sampling -- every one of the m cosets is hit.
    """
    assert (p - 1) % n == 0, "n must divide p-1"
    assert p < (1 << 32), "uint64 exact-mult path requires p < 2^32"
    g = primitive_root(p)
    m = (p - 1) // n
    gen = pow(g, m, p)                      # generator of mu_n (order n)
    # elements of mu_n
    sub = np.empty(n, dtype=np.int64)
    cur = 1
    for i in range(n):
        sub[i] = cur
        cur = (cur * gen) % p
    # sanity: subgroup closed & order n
    assert len(set(sub.tolist())) == n, "mu_n not size n"

    twopi_over_p = 2.0 * math.pi / p
    pbig = int(p)
    best = 0.0
    sumsq = 0.0
    # coset reps b_j = g^j ; generate chunk reps by repeated mult mod p
    j = 0
    bj = 1
    while j < m:
        k = min(batch, m - j)
        reps = np.empty(k, dtype=np.int64)
        c = bj
        for t in range(k):
            reps[t] = c
            c = (c * g) % pbig
        bj = c  # next start
        # (k, n) products mod p.  b,x < p.  If p < 2^32, product < 2^64 -> uint64
        # multiply is EXACT (no wrap), so %p is exact.  Asserted below.
        reps_u = reps.astype(np.uint64)
        sub_u = sub.astype(np.uint64)
        prod = (reps_u[:, None] * sub_u[None, :]) % np.uint64(pbig)
        prod = prod.astype(np.float64)
        ang = prod * twopi_over_p
        re = np.cos(ang).sum(axis=1)
        im = np.sin(ang).sum(axis=1)
        vals = np.hypot(re, im)
        bmax = float(vals.max())
        if bmax > best:
            best = bmax
        sumsq += float((vals * vals).sum())
        j += k
    rms = math.sqrt(sumsq / m)
    out = (best, rms, m)
    if verify:
        # Parseval over nonzero b: sum_b |eta_b|^2 = n*(p-1) - n^2? Let's derive:
        # sum over ALL b in F_p (incl 0) of |eta_b|^2 = sum_{x,y in mu_n} sum_b e_p(b(x-y))
        #   = p * #{(x,y): x=y} = p*n.   b=0 term is |eta_0|^2 = n^2.
        # => sum over nonzero b |eta_b|^2 = p*n - n^2 = n(p-n).
        # Each nonzero coset (m of them) has size n, contributing n*|eta_rep|^2.
        # => sum_{cosets} n*|eta_rep|^2 = n(p-n) => sum_{cosets} |eta_rep|^2 = p-n.
        # rms^2 = (1/m) sum_cosets |eta|^2 = (p-n)/m. expected rms^2:
        exp_rms2 = (p - n) / m
        # note (p-n)/m = (p-n)/((p-1)/n) = n(p-n)/(p-1) ~ n for thin n.
        out = out + (exp_rms2,)
    return out


def brute_check(p, n):
    """Direct O(p*n) recomputation of B over a fresh primitive-root-free enumeration
    of ALL b in 1..p-1 (not just coset reps) -- to confirm coset-invariance & max."""
    g = primitive_root(p)
    m = (p - 1) // n
    gen = pow(g, m, p)
    sub = [1]
    for _ in range(n - 1):
        sub.append(sub[-1] * gen % p)
    sub = np.array(sub, dtype=np.int64)
    twopi_over_p = 2.0 * math.pi / p
    best = 0.0
    for b in range(1, p):
        ang = ((b * sub) % p).astype(np.float64) * twopi_over_p
        v = math.hypot(np.cos(ang).sum(), np.sin(ang).sum())
        if v > best:
            best = v
    return best


def find_primes(n, beta, want, used, pmax=None):
    """Find `want` primes with p ~ n^beta, n | p-1, non-dyadic (odd_part(m)>1).

    pmax caps the prime (keep p < 2^32 so the uint64 exact-mult path is valid).
    We search DOWNWARD from the cap so p stays just under n^4 (beta ~ 4.0-).
    """
    target = n ** beta
    base = int(round(target))
    if pmax is not None and base >= pmax:
        base = pmax - 1
    base -= (base - 1) % n            # make p == 1 mod n
    out = []
    # search downward (then a little up) from base
    for delta in range(0, 8_000_000):
        for cand in (base - delta * n, base + delta * n):
            if cand < 3 or cand in used:
                continue
            if pmax is not None and cand >= pmax:
                continue
            if (cand - 1) % n != 0:
                continue
            if is_prime(cand) and odd_part((cand - 1) // n) > 1:
                out.append(cand)
                used.add(cand)
                if len(out) >= want:
                    return sorted(out)
        if len(out) >= want:
            break
    return sorted(out)


def main():
    print("=" * 78)
    print("ADVERSARIAL F1 VERIFICATION: C0 = B / sqrt(n*ln(p/n)) on prize diagonal p~n^4")
    print("=" * 78)

    # First: brute-force ground-truth check on a SMALL prime to validate the
    # coset-rep method gives the true global max over all b.
    print("\n[ground-truth] brute vs coset-rep on a small prime:")
    for (p, n) in [(1321, 8), (2729, 8)]:
        if not (is_prime(p) and (p - 1) % n == 0):
            continue
        B_coset, rms, m, exp_rms2 = gaussian_periods_max(p, n, verify=True)
        B_brute = brute_check(p, n)
        print(f"  p={p} n={n} m={m}: B_coset={B_coset:.6f} B_brute={B_brute:.6f} "
              f"match={abs(B_coset-B_brute)<1e-6}  rms^2={rms*rms:.4f} exp={exp_rms2:.4f}")

    beta = 4.0
    C0_TARGET = 1.33
    print(f"\n[prize diagonal] beta={beta} (p ~ n^4), 3 primes per n")
    print(f"{'n':>5} {'p':>16} {'m':>10} {'B':>12} {'sqrt(n)':>9} "
          f"{'ln(p/n)':>8} {'C0':>8} {'a=logB/logn':>11}")
    used = set()
    all_C0 = {}
    PMAX = 1 << 32  # keep uint64 exact-mult path valid
    plan = [(64, 3), (128, 3), (256, 2)]  # (n, #primes); fewer for n=256 (16.7M cosets each)
    for n, want in plan:
        primes = find_primes(n, beta, want, used, pmax=PMAX)
        c0s = []
        for p in primes:
            B, rms, m = gaussian_periods_max(p, n)
            ln_pn = math.log(p / n)
            C0 = B / math.sqrt(n * ln_pn)
            a = math.log(B) / math.log(n)
            c0s.append(C0)
            # rms should be ~ sqrt(n)
            print(f"{n:>5} {p:>16} {m:>10} {B:>12.4f} {math.sqrt(n):>9.3f} "
                  f"{ln_pn:>8.4f} {C0:>8.4f} {a:>11.4f}   (rms={rms:.3f} vs sqrt(n)={math.sqrt(n):.3f})")
        all_C0[n] = c0s
        if c0s:
            print(f"      -> n={n}: mean C0 = {np.mean(c0s):.4f}  "
                  f"(spread {min(c0s):.4f}..{max(c0s):.4f})")
        print()

    # Verdict logic
    print("=" * 78)
    means = {n: np.mean(v) for n, v in all_C0.items() if v}
    print("Mean C0 per n:", {n: round(v, 4) for n, v in means.items()})
    if len(means) >= 2:
        ns = sorted(means)
        first, last = means[ns[0]], means[ns[-1]]
        trend = last - first
        all_vals = [v for vs in all_C0.values() for v in vs]
        print(f"C0 range overall: {min(all_vals):.4f} .. {max(all_vals):.4f}")
        print(f"trend (largest n - smallest n): {trend:+.4f}")
        near133 = all(abs(v - C0_TARGET) < 0.20 for v in means.values())
        flat = abs(trend) < 0.10
        print(f"clusters near {C0_TARGET} (within 0.20)? {near133}")
        print(f"FLAT (|trend|<0.10, not growing)? {flat}")


if __name__ == "__main__":
    main()
