"""
probe_dsj_dyadic_defect_audit  (#444)
Adversarial audit of the GPU-pinned formula s*(n)=n/2+1-2(log2 n-3), rho=1/4.

Claims under test:
  (D/A8) defect = -2*(tower depth), exact integer, per-rung antipodal pair (Lam-Leung).
  (J)    main term n/2 = sqrt(rho)*n re-derives Johnson.
  (A6)   s* STALLS within a dyadic octave (constant between powers of 2).
  (A10)  NOT square-root cancellation; exact Z-lattice count.

We have NO new GPU runs; we test the INTERNAL CONSISTENCY + structural predictions
of the formula against what an antipodal-pair count must satisfy, and against the
Johnson ceiling. This is a refutation-oriented probe.
"""
import math

def s_star(n):
    return n/2 + 1 - 2*(int(math.log2(n)) - 3)

print("=== 1. Data support audit ===")
print("GPU pinned at n in {8,16,32}: mu in {3,4,5} -> THREE points.")
print("Model s*=n/2+1-2(mu-3) is affine in (n, mu) with FIXED slopes => 2 free")
print("params effectively (intercept + mu-slope, n/2 forced). 3 pts, ~2 params:")
print("NOT over-determined in mu. 'over-determined' refers to the incidence linear")
print("system per fixed n, not the n-extrapolation. The n-extrapolation is a GUESS.\n")

print("=== 2. Johnson-ceiling consistency (REFUTATION test) ===")
print("rho=1/4, Johnson list-decoding radius J = 1-sqrt(rho) = 1/2.")
print("delta* = (s*-k)/n + k/n ... actually delta* = 1 - s*/n (agreement->distance).")
print("Check both readings:")
for mu in range(3,12):
    n=2**mu
    ss=s_star(n)
    # agreement s* as #agreeing points; distance fraction = 1 - s*/n
    d_dist = 1 - ss/n
    # prompt's stated delta* formula
    d_prompt = 1/2 - 1/n + 2*(mu-3)/n
    print(f" n={n:5d} s*={ss:6.1f} 1-s*/n={d_dist:.5f}  prompt_delta*={d_prompt:.5f}")
print("NOTE: prompt's delta* = s*/n - ... NO: 1/2-1/n+2(mu-3)/n. Let's see s*/n:")
for mu in range(3,8):
    n=2**mu; ss=s_star(n)
    print(f"  n={n} s*/n={ss/n:.5f}  (=agreement fraction)")
print("So delta*(prompt) = s*/n - epsilon? s*/n for n=16 =7/16=0.4375, prompt=0.5625.")
print("s*/n + something? 0.4375 vs 0.5625 differ by 0.125=2/16. INCONSISTENT labeling.")
print("The prompt's delta* formula is NOT 1-s*/n NOR s*/n. The narrative's algebra")
print("does not close. This alone makes (J)+(D) as stated UNVERIFIABLE from the data.\n")

print("=== 3. Antipodal-pair-count prediction (the falsifiable core of A8/A2) ===")
print("A8: each rung removes exactly ONE antipodal pair = 2 incidences.")
print("Lam-Leung W(2^mu)=evens: minimal vanishing sums of 2-power roots of unity")
print("have even length, generated by {1,-1} (zeta^(2^(mu-1))=-1) negation pairs.")
print("That is a TRUE theorem (Lam-Leung 2000). But it bounds VANISHING SUM length,")
print("NOT the over-determined incidence threshold s*. The link 'one rung = -2 in s*'")
print("is an ASSERTED bijection with no derivation. Test its only check: integrality.")
for mu in range(3,8):
    n=2**mu
    defect = s_star(n) - (n/2+1)   # = -2(mu-3)
    print(f" n={n:4d} defect={defect:+.0f} = -2*(mu-3), mu-3={mu-3} rungs. integer: OK")
print("Integrality holds by construction (defect DEFINED as -2(mu-3)). This is")
print("circular: A8 'predicts' the integer it was fit to. No independent content.\n")

print("=== 4. Is it square-root cancellation in disguise? (A10 test) ===")
print("A10 claims NOT sqrt-cancellation. But the SECOND, deeper band (under-det s=k+1)")
print("IS admittedly BGK/Paley (square-root). The prompt concedes the binding object")
print("near delta* could be the over-det band ONLY IF over-det sits shallower. The GPU")
print("validated at p~n^4, NOT at prize p~2^160. KKH26/Paley wall: at large q the")
print("char-sum band MOVES. So 'under-det stays non-binding at p~2^160' (R3) is")
print("EXACTLY the open Paley Graph Conjecture wall (per CLAUDE.md face 3). UNPROVEN.")
