"""
L1 / #407 count-lane: APPLY the EXACT Dvornicich-Zannier theorem to dyadic roots of unity.

DZ Theorem (Arch. Math. 79 (2002) 104-108), verbatim:
  Assume sum_{i=0}^{k-1} a_i*zeta_i == 0 (mod ell) [in ring of alg. integers, a_i in Z,
  ell prime] is a NORMALIZED relation:
    (i)  zeta_0 = 1
    (ii) no proper subsum is == 0 (mod ell)   [INDECOMPOSABLE mod ell]
  Then the least common order Q of zeta_0,...,zeta_{k-1} is SQUAREFREE and satisfies
    sum_{p|Q} (p-2) <= k-2.                                                    (2)

DYADIC CONSEQUENCE (the L1 claim to verify):
  For zeta_i in mu_n, n=2^mu, the order Q | 2^mu. Squarefree divisors of 2^mu are {1,2}.
    Q=2 => bound (2) is (2-2)=0 <= k-2, i.e. k>=2; the roots lie in mu_2 = {+-1}.
    Q=1 => all roots equal 1 (the trivial subgroup).
  So EVERY indecomposable vanishing congruence of 2^mu-th roots of unity mod p
  has its roots (after normalizing zeta_0=1) of order dividing 2, i.e. is a +-1 relation.

  => A char-p vanishing 0/1-sum  sum_{y in Y} y == 0 (mod p), Y subset mu_n,
     DECOMPOSES mod p into indecomposable pieces, EACH of which is (after scaling)
     a +-1 relation, i.e. EACH piece is supported on a single mu_2-coset {z, -z}
     and is the relation z + (-z) == 0 ... OR a piece whose roots, scaled by z^{-1},
     lie in {+-1} -- i.e. of the form  sum (with signs) of {z,-z}.

  Concretely: the DZ structure theorem says the indecomposable mod-p vanishing
  relations of 2^mu-th roots are EXACTLY the char-0 ones (z + (-z) = 0), because the
  ORDER is forced to {1,2} -- the SAME structure as Lam-Leung over C.

  This is the OFF-WALL closure: it does NOT bound the prime ell; instead it forces the
  STRUCTURE (every indecomposable mod-p relation = a +-pair), so an ANTIPODAL-FREE Y
  (no +-pairs) admits NO indecomposable subrelation => its vanishing sum cannot occur
  at all (mod any prime p with p prime, char != 2) UNLESS Y is empty.

  THE ONLY GAP: DZ requires a_i in Z (integer coefficients), and the order Q is the
  *least common order* -- after normalization zeta_0=1 the residual roots zeta_i/zeta_0
  have order dividing 2^mu still. The decomposition is mod-p (in alg integers / a prime
  above p). We TEST the structural claim directly: does every char-p antipodal-free
  vanishing 0/1-sum of 2^mu-th roots decompose into +-pairs mod p?

Run: python3 probe_407_L1_dz_dyadic_structure.py
"""
import itertools
from sympy import primerange, isprime


def get_primitive_2pow_root(n, p):
    """Return a primitive n-th root g of unity in F_p (n=2^mu, p==1 mod n), or None."""
    if (p - 1) % n != 0:
        return None
    e = (p - 1) // n
    HALF = n // 2
    for a in range(2, p):
        g = pow(a, e, p)
        if pow(g, n, p) == 1 and pow(g, HALF, p) == p - 1:  # primitive: g^(n/2) = -1
            return g
    return None


def decomposes_into_pm_pairs(Yexp, n, p, g):
    """
    Given an antipodal-free exponent set Yexp subset {0,..,n-1} with sum_{j in Y} g^j == 0,
    test whether the vanishing sum DECOMPOSES mod p into indecomposable pieces each of
    which is a +-pair {z,-z} (i.e. exponents j and j+n/2).  Antipodal-free => no such pair
    is present => the ONLY way to satisfy DZ-structure is the empty decomposition => Y empty.
    We instead directly search: is there ANY proper nonempty subset of Y summing to 0 mod p?
    (indecomposability test).  Return the minimal indecomposable subrelation's root-orders.
    """
    vals = [pow(g, j, p) for j in Yexp]
    m = len(Yexp)
    # find a minimal nonempty subset summing to 0 mod p
    for size in range(1, m + 1):
        for sub in itertools.combinations(range(m), size):
            if sum(vals[i] for i in sub) % p == 0:
                # this is an indecomposable (minimal) vanishing subrelation
                subexp = [Yexp[i] for i in sub]
                return subexp
    return None


def order_of_normalized_relation(subexp, n):
    """
    For a minimal vanishing relation on exponents subexp subset Z/n (n=2^mu), normalize by
    dividing by the first element (subtract subexp[0] from all exponents mod n). The 'least
    common order Q' = n / gcd(n, all normalized exponents). DZ says Q must be in {1,2}.
    Returns Q.
    """
    from math import gcd
    e0 = subexp[0]
    norm = [(e - e0) % n for e in subexp]  # zeta_0 = 1
    g = n
    for e in norm:
        g = gcd(g, e)
    # the normalized roots are g^{norm_i}, order = n/gcd(n, lattice generated by norm)
    # least common order Q = n / gcd(n, gcd of all norm exponents)
    Q = n // gcd(n, g) if g != 0 else 1
    # but if all norm==0, Q=1
    if all(e == 0 for e in norm):
        Q = 1
    return Q, norm


def scan(n, sizes, hi):
    mu = n.bit_length() - 1
    print(f"\n=== n={n} (mu={mu}), antipodal-free sizes={sizes}, primes p==1 mod {n} < {hi} ===")
    results = []
    for p in primerange(n + 1, hi):
        if p % n != 1 or not isprime(p):
            continue
        g = get_primitive_2pow_root(n, p)
        if g is None:
            continue
        HALF = n // 2
        for size in sizes:
            for S in itertools.combinations(range(n), size):
                Sset = set(S)
                # antipodal-free
                if any(((j + HALF) % n) in Sset for j in S):
                    continue
                vals = [pow(g, j, p) for j in S]
                if sum(vals) % p != 0:
                    continue
                # found an antipodal-free vanishing 0/1-sum mod p => a "spurious" config
                # test DZ structure: find a minimal indecomposable subrelation, its order Q
                minsub = decomposes_into_pm_pairs(list(S), n, p, g)
                Q, norm = order_of_normalized_relation(minsub, n)
                results.append((p, size, tuple(S), tuple(minsub), Q))
    if not results:
        print("  NO antipodal-free vanishing 0/1-sum (spurious config) found at all.")
        print("  => DZ-dyadic structure holds VACUOUSLY: no spurious config exists.")
        return results
    # report
    badQ = [r for r in results if r[4] not in (1, 2)]
    print(f"  Found {len(results)} antipodal-free vanishing configs.")
    print(f"  Minimal indecomposable subrelation orders Q:")
    from collections import Counter
    qc = Counter(r[4] for r in results)
    print(f"    Q-distribution: {dict(qc)}")
    if badQ:
        print(f"  *** {len(badQ)} configs whose MINIMAL subrelation has order Q NOT in {{1,2}} ***")
        print(f"      DZ-VIOLATION? (would mean my dyadic deduction is wrong) -- examine:")
        for r in badQ[:5]:
            p, size, S, minsub, Q = r
            print(f"      p={p} S={S} minsub={minsub} Q={Q}")
    else:
        print(f"  ALL minimal indecomposable subrelations have order Q in {{1,2}}")
        print(f"  => CONFIRMS DZ: every indecomposable mod-p relation of 2^mu-roots is a +-1 relation.")
        # but a +-pair {z,-z} means exponents j, j+n/2 -- which the antipodal-free Y CANNOT contain!
        # so the minimal subrelation, if Q=2, must use exponents differing by n/2 -- check
        for r in results[:8]:
            p, size, S, minsub, Q = r
            print(f"      p={p} S={S}: minimal vanishing subset={minsub} (Q={Q})")
    return results


if __name__ == "__main__":
    # n=16, n=32: known bad primes {17}, {97}
    scan(16, [4, 6, 8], 8000)
    scan(32, [4, 6], 3000)
