#!/usr/bin/env python3
r"""#444 LANE S6: the EXACT Weil-II exponent of the spurious mass on the config variety.

The S6 reduction (axiom-clean, _wfS6_toric_config_betti.lean) shows: IF
   spur_r(p) <= C(2r,r) * p^{r-1}                       (SpurToricBounded)
then E_r^charp <= (2r-1)!! n^r + 4^r p^{r-1}, giving K=4 absolute => prize via L3.

The genuine open AG content is whether THAT inequality holds uniformly. This probe
DOES NOT assume it -- it MEASURES the true scaling of spur in p at fixed (n,r), i.e.
fits spur_r(p) ~ C_r * p^{alpha_r}, to discover the ACTUAL Weil weight of the
governing subvariety of V_r = { x in mu_n^{2r} : sum eps_i x_i = 0 mod p }.

Weil-II prediction for a TORIC linear slice (Adolphson-Sperber / Bombieri-Katz):
  V_r is a hyperplane slice of the torus power; the char-p point count is
     #V_r(F_p) = main(char-0 geometric) + (Weil error),
  |Weil error| <= (total Betti) * p^{w/2},  w = top cohomological weight of the
  PRIMITIVE part. For the linear form in 2r torus variables the relevant weight is
  the one GLT found for r=2: a WEIGHT-1 curve (error O(p^{(2r-3)/2})? we MEASURE it),
  NOT the naive Fermat weight-(2r-2).

KEY DISTINCTION the prize hinges on:
  - if alpha_r <= r-1   AND C_r <= C(2r,r): SpurToricBounded holds => PROVEN route.
  - if alpha_r = r-1    but C_r grows in n: TRANSFER-FALSE (n-dependent constant).
  - if alpha_r < r-1 (sub-Weil cancellation): spur is even smaller (better).

We measure: for several n=2^mu and r, sweep many primes p=1 mod n in a band around
the prize ratio beta=log_n p in [3,5], compute spur_r(p) EXACTLY (FFT over n periods,
big-int), least-squares fit log spur vs log p to get alpha_r and the implied constant.

EXACT ARITHMETIC. p = 1 mod n, p prime, n = 2^a.
"""
import sys
from math import comb, log, isqrt
from itertools import combinations

def is_prime(m):
    if m < 2: return False
    for q in (2,3,5,7,11,13,17,19,23,29,31,37):
        if m % q == 0: return m == q
    d = m - 1; s = 0
    while d % 2 == 0: d //= 2; s += 1
    for a in (2,3,5,7,11,13,17,19,23,29,31,37):
        x = pow(a, d, m)
        if x == 1 or x == m-1: continue
        for _ in range(s-1):
            x = x*x % m
            if x == m-1: break
        else: return False
    return True

def primes_1modn(n, beta_lo, beta_hi, count):
    """primes p = 1 mod n with log_n(p) in [beta_lo, beta_hi]."""
    lo = int(n**beta_lo); hi = int(n**beta_hi)
    p = lo - (lo % n) + 1
    if p < lo: p += n
    out = []
    while p <= hi and len(out) < count:
        if is_prime(p): out.append(p)
        p += n
    return out

def double_dft_factorial(n):
    # char-0 energy = (2r-1)!! n^r  (Lam-Leung Wick). Return function of r.
    return lambda r: _df(r) * n**r

def _df(r):
    v = 1
    for j in range(1, r+1): v *= (2*j-1)
    return v

def Er_charp(n, r, p, g):
    """EXACT E_r^charp via period histogram, residues mod p."""
    elts = [pow(g, k, p) for k in range(n)]
    from collections import defaultdict
    dist = defaultdict(int)
    for e in elts: dist[e % p] += 1
    cur = dict(dist)
    for _ in range(r-1):
        nxt = defaultdict(int)
        for s1,c1 in cur.items():
            for e in elts:
                nxt[(s1+e) % p] += c1
        cur = nxt
    return sum(c*c for c in cur.values())

def Er_char0(n, r):
    """EXACT char-0 additive 2r-energy of the COMPLEX n-th roots of unity mu_n.
    E_r^char0 = #{(a,b) in [n]^r x [n]^r : sum zeta^{a_i} = sum zeta^{b_j} in C}.
    For n=2^mu, sums of r n-th roots of unity coincide over C; count via the
    exact integer vector (sum over the n roots, as a Z-combination) matching.
    Represent sum of r roots as a tuple of multiplicities mod the cyclotomic
    relation. For n=2^mu the only Z-relations among n-th roots are generated by
    zeta^{k+n/2} = -zeta^k, so two multisets of roots have equal complex sum iff
    their reduced signed coefficient vectors (length n/2) agree. We compute the
    reduced vector exactly."""
    half = n//2
    from collections import defaultdict
    # base vectors for single root k: +1 at k mod half if k<half else -1 at k-half
    cur = defaultdict(int)
    for k in range(n):
        idx = k % half
        sgn = 1 if k < half else -1
        v = [0]*half; v[idx] = sgn
        cur[tuple(v)] += 1
    for _ in range(r-1):
        nxt = defaultdict(int)
        for vt, c in cur.items():
            for k in range(n):
                idx = k % half
                sgn = 1 if k < half else -1
                w = list(vt); w[idx] += sgn
                nxt[tuple(w)] += c
        cur = nxt
    return sum(c*c for c in cur.values())

def main():
    print("="*78)
    print("S6: WEIL EXPONENT of spurious mass spur_r(p) = E_r^charp - (2r-1)!! n^r")
    print("="*78)
    results = []
    for n in (8, 16):
        g_needed = None
        for r in (2, 3):
            wick = _df(r) * n**r
            char0 = Er_char0(n, r)   # EXACT complex char-0 energy
            print(f"\n[n={n} r={r}] EXACT char0 energy={char0}  Wick (2r-1)!!n^r={wick}  ratio={char0/wick:.4f}")
            # sweep primes across beta in [3,5]
            ps = primes_1modn(n, 3.0, 5.0, 14)
            rows = []
            for p in ps:
                # primitive root mod p, then generator of order-n subgroup
                # find element of order n: take any g0 primitive root, g = g0^((p-1)/n)
                g0 = 2
                while True:
                    # check g0 primitive: order = p-1
                    ok = True
                    m = p-1; fs = []
                    mm = m; d = 2
                    while d*d <= mm:
                        if mm % d == 0:
                            fs.append(d)
                            while mm % d == 0: mm//=d
                        d += 1
                    if mm > 1: fs.append(mm)
                    for f in fs:
                        if pow(g0, (p-1)//f, p) == 1: ok=False; break
                    if ok: break
                    g0 += 1
                g = pow(g0, (p-1)//n, p)
                Er = Er_charp(n, r, p, g)
                spur = Er - char0
                rows.append((p, Er, spur, log(p, n)))
            # least squares fit log(spur) ~ alpha*log(p) + log C  over spur>0
            pos = [(p, spur) for (p,_,spur,_) in rows if spur > 0]
            if len(pos) >= 3:
                xs = [log(p) for p,_ in pos]
                ys = [log(s) for _,s in pos]
                m_ = len(xs)
                sx = sum(xs); sy = sum(ys); sxx = sum(x*x for x in xs); sxy = sum(x*y for x,y in zip(xs,ys))
                alpha = (m_*sxy - sx*sy)/(m_*sxx - sx*sx)
                logC = (sy - alpha*sx)/m_
                from math import exp
                Cfit = exp(logC)
            else:
                alpha = None; Cfit = None
            cbin = comb(2*r, r)
            # also: at each prime, spur / p^{r-1} (the SpurToricBounded test ratio) and / C(2r,r)
            ratios = [(round(log(p,n),3), spur, spur / p**(r-1) if p>0 else 0,
                       (spur / p**(r-1))/cbin) for (p,_,spur,b) in rows]
            print(f"\n--- n={n} r={r}  char0(exact)={char0} wick={wick}  C(2r,r)={cbin} ---")
            print(f"  fitted spur ~ C*p^alpha:  alpha={alpha}  C={Cfit}")
            print(f"  (toric SpurToricBounded predicts alpha<=r-1={r-1}, ratio spur/p^(r-1)<=C(2r,r))")
            nzero = sum(1 for (_,_,s,_) in rows if s==0)
            print(f"  primes with spur==0 (faithful transfer): {nzero}/{len(rows)}")
            worst = max((rr[2] for rr in ratios), default=0)
            worstC = max((rr[3] for rr in ratios), default=0)
            print(f"  worst spur/p^(r-1) = {worst:.4g}   worst /C(2r,r) = {worstC:.4g}  (toric holds iff <=1)")
            for (b, spur, ratio, rC) in ratios:
                flag = "FAITHFUL" if spur==0 else ("TORIC-OK" if rC<=1 else "TORIC-VIOLATED")
                print(f"    beta={b:5}  spur={spur:<10} spur/p^(r-1)={ratio:.5g}  /C(2r,r)={rC:.5g}  {flag}")
            results.append((n,r,alpha,Cfit,worst,worstC,nzero,len(rows)))
    print("\n" + "="*78)
    print("VERDICT")
    print("="*78)
    for (n,r,alpha,Cfit,worst,worstC,nz,tot) in results:
        verdict = "UNDETERMINED"
        if alpha is not None:
            if alpha <= r-1 + 0.15 and worstC <= 1.0:
                verdict = "SpurToricBounded HOLDS (alpha<=r-1, C<=C(2r,r))"
            elif alpha <= r-1 + 0.15:
                verdict = f"alpha ok but constant exceeds C(2r,r) (worstC={worstC:.3g})"
            else:
                verdict = f"alpha={alpha:.3g} EXCEEDS r-1={r-1}: toric exponent violated"
        print(f"  n={n} r={r}: alpha={alpha if alpha is None else round(alpha,3)}  faithful={nz}/{tot}  => {verdict}")

if __name__ == "__main__":
    main()
