#!/usr/bin/env python3
"""
Door-(iv) Lane 1 sweep 4 — the JOINT b<->b' correlation of the period field.

My three prior sweeps (758205014, 592490748, 42c4551ca) pinned that the worst-b cancellation lives
entirely in the MARGINAL second moment / Gaussian-EVT law of {|eta_b|}, which is door (iii)=BGK=dead.
The localization: the ONLY surviving door-(iv) surface is the JOINT correlation structure across
distinct cosets b that the marginal moments cannot see.

This probe characterizes that joint structure. eta is constant on multiplicative mu_n-cosets
(eta_{c b}=eta_b for c in mu_n), so the field lives on the QUOTIENT F_p* / mu_n ~= Z_{(p-1)/n}. The
quotient is cyclic, generated by the image of a primitive root g: coset_j has representative g^j.
Question: is the field j -> eta_{g^j} a SHORT-RANGE-correlated (Gaussian-field, dead) or a
LONG-RANGE / multiplicatively-structured field (potential door-iv grip)?

Measure on the cyclic quotient (over coset reps g^j, j=0..N-1, N=(p-1)/n):
  - lag-1 autocorrelation of the real field f_j = |eta_{g^j}|  (mult-shift by g)
  - lag-1 autocorrelation of the COMPLEX field eta_{g^j} (phase-sensitive)
  - the squared field's autocorr (energy field) at small lags
  - additive-shift correlation: corr(|eta_b|, |eta_{b+1}|) over b (the ADDITIVE neighbor, breaks coset)
  - is there ANY lag with |autocorr| bounded away from 0 as N grows? (long-range => exploitable)
EXACT complex arithmetic, proper mu_n, p>>n^3, never n=q-1.
"""
import cmath, math, statistics

def is_prime(n):
    if n<2: return False
    for q in (2,3,5,7,11,13,17,19,23,29,31,37):
        if n%q==0: return n==q
    d=n-1; r=0
    while d%2==0: d//=2; r+=1
    for a in (2,3,5,7,11,13,17,19,23,29,31,37):
        x=pow(a,d,n)
        if x in (1,n-1): continue
        for _ in range(r-1):
            x=x*x%n
            if x==n-1: break
        else: return False
    return True

def find_prime(n,beta):
    t=int(round(n**beta)); k0=max(2,t//n)
    for dk in range(0,400000):
        for k in (k0+dk,k0-dk):
            if k<2: continue
            p=k*n+1
            if p>n and is_prime(p): return p
    return None

def subgroup(p,n):
    pm1=p-1; f={}; m=pm1; d=2
    while d*d<=m:
        while m%d==0: f[d]=1; m//=d
        d+=1
    if m>1: f[m]=1
    def isg(g): return all(pow(g,pm1//q,p)!=1 for q in f)
    g=2
    while not isg(g): g+=1
    h=pow(g,pm1//n,p); mu=[]; c=1
    for _ in range(n): mu.append(c); c=c*h%p
    return mu,g

def eta_c(b,mu,p):
    return sum(cmath.exp(2j*math.pi*((b*y)%p)/p) for y in mu)

def autocorr_real(f, lag):
    N=len(f); mu=statistics.mean(f); v=statistics.pvariance(f)
    if v==0: return 0.0
    s=sum((f[i]-mu)*(f[(i+lag)%N]-mu) for i in range(N))/N
    return s/v

def autocorr_complex(z, lag):
    N=len(z); m=sum(z)/N
    num=sum((z[i]-m)*((z[(i+lag)%N]-m).conjugate()) for i in range(N))/N
    den=sum(abs(z[i]-m)**2 for i in range(N))/N
    return abs(num/den) if den>0 else 0.0

def main():
    print("=== joint b<->b' correlation of the period field on the cyclic quotient ===")
    print(f"{'n':>4} {'p':>10} {'N=cos':>7} {'ac1|eta|':>9} {'ac2|eta|':>9} {'ac1_cplx':>9} "
          f"{'ac1_E':>7} {'add_nbr':>8} {'maxlag_ac':>10}")
    for n,beta in [(16,4.0),(32,4.0),(64,4.0),(16,4.5),(32,4.5)]:
        p=find_prime(n,beta)
        if p is None: continue
        mu,g=subgroup(p,n)
        N=(p-1)//n
        cap=min(N, 40000)
        # build field over coset reps g^0..g^{cap-1}
        z=[]; cur=1
        for j in range(cap):
            z.append(eta_c(cur,mu,p)); cur=cur*g%p
        f=[abs(v) for v in z]
        E=[abs(v)**2 for v in z]
        ac1=autocorr_real(f,1); ac2=autocorr_real(f,2)
        ac1c=autocorr_complex(z,1); ac1E=autocorr_real(E,1)
        # additive neighbor: corr(|eta_b|,|eta_{b+1}|) over b=1..cap (breaks coset structure)
        fb=[abs(eta_c(b,mu,p)) for b in range(1,cap+1)]
        fb1=[abs(eta_c(b+1,mu,p)) for b in range(1,cap+1)]
        mb=statistics.mean(fb); mb1=statistics.mean(fb1)
        vb=statistics.pvariance(fb); vb1=statistics.pvariance(fb1)
        addc=(sum((fb[i]-mb)*(fb1[i]-mb1) for i in range(len(fb)))/len(fb))/math.sqrt(vb*vb1) if vb>0 and vb1>0 else 0.0
        # scan lags for any large autocorr
        maxac=max(abs(autocorr_real(f,L)) for L in range(1,min(cap//2,50)))
        print(f"{n:>4} {p:>10} {N:>7} {ac1:>9.4f} {ac2:>9.4f} {ac1c:>9.4f} "
              f"{ac1E:>7.4f} {addc:>8.4f} {maxac:>10.4f}")

if __name__=="__main__":
    main()
