#!/usr/bin/env python3
"""
probe_nc2_weil_lift.py  (#444 Weil-representation / theta-lift family)

CENTRAL QUESTION: does lifting e_p(bx) on mu_n into a Heisenberg/metaplectic
Weil-representation orbit produce GENUINE cancellation among the n/2 Galois
conjugates of beta = sum eps_i zeta^{a_i} (the only way to beat the obstruction),
or does it secretly bound-each-conjugate / reduce to a phase-blind (Weil-sqrt-q,
dead) route?

We test three concrete sub-questions:

(Q1) DOES mu_n sit as a Lagrangian / Weil-rep orbit in a symplectic F_p^{2d}?
     The squares (QR) do: x -> x^2 is the metaplectic theta orbit, quadratic Gauss
     sum = exact sqrt(p). Does the 2-power subgroup mu_n have a quadratic-form
     structure that the Weil rep can act on? Test: is the indicator 1_{mu_n}
     expressible as a theta-series sum_{l in Lagrangian} e_p(Q(l)) for some
     quadratic form Q? If yes, the Weil bound applies to the WHOLE sum.

(Q2) THETA-TRANSFORM SUP-NORM. Compute the Weil/metaplectic transform of 1_{mu_n}
     (the finite Weil representation acting via SL_2(F_p) generators: the Fourier
     transform F and the multiplication-by-Gauss-quadratic M_a). Does the orbit
     of 1_{mu_n} under the Weil rep have BOUNDED sup-norm (~ sqrt(n)), or does the
     2-power structure escape the quadratic orbit?

(Q3) THE DECISIVE TEST: is the Weil bound PHASE-BLIND? Construct a "phase-aligned
     adversary" beta whose Galois conjugates all have aligned phases (so no
     inter-conjugate cancellation) but which is consistent with all Weil/theta
     INVARIANTS (moduli |g(chi)|=sqrt p, Maslov index, phase-differences). If such
     an adversary achieves |sum| ~ sqrt(p) (NOT sqrt(n)), the route is phase-blind
     => dead. Compare to the actual M(n).
"""
import numpy as np
import cmath, math
from itertools import product

def primitive_root(p):
    # smallest primitive root mod p
    def order(g):
        x=1
        for k in range(1,p):
            x=(x*g)%p
            if x==1: return k
        return p-1
    for g in range(2,p):
        if order(g)==p-1: return g
    return None

def find_prime_with_mu(n, lo=10):
    # smallest prime p with n | p-1, p > lo
    p = max(lo, n+1)
    while True:
        if (p-1)%n==0 and is_prime(p): return p
        p+=1

def is_prime(m):
    if m<2: return False
    for d in range(2,int(m**0.5)+1):
        if m%d==0: return False
    return True

def mu_n(p, n):
    g = primitive_root(p)
    h = pow(g, (p-1)//n, p)   # primitive n-th root
    return sorted({pow(h, j, p) for j in range(n)})

def ep(p):
    return cmath.exp(2j*math.pi/p)

# ---------------------------------------------------------------------------
print("="*78)
print("(Q1)  Is mu_n a quadratic / Lagrangian orbit?  (theta-series expressibility)")
print("="*78)
# The squares S = {x^2} are the canonical theta orbit: 1_S(y) = (1/2)(1 + chi(y))
# where chi = quadratic character, and sum_y 1_S(y) e_p(by) is a quadratic Gauss sum
# = sqrt(p)-bounded EXACTLY. Question: is mu_n (n=2^a, n | p-1) ALSO such an orbit?
# mu_n = {x : x^n = 1} = ker of the map x -> x^n on F_p^*. It is the IMAGE of x -> x^{(p-1)/n}.
# For it to be a quadratic theta orbit we'd need mu_n = {Q-values} for a quadratic form,
# i.e. mu_n = image of a degree-2 map. But mu_n is the image of a degree-(p-1)/n map.
# Only when (p-1)/n = 2, i.e. n = (p-1)/2, is mu_n = squares = quadratic orbit.
# In the PRIZE regime n ~ p^{1/4}, (p-1)/n ~ p^{3/4} >> 2.  Verify the index:
for (n,) in [(4,),(8,),(16,),(32,)]:
    p = find_prime_with_mu(n, lo=n*n*n+10)  # prize-ish q >> n^3
    idx = (p-1)//n
    print(f"  n={n:3d}  p={p:6d}  index (p-1)/n = {idx:6d}   "
          f"{'QUADRATIC orbit (n=squares)' if idx==2 else 'degree-'+str(idx)+' orbit -- NOT quadratic'}")
print("  => In the prize regime mu_n is a high-degree (p^{3/4}) orbit, NOT a quadratic/")
print("     Lagrangian theta orbit. The Weil rep acts on QUADRATIC orbits (squares); the")
print("     2-power subgroup is not one. (n=squares only at the boundary n=(p-1)/2 ~ p, not p^{1/4}.)")

# ---------------------------------------------------------------------------
print()
print("="*78)
print("(Q2)  Weil-rep orbit sup-norm of 1_{mu_n}  vs  the quadratic (squares) baseline")
print("="*78)
# The finite Weil representation of SL_2(F_p) on C[F_p] is generated by:
#   F : (F f)(y) = p^{-1/2} sum_x f(x) e_p(xy)         [Fourier, = w = [[0,-1],[1,0]]]
#   M_a: (M_a f)(x) = e_p(a x^2) f(x)                  [unipotent, = [[1,a],[0,1]] up to Weil cst]
#   D_t: (D_t f)(x) = chi(t) f(t^{-1} x)               [diagonal scaling]
# A vector is a "theta vector" (sqrt-bounded sup-norm under the WHOLE orbit) iff it is a
# delta or a Gaussian e_p(a x^2). Test: how does sup|.| evolve along the orbit of 1_{mu_n}?
def fourier(f, p, om):
    n=len(f)
    out=np.zeros(p, dtype=complex)
    for y in range(p):
        s=0
        for x in range(p):
            s+= f[x]*om**((x*y)%p)
        out[y]=s/math.sqrt(p)
    return out

def gaussmult(f, p, a, om):
    return np.array([f[x]*om**((a*x*x)%p) for x in range(p)], dtype=complex)

for (n,) in [(4,),(8,),(16,)]:
    p = find_prime_with_mu(n, lo=n*n+10)   # q ~ n^2 region (keeps p small enough to DFT)
    om = ep(p)
    M = mu_n(p,n)
    f0 = np.zeros(p, dtype=complex);
    for x in M: f0[x]=1.0
    # squares baseline
    sq = sorted({pow(x,2,p) for x in range(1,p)})
    g0 = np.zeros(p, dtype=complex)
    for x in sq: g0[x]=1.0
    # apply a length-4 Weil word F M_1 F M_1 to each and track sup along the way
    def orbit_sup(vec):
        sups=[np.max(np.abs(vec))]
        v=vec
        for a in [1,1,1,1]:
            v=gaussmult(v,p,a,om);
            v=fourier(v,p,om)
            sups.append(np.max(np.abs(v)))
        return sups
    sm = orbit_sup(f0); sg = orbit_sup(g0)
    print(f"  n={n:3d} p={p:5d}  sqrt(n)={math.sqrt(n):.2f}  sqrt(p)={math.sqrt(p):.2f}")
    print(f"     mu_n   sup along Weil orbit: {[f'{s:.2f}' for s in sm]}")
    print(f"     squares sup along Weil orbit:{[f'{s:.2f}' for s in sg]}")
print("  Interpretation: a TRUE theta vector keeps sup ~ O(1) or sqrt(p)/sqrt(p)=1 (the")
print("  Gaussian is a Weil eigenvector). If mu_n's orbit sup BLOWS UP / wanders to ~sqrt(p),")
print("  it is NOT a theta vector and the Weil bound does not apply to it as a whole.")
