"""
char-0 baseline: E_r over COMPLEX n-th roots of unity. Zero-sum 2r-tuples from
the complex group mu_n^C. Graded by distinct-value count, EXACTLY, via the same DP
but with sums tracked as the EXACT integer exponent-sum being a multiple of n
ONLY when the vanishing-sum is forced... NO: complex zero-sums of roots of unity are
NOT just exponent-balanced. We need genuine vanishing sums of n-th roots of unity.

A multiset of n-th roots sums to 0 over C iff it is a non-negative-integer combination
of 'rotated' primitive vanishing sums. For 2-power n=2^mu the vanishing sums of n-th
roots of unity are EXACTLY generated by the antipodal relation 1 + (-1) = 0 (zeta^k + zeta^{k+n/2}=0)
because the only prime dividing n is 2 (Lam-Leung: minimal vanishing sums of n-th roots
have length = sum of prime factors with multiplicity; for n=2^mu the only minimal
vanishing sum length is 2 => every vanishing sum is a union of antipodal pairs).
THIS IS THE KEY char-0 STRUCTURE FACT (proven, Lam-Leung 2000).

So char-0 zero-sum 2r-tuples = tuples that decompose as r antipodal pairs (with multiplicity).
We count them EXACTLY and grade by distinct-value count.
"""
import sys; sys.path.insert(0,'/tmp/tool5')
from fractions import Fraction
from math import factorial, comb
from collections import defaultdict

def char0_zero_sum_ordered(n, twor):
    """Ordered zero-sum 2r-tuples of complex n-th roots, graded by distinct-value count.
    For n=2^mu: zero-sum multiset <=> union of antipodal pairs {zeta^j, zeta^{j+n/2}}.
    Enumerate multiplicity m_j for j=0..n-1 with constraint that the multiset is a union of
    antipodal pairs: i.e. for each antipodal pair (j, j+n/2), the COMBINED multiset on that
    pair must itself be antipodal-balanced? NO -- a union of antipodal pairs means we pick
    some number c_j>=0 of pairs at antipodal-class j (j in 0..n/2-1), contributing c_j copies
    of zeta^j and c_j copies of zeta^{j+n/2}. Total coords = 2*sum c_j = 2r => sum c_j = r.
    distinct values used = #{j: c_j>0} (each engaged class gives 2 distinct values, UNLESS the
    two antipodal points coincide, impossible for roots) -> distinct = 2*#{j:c_j>0}.
    ordered count = (2r)! / prod( c_j! c_j! )  [m on zeta^j = c_j, on zeta^{j+n/2} = c_j].
    """
    half = n//2
    # DP over classes j=0..half-1, choose c_j>=0, sum c_j = r, track distinct=2*engaged
    r = twor//2
    cur = { (0,0): Fraction(1) }  # (pairs_used, engaged_classes) -> prod 1/(c_j!^2)
    for j in range(half):
        nxt = defaultdict(Fraction)
        for (used, eng), w in cur.items():
            c=0; fact=1
            while used + c <= r:
                if c==0:
                    nxt[(used,eng)] += w
                else:
                    fact *= c
                    nxt[(used+c, eng+1)] += w * Fraction(1, fact*fact)
                c+=1
        cur=dict(nxt)
    F = factorial(twor)
    prof=defaultdict(int)
    for (used,eng),w in cur.items():
        if used==r:
            ordered = w*F
            assert ordered.denominator==1
            prof[2*eng] += int(ordered)
    return dict(prof)

if __name__=="__main__":
    import depth_core as d
    for n in [16,32]:
        for twor in [4,6]:
            prof = char0_zero_sum_ordered(n,twor)
            tot=sum(prof.values()); r=twor//2
            print(f"char0 n={n} 2r={twor} r={r}: E_r^char0={tot}  Wick={d.dfac(r)*n**r}  profile(distinct->cnt)={dict(sorted(prof.items()))}")
