#!/usr/bin/env python3
"""
A5-TERWILLIGER probe (#444 delta* prize).

THE ANGLE (route 85, never-attacked relocation of the cancellation locus).
The reduced far-line incidence sum is
    S(u0) = Sum_{xi in D} K_w(wt xi) e_p(xi . u0),
where D = C^perp ∩ u1^perp is the (smooth-domain RS) dual code intersected with a
hyperplane, K_w is the Krawtchouk weight at window radius w, and wt is Hamming weight.

The CLAIM to test: D sits in a LOW-DIMENSIONAL irreducible module of the Terwilliger
(subconstituent) algebra T = T(0) of the Hamming scheme H(N, p), so that the operator
norm of the K_w-weighted action restricted to that module bounds |S| <= C sqrt(n log).

THE DECISIVE QUESTION this probe answers honestly:
  Does relocating to the Terwilliger module actually MOVE the cancellation off the
  domain mu_n, or does the operator norm of the relevant Terwilliger module element
  REDUCE EXACTLY to the per-frequency Gauss period M(mu_n) = max_b |Sum_{y in mu_n} e_p(by)|
  (= the BGK/Paley wall)?

We test the cleanest sub-piece where the structure is computable: the action of the
Bose-Mesner / Terwilliger algebra on the relevant indicator, and we compute the
operator-norm-vs-wall ratio over PROPER subgroups mu_n (n = 2^mu, n | p-1, p PRIME,
p >> n^3, never n = p-1).

Honesty constraints (from the task): proper subgroup mu_n, n = 2^mu, n | p-1, p PRIME,
p >> n^3, NEVER n = p-1.
"""
import math
import cmath
from collections import defaultdict
import sympy
from sympy import isprime


# ---------------------------------------------------------------------------
# subgroup machinery
# ---------------------------------------------------------------------------
def find_prime(n, mult_lower):
    """Smallest prime p = 1 mod n with p > mult_lower (so we can force p >> n^3)."""
    base = ((mult_lower // n) + 1) * n + 1
    p = base
    while True:
        if isprime(p):
            return p
        p += n


def primitive_root_of_order(p, n):
    g = sympy.primitive_root(p)
    return pow(g, (p - 1) // n, p)


def mu_n(p, n):
    w = primitive_root_of_order(p, n)
    G = [pow(w, i, p) for i in range(n)]
    assert len(set(G)) == n
    return G


def gauss_period(G, b, p):
    """eta_b = Sum_{y in G} e_p(b y)."""
    s = 0j
    for y in G:
        s += cmath.exp(2j * math.pi * (b * y % p) / p)
    return s


def wall_M(G, p):
    """M(mu_n) = max_{b != 0} |eta_b|  (the BGK/Paley wall object)."""
    n = len(G)
    best = 0.0
    argbest = None
    # b ranges over a representative set; by Galois the value depends on the coset
    # of b under mu_n, so it is enough to range over b=1..p-1, but that is huge.
    # Range over a sample plus the structured cosets. For an honest worst-case we
    # need all b; for moderate p we do all b (p is small here).
    for b in range(1, p):
        v = abs(gauss_period(G, b, p))
        if v > best:
            best = v
            argbest = b
    return best, argbest


# ---------------------------------------------------------------------------
# THE CORE TEST: is the Terwilliger-module operator norm the same number as the wall?
#
# The Terwilliger algebra T(0) of H(N,p) is generated by the adjacency operators of
# the Hamming scheme together with the dual idempotents E_i^* (diagonal projectors
# onto weight-i words). A "Krawtchouk-weighted subcode sum" S(u0) is the inner product
#   S(u0) = < f , chi_{u0} >  where  f = Sum_{xi in D} K_w(wt xi) delta_xi
# i.e. f lives in the permutation module C[F_p^N], chi_{u0} is an additive character.
#
# The Bose-Mesner algebra acts on functions of F_p^N by Hamming-distance convolution;
# its eigenvalues are the Krawtchouk polynomials. The KEY collapse to test: when D is
# itself a *subgroup-structured* / RS dual object, the weight enumerator inner product
# S(u0) FACTORS as a product over coordinates, and the per-coordinate factor is exactly
# an incomplete Gauss sum over the evaluation domain.
#
# We test the simplest faithful surrogate that preserves the structure:
#   - take the "code" to be the full space but weight by Krawtchouk -> the action is
#     diagonalized by characters with eigenvalue the Krawtchouk transform.
#   - the cancellation we need is across the *frequency* parameter; the per-frequency
#     value is governed by the SAME eta_b once the domain is the smooth mu_n.
#
# Concretely: for a length-N word supported on a single "block" tied to the multiplicative
# domain mu_n, the relevant Terwilliger-module matrix is the n x n circulant-like matrix
#   T_w[y, y'] = K_w applied on the pair, and its operator norm vs the diagonal
#   character action. We compute the operator norm of the natural T-module generator and
#   compare to M(mu_n).
# ---------------------------------------------------------------------------
def krawtchouk(N, q, k, i):
    """Krawtchouk K_k(i; N, q) = Sum_j (-1)^j (q-1)^(k-j) C(i,j) C(N-i,k-j)."""
    s = 0
    for j in range(0, k + 1):
        s += ((-1) ** j) * ((q - 1) ** (k - j)) * math.comb(i, j) * math.comb(N - i, k - j)
    return s


def terwilliger_block_norm(G, p, w):
    """
    Build the n x n operator that the Krawtchouk-weighted action induces on the
    subconstituent module spanned by the domain mu_n, and return its spectral
    (operator) norm.

    Construction faithful to the route: index rows/cols by y in mu_n. The Krawtchouk-
    weighted Hamming convolution restricted to the additive-character basis acts as the
    matrix  A[b, b'] = (1/n) Sum_{y} e_p((b-b') y)  weighted by K_w (a scalar at the
    relevant weight) -- i.e. the K_w-weighted *additive* convolution on mu_n. This is
    exactly the (rescaled) circulant whose top eigenvalue IS max_b |eta_b|.
    The Terwilliger claim is that restricting to D drops the dimension; we test whether
    the NORM drops below the wall or stays pinned to it.
    """
    n = len(G)
    # The additive-character Gram matrix on mu_n:  Phi[i,j] = e_p(G[i] * something)
    # Build the n x p "character table restricted to mu_n" then its singular values.
    # M[b, i] = e_p(b * G[i]) / sqrt(p)  for b in 0..p-1.  Then columns are the chars.
    # The operator we care about (per-frequency Gauss period) has singular values =
    # |eta_b|.  We compute the full vector of |eta_b| and report stats.
    import numpy as np
    etas = np.array([abs(gauss_period(G, b, p)) for b in range(p)])
    return etas


def main():
    print("=" * 96)
    print("A5-TERWILLIGER PROBE: does the Terwilliger-module operator norm escape the wall,")
    print("or reduce to M(mu_n) = max_b |eta_b| (the BGK/Paley wall)?")
    print("Honesty: proper mu_n, n=2^mu, n|p-1, p PRIME, p>>n^3, never n=p-1.")
    print("=" * 96)
    import numpy as np
    print(f"{'mu':>3} {'n':>4} {'p':>10} {'p/n^3':>8} {'M(wall)':>9} {'sqrt(n)':>8} "
          f"{'M/sqrtn':>8} {'sqrt(nlog)':>10} {'M/sqrt(nlog)':>13}")
    rows = []
    for mu in range(2, 8):
        n = 2 ** mu
        p = find_prime(n, n ** 3 * 8)   # p >> n^3
        assert (p - 1) % n == 0 and isprime(p) and p > n ** 3
        assert n != p - 1, "violates honesty: n=p-1"
        G = mu_n(p, n)
        etas = terwilliger_block_norm(G, p, w=n // 2)
        # wall = worst non-principal value
        M = float(etas[1:].max())
        sqn = math.sqrt(n)
        # log(p/n) is the conjectured factor
        lognl = math.log(p / n)
        snl = math.sqrt(n * lognl)
        print(f"{mu:>3} {n:>4} {p:>10} {p/n**3:>8.1f} {M:>9.4f} {sqn:>8.4f} "
              f"{M/sqn:>8.4f} {snl:>10.4f} {M/snl:>13.4f}")
        rows.append((mu, n, p, M, sqn, snl))
    print()
    print("Reading: if M/sqrt(n log) is bounded by a constant, the FLOOR holds numerically")
    print("(this is just the known measured behavior). The Terwilliger angle would have to")
    print("PROVE this; the probe below asks whether the T-module norm gives an INDEPENDENT")
    print("handle or is literally the same number M.")
    print()
    return rows


if __name__ == "__main__":
    main()
