#!/usr/bin/env python3
"""
probe_407_Ar_thinness_essential.py  (#407)

DECISIVE THINNESS-ESSENTIALITY TEST for the DC-subtracted moment input A_r <= Wick.

Background:
  - The prize moment chain (DCMomentSupBound) consumes the OPEN input
        A_r = E_r - |G|^{2r}/q  <=  Wick(r) = (2r-1)!! |G|^r      (= BGK)
  - This A_r<=Wick is CONFIRMED measured-true at prize depth (grind 01:45).
  - RULE 3 (honesty contract): ANY valid proof of CORE must be THINNESS-ESSENTIAL:
    its certifying inequality must be FALSE in the thick window (beta~2.3-3.2).
  - So: is A_r<=Wick itself thinness-essential? If A_r<=Wick ALSO holds in the
    thick regime (it should, Wick is the Gaussian/random ceiling, generically true),
    then A_r<=Wick is SUBSTRATE, not the prize lever. The thinness must live in the
    GAP A_r/Wick or in the relation M^2 vs (q A_r)^{1/r}, not in A_r<=Wick.

What this probe MEASURES (exact FFT over PROPER 2-power subgroups mu_n < F_p*):
  For matched n, sweep beta = log_n(p) across the THICK window (beta~2.3-3.2) and
  the THIN prize window (beta~4-5):
    (1) Does A_r <= Wick hold in BOTH regimes? (ratio A_r/Wick)
    (2) The TRUE sup-norm M(n) = max_{b!=0}|eta_b|, and the moment-certified
        upper bound min_r (q A_r)^{1/2r}.  Their RATIO (certified/true) -- does the
        moment route's SLACK behave differently thin vs thick?
    (3) The decisive object: M(n)/sqrt(n)  (the prize wants this <= C sqrt(log(p/n))).
        Plot it vs beta. Where does the moment-certified bound BEAT vs MISS the
        prize target sqrt(n log(p/n))?

VERDICT LOGIC:
  - If A_r<=Wick holds in thick AND thin alike => A_r<=Wick is NOT thinness-essential
    => it is honest substrate, and the prize lever (rule-3 inequality) must be a
    DIFFERENT, thin-only inequality. This MAPS where the real open content lives.
  - If the moment-certified M-bound matches the prize target only in thin and blows
    up (relative to target) in thick, that is exactly the thinness signature we want
    -- but we must check it is in the CERTIFIED bound, not just true M.
"""
import math, cmath

def factor_small(m):
    f={}
    d=2
    while d*d<=m:
        while m%d==0:
            f[d]=f.get(d,0)+1; m//=d
        d+=1
    if m>1: f[m]=f.get(m,0)+1
    return f

def is_prime(m):
    if m<2: return False
    d=2
    while d*d<=m:
        if m%d==0: return False
        d+=1
    return True

def primitive_root(p):
    # p prime; find generator of F_p^*
    fac=list(factor_small(p-1).keys())
    for g in range(2,p):
        if all(pow(g,(p-1)//q,p)!=1 for q in fac):
            return g
    return None

def find_prime_near(target, mod_n):
    """find prime p with p ≡ 1 mod mod_n, near target."""
    # need n | p-1 so mu_n (the order-n subgroup) exists
    k = max(1, round(target/mod_n))
    for delta in range(0, 200000):
        for s in (1,-1):
            kk = k + s*delta
            if kk < 1: continue
            p = kk*mod_n + 1
            if p>3 and is_prime(p):
                return p
    return None

def eta_sup(n, p):
    """exact M(n)=max_{b!=0}|sum_{x in mu_n} e_p(b x)| over PROPER subgroup mu_n<F_p^*."""
    g = primitive_root(p)
    # subgroup of order n: generated by g^((p-1)/n)
    h = pow(g, (p-1)//n, p)
    elts = []
    x=1
    for _ in range(n):
        elts.append(x); x=(x*h)%p
    w = 2*math.pi/p
    best=0.0
    bestb=0
    for b in range(1,p):
        s=0j
        for xx in elts:
            s+=cmath.exp(1j*w*((b*xx)%p))
        m=abs(s)
        if m>best:
            best=m; bestb=b
    return best, elts, g

def rEnergy_via_periods(elts, p, r):
    """E_r(G) for additive-character version:
       sum_b |eta_b|^{2r} = q * E_r  (full, incl b=0 giving |G|^{2r}).
       We compute A_r = E_r - |G|^{2r}/q directly via the DC-subtracted moment:
         q*A_r = sum_{b!=0} |eta_b|^{2r}.
       Return (A_r, q*A_r, max over b!=0 of |eta_b|)."""
    w=2*math.pi/p
    n=len(elts)
    tot=0.0
    mx=0.0
    for b in range(1,p):
        s=0j
        for xx in elts:
            s+=cmath.exp(1j*w*((b*xx)%p))
        a=abs(s)
        if a>mx: mx=a
        tot += a**(2*r)
    qAr = tot
    Ar = qAr/p
    return Ar, qAr, mx

def dfact(k):
    r=1.0
    while k>1:
        r*=k; k-=2
    return r

def run():
    print("THINNESS-ESSENTIALITY of A_r<=Wick  (proper mu_n < F_p^*, exact FFT)\n")
    print("Legend: A_r<=Wick? ratio=A_r/Wick (<1 => holds). M/sqrt(n) vs prize target sqrt(log(p/n)).")
    print("Certified-M = min_r (q A_r)^{1/2r}.  cert/true = certified-M / true-M.\n")
    # keep p modest: O(p^2) FFT cost per beta. n=8 with beta up to ~4.5 => p<=~16k ok.
    for n in [8, 16]:
        print(f"==== n={n} ====")
        # n=16 capped at modest beta to keep p^2 cost sane
        betas = [2.3, 2.7, 3.2, 3.6, 4.0, 4.5] if n==8 else [2.3, 2.7, 3.0, 3.3]
        for beta in betas:
            target = n**beta
            p = find_prime_near(int(target), n)
            if p is None:
                print(f"  beta~{beta}: no prime found"); continue
            actual_beta = math.log(p)/math.log(n)
            best, elts, g = eta_sup(n, p)
            # certified-M: optimize over r
            cert_best = float('inf'); cert_r=0; ar_at=None; wick_at=None; ratio_at=None
            rmax = max(2, int(round(math.log(p)))+2)
            for r in range(1, rmax+1):
                Ar, qAr, mx = rEnergy_via_periods(elts, p, r)
                wick = dfact(2*r-1)*(n**r)
                cert = qAr**(1.0/(2*r))   # (q A_r)^{1/2r} >= M
                if cert < cert_best:
                    cert_best=cert; cert_r=r; ar_at=Ar; wick_at=wick; ratio_at=Ar/wick
                # record Ar<=Wick at the prize depth r~ln q
            r_prize = max(1, round(math.log(p)))
            Ar_pz, qAr_pz, _ = rEnergy_via_periods(elts, p, r_prize)
            wick_pz = dfact(2*r_prize-1)*(n**r_prize)
            holds = "YES" if Ar_pz<=wick_pz else "NO!"
            M_over_sqrtn = best/math.sqrt(n)
            prize_target = math.sqrt(max(1e-9, math.log(p/n)))
            cert_over_true = cert_best/best if best>0 else float('nan')
            print(f"  beta={actual_beta:.2f} p={p}: A_r<=Wick(r={r_prize})={holds} "
                  f"(A_r/Wick={Ar_pz/wick_pz:.3f}) | M/sqrt(n)={M_over_sqrtn:.3f} "
                  f"target sqrt(log(p/n))={prize_target:.3f} | cert/true={cert_over_true:.3f} (r*={cert_r})")
        print()

if __name__=="__main__":
    run()
