#!/usr/bin/env python3
"""#466 R305: COMPLETE classification of the depth-3 excess at n = 2^k via exact
cyclotomic difference classes.

Represent mu_n exactly: for n = 2^k, Phi_n(x) = x^(n/2) + 1, so zeta^j for j in [0, n/2)
is a basis vector e_j of Z^(n/2) and zeta^(j + n/2) = -e_j.  Every 3-sum of mu_n elements
is an exact integer vector w in Z^(n/2) with |w|_1 <= 3.  Let

    N3(w)  = #ordered triples (x1,x2,x3) in mu_n^3 with x1+x2+x3 = w   (in char 0)
    M(z)   = sum_w N3(w) * N3(w+z)   (difference-class pair count, z != 0)

Then for ANY prime p ≡ 1 (mod n) with mu_n generated by g (order n mod p):

    excess(p, n) = E3(p,n) - E3^char0(n) = sum_{z != 0, z(g) ≡ 0 mod p} M(z)

because a wraparound pair of triples is exactly a pair of distinct char-0 vectors that
collide mod p, and z(g) = sum_j z_j g^j is the mod-p evaluation.

This computes, in one pass:
  * the full difference-class spectrum {(M(z), Norm(z))} — the excess quantization law;
  * the COMPLETE bad-prime list to any bound (primes dividing some Norm(z));
  * for each such prime, the exact predicted excess (verifiable against E3 scans);
  * the maximal beta at which the exact-Wick rung E3 <= 15 n^3 can still fail
    (largest prime factor ≡ 1 mod n of any Norm(z) whose vanishing set carries
    total M > 45n^2 - 40n).
"""

from __future__ import annotations

import argparse
import math
import sys
from collections import defaultdict

import numpy as np


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=32, help="must be a power of two")
    ap.add_argument("--top-classes", type=int, default=20)
    ap.add_argument("--factor-limit", type=int, default=10**7,
                    help="trial-division limit for norm factorization")
    ap.add_argument("--verify-primes", type=str, default="",
                    help="comma-separated primes to cross-check predicted excess")
    args = ap.parse_args()

    n = args.n
    m = n // 2  # dimension of Z[zeta]/Phi_n
    assert n & (n - 1) == 0, "n must be a power of two"

    # mu_n as signed basis vectors: j -> (+1, j) for j < m, (-1, j - m) for j >= m
    def root_vec(j: int) -> tuple[int, int]:
        return (1, j) if j < m else (-1, j - m)

    # enumerate all ordered triples -> exact vector; histogram N3 over vector keys
    N3: dict[tuple[int, ...], int] = defaultdict(int)
    for a in range(n):
        sa, ia = root_vec(a)
        for b in range(n):
            sb, ib = root_vec(b)
            for c in range(n):
                sc, ic = root_vec(c)
                v = [0] * m
                v[ia] += sa
                v[ib] += sb
                v[ic] += sc
                N3[tuple(v)] += 1
    keys = list(N3.keys())
    print(f"n={n}: {len(keys)} distinct char-0 3-sum vectors (of {n**3} triples)", flush=True)

    # char-0 energy check: sum N3^2 should equal 15n^3 - 45n^2 + 40n
    e3_char0 = sum(v * v for v in N3.values())
    print(f"char-0 E3 = {e3_char0} (closed form {15*n**3 - 45*n**2 + 40*n})", flush=True)

    # difference classes
    M: dict[tuple[int, ...], int] = defaultdict(int)
    karr = np.array(keys, dtype=np.int64)
    cnt = np.array([N3[k] for k in keys], dtype=np.int64)
    for i in range(len(keys)):
        diffs = karr - karr[i]
        for j in range(len(keys)):
            if i == j:
                continue
            M[tuple(diffs[j])] += int(cnt[i] * cnt[j])
    print(f"{len(M)} nonzero difference classes", flush=True)

    # norm of z: prod over odd u mod 2n? For n=2^k, Gal conjugates zeta -> zeta^u, u odd,
    # u in (Z/n... wait: zeta has order n; conjugates are zeta^u for u odd in [1, n).
    # Norm(z) = prod_{u odd mod n} z(zeta^u) — degree m = n/2 conjugates? No: [Q(zeta_n):Q]
    # = phi(n) = n/2 = m, u ranges over odd residues mod n (there are n/2 of them).
    thetas = 2.0 * math.pi / n
    odd_us = [u for u in range(1, n) if u % 2 == 1]

    def norm_of(z: tuple[int, ...]) -> int:
        val = 1.0 + 0.0j
        for u in odd_us:
            s = 0.0 + 0.0j
            for j, zj in enumerate(z):
                if zj:
                    s += zj * complex(math.cos(thetas * j * u), math.sin(thetas * j * u))
            val *= s
        # norm is a rational integer; val should be real
        return int(round(val.real))

    # aggregate: for each class compute norm; collect nonzero-norm classes.
    # Norm(z) == 0 cannot happen for z != 0 in the integral basis (Phi_n irreducible).
    spectrum: dict[int, int] = defaultdict(int)  # norm -> total M
    class_rows = []
    for z, mz in M.items():
        nz = norm_of(z)
        assert nz != 0, f"zero norm for nonzero class {z}"
        spectrum[abs(nz)] += mz
        class_rows.append((mz, abs(nz), z))

    class_rows.sort(reverse=True)
    print(f"\ntop {args.top_classes} difference classes by pair count M(z):")
    print(f"{'M(z)':>10} {'|Norm(z)|':>16} z (sparse)")
    for mz, nz, z in class_rows[: args.top_classes]:
        sparse = {j: v for j, v in enumerate(z) if v}
        print(f"{mz:>10} {nz:>16} {sparse}")

    quantum = 0
    for mz, _, _ in class_rows:
        quantum = math.gcd(quantum, mz)
    print(f"\ngcd of all M(z) (the quantization quantum candidate): {quantum}")

    # bad primes: primes p ≡ 1 mod n dividing some |Norm(z)|; predicted excess needs
    # per-prime vanishing test, but a superset + per-norm M gives the census.
    # factor each distinct norm by trial division up to limit
    headroom = 45 * n**2 - 40 * n
    norms = sorted(spectrum.keys())
    print(f"\n{len(norms)} distinct |Norm| values; max = {max(norms):.3e}; "
          f"headroom = {headroom}")

    def trial_factor(x: int, limit: int) -> tuple[list[int], int]:
        fs = []
        d = 2
        while d * d <= x and d <= limit:
            while x % d == 0:
                fs.append(d)
                x //= d
            d += 1 if d == 2 else 2
        return fs, x  # x = remaining cofactor (1 if fully factored)

    bad_primes: dict[int, int] = defaultdict(int)  # p -> max single-norm M carried
    cofactors = []
    for nz in norms:
        fs, rest = trial_factor(nz, args.factor_limit)
        for p in set(fs):
            if p % n == 1:
                bad_primes[p] = max(bad_primes[p], spectrum[nz])
        if rest > 1:
            cofactors.append((rest, nz, spectrum[nz]))

    print(f"\nbad primes ≡ 1 (mod {n}) found by trial division (p, max M on one norm):")
    for p in sorted(bad_primes):
        beta = math.log(p) / math.log(n)
        flag = " <-- can violate exact Wick alone" if bad_primes[p] > headroom else ""
        print(f"  p={p:>12} beta={beta:.3f} maxNormM={bad_primes[p]}{flag}")

    if cofactors:
        print(f"\n{len(cofactors)} unfactored cofactors > {args.factor_limit} "
              f"(may hide high-beta bad primes); largest few:")
        cofactors.sort(reverse=True)
        for rest, nz, mz in cofactors[:10]:
            beta = math.log(rest) / math.log(n)
            print(f"  cofactor={rest} (beta<={beta:.3f} if prime) norm={nz} classM={mz}"
                  + (" <-- exceeds headroom" if mz > headroom else ""))

    # optional verification against direct E3
    if args.verify_primes:
        for p in [int(t) for t in args.verify_primes.split(",") if t]:
            # find element of order n mod p
            g0 = None
            for g in range(2, p):
                if pow(g, (p - 1) // 2, p) != 1:  # primitive-ish start
                    g0 = pow(g, (p - 1) // n, p)
                    if pow(g0, n // 2, p) != 1:
                        break
            assert g0 is not None
            powers = [pow(g0, j, p) for j in range(m)]
            pred = 0
            for z, mz in M.items():
                s = 0
                for j, zj in enumerate(z):
                    if zj:
                        s += zj * powers[j]
                if s % p == 0:
                    pred += mz
            print(f"verify p={p}: predicted excess = {pred}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
