#!/usr/bin/env python3
"""
Door-IV probe (#444): arithmetic of the worst frequency cosets.

For primes p ≡ 1 (mod n), n=2^a, the Gauss period
  eta_b = sum_{x in mu_n} exp(2πi b x / p)
is constant on multiplicative mu_n-cosets of b.  So the true search space is the
quotient F_p^*/mu_n of size m=(p-1)/n.

This probe scans all quotient cosets for n <= 64 in the beta≈4 regime and records:
  * worst quotient index j and top cosets,
  * whether top cosets have visible cyclic/arithmetic structure in Z/mZ,
  * the half-coset coherence |A+B|/(|A|+|B|), A=sum on mu_{n/2}, B=sum on odd half.

It is empirical only.  It intentionally avoids moment/energy/completion bounds.
"""
from __future__ import annotations

import argparse
import math
import numpy as np
import sympy as sp

TAU = 2.0 * math.pi


def prime_1_mod_n_near(n: int, target: int) -> int:
    k = max(1, (target - 1 + n - 1) // n)
    p = k * n + 1
    while not sp.isprime(p):
        k += 1
        p = k * n + 1
    return p


def scan_instance(n: int, beta: int, topk: int, chunk: int):
    p = prime_1_mod_n_near(n, n**beta)
    m = (p - 1) // n
    g = int(sp.primitive_root(p))
    # quotient reps b_j = g^j, subgroup mu_n = <g^m>.
    reps = np.array([pow(g, j, p) for j in range(m)], dtype=np.int64)
    G = np.array([pow(g, m * t, p) for t in range(n)], dtype=np.int64)
    Geven = G[0::2]
    Godd = G[1::2]

    vals = np.empty(m, dtype=np.complex128)
    Avals = np.empty(m, dtype=np.complex128)
    Bvals = np.empty(m, dtype=np.complex128)
    for lo in range(0, m, chunk):
        rr = reps[lo : lo + chunk]
        # Shape len(rr) x n.  The largest scanned case below is ~262k*64 total ops,
        # but chunking keeps peak memory controlled.
        phase_full = (rr[:, None] * G[None, :]) % p
        phase_even = (rr[:, None] * Geven[None, :]) % p
        phase_odd = (rr[:, None] * Godd[None, :]) % p
        vals[lo : lo + len(rr)] = np.exp(1j * TAU * phase_full / p).sum(axis=1)
        Avals[lo : lo + len(rr)] = np.exp(1j * TAU * phase_even / p).sum(axis=1)
        Bvals[lo : lo + len(rr)] = np.exp(1j * TAU * phase_odd / p).sum(axis=1)

    absvals = np.abs(vals)
    order = np.argsort(absvals)[::-1]
    best = int(order[0])
    maxv = float(absvals[best])
    mean = float(absvals.mean())
    std = float(absvals.std())
    # multiplicity of numerical near-ties in quotient space
    eps = max(1e-9, 1e-10 * maxv)
    ties = np.flatnonzero(absvals >= maxv - eps)

    def row(j: int):
        A, B = Avals[j], Bvals[j]
        denom = abs(A) + abs(B)
        rho = abs(A + B) / denom if denom else float("nan")
        cos = (np.real(A * np.conj(B)) / (abs(A) * abs(B))) if abs(A) and abs(B) else float("nan")
        return {
            "j": j,
            "abs_eta": float(absvals[j]),
            "shaw": float(absvals[j] / math.sqrt(n * math.log(p / n))),
            "rho_half": float(rho),
            "cos_half": float(cos),
            "gcd(j,m)": math.gcd(j, m),
            "j_mod_16": j % 16,
            "j_mod_32": j % 32,
        }

    top = [row(int(j)) for j in order[:topk]]
    top_indices = [r["j"] for r in top]
    # Difference gcd in Z/mZ: include the modulus, so the result is the exact
    # subgroup step generated by pairwise cyclic differences and always divides m.
    diffg = m
    for i in range(len(top_indices)):
        for j in range(i + 1, len(top_indices)):
            diffg = math.gcd(diffg, (top_indices[i] - top_indices[j]) % m)
    residue_hist16 = {r: sum(1 for j in top_indices if j % 16 == r) for r in range(16)}
    residue_hist16 = {k: v for k, v in residue_hist16.items() if v}
    return {
        "n": n,
        "p": p,
        "beta_eff": math.log(p, n),
        "m=(p-1)/n": m,
        "primitive_root": g,
        "max_abs_eta": maxv,
        "mean_abs_eta": mean,
        "std_abs_eta": std,
        "near_tie_count_quotient": int(len(ties)),
        "top_difference_gcd_mod_m": diffg,
        "top_residue_hist_mod16": residue_hist16,
        "top": top,
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ns", default="16,32,64", help="comma separated powers of two")
    ap.add_argument("--beta", type=int, default=4)
    ap.add_argument("--topk", type=int, default=16)
    ap.add_argument("--chunk", type=int, default=4096)
    args = ap.parse_args()
    for n in [int(x) for x in args.ns.split(",") if x]:
        res = scan_instance(n, args.beta, args.topk, args.chunk)
        print("=" * 88)
        print(f"n={res['n']} p={res['p']} beta_eff={res['beta_eff']:.4f} m={res['m=(p-1)/n']} g={res['primitive_root']}")
        print(f"max|eta|={res['max_abs_eta']:.12g} mean={res['mean_abs_eta']:.6g} std={res['std_abs_eta']:.6g} ties={res['near_tie_count_quotient']}")
        print(f"top_diff_gcd_mod_m={res['top_difference_gcd_mod_m']} top_residue_hist_mod16={res['top_residue_hist_mod16']}")
        for r in res["top"]:
            print(
                "  j={j:8d} |eta|={abs_eta:.12g} Sh={shaw:.6g} rho={rho_half:.9f} "
                "cos={cos_half:+.9f} gcd={gcd(j,m):6d} mod16={j_mod_16:2d} mod32={j_mod_32:2d}".format(**r)
            )


if __name__ == "__main__":
    main()
