#!/usr/bin/env python3
# LANE S4 — GF-ceiling brick at p = 65537, n = 32.
# mu_32 = {+-4^j mod p : j=0..15}, closed under negation.
# eta_1 = sum_{x in mu_32} e_p(x) = sum_{x} cos(2 pi x/p)  (real, since +-symmetric).
#
# GOAL: an axiom-clean LOWER bound on |eta_1|. Route:
#   - reduce each 4^j to its representative in (-p/2, p/2]; pair with -that.
#   - contribution of the pair {+r,-r} to eta_1 is 2 cos(2 pi r/p).
#   - "small" reps r with |r| < p/4 give cos > 0 (positive, keep as lower budget via
#     cos(t) >= 1 - t^2/2); "large" reps bounded adversarially by |cos| <= 1 (>= -1).
#   - net lower bound: sum_small 2(1 - t^2/2)  -  sum_large 2.
import math

p = 65537
n = 32

# mu_32 = <2> has ORDER 32: 2^16 = -1 mod p, 2^32 = 1 mod p.
# (Powers of 4 = <4> has order 16 only; the prompt's "B=4" was a slip.
#  The order-32 subgroup is generated by 2, and equals {+-2^k : k=0..15}.)
print("2^16 mod p =", pow(2,16,p), "(should be p-1 =", p-1, ")")
print("2^32 mod p =", pow(2,32,p), "(should be 1)")

powers = [pow(2, j, p) for j in range(32)]

# mu_32 = {2^j}; reduce each to signed rep in (-p/2, p/2]
def signed_rep(a):
    a %= p
    return a - p if a > p//2 else a

reps = sorted(set(signed_rep(powers[j]) for j in range(32)))
print("size of mu_32 =", len(reps))
assert len(reps) == 32

# eta_1 exact (float)
eta1 = sum(math.cos(2*math.pi*r/p) for r in reps)
print("eta_1 (float) =", eta1)
print("2 sqrt(n) =", 2*math.sqrt(n), "  C = |eta_1|/(2 sqrt n) =", abs(eta1)/(2*math.sqrt(n)))
print("n - eta_1 =", n - eta1, " (round-2 c_4)")

# Split by |rep| < p/4  (cos of 2pi rep/p > 0 iff |rep| < p/4)
quarter = p/4
small = [r for r in reps if abs(r) < quarter]
large = [r for r in reps if abs(r) >= quarter]
print("\n#small (|rep|<p/4, cos>0) =", len(small))
print("#large (|rep|>=p/4)      =", len(large))
print("small reps:", sorted(small, key=abs))
print("large reps:", sorted(large, key=abs))

# Lower bound: pairs. Note reps come in +-pairs, so process by absolute value.
# For each small rep r: cos(2 pi r/p) >= 1 - (2 pi r/p)^2/2  (cos t >= 1 - t^2/2).
# For each large rep: cos >= -1.
t = lambda r: 2*math.pi*abs(r)/p
lb_small = sum(1 - t(r)**2/2 for r in small)
lb_large = -1.0 * len(large)
lb = lb_small + lb_large
print("\nLB via cos t >= 1 - t^2/2 on small, cos>=-1 on large:")
print("  sum_small (1 - t^2/2) =", lb_small)
print("  -#large               =", lb_large)
print("  total LB              =", lb)
print("  actual eta_1          =", eta1)
print("  LB > 2 sqrt(n)?", lb, ">", 2*math.sqrt(n), "=>", lb > 2*math.sqrt(n))
print("  C_LB = LB/(2 sqrt n)  =", lb/(2*math.sqrt(n)))

# EXACT-RATIONAL version of the bound (for Lean): use t^2 = (2 pi |r|/p)^2 = 4 pi^2 r^2/p^2.
# 1 - t^2/2 = 1 - 2 pi^2 r^2 / p^2. Sum over small reps.
# To keep it rational, bound pi^2 <= 10 (pi^2 = 9.8696..). So 1 - t^2/2 >= 1 - 20 r^2/p^2.
from fractions import Fraction as Fr
P2 = p*p
lb_small_rat = sum(Fr(1) - Fr(20)*Fr(r*r, P2) for r in small)  # pi^2 <= 10
lb_rat = lb_small_rat - len(large)
print("\nRATIONAL LB (pi^2 <= 10): 1 - 20 r^2/p^2 on small, -1 on large:")
print("  = ", lb_rat, "=", float(lb_rat))
print("  > 2 sqrt(32) = 11.3137? ", float(lb_rat) > 2*math.sqrt(32))
print("  C_LB(rational) =", float(lb_rat)/(2*math.sqrt(32)))

# Print the small reps and their 20 r^2/p^2 terms for Lean transcription
print("\n--- for Lean: small |rep| list and rational deficits (pi^2<=10) ---")
tot = Fr(0)
for r in sorted(small, key=abs):
    ar = abs(r)
    term = Fr(1) - Fr(20)*Fr(ar*ar, P2)
    tot += term
    print(f"  |r|={ar:5d}  1-20r^2/p^2 = {float(term):.6f}")
print("  sum over small =", float(tot), "  minus #large(", len(large), ") =>", float(tot-len(large)))
