#!/usr/bin/env python3
"""
probe_dstrop_logconcave.py  (#444, TROPICAL/VALUATED-MATROID lead)

QUESTION (the lead): the over-determined char-0 far-line incidence count
#bad(n,k,w) is the binding object for delta*. The generalized-Vandermonde / NVM
structure of mu_n is a matroid; the 2-adic valuation makes it a VALUATED matroid;
Adiprasito-Huh-Katz log-concavity / Bergman-fan / tropicalization MIGHT bound
#bad combinatorially. Beukers-Smyth: isolated cyclotomic points <= O(Newton-
polytope volume).

We MEASURE three things EXACTLY (char-0, p-independent: an integer relation
sum_{a in S} zeta^a = 0 AND sum_{a in S} zeta^{3a} = 0 in Z[zeta_n], the t=2
over-determined power-sum face; zeta_n a primitive n-th root, n=2^mu):

  #bad(n,w)      = # of w-subsets S of Z/n with a CHAR-0 vanishing relation on
                   BOTH p_1 and p_3 readouts (the over-det far-line incidence).
                   By Lam-Leung (n=2^mu) a vanishing sum of n-th roots is a
                   nonneg-integer combination of antipodal pairs zeta^a+zeta^{a+n/2}.
                   So a char-0 zero of p_1 = S is a union of antipodal pairs;
                   adding the p_3 constraint (3a, also n=2^mu so antipodal again)
                   gives the OVER-DETERMINED face.

  depth d        = the dyadic coset-level (= 2-adic valuation grading of the
                   binding config): a binding config is a union of 2-power-coset
                   structure; depth d = # of distinct (n/2^d)-cosets it touches /
                   the tower rung. We grade #bad by depth and test LOG-CONCAVITY
                   of the sequence {#bad at depth d}_d.

  NP face count  = bounded faces of the dyadic-coset Newton polytope = the
                   Beukers-Smyth O(volume) proxy. We compute the literal count of
                   antipodal-matching structures (the char-0 vanishing variety's
                   lattice points) and compare its growth to the polytope volume.

VERDICT printed at the end, with the explicit NEW-HANDLE vs reduces-to-orbit-count
call. All arithmetic exact (integer relations among roots of unity via the
antipodal/Lam-Leung normal form for n=2^mu; NO floating point, NO mod-p).
"""
import itertools, math
from fractions import Fraction

# ---------------------------------------------------------------------------
# CHAR-0 vanishing test for n=2^mu via Lam-Leung normal form.
# A multiset M of exponents in Z/n has sum_{a in M} zeta_n^a = 0 in Z[zeta_n]
# (n=2^mu) IFF M decomposes into antipodal pairs {a, a+n/2}. Equivalently: the
# multiplicity vector c in Z^n satisfies c[a] = c[a+n/2] for all a in [0,n/2).
# (Lam-Leung 2000: for n a prime power, minimal vanishing sums are the full set
#  of p-th-power cosets; for p=2 these are exactly antipodal pairs.)
# For a SET S (mult 0/1) the p_1 char-0 zero condition is: S is a disjoint union
# of antipodal pairs, i.e. S = S + n/2 (closed under antipodal shift).
# ---------------------------------------------------------------------------
def antipodal_closed(S, n):
    h = n // 2
    Sset = set(S)
    return all(((a + h) % n) in Sset for a in Sset)

def p1_char0_zero(S, n):
    """sum_{a in S} zeta_n^a = 0 in Z[zeta_n], n=2^mu (Lam-Leung)."""
    return antipodal_closed(S, n)

def p3_char0_zero(S, n):
    """sum_{a in S} zeta_n^{3a} = 0. gcd(3,n)=1 so a -> 3a mod n is a bijection;
    the image multiset is {3a mod n}; char-0 zero iff that image is antipodal-closed."""
    img = [(3 * a) % n for a in S]
    return antipodal_closed(img, n)

def overdet_bad(S, n):
    """The OVER-DETERMINED char-0 far-line incidence: BOTH p_1 and p_3 vanish."""
    return p1_char0_zero(S, n) and p3_char0_zero(S, n)

# depth = dyadic coset grading. A binding (antipodal-closed) config S is a union
# of antipodal pairs; "depth d" = the coarsest 2-power-coset level at which S is
# a coset-union. We define depth(S) = mu - v, where v = max k such that S is a
# union of cosets of the order-2^k subgroup mu_{2^k} (the GPU ladder grading:
# binding configs = 2-power-subgroup coset-unions).
def coset_union_level(S, n):
    """Largest k s.t. S is a union of cosets of the subgroup of index 2^k
    (i.e. S closed under +n/2^k ... actually under the order-2^k subgroup, which
    is generated by +n/2^k? No: order-2^k subgroup of Z/n=Z/2^mu is 2^{mu-k}*Z/n,
    generated by n/2^k). Returns the largest k in [0..mu] with S + n/2^k = S
    (closed under the index-2^k subgroup's coset shift)."""
    mu = n.bit_length() - 1
    Sset = set(S)
    best = 0
    for k in range(1, mu + 1):
        step = n // (2 ** k)        # generator of the order-2^k subgroup
        if all(((a + step) % n) in Sset for a in Sset):
            best = k
        else:
            break
    return best

def depth(S, n):
    mu = n.bit_length() - 1
    return mu - coset_union_level(S, n)

# ---------------------------------------------------------------------------
# Log-concavity test
# ---------------------------------------------------------------------------
def is_log_concave(seq):
    """seq[i]^2 >= seq[i-1]*seq[i+1] for all interior i (over support, no internal zeros)."""
    s = list(seq)
    # restrict to support hull
    nz = [i for i, v in enumerate(s) if v > 0]
    if len(nz) < 3:
        return True, "trivial (<3 nonzero terms)"
    lo, hi = nz[0], nz[-1]
    # internal zeros break log-concavity of a *positive* sequence's support
    for i in range(lo, hi + 1):
        if s[i] == 0:
            return False, f"internal zero at d={i} (support [{lo},{hi}])"
    bad = []
    for i in range(lo + 1, hi):
        if s[i] * s[i] < s[i - 1] * s[i + 1]:
            bad.append((i, s[i - 1], s[i], s[i + 1]))
    return (len(bad) == 0), (bad if bad else "log-concave on support")

# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------
def census(n, wmax):
    mu = n.bit_length() - 1
    # count bad configs by (w, depth)
    by_depth = {}            # depth -> total #bad over all w
    by_w_depth = {}          # (w) -> {depth: count}
    total_bad = 0
    for w in range(2, wmax + 1, 2):   # antipodal-closed => even size
        wd = {}
        for S in itertools.combinations(range(n), w):
            if overdet_bad(S, n):
                d = depth(S, n)
                by_depth[d] = by_depth.get(d, 0) + 1
                wd[d] = wd.get(d, 0) + 1
                total_bad += 1
        if wd:
            by_w_depth[w] = wd
    return mu, by_depth, by_w_depth, total_bad

def newton_polytope_volume_proxy(n, w):
    """Beukers-Smyth O(volume): the cyclotomic-point count for the lacunary system
    {p_1=0, p_3=0} restricted to w-subsets of mu_n is <= O(vol(Newton polytope)).
    The Newton polytope of the 2-constraint system in the w-subset model has
    dimension governed by (n - 2) (two linear power-sum constraints on the n-dim
    indicator). Beukers-Smyth normalized-volume proxy here: the number of antipodal
    PAIRINGS available = product over orbit structure. We report the antipodal-pair
    selection count C(n/2, w/2)*2^? as the lattice-point ceiling for p_1 alone, and
    the antipodal pairings surviving p_3 as the over-det count -- the volume scale."""
    h = n // 2
    # p_1 char-0 zeros of size w: choose w/2 of the n/2 antipodal pairs.
    p1_only = math.comb(h, w // 2) if w % 2 == 0 else 0
    return p1_only

if __name__ == "__main__":
    print("=" * 78)
    print("probe_dstrop_logconcave: over-det #bad, depth grading, log-concavity,")
    print("                         Newton-polytope/Beukers-Smyth volume bound")
    print("=" * 78)

    for n in (16, 32):
        wmax = n // 2 if n == 16 else 8   # n=32 full census too big; cap w
        print(f"\n########## n = {n} (mu={n.bit_length()-1}), w up to {wmax} ##########")
        mu, by_depth, by_w_depth, total = census(n, wmax)
        print(f"  total over-det #bad configs (both p_1,p_3 char-0 zero): {total}")

        # depth histogram + log-concavity
        if by_depth:
            dmax = max(by_depth)
            seq = [by_depth.get(d, 0) for d in range(dmax + 1)]
            print(f"  #bad by depth d (d=0 = full mu_n coset-union, deepest ladder):")
            for d, v in enumerate(seq):
                print(f"     depth {d}: {v}")
            lc, why = is_log_concave(seq)
            print(f"  LOG-CONCAVE in depth?  {lc}   [{why}]")

        # per-w: depth grading + log-concavity of the depth slice + volume bound
        print(f"  per-w breakdown (depth-slice log-concavity + Beukers-Smyth vol bound):")
        for w in sorted(by_w_depth):
            wd = by_w_depth[w]
            dmax = max(wd)
            seq = [wd.get(d, 0) for d in range(dmax + 1)]
            lc, why = is_log_concave(seq)
            vol = newton_polytope_volume_proxy(n, w)
            cnt = sum(wd.values())
            print(f"     w={w:2d}: depth-seq={seq}  total={cnt:5d}  "
                  f"NP/BS-vol-proxy={vol:6d}  cnt<=vol? {cnt <= vol}  "
                  f"logconc(depth)? {lc}")

    print("\n" + "=" * 78)
    print("KEY: depth-seq is the {#bad at depth d} sequence (valuated-matroid prediction:")
    print("     should be LOG-CONCAVE if AHK-style holds). NP/BS-vol-proxy = C(n/2,w/2),")
    print("     the antipodal-pairing lattice-point ceiling (p_1 alone) = Beukers-Smyth")
    print("     O(volume) scale. cnt<=vol tests whether the over-det count is volume-bounded.")
    print("=" * 78)
