#!/usr/bin/env python3
"""
probe_444_verify1_stepb.py  (#444 Verify-1, step (b) the DISTINCT-primes claim)

Step (b) of the Action-Orbit argument: the c vanishing power sums (mod p) of a non-coset T
force c DISTINCT primes above p to divide beta_T, hence p^c | N(beta_T).

This probe hunts c>=2 non-coset defects (the binding regime is c=s-k>=2) and DIRECTLY checks:
  - does p^c actually divide N(beta_T)?  (the headline)
  - WHY: the argument says o_j(T)=sigma_j(beta_T) for the c Galois autos indexed by the odd
    residues j; vanishing o_j mod p puts beta_T in c distinct primes 𝔭_j above p.
    We test the mechanism: beta_T mod 𝔭 = 0 means sigma_inv(beta_T)... Instead we test the
    ROBUST consequence: power sum p_j(T) = sum x^j over T; relation to traces of beta.

KEY DISTINCTION the probe exposes:
  * o_j(T) here are POWER SUMS p_j = Σ_{x∈T} x^j  (the elementary-symmetric / Newton data).
  * sigma_j(beta_T) are GALOIS CONJUGATES of the single algebraic integer beta_T=Σ ζ^{idx}.
  These are NOT the same indexing in general: sigma_j(beta_T) = Σ_{x∈T} ζ^{j·idx(x)}, which is
  the beta of the DILATED set T^j = {x^j}. Under the reduction map ζ->generator-of-mu_n in F_p,
  sigma_j(beta_T) maps to Σ x^j = p_j(T). So "p_j(T)=0 mod p for j=1..c" = "the c conjugates
  sigma_1..sigma_c of beta_T are all ≡0 at the prime 𝔭 (and its conjugates)".
  We verify this identity exactly, then check the distinct-prime / p^c | N consequence.
"""
import itertools, cmath
from sympy import isprime, primitive_root, symbols, Poly, ZZ

def subgroup_with_idx(n,p):
    g=primitive_root(p); zeta=pow(g,(p-1)//n,p)
    out=[]; x=1
    for idx in range(n): out.append((idx,x)); x=(x*zeta)%p
    return out, zeta

def reduce_cyclotomic(coeffs, half):
    out=[0]*half
    for e,c in enumerate(coeffs):
        r=e%(2*half); sign=1
        if r>=half: r-=half; sign=-1
        out[r]+=sign*c
    return out

def beta_vec_dilated(Tidx,n,j):
    """beta of T^j = {ζ^{j*idx}}: Σ ζ^{j*idx}."""
    half=n//2; coeffs=[0]*n
    for idx in Tidx: coeffs[(j*idx)%n]+=1
    return reduce_cyclotomic(coeffs,half)

def beta_vec(Tidx,n): return beta_vec_dilated(Tidx,n,1)
def is_zero_vec(v): return all(c==0 for c in v)

def norm_beta(vec,n):
    half=n//2; X=symbols('X')
    B=Poly(sum(int(vec[i])*X**i for i in range(half)),X,domain=ZZ)
    Phi=Poly(X**half+1,X,domain=ZZ)
    return int(Phi.resultant(B))

def is_antipodal_balanced(Tidx,n):
    half=n//2; S=set(i%n for i in Tidx)
    return all(((i+half)%n in S)==(i in S) for i in range(n))

def is_coset_union_any(Tidx,n):
    """Union of cosets of ANY nontrivial 2-power subgroup H<mu_n? Test all H=<n/2^t>."""
    S=set(i%n for i in Tidx); mu=n.bit_length()-1
    for t in range(1,mu+1):
        h=n>>t  # subgroup generated by index-step h has order 2^t; its elements {0,h,2h,...}
        # actually subgroup of order 2^t = {idx : idx multiple of n/2^t}
        sub=n//(2**t)
        gen=set(range(0,n,sub))  # the order-2^t subgroup as index set
        # T is union of cosets of this subgroup iff closed under +sub-translation by the subgroup
        ok=all(((i+sub)%n in S)==(i in S) for i in range(n))
        if ok and len(gen)>1: return True
    return False

def power_sum_mod_x(Tx,j,p):
    return sum(pow(x,j,p) for x in Tx)%p

def small_primes_1modn(n,count):
    ps=[]; p=2*n+1
    while len(ps)<count:
        if isprime(p) and (p-1)%n==0: ps.append(p)
        p+=n
    return ps

def scan(n,k,s,nprimes=20):
    c=s-k; half=n//2; ceiling=s**(n/(2*c))
    print(f"\n===== n={n} k={k} s={s} c={c}  ceiling={s}^{n/(2*c):.3g}={ceiling:.6g} =====",flush=True)
    print("  (hunting c>=2 non-coset defects to test the DISTINCT-prime / p^c|N claim)",flush=True)
    found_any=False
    for p in small_primes_1modn(n,nprimes):
        elts,zeta=subgroup_with_idx(n,p); all_x=[x for _,x in elts]
        for combo in itertools.combinations(range(n),s):
            Tidx=list(combo); Tx=[all_x[i] for i in Tidx]
            if not all(power_sum_mod_x(Tx,j,p)==0 for j in range(1,c+1)): continue
            if is_antipodal_balanced(Tidx,n): continue   # coset of <n/2> -> beta=0
            v=beta_vec(Tidx,n)
            if is_zero_vec(v): continue   # also a coset-type (beta=0)
            # genuine non-coset defect with c>=? power sums vanishing
            found_any=True
            Nb=norm_beta(v,n); nb=abs(Nb); vp=0
            while nb and nb%p==0: nb//=p; vp+=1
            # VERIFY the identity sigma_j(beta) reduces to p_j(T) mod p, j odd coprime
            # check for j=1..c (odd ones matter for the c distinct conjugates)
            id_ok=True
            for j in range(1,2*c,2):  # odd j
                if j>=n: break
                vj=beta_vec_dilated(Tidx,n,j)
                # reduce vj at the prime: evaluate Σ ζ^{j idx} in F_p == p_j(T) mod p
                val=power_sum_mod_x(Tx,j,p)
                # vj is the algebraic integer; its image mod 𝔭 corresponds to plugging ζ->actual zeta:
                img=sum(vj[i]*pow(zeta,i,p) for i in range(half))%p
                if img!=val: id_ok=False
            distinct_primes_consistent = (vp>=c)
            print(f"  p={p:<7} c={c} T={Tidx}: |N|={abs(Nb)} v_p(N)={vp} "
                  f"p^c|N:{vp>=c} (need {c} distinct primes) identity[sigma_j~p_j]:{id_ok} "
                  f"|N|<=s^(n/2):{abs(Nb)<=s**half} p<=ceil:{p<=ceiling}",flush=True)
            # only show a handful per prime
        # limit output
    if not found_any:
        print("  -> NO c>=2 non-coset defect found in scanned small primes.",flush=True)

if __name__=="__main__":
    # c=2 binding config k=2,s=4 found NOTHING down to p=97. Try even-smaller-window configs
    # that admit c=2 defects: increase s so more room.
    scan(16, k=4, s=6)   # c=2, ceiling=6^4=1296
    scan(16, k=3, s=5)   # c=2, ceiling=5^4=625
    scan(16, k=5, s=7)   # c=2, ceiling=7^4=2401
    scan(16, k=2, s=4)   # the actual binding config c=2, ceiling=256
    scan(16, k=4, s=7)   # c=3, ceiling=7^(16/6)=7^2.667
