"""
sweep_A33_realizability_v2.py  —  Actionable A33 (merged 407-T05), SHARPENED.

The v1 probe showed: the TRUE realizable max |S| (largest set on which a deg-<k poly agrees
with a genuine monomial line x^a+gamma*x^b) >= sqrt(n*k) at d>=2, because COSET-UNION sets
(the legitimate Kambire bad side) are included and they reach large size.  That is EXPECTED
and does NOT bear on the R-thin lever.

R-thin is specifically about RAGGED sets (NOT unions of mu_d-cosets).  The 407-T05 claim is:
  "the orbit profile is realized by ONE deg-<k polynomial c, a Hankel/rank constraint the
   circulant-of-counts discards" -> does REALIZABILITY force the RAGGED agreement sets below
   sqrt(n*k) at intermediate d (Kambire worst direction)?

So v2 computes, EXACTLY (n=8,16 fully; n=32 heuristic):
  (R) MAX |S| over REALIZABLE RAGGED sets = largest S subset of mu_n s.t.
        (a) there exist a deg-<k poly c and a scalar gamma with c(x)=x^a+gamma x^b on all of S
            (REALIZABILITY: agreement set of one deg-<k codeword on a genuine line), AND
        (b) S is NOT a union of cosets of ANY nontrivial subgroup of mu_n (RAGGED).
  (C) MAX |S| over realizable COSET-UNION sets (the Kambire bad side, for contrast).
  compare (R) to sqrt(n*k) and to the orbit-incidence relaxation.

VERDICT criterion: if  MAX-RAGGED-REALIZABLE  <  sqrt(n*k)  at the Kambire worst direction,
char-free across primes, then REALIZABILITY BEATS the moment-method bound (= the live lever
delivers).  If it ties / exceeds, the lever is empty and R-thin is NOT closable this way.

Self-contained pure-python F_q linear algebra.
Run:  python sweep_A33_realizability_v2.py
"""

import itertools
import math
import random

# ---------------- F_q linear algebra ----------------

def inv_mod(a, q):
    return pow(a % q, q - 2, q)

def is_prime(m):
    if m < 2: return False
    if m % 2 == 0: return m == 2
    d = 3
    while d * d <= m:
        if m % d == 0: return False
        d += 2
    return True

def find_primitive_root(q):
    phi = q - 1
    fac = {}
    m = phi; d = 2
    while d * d <= m:
        while m % d == 0:
            fac[d] = 1; m //= d
        d += 1
    if m > 1: fac[m] = 1
    for g in range(2, q):
        if all(pow(g, phi // pf, q) != 1 for pf in fac):
            return g
    raise RuntimeError("no primitive root")

def mu_n_elements(n, q):
    assert (q - 1) % n == 0
    g = find_primitive_root(q)
    zeta = pow(g, (q - 1) // n, q)
    return [pow(zeta, j, q) for j in range(n)]

def rank_mod(rows, q):
    rows = [r[:] for r in rows]
    if not rows: return 0
    nc = len(rows[0]); r = 0
    for c in range(nc):
        piv = None
        for i in range(r, len(rows)):
            if rows[i][c] % q != 0:
                piv = i; break
        if piv is None: continue
        rows[r], rows[piv] = rows[piv], rows[r]
        ip = inv_mod(rows[r][c], q)
        rows[r] = [(x * ip) % q for x in rows[r]]
        for i in range(len(rows)):
            if i != r and rows[i][c] % q != 0:
                f = rows[i][c]
                rows[i] = [(rows[i][j] - f * rows[r][j]) % q for j in range(nc)]
        r += 1
        if r == len(rows): break
    return r

# ---------------- realizability + raggedness ----------------

def divisors(n):
    return [d for d in range(1, n + 1) if n % d == 0]

def is_coset_union(Sexp, n):
    """True iff Sexp (subset of Z/n) is a union of cosets of SOME nontrivial subgroup of (Z/n,+).
       Subgroups of Z/n are generated by n/d (order d), i.e. multiples of n/d for d | n, 1<=d<n
       gives subgroup {0,n/d,2n/d,...} of order d. (We treat the additive group of exponents;
       multiplicative mu_d-cosets correspond to these.)  Trivial subgroup (d=1, just {0}) and the
       whole group are excluded; a single-point set is ragged by convention only if it is forced
       (we require |S|>=2 and reject any genuine subgroup-coset-union)."""
    Sset = set(x % n for x in Sexp)
    if len(Sset) <= 1:
        return False
    for d in divisors(n):
        if d == 1 or d == n:
            continue
        g = n // d  # subgroup H = {0, g, 2g, ..., (d-1)g}, order d
        H = set((i * g) % n for i in range(d))
        # is Sset a union of H-cosets?  for every s in Sset, s+H subset Sset
        ok = True
        for s in Sset:
            for h in H:
                if (s + h) % n not in Sset:
                    ok = False; break
            if not ok: break
        if ok:
            return True
    return False

def realizable(Sexp, n, k, a, b, mu_elts, q):
    """exists deg-<k poly c and scalar gamma with c(zeta^j)=zeta^{aj}+gamma zeta^{bj} for j in Sexp.
       Solve  V_k(x) c - gamma x^b = x^a  over Sexp ; feasible iff rank(M)=rank(M|rhs)."""
    M = []; Mr = []
    for j in Sexp:
        x = mu_elts[j % n]
        vrow = [pow(x, t, q) for t in range(k)]
        xb = pow(x, b, q); xa = pow(x, a, q)
        row = vrow + [(-xb) % q]
        M.append(row); Mr.append(row + [xa % q])
    return rank_mod(M, q) == rank_mod(Mr, q)

def max_realizable_by_class(n, k, a, b, q, exhaustive=True, seeds=6000):
    """Return (max_ragged, max_coset, witness_ragged) over realizable sets."""
    mu_elts = mu_n_elements(n, q)
    best_r, best_c = 0, 0
    wit_r = None
    if exhaustive:
        # enumerate from large sizes down; track both classes
        for t in range(n, 1, -1):
            for Sexp in itertools.combinations(range(n), t):
                if not realizable(Sexp, n, k, a, b, mu_elts, q):
                    continue
                if is_coset_union(Sexp, n):
                    if t > best_c: best_c = t
                else:
                    if t > best_r:
                        best_r = t; wit_r = Sexp
            # early stop: once we have found a ragged of size t and t<=best_c context, keep scanning
            # but we want the MAX of each class, so only break when both can't grow.
            if best_r >= t and best_c >= t:
                # both already found at >= current size; smaller t cannot exceed
                if best_r > 0 and best_c > 0:
                    break
        return best_r, best_c, wit_r
    else:
        # heuristic greedy with random restarts: grow ragged + coset separately
        for _ in range(seeds):
            order = list(range(n)); random.shuffle(order)
            cur = []
            for j in order:
                cand = cur + [j]
                if realizable(cand, n, k, a, b, mu_elts, q):
                    cur = cand
            if len(cur) >= 2:
                if is_coset_union(cur, n):
                    best_c = max(best_c, len(cur))
                else:
                    if len(cur) > best_r:
                        best_r = len(cur); wit_r = tuple(cur)
        return best_r, best_c, wit_r

# ---------------- sweep ----------------

def primes_1_mod_n(n, count, start):
    out = []
    cand = ((start - 1) // n) * n + 1
    while cand <= start: cand += n
    while len(out) < count:
        if cand > 1 and is_prime(cand): out.append(cand)
        cand += n
    return out

def genuine_dir(n, k, d):
    for bb in range(k, n):
        aa = bb + d
        if aa < n and math.gcd(aa - bb, n) == d:
            return aa, bb
    return None, None

def run_for_n(n, rhos, q_list, mu, exhaustive=True):
    print("=" * 92)
    print(f"n = {n} = 2^{mu}   (exhaustive={exhaustive})")
    print("=" * 92)
    for rho in rhos:
        k = int(round(rho * n))
        if k < 1: continue
        target = math.sqrt(n * k)
        print(f"\n  rho={rho}, k={k}, sqrt(n*k)={target:.3f}")
        ds = sorted(set(math.gcd(abs(aa - bb), n)
                        for aa in range(k, n) for bb in range(k, n) if aa != bb))
        print(f"    {'d':>4} {'s':>4} {'(a,b)':>9} {'q':>9} | {'MAXragged':>9} {'sqrt(nk)':>9} {'RAGGEDbeats?':>13} {'orbit-inc':>10} {'MAXcoset':>9}")
        for d in ds:
            if d == n: continue
            s = n // d
            a, b = genuine_dir(n, k, d)
            if a is None: continue
            t1 = n / (2.0 * d)
            orbit_inc = t1 + math.sqrt(t1 * t1 + n * (d - 1) * (k - 1) / d)
            q = q_list[0]
            if (q - 1) % n != 0: continue
            mr, mc, _ = max_realizable_by_class(n, k, a, b, q, exhaustive=exhaustive)
            beats = "YES" if mr < target - 1e-9 else ("tie" if abs(mr - target) < 1e-9 else "no")
            ab = f"({a},{b})"
            print(f"    {d:>4} {s:>4} {ab:>9} {q:>9} | {mr:>9} {target:>9.3f} {beats:>13} {orbit_inc:>10.2f} {mc:>9}")

def char_test(n, rho, mu, q_list, exhaustive=True):
    k = int(round(rho * n))
    target = math.sqrt(n * k)
    ds = sorted(set(math.gcd(abs(aa - bb), n)
                    for aa in range(k, n) for bb in range(k, n) if aa != bb
                    if math.gcd(abs(aa - bb), n) not in (1, n)))
    if not ds: return
    target_d = min(ds, key=lambda dd: abs(dd - max(2, int(round(n ** 0.5)))))
    a, b = genuine_dir(n, k, target_d)
    if a is None: return
    print(f"\n  [char-test n={n} rho={rho} k={k}] worst-ish d={target_d}, s={n//target_d}, (a,b)=({a},{b}), sqrt(nk)={target:.3f}")
    vals = []
    for q in q_list:
        if (q - 1) % n != 0: continue
        mr, mc, _ = max_realizable_by_class(n, k, a, b, q, exhaustive=exhaustive)
        vals.append(mr)
        print(f"      q={q:>9}  MAXragged={mr}  MAXcoset={mc}  raggedBeats={'YES' if mr<target-1e-9 else 'no'}")
    print(f"      -> ragged char-{'INDEPENDENT' if len(set(vals))==1 else 'DEPENDENT'} (values {sorted(set(vals))})")

if __name__ == "__main__":
    print("\n### A33 v2: realizable RAGGED max vs sqrt(n*k) (coset-unions separated out)\n")

    q8 = primes_1_mod_n(8, 6, 17)
    run_for_n(8, [0.5, 0.25], q8, 3, exhaustive=True)
    char_test(8, 0.25, 3, q8, exhaustive=True)

    q16 = primes_1_mod_n(16, 6, 97)
    run_for_n(16, [0.5, 0.25, 0.125], q16, 4, exhaustive=True)
    char_test(16, 0.25, 4, q16, exhaustive=True)
    char_test(16, 0.5, 4, q16, exhaustive=True)

    q32 = primes_1_mod_n(32, 4, 193)
    run_for_n(32, [0.25], q32, 5, exhaustive=False)
    char_test(32, 0.25, 5, q32, exhaustive=False)

    print("\n### DONE.")
