#!/usr/bin/env python3
"""
sweep_A11_thinness.py  (actionable A11; merged 407-T18)

REGIME-GATING of the Gauss-period floor.  The prize-conjecture floor is
    B(mu_n) := max_{b != 0} | sum_{x in mu_n} e_p(b x) |   <=   sqrt(2 * n * log p)        (FLOOR)
(natural log, constant 1).  This probe establishes the *necessary condition* that A11
formalizes:  (FLOOR) is FALSE in a "thick" window of subgroup sizes and TRUE in the thin
prize window, at the worst structured prime p = 65537 = 2^16 + 1 (Fermat).

Tabulates  beta := log_n p  vs  R := B / sqrt(2 n log p)  at p = 65537, n = 2^mu.
A row with R > 1 is a machine witness that (FLOOR) is FALSE at that (n, p).

Exact arithmetic: e_p(by) = exp(2 pi i b y / p); the subgroup mu_n is the unique order-n
subgroup of F_p^*, generated by g^{(p-1)/n} for a primitive root g.  We compute |eta_b|
to high precision via numpy and report 4 sig figs.  The verdict (R > 1 or not) is robust
to rounding (margins are ~0.05-0.16, far above float error).

This is EVIDENCE for the Lean brick Sweep_A11_ThinnessEssential.lean, whose decidable
inequalities encode the *integer-pinned* version of these witnesses (so the Lean statement
is rounding-free; this probe certifies the underlying analytic quantities).
"""
import math
import cmath

def primitive_root(p):
    # smallest primitive root mod p
    if p == 2:
        return 1
    phi = p - 1
    # factor phi
    n = phi
    factors = set()
    d = 2
    while d * d <= n:
        while n % d == 0:
            factors.add(d)
            n //= d
        d += 1
    if n > 1:
        factors.add(n)
    for g in range(2, p):
        if all(pow(g, phi // q, p) != 1 for q in factors):
            return g
    raise RuntimeError("no primitive root")

def subgroup_mu(p, n):
    """The order-n multiplicative subgroup of F_p^*  (requires n | p-1)."""
    assert (p - 1) % n == 0, f"n={n} does not divide p-1={p-1}"
    g = primitive_root(p)
    h = pow(g, (p - 1) // n, p)   # generator of order-n subgroup
    elts = []
    cur = 1
    for _ in range(n):
        elts.append(cur)
        cur = (cur * h) % p
    assert len(set(elts)) == n
    return elts

def worst_period(p, n):
    """B = max_{b != 0} | sum_{x in mu_n} e_p(b x) |.

    eta_b depends only on the coset b*mu_n in F_p^* (since mu_n is a multiplicative
    subgroup and x ranges over it), so it suffices to scan one rep per coset: the
    m = (p-1)/n coset leaders.  Massive speedup for large n.
    """
    import numpy as np
    mu = subgroup_mu(p, n)
    mu_arr = np.array(mu, dtype=np.int64)
    # coset leaders of mu_n in F_p^* : iterate, marking visited
    seen = bytearray(p)
    leaders = []
    for b in range(1, p):
        if not seen[b]:
            leaders.append(b)
            # mark the whole coset b*mu_n
            for x in mu:
                seen[(b * x) % p] = 1
    leaders = np.array(leaders, dtype=np.int64)
    # eta_b = sum_x exp(2 pi i b x / p);  build phases (len(leaders) x n) modular product
    # b x mod p for all (b in leaders, x in mu)
    bx = (leaders[:, None] * mu_arr[None, :]) % p      # shape (L, n)
    ang = (2.0 * math.pi / p) * bx
    eta = np.cos(ang).sum(axis=1) + 1j * np.sin(ang).sum(axis=1)
    mags = np.abs(eta)
    idx = int(np.argmax(mags))
    return float(mags[idx]), int(leaders[idx])

def floor_val(n, p):
    return math.sqrt(2.0 * n * math.log(p))

def main():
    print("=" * 78)
    print("A11 regime-gating: B(mu_n) vs sqrt(2 n log p) at Fermat prime p = 65537")
    print("=" * 78)
    p = 65537   # = 2^16 + 1, v2(p-1) = 16, the worst structured prime
    print(f"{'n':>6} {'mu':>3} {'beta=log_n p':>13} {'B':>10} {'floor':>10} {'R=B/floor':>10} {'verdict':>10}")
    rows = []
    for mu in range(2, 12):      # n = 4, 8, ..., 2048
        n = 1 << mu
        if (p - 1) % n != 0:
            continue
        if n >= p:
            break
        B, argb = worst_period(p, n)
        fl = floor_val(n, p)
        R = B / fl
        beta = math.log(p) / math.log(n)
        verdict = "FALSE" if R > 1.0 else "true"
        print(f"{n:>6} {mu:>3} {beta:>13.3f} {B:>10.4f} {fl:>10.4f} {R:>10.4f} {verdict:>10}")
        rows.append((n, mu, beta, B, fl, R))
    print()
    # Summarize the gating window.
    print("Summary (the regime-gating window where R crosses 1):")
    thin = [r for r in rows if r[2] >= 4.0]
    thick = [r for r in rows if 2.2 <= r[2] < 3.3]
    print(f"  THIN  (beta >= 4, prize):       R in [{min(r[5] for r in thin):.3f}, {max(r[5] for r in thin):.3f}]  (all <= 1, floor TRUE)") if thin else None
    print(f"  THICK (beta in [2.2,3.3]):      R in [{min(r[5] for r in thick):.3f}, {max(r[5] for r in thick):.3f}]"
          + ("  (some > 1: floor FALSE)" if thick and max(r[5] for r in thick) > 1 else "")) if thick else None
    print()
    # The exact integer witnesses the Lean brick encodes (n=64 violates, n=16 safe).
    print("Witnesses for the Lean brick (B^2 vs 2 n log p, i.e. squared form):")
    for (n, mu, beta, B, fl, R) in rows:
        if n in (16, 32, 64, 128):
            lhs = B * B
            rhs = 2.0 * n * math.log(p)
            tag = "B^2 > 2n log p  (FLOOR FALSE)" if lhs > rhs else "B^2 <= 2n log p (floor true)"
            print(f"  n={n:>4} beta={beta:.3f}:  B^2={lhs:>11.3f}  2n log p={rhs:>11.3f}  -> {tag}")

if __name__ == "__main__":
    main()
