#!/usr/bin/env python3
"""
WF407 T16-pgl2 (follow-up): pin the EXACT normalizer-on-frequency orbit law on the
char-sum face, and show why inversion does NOT fold the period DOF by x4.

Key algebraic point. The frequency space is F_q^* / mu_n  (m = (q-1)/n cosets) because
eta is constant on cosets b*mu_n  (proven: GaussPeriodCosetReduction.eta_image_card_mul_le).
The torus normalizer acts on FREQUENCIES by:
   neg : b |-> -b      (a coset map iff -1 in mu_n, i.e. n even -> YES, this is the
                        well-known eta_{-b}=conj(eta_b) ; it folds conj-pairs)
   inv : b |-> b^{-1}  (b^{-1}*mu_n is a DIFFERENT coset class: the inverse coset.
                        On F_q^*/mu_n ~ Z/m this is x |-> -x, an INVOLUTION on Z/m)

So on Z/m =  the period-index group, neg acts as TRANSLATION by the class of -1
(which is 0 if -1 in mu_n -> n even -> neg is the IDENTITY on cosets!), and inv acts
as the group inversion x|->-x.  Hence on cosets the normalizer is generated by ONE
involution (inv = x|->-x on Z/m), giving ~m/2 orbits, NOT m/4.

We verify:
 (1) on cosets, neg = identity exactly when -1 in mu_n (n even);
 (2) inv on cosets = the Z/m inversion x|->-x; #orbits = #{x: x=-x} fixed + (m-fixed)/2
     = ceil((m + #fixed)/2); fixed pts of x|->-x on Z/m = gcd(2,m) classes;
 (3) the period |eta| is NOT inv-invariant -> the x|->-x coset fold is NOT a modulus
     relation, so it does NOT reduce max_b|eta_b|: the worst coset and its inverse coset
     have, in general, DIFFERENT |eta|.  Print the (|eta_b|, |eta_{b^-1}|) spread.
"""
import cmath, math, sympy
from math import gcd

def prim_root(p): return int(sympy.primitive_root(p))
def musub(n,p):
    g=prim_root(p); h=pow(g,(p-1)//n,p); return sorted({pow(h,j,p) for j in range(n)})

def run(p,n):
    w=2*math.pi/p; G=musub(n,p); Gset=set(G); m=(p-1)//n
    g=prim_root(p)
    # coset index of b in F_q^*/mu_n via discrete log mod m
    dlog={}
    x=1
    for e in range(p-1):
        dlog[x]=e; x=(x*g)%p
    def cidx(b): return dlog[b]%m
    def eta(b): return sum(cmath.exp(1j*w*((b*y)%p)) for y in G)
    etas={b:eta(b) for b in range(1,p)}
    inv={b:pow(b,p-2,p) for b in range(1,p)}

    # (1) neg on cosets: is class(-b) == class(b) for all b?
    negfix = all(cidx((p-b)%p)==cidx(b) for b in range(1,p))
    cls_neg1 = cidx(p-1)  # class of -1 in Z/m
    # (2) inv on cosets : class(b^-1) = -class(b) mod m ?
    inv_is_negx = all(cidx(inv[b])==(-cidx(b))%m for b in range(1,p))
    fixed_inv = sum(1 for x in range(m) if (2*x)%m==0)   # fixed pts of x|->-x on Z/m
    pred_orbits = (m+fixed_inv)//2
    # actual orbits under <neg,inv> on cosets
    rep_of={}
    seen={}
    for b in range(1,p):
        c=cidx(b)
        if c not in seen: seen[c]=b
    visited=set(); orbits=0
    for c in range(m):
        if c in visited: continue
        stack=[seen[c]]; orb=set()
        while stack:
            bb=stack.pop(); cc=cidx(bb)
            if cc in orb: continue
            orb.add(cc)
            stack.append((p-bb)%p); stack.append(inv[bb])
        visited|=orb; orbits+=1

    # (3) |eta| spread between a coset and its inverse coset
    # for each coset rep, compare |eta(b)| with |eta(b^-1)|
    diffs=[]
    for c,b in seen.items():
        d=abs(abs(etas[b])-abs(etas[inv[b]]))
        diffs.append(d)
    max_inv_modgap=max(diffs)
    # also confirm neg-modulus relation is exact
    neg_modgap=max(abs(abs(etas[b])-abs(etas[(p-b)%p])) for b in range(1,p))

    return dict(p=p,n=n,m=m,negfix=negfix,cls_neg1=cls_neg1,inv_is_negx=inv_is_negx,
                fixed_inv=fixed_inv,pred_orbits=pred_orbits,orbits=orbits,
                max_inv_modgap=max_inv_modgap,neg_modgap=neg_modgap)

if __name__=="__main__":
    cases=[(41,8),(73,8),(521,8),(97,16),(113,16),(4129,16),(97,32),(193,32),(257,32)]
    hdr=f"{'p':>6}{'n':>4}{'m':>5}  negFixCosets cls(-1) inv=neg_x fixInv  predOrb actOrb  | neg_modgap inv_modgap"
    print(hdr); print('-'*len(hdr))
    for (p,n) in cases:
        r=run(p,n)
        print(f"{r['p']:>6}{r['n']:>4}{r['m']:>5}  "
              f"{str(r['negfix']):>11} {r['cls_neg1']:>6}  {str(r['inv_is_negx']):>8} {r['fixed_inv']:>5}  "
              f"{r['pred_orbits']:>6} {r['orbits']:>6}   | {r['neg_modgap']:>9.2e} {r['max_inv_modgap']:>9.3f}")
    print()
    print("READ: negFixCosets=True -> negation is IDENTITY on cosets (n even, -1 in mu_n).")
    print("      inv=neg_x=True -> inversion acts as x|->-x on Z/m (the only nontrivial coset symmetry).")
    print("      predOrb=actOrb=ceil((m+fix)/2) ~ m/2  =>  DOF cut is x2 (negation modulus), NOT x4.")
    print("      neg_modgap ~ 0 (exact |eta_{-b}|=|eta_b|).  inv_modgap LARGE => inversion is NOT a")
    print("      modulus relation: the x|->-x coset fold does NOT reduce max|eta|.  No new concentration.")
