export const meta = {
  name: 'etacrit-synthesis-444',
  description: 'Verify/refute the eta-crit synthesis unifying the even/odd descent + Action-Orbit norm bound + the BGK wall for delta* (prize list-decoding)',
  phases: [
    { title: 'Verify', detail: 'norm-bound rigor, eta_crit formula, numerical defect-onset in the wall regime' },
    { title: 'Audit', detail: 'ePrint 2026/861 (Chai-Fan Action-Orbit) + in-tree Sweep_A10 vs the eta-crit picture' },
    { title: 'Attack', detail: 'can anything push eta_crit -> 0 (the actual prize)? sharper-than-AM-GM / 2-power obstruction' },
    { title: 'Synthesize', detail: 'go/no-go + the precise honest verdict' },
  ],
}

const REPO = 'C:/Users/Administrator/arklib'
const CTX = `
CONTEXT (#444 delta* prize). Two grand challenges (list-decoding + MCA), one threshold delta*.
Prize regime: mu_n = order-n (n=2^mu) multiplicative subgroup of F_p*, PROPER (m=(p-1)/n>=2, NEVER n=p-1),
p ~ n^4..n^5 prime (Burgess barrier beta~4), eps*=2^-128, p ~ n*2^128, prize n~2^30 (mu=30), log2(p)~128+mu.
Window interior radius delta = 1-rho-eta, rho=k/n in {1/2,1/4,1/8,1/16}; delta* sits at eta = Theta(1/log n)
(KKH26), i.e. near capacity. Honesty contract: exact arithmetic / axiom-clean Lean only; multi-prime; never the
full group; exclude correlated x^{n/2}=+-1; a refutation is a WIN; NEVER fabricate closure.

THE NEW SYNTHESIS UNDER TEST (this session). Two independent threads CONVERGE:
(1) EVEN/ODD DESCENT (list-decoding side, axiom-clean Frontier/Sweep_A40_EvenOddDescentIdentity.lean): the window
    list of the binding word x^{n/4}+1 at agreement s equals EXACTLY #{size-s subsets T of mu_n with the first
    c := s-k power sums vanishing mod p} (verified n=16: list=count=4 = the 4 binomial cosets X^{n/4}-c, c in mu_4).
(2) ACTION-ORBIT norm bound (Chai-Fan ePrint 2026/861; in-tree Frontier/Sweep_A10_ActionOrbitBadPrime.lean,
    AXIOM-CLEAN badPrimeBound_core): a NON-coset defect subset T (beta_T = sum_{x in T} zeta^{idx(x)} != 0 over C by
    Lam-Leung rigidity for 2-power n) with c vanishing power sums mod p forces c distinct primes above p to divide
    beta_T, so p^c | N(beta_T) <= |T|^{phi(n)} = s^{n/2}. Hence DEFECT REQUIRES p <= s^{n/(2c)}.

THE eta-crit CLAIM. At the window radius, c = s-k = eta*n, s=(rho+eta)n, so the norm ceiling is
   p <= s^{n/(2c)} = s^{1/(2 eta)}.
=> the binding list is PROVABLY BOUNDED (no defect, list = char-0 coset count = O(1)) iff
   log2(p) > (1/(2 eta)) * log2(s),  i.e.  eta > eta_crit := mu / (2*(128+mu))  (approx, for prize params).
For mu=30: eta_crit ~ 0.095. But delta* lives at eta_delta* = Theta(1/mu) ~ 0.033 < eta_crit => the norm bound is
VACUOUS at delta* => the BGK wall. eta_crit GROWS with mu (toward 1/2) while eta_delta* ~ 1/mu SHRINKS => the gap
WIDENS at scale. CONCLUSION (to verify): the descent + Action-Orbit make the list-decoding bound CLEAN for
eta > eta_crit (a constant), but delta* is in the wall regime eta < eta_crit; no closure, but a SHARP quantitative
boundary explaining exactly why every clean route is "delta*-irrelevant".

Probes you can run/extend (sympy installed; python3 -u; exact mod-p arithmetic):
  ${REPO}/scripts/probes/probe_444_worstword_exponent.py   (list_RS, subgroup, find_window_prime helpers)
  ${REPO}/scripts/probes/probe_444_list_eq_lacunary.py     (list == lacunary count)
  ${REPO}/scripts/probes/probe_444_binomial_gapfactor.py   (lacunary subsets == binomials)
  /tmp/defect_onset.py (n=16: ZERO defects at all primes), /tmp/condcount.py (condition-count vs list)
In-tree: Frontier/Sweep_A10_ActionOrbitBadPrime.lean, Frontier/Sweep_A40_EvenOddDescentIdentity.lean,
  DISPROOF_LOG.md, docs/kb/deltastar-444-evenodd-descent.md.
Return ONLY the structured fields requested.`

const V = {
  type: 'object',
  properties: {
    finding: { type: 'string', description: 'precise finding with exact numbers / formulas' },
    verdict: { type: 'string', enum: ['supports-synthesis', 'refutes-synthesis', 'inconclusive'] },
    detail: { type: 'string', description: 'the key numbers, the gap if any, reproduce command' },
  },
  required: ['finding', 'verdict', 'detail'],
}

phase('Verify')
const verify = await parallel([
  () => agent(`${CTX}

YOUR TASK (Verify-1: the norm-bound argument RIGOR). Independently re-derive and CHECK the Action-Orbit norm bound
applied to the descent's list-defect: for a NON-coset size-s subset T of mu_n (n=2^mu) with the first c power sums
vanishing mod p, does p^c | N(beta_T) genuinely hold, and is |N(beta_T)| <= s^{n/2}? Verify each step: (a) beta_T != 0
over C for non-coset T (Lam-Leung: vanishing sums of 2-power roots of unity are generated by antipodal pairs; a
non-coset T is not antipodal-balanced) -- is this EXACTLY right, or are there non-coset T with beta_T=0? (b) do c
DISTINCT primes above p divide beta_T (needs the c vanishing power sums to correspond to c distinct Galois
conjugates being 0 mod p)? (c) the norm bound |sigma(beta_T)| <= s. Find any GAP in the argument. Verify numerically
at n=16,32 that whenever a non-coset defect exists, p <= s^{n/(2c)} holds (no defect above the ceiling).`,
    { label: 'verify:norm-rigor', phase: 'Verify', schema: V }),

  () => agent(`${CTX}

YOUR TASK (Verify-2: DEFECT ONSET at larger n -- the decisive numerical test). At n=16 there are ZERO non-coset
defects at ANY prime (too rigid). Search for the FIRST n and prime where a non-coset defect actually appears (a
non-coset size-s subset T of mu_n with first c=s-k power sums = 0 mod p). Use a SMALL number of conditions c (e.g.
c=2,3 -- the wall regime where the ceiling is high) so defects are possible, at n=32,64,128 if feasible (use clever
search, not full C(n,s) enumeration: e.g. fix most of T as a partial coset and solve for the rest, or use the
weight-bounded surrogate then verify exact). KEY QUESTION: when a defect first appears, does p <= s^{n/(2c)} (norm
ceiling) hold? And does the defect appear at SMALL c (wall regime) but NOT large c (clean regime)? Report the
smallest (n, p, c) with a defect and whether it obeys the ceiling.`,
    { label: 'verify:defect-onset', phase: 'Verify', schema: V }),

  () => agent(`${CTX}

YOUR TASK (Verify-3: the eta_crit FORMULA + the widening gap). Verify the claim that, at the window radius,
c = s-k = eta*n and the norm ceiling is p <= s^{1/(2 eta)}, so the clean/wall boundary is eta_crit = mu/(2(128+mu)).
Compute eta_crit precisely (keep the log2(rho+eta) term) for mu in {20,25,30,35,40} and rho in {1/8,1/16}, and
compare to eta_delta* = Theta(1/mu) (the KKH26 delta* location, eta ~ c0/log n). Confirm: (a) eta_delta* < eta_crit
for all prize-scale mu (delta* in the wall regime); (b) the gap eta_crit - eta_delta* WIDENS as mu grows (eta_crit ->
toward a constant ~1/2, eta_delta* -> 0). Is there any mu where eta_delta* >= eta_crit (which would make delta*
clean)? Report the exact eta_crit values and whether delta* is ever clean.`,
    { label: 'verify:eta-crit', phase: 'Verify', schema: V }),
])

phase('Audit')
const audit = await agent(`${CTX}

YOUR TASK (Audit ePrint 2026/861 + in-tree Sweep_A10). Read Frontier/Sweep_A10_ActionOrbitBadPrime.lean,
DISPROOF_LOG.md (search "Action-Orbit"/"Chai-Fan"/"2026/861"/"Q1"), and the relevant memory. Determine: (1) does
Chai-Fan ePrint 2026/861 CLAIM to close delta* / the prize, or only a soundness gate / the deep-window (large-c)
regime? (2) Is the campaign's "delta*-irrelevant" verdict on Action-Orbit EXACTLY the eta < eta_crit collapse
(i.e. the norm bound governs simultaneous/many-condition vanishing but delta* is the few-condition single-window
o_1=0)? (3) Does 2026/861 OVERCLAIM relative to what it proves (the literature flagged it as prize-adjacent, audit
skeptically)? (4) Is the eta_crit quantitative boundary NEW relative to what's already in-tree, or already known
(the campaign has 'EffectiveTransfer p>2^n' and 'p<=n^2/4' thresholds -- is eta_crit a sharper unifying statement)?`,
  { label: 'audit:861', phase: 'Audit', schema: {
      type: 'object',
      properties: {
        claims_delta_star: { type: 'string', enum: ['yes-claims-closure', 'no-only-soundness-or-deepwindow', 'unclear'] },
        eta_crit_is_new: { type: 'string', enum: ['new-sharper', 'already-known', 'partial'] },
        assessment: { type: 'string' },
      }, required: ['claims_delta_star', 'eta_crit_is_new', 'assessment'] } })

phase('Attack')
const attack = await parallel([
  () => agent(`${CTX}

YOUR TASK (Attack-1: can a SHARPER norm bound push eta_crit -> 0?). The norm bound used AM-GM: |N(beta_T)| <= s^{n/2}.
This is loose (equality only if all conjugates equal). For the SPECIFIC defect subsets T (with c vanishing power sums),
the conjugates |sigma(beta_T)| are NOT all equal -- and c of them are SMALL (divisible by p, so |sigma|>=... actually
the vanishing ones are 0 mod p but nonzero in C). Can a sharper bound on |N(beta_T)| (using that c conjugates are
p-divisible hence have |sigma(beta_T)| >= 1 but the OTHERS are constrained) LOWER the ceiling, pushing eta_crit toward
0 (which would make delta* clean = solve the prize)? Or is AM-GM essentially tight for the worst-case T (so eta_crit
cannot be improved)? This is THE prize question. Be rigorous; test numerically whether N(beta_T) for actual defects
is close to s^{n/2} (AM-GM tight) or much smaller (room to improve).`,
    { label: 'attack:sharper-norm', phase: 'Attack', schema: V }),

  () => agent(`${CTX}

YOUR TASK (Attack-2: a 2-POWER-specific obstruction at small c?). The char-0 rigidity (Tao cyclic uncertainty /
Lam-Leung / divisors of X^n-1) says: a size-s subset of mu_n (n=2^mu) with first c power sums vanishing OVER C is a
union of mu_tau-cosets (tau = least 2-power >= c+1). Over F_p the defect = NON-coset solutions. The cyclotomic
resultants Res(Phi_{2^a}, Phi_{2^b}) are POWERS OF 2, hence coprime to the ODD prime p. Does this 2-power coprimality
give a CHAR-P rigidity (no non-coset defect) that holds at SMALL c (where the norm bound fails)? I.e., can the
elementary cyclotomic-divisibility proof of char-0 rigidity be transferred to char-p for 2-power n, killing the
defect at all c (including the delta* regime)? Or does the splitting of Phi_{2^a} mod p (p=1 mod n) break the transfer
(the known additive-energy defect)? Determine precisely where the char-0 -> char-p transfer breaks for small c.`,
    { label: 'attack:2power-rigidity', phase: 'Attack', schema: V }),
])

phase('Synthesize')
const syn = await agent(`${CTX}

YOUR TASK (Synthesis). Collate into ONE go/no-go verdict on the eta_crit synthesis and whether ANY of the attack
routes (sharper norm bound, 2-power char-p rigidity) reaches eta_crit -> 0 (= the prize). State precisely: what is
now PROVEN/clean (which eta regime), what is the SHARP boundary (eta_crit formula), and what remains the open wall
(eta < eta_crit, the delta* regime). Be brutally honest -- if nothing reaches the prize, say so and give the precise
residual.

VERIFY: ${JSON.stringify(verify.map(r=>r&&{v:r.verdict,f:r.finding}))}
AUDIT: ${JSON.stringify(audit)}
ATTACK: ${JSON.stringify(attack.map(r=>r&&{v:r.verdict,f:r.finding}))}`,
  { label: 'synthesis', phase: 'Synthesize' })

return { verify, audit, attack, synthesis: syn }
