/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import ArkLib.Data.CodingTheory.ProximityGap.Frontier._G156PrimitiveSwapParity
import ArkLib.Data.CodingTheory.ProximityGap.Frontier._G150PrimitivePacketDepthTwoBase

/-!
# G161: negation-stabilizer rigidity for primitive balanced cores

For the production two-power multiplicative subgroup, negation preserves the ambient support.
This file proves a characteristic-free packet statement under the exact no-fixed-point hypothesis:
if negation preserves each endpoint of a primitive balanced core, then that core has depth exactly
two.  Indeed, choosing one point from each endpoint produces two antipodal pairs; both sum to zero
and form a balanced subcore.  Primitivity forces that subcore to be the whole packet.

Thus above depth two the endpointwise-negation stabilizer class is empty.  This removes one fixed
class from the Klein-four action generated by endpoint swap and negation, preparing a stronger
orbit divisor than G156 parity.

Issue #466.
-/

set_option autoImplicit false

namespace ArkLib.ProximityGap.Frontier.G161NegationStabilizerRigidity

open scoped BigOperators
open ArkLib.ProximityGap.Frontier.G147ConnectedBalancedCoreRecursion
open ArkLib.ProximityGap.Frontier.G150PrimitivePacketDepthTwoBase
open ArkLib.ProximityGap.Frontier.G152DepthFourCompositeCensus
open ArkLib.ProximityGap.Frontier.G145LowerDepthMultiplicityEnvelope

variable {F : Type*} [AddCommGroup F] [Fintype F] [DecidableEq F]

def antipodalPair (x : F) : Finset F := {x, -x}

theorem neg_mem_of_image_neg_eq {S : Finset F} (hS : S.image Neg.neg = S)
    {x : F} (hx : x ∈ S) : -x ∈ S := by
  rw [← hS]
  exact Finset.mem_image.mpr ⟨x, hx, rfl⟩

theorem antipodalPair_subset_of_image_neg_eq {S : Finset F}
    (hS : S.image Neg.neg = S) {x : F} (hx : x ∈ S) : antipodalPair x ⊆ S := by
  intro z hz
  simp only [antipodalPair, Finset.mem_insert, Finset.mem_singleton] at hz
  rcases hz with rfl | rfl
  · exact hx
  · exact neg_mem_of_image_neg_eq hS hx

theorem antipodalPair_card {x : F} (hx : -x ≠ x) : (antipodalPair x).card = 2 := by
  simp [antipodalPair, Ne.symm hx]

theorem antipodalPair_sum (x : F) (hx : -x ≠ x) :
    ∑ z ∈ antipodalPair x, z = 0 := by
  simp [antipodalPair, Ne.symm hx]

/-- Two endpointwise antipodal pairs form a balanced subcore. -/
theorem antipodalPairCore_balanced {c : Finset F × Finset F}
    (hc : IsBalancedCore c)
    (hnegL : c.1.image Neg.neg = c.1) (hnegR : c.2.image Neg.neg = c.2)
    {x y : F} (hx : x ∈ c.1) (hy : y ∈ c.2)
    (hfreeX : -x ≠ x) (hfreeY : -y ≠ y) :
    IsBalancedCore (antipodalPair x, antipodalPair y) := by
  refine ⟨⟨x, by simp [antipodalPair]⟩, ?_, ?_, ?_⟩
  · rw [antipodalPair_card hfreeX, antipodalPair_card hfreeY]
  · exact hc.2.2.1.mono
      (antipodalPair_subset_of_image_neg_eq hnegL hx)
      (antipodalPair_subset_of_image_neg_eq hnegR hy)
  · rw [antipodalPair_sum x hfreeX, antipodalPair_sum y hfreeY]

/-- A negation-stable balanced core of depth above two contains a proper antipodal balanced
subcore. -/
theorem exists_proper_antipodal_subcore {c : Finset F × Finset F}
    (hc : IsBalancedCore c)
    (hnegL : c.1.image Neg.neg = c.1) (hnegR : c.2.image Neg.neg = c.2)
    (hfree : ∀ z ∈ c.1 ∪ c.2, -z ≠ z) (hdepth : 2 < c.1.card) :
    ∃ d, IsProperBalancedSubcore d c := by
  obtain ⟨x, hx⟩ := hc.1
  have hcR : c.2.Nonempty := by
    rw [← Finset.card_pos, ← hc.2.1]
    exact Finset.card_pos.mpr hc.1
  obtain ⟨y, hy⟩ := hcR
  let d : Finset F × Finset F := (antipodalPair x, antipodalPair y)
  have hdx : -x ≠ x := hfree x (Finset.mem_union_left _ hx)
  have hdy : -y ≠ y := hfree y (Finset.mem_union_right _ hy)
  refine ⟨d, antipodalPairCore_balanced hc hnegL hnegR hx hy hdx hdy,
    antipodalPair_subset_of_image_neg_eq hnegL hx,
    antipodalPair_subset_of_image_neg_eq hnegR hy, ?_⟩
  intro heq
  have hcard := congrArg Finset.card heq
  change (antipodalPair x).card = c.1.card at hcard
  rw [antipodalPair_card hdx] at hcard
  omega

/-- **G161 capstone.** An endpointwise-negation-stable primitive packet is forced to be the
depth-two antipodal base packet. -/
theorem primitive_negation_stable_card_eq_two {c : Finset F × Finset F}
    (hc : IsPrimitiveBalancedCore c)
    (hnegL : c.1.image Neg.neg = c.1) (hnegR : c.2.image Neg.neg = c.2)
    (hfree : ∀ z ∈ c.1 ∪ c.2, -z ≠ z) : c.1.card = 2 := by
  have hle : c.1.card ≤ 2 := by
    by_contra h
    have hgt : 2 < c.1.card := by omega
    exact hc.2 (exists_proper_antipodal_subcore hc.1 hnegL hnegR hfree hgt)
  exact Nat.le_antisymm hle (primitiveCore_two_le_left_card hc)

theorem not_primitive_negation_stable_of_two_lt {c : Finset F × Finset F}
    (hc : IsPrimitiveBalancedCore c) (hdepth : 2 < c.1.card)
    (hfree : ∀ z ∈ c.1 ∪ c.2, -z ≠ z) :
    ¬(c.1.image Neg.neg = c.1 ∧ c.2.image Neg.neg = c.2) := by
  rintro ⟨hL, hR⟩
  have := primitive_negation_stable_card_eq_two hc hL hR hfree
  omega

/-- Endpointwise-negation-fixed part of the finite primitive census. -/
noncomputable def negationStablePrimitiveCorePairs (G : Finset F) (t : ℕ) :
    Finset (Finset F × Finset F) :=
  (primitiveCorePairs G t).filter fun c =>
    c.1.image Neg.neg = c.1 ∧ c.2.image Neg.neg = c.2

/-- **Finite G161 capstone.** Above depth two the negation-fixed primitive sector is empty whenever
the ambient support has no fixed point under negation. -/
theorem negationStablePrimitiveCorePairs_eq_empty
    (G : Finset F) {t : ℕ} (ht : 2 < t)
    (hfreeG : ∀ z ∈ G, -z ≠ z) :
    negationStablePrimitiveCorePairs G t = ∅ := by
  classical
  rw [Finset.eq_empty_iff_forall_notMem]
  intro c hc
  rw [negationStablePrimitiveCorePairs, Finset.mem_filter] at hc
  obtain ⟨hcPrimMem, hstable⟩ := hc
  rw [primitiveCorePairs, Finset.mem_filter] at hcPrimMem
  obtain ⟨hcCore, hcPrim⟩ := hcPrimMem
  have hcard : c.1.card = t := by
    exact (Finset.mem_powersetCard.mp (mem_subsetCorePairs_iff.mp hcCore).1).2
  apply not_primitive_negation_stable_of_two_lt hcPrim (by omega) ?_ hstable
  intro z hz
  rw [Finset.mem_union] at hz
  rcases hz with hz | hz
  · exact hfreeG z ((Finset.mem_powersetCard.mp
      (mem_subsetCorePairs_iff.mp hcCore).1).1 hz)
  · exact hfreeG z ((Finset.mem_powersetCard.mp
      (mem_subsetCorePairs_iff.mp hcCore).2.1).1 hz)

#print axioms antipodalPairCore_balanced
#print axioms exists_proper_antipodal_subcore
#print axioms primitive_negation_stable_card_eq_two
#print axioms not_primitive_negation_stable_of_two_lt
#print axioms negationStablePrimitiveCorePairs_eq_empty

end ArkLib.ProximityGap.Frontier.G161NegationStabilizerRigidity
