/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import ArkLib.Data.CodingTheory.ProximityGap.Frontier._G201CommonEnvelopeStepanov

/-!
# G202: common envelopes need not retain the subgroup exponent

G201 bounds the affine collision through a root-of-unity envelope `H` containing `2G` and `-G`.
There is no uniform zero-overhead choice: if `1 ∈ G`, `2G ⊆ H`, and every element of `H` has
`n`-th power one, then necessarily `2^n=1`.

For the genuine order-eight subgroup generated by `3` in `F₄₁ˣ`, `2^8=10≠1`.  Hence no
envelope containing even `2G` can retain exponent eight.  In fact `-2` has order twenty in this
field, illustrating the arithmetic enlargement that G201 exposes.

Issue #466.
-/

set_option autoImplicit false

namespace ArkLib.ProximityGap.Frontier.G202EnvelopeExponentOverhead

variable {F : Type*} [Semiring F] [DecidableEq F]

/-- **Necessary condition for retaining exponent `n` after adjoining the coefficient `2`.** -/
theorem two_pow_eq_one_of_envelope (G H : Finset F) (n : ℕ) (hone : 1 ∈ G)
    (htwo : ∀ u ∈ G, (1 + 1) * u ∈ H) (hpow : ∀ x ∈ H, x ^ n = 1) :
    (1 + 1 : F) ^ n = 1 := by
  have hmem := htwo 1 hone
  simpa using hpow ((1 + 1) * 1) hmem

namespace F41

local instance : Fact (Nat.Prime 41) := ⟨by decide⟩

def G : Finset (ZMod 41) := {1, 3, 9, 27, 40, 38, 32, 14}

theorem G_is_order_eight_subgroup : G.card = 8 ∧ (1 : ZMod 41) ∈ G ∧
    (∀ x ∈ G, ∀ y ∈ G, x * y ∈ G) ∧
      (∀ x ∈ G, x⁻¹ ∈ G) ∧ (0 : ZMod 41) ∉ G := by
  decide

theorem two_pow_eight_eq_ten : (2 : ZMod 41) ^ 8 = 10 := by decide

theorem two_pow_eight_ne_one : (2 : ZMod 41) ^ 8 ≠ 1 := by decide

/-- **Concrete smooth-subgroup envelope obstruction.** No root-of-unity envelope containing
`2G` can keep the original exponent eight. -/
theorem no_exponent_eight_envelope :
    ¬∃ H : Finset (ZMod 41),
      (∀ u ∈ G, (1 + 1) * u ∈ H) ∧ (∀ x ∈ H, x ^ 8 = 1) := by
  rintro ⟨H, htwo, hpow⟩
  have hone : (1 : ZMod 41) ∈ G := G_is_order_eight_subgroup.2.1
  have h := two_pow_eq_one_of_envelope G H 8 hone htwo hpow
  exact two_pow_eight_ne_one h

theorem neg_two_pow_twenty_eq_one : (-2 : ZMod 41) ^ 20 = 1 := by decide

theorem neg_two_pow_ten_ne_one : (-2 : ZMod 41) ^ 10 ≠ 1 := by decide

theorem neg_two_no_positive_power_lt_twenty :
    ∀ k : Fin 19, (-2 : ZMod 41) ^ (k + 1 : ℕ) ≠ 1 := by
  decide

#print axioms G_is_order_eight_subgroup
#print axioms no_exponent_eight_envelope
#print axioms neg_two_pow_twenty_eq_one
#print axioms neg_two_pow_ten_ne_one
#print axioms neg_two_no_positive_power_lt_twenty

end F41

#print axioms two_pow_eq_one_of_envelope

end ArkLib.ProximityGap.Frontier.G202EnvelopeExponentOverhead
