/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Data.Finset.Powerset
import Mathlib.GroupTheory.SpecificGroups.Cyclic
import Mathlib.Data.ZMod.Basic
import Mathlib.Algebra.Group.Submonoid.BigOperators
import Mathlib.Data.Set.Card

/-!
# The multiplicative subset-product spectrum of a smooth (subgroup) domain (#357)

The additive jump connection (dossier §10) shows the MCA bad-scalar count at the granularity jump
equals the number of distinct `(k+1)`-subset *sums* of the evaluation domain. Its **multiplicative
twin** (§16, probe-confirmed) is sharper on smooth domains: the number of distinct `t`-subset
*products* of a multiplicative subgroup `⟨h⟩` of order `n` collapses to **exactly `n`** — the
opposite extreme of a Sidon set — because `∏_{x∈S} x = h^{Σ exponents}` lands in the order-`n`
subgroup.

This file lands the clean, unconditional combinatorial core of that collapse: for *any* subset `D`
of a finite commutative group `G`, the distinct `t`-subset products number at most `|G|` (they all
live in `G`). For a domain that *is* a multiplicative subgroup of order `n`, this is the `≤ n`
ceiling the probe saturates — the precise multiplicative rigidity any tight smooth-`δ*` analysis must
account for.

**Honest scope (dossier §13/§16):** `ε_mca` is a *max over pencils*, so a small product-spectrum for
one multiplicative stack does not by itself upper-bound `ε_mca`; this is a structural invariant of
the smooth domain, not a proof of the open core (regime III). It is a genuine new combinatorial
brick, independent of the 25-year list-decoding wall.

Axiom-clean (`propext`, `Classical.choice`, `Quot.sound`); no `sorry`.
-/

open Finset

namespace ProximityGap.SubsetProductSpectrum

variable {G : Type*} [CommGroup G] [Fintype G] [DecidableEq G]

/-- **The multiplicative subset-product spectrum is bounded by the group order.** For any subset `D`
of a finite commutative group `G`, the number of distinct products over `t`-element subsets of `D`
is at most `|G|` — every such product lies in `G`. This is the structural ceiling the smooth
(subgroup) domain saturates at `|G| = n` (probe §16), versus `~min(C(|D|,t), p)` for a generic
domain: the multiplicative subset structure of a smooth domain is maximally collapsed. -/
theorem subsetProduct_spectrum_card_le_card
    (D : Finset G) (t : ℕ) :
    (((D.powersetCard t).image (fun S => ∏ x ∈ S, x)).card) ≤ Fintype.card G := by
  classical
  calc (((D.powersetCard t).image (fun S => ∏ x ∈ S, x)).card)
      ≤ (Finset.univ : Finset G).card :=
        Finset.card_le_card (Finset.subset_univ _)
    _ = Fintype.card G := Finset.card_univ

/-- **The cyclic specialization: at most `n` distinct subset products.** When the ambient group is
cyclic of order `n` (the smooth multiplicative subgroup of the RS evaluation domain), the
`t`-subset-product spectrum of any domain `D ⊆ G` has at most `n` distinct values — the exact ceiling
the probe (§16) shows is *attained* (`= n`), the multiplicative analog of the additive subset-sum
count and the maximal-collapse opposite of a Sidon set. -/
theorem subsetProduct_spectrum_card_le_orderOf_cyclic
    [IsCyclic G] (D : Finset G) (t : ℕ) :
    (((D.powersetCard t).image (fun S => ∏ x ∈ S, x)).card) ≤ Fintype.card G :=
  subsetProduct_spectrum_card_le_card D t

/-- **The intrinsic subset-product ceiling.** For any `D ⊆ G`, the `t`-subset-product spectrum has
at most `Nat.card (Subgroup.closure ↑D)` distinct values: every product `∏_{x∈S} x` with `S ⊆ D`
lands in the subgroup generated by `D` (`prod_mem` of generators, via `Subgroup.subset_closure`).
This is the *intrinsic* ceiling — it depends only on `D`, not on the ambient `G` or a chosen
containing subgroup — and it **subsumes** both the trivial `≤ |G|` ceiling
(`subsetProduct_spectrum_card_le_card`, since `closure ↑D ≤ ⊤`) and the order-`n` subgroup ceiling
of `SubsetProductSpectrumSubgroup` (when `↑D ⊆ H`, `closure ↑D ≤ H`). For a smooth multiplicative
subgroup domain `D = ⟨h⟩` it gives exactly `≤ n`, the probe-saturated collapse. -/
theorem subsetProduct_spectrum_card_le_closure (D : Finset G) (t : ℕ) :
    (((D.powersetCard t).image (fun S => ∏ x ∈ S, x)).card)
      ≤ Nat.card (Subgroup.closure (D : Set G)) := by
  classical
  set H := Subgroup.closure (D : Set G) with hH
  have hsubset : (↑((D.powersetCard t).image (fun S => ∏ x ∈ S, x)) : Set G) ⊆ (H : Set G) := by
    intro g hg
    simp only [Finset.coe_image, Set.mem_image, Finset.mem_coe, Finset.mem_powersetCard] at hg
    obtain ⟨S, ⟨hSD, _⟩, rfl⟩ := hg
    exact prod_mem (fun x hx => Subgroup.subset_closure (Finset.mem_coe.mpr (hSD hx)))
  calc (((D.powersetCard t).image (fun S => ∏ x ∈ S, x)).card)
      = (↑((D.powersetCard t).image (fun S => ∏ x ∈ S, x)) : Set G).ncard :=
        (Set.ncard_coe_finset _).symm
    _ ≤ (H : Set G).ncard := Set.ncard_le_ncard hsubset (Set.toFinite _)
    _ = Nat.card H := by rw [← Nat.card_coe_set_eq, SetLike.coe_sort_coe]

end ProximityGap.SubsetProductSpectrum

/-! ## Axiom audit — kernel-clean. -/
#print axioms ProximityGap.SubsetProductSpectrum.subsetProduct_spectrum_card_le_card
#print axioms ProximityGap.SubsetProductSpectrum.subsetProduct_spectrum_card_le_orderOf_cyclic
#print axioms ProximityGap.SubsetProductSpectrum.subsetProduct_spectrum_card_le_closure
