import ArkLib.OracleReduction.FiatShamir.DuplexSponge.Security.Completeness
import ArkLib.OracleReduction.Composition.Sequential.Append
import ArkLib.OracleReduction.LiftContext.OracleReduction
import ArkLib.ProofSystem.Binius.BinaryBasefold.Code
import ArkLib.ToMathlib.ToyStep4
import ArkLib.ToMathlib.ToyProblemRewinding
import ArkLib.ToMathlib.L13Milestone

#check Reduction.duplexSpongeFiatShamir_completeness_unroll_of_run_eq
#check Reduction.duplexSpongeFiatShamirSalted_completeness_unroll_of_run_eq
#check OracleVerifier.liftContext_soundness
#check Prover.append_run
#check Verifier.append_run
#check Binius.BinaryBasefold.constFunc_UDRClose
#check ToyProblem.simplified_iop_listDecoding_lb_of_winningChallenges
#check ToyProblem.Spec.toyProtocol_extracts
#check ArkLib.L13Milestone.alpha_strong_eq_alphaFromBeta
#check ArkLib.L13Milestone.correlatedAgreement_affine_curves_strongBeta_of_betaRecFin
