name = "Arklib"
lintDriver = "batteries/runLinter"
defaultTargets = ["ArkLib"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.longFile = 1500

[moreServerOptions]
linter.mathlibStandardSet = true
linter.style.longFile = 1500

[[require]]
name = "VCVio"
git = "https://github.com/lalalune/VCV-io"
rev = "576766ab24a044af560b05c58d2a1229857c7c07"

[[require]]
name = "PolyFun"
git = "https://github.com/lalalune/PolyFun"
rev = "5d3a160ed751b9227af90adb9da41d0eae2e0238"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "v4.29.0"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"
rev = "lean4.18.0"

[[require]]
name = "CompPoly"
git = "https://github.com/lalalune/CompPoly"
rev = "0cfaaea9356dea1b292476fa5c25ac8a59b4b06a"

[[lean_lib]]
name = "ArkLib"
