name = "Arklib"
lintDriver = "batteries/runLinter"
defaultTargets = ["ArkLib"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.longFile = 1500

[moreServerOptions]
linter.mathlibStandardSet = true
linter.style.longFile = 1500

[[require]]
name = "VCVio"
git = "https://github.com/lalalune/VCV-io"
rev = "b87119da538df85375ab4893a5535ec76dcbcd41"

[[require]]
name = "PolyFun"
git = "https://github.com/lalalune/PolyFun"
rev = "5d3a160ed751b9227af90adb9da41d0eae2e0238"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "v4.29.0"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"
rev = "lean4.18.0"

[[require]]
name = "CompPoly"
git = "https://github.com/lalalune/CompPoly"
rev = "fef24888838194617661f810937f807432b66c84"

[[lean_lib]]
name = "ArkLib"
