#!/usr/bin/env python3
"""
Mixed-radix tower fiber probes (continuation of DISPROOF_LOG O65-O68).

For n in {12,18,24,36} and large p = 1 mod 72, computes inside F_p the exact
t-fibers  F_n(t) = { S subset mu_n : p_1(S) = ... = p_t(S) = 0 }  for ALL t,
and compares them SET-EXACTLY against the packet-union prediction

  P_n(t) = { disjoint unions of rotated mu_d-cosets, d | n, d > t }
         = family generated by the divisibility-MINIMAL divisors d > t.

Notes on rigor:
 * Newton's identity p_k = e_1 p_{k-1} - ... + (-1)^{k-1} k e_k holds over any
   commutative ring, so e_1..e_t = 0 ==> p_1..p_t = 0 always, and the converse
   holds whenever char > t.  Here char = p ~ 1e9 >> n > t, so the e-window and
   p-window fibers coincide in F_p exactly.  (Spot-checked directly at n=12.)
 * char-0 sandwich: e_j(S) lives in Z[zeta_n]; vanishing in char 0 implies
   vanishing mod any prime above p, so Fiber_char0 is contained in Fiber_Fp.
   Predicted is contained in Fiber_char0 trivially (coset power sums vanish
   identically).  Hence  Fiber_Fp == Predicted  pins  Fiber_char0 == Predicted.
 * n=12,18,24: exhaustive over all 2^n subsets (bitmask linear forms, numpy).
   n=36: exhaustive via meet-in-the-middle on p_1 (the e_1=0 superset), then
   exact filtering of all higher power sums on the members. Still exhaustive.
"""
import numpy as np, json, sys, time
from collections import defaultdict

T0 = time.time()
def log(*a):
    print(f"[{time.time()-T0:8.1f}s]", *a, flush=True)

# ---------------- primes / roots ----------------
def is_prime(x):
    if x < 2: return False
    for q in (2,3,5,7,11,13,17,19,23,29,31,37):
        if x % q == 0: return x == q
    d, r = x-1, 0
    while d % 2 == 0: d //= 2; r += 1
    for a in (2,3,5,7,11,13,17,19,23,29,31,37):
        y = pow(a, d, x)
        if y in (1, x-1): continue
        for _ in range(r-1):
            y = y*y % x
            if y == x-1: break
        else:
            return False
    return True

def find_prime_1mod(n, lo):
    p = lo + ((1 - lo) % n)
    while p < lo or not is_prime(p): p += n
    return p

def prime_factors(n):
    fs, d, m = set(), 2, n
    while d*d <= m:
        while m % d == 0: fs.add(d); m //= d
        d += 1
    if m > 1: fs.add(m)
    return fs

def primitive_root_of_unity(n, p):
    e = (p-1)//n
    g = 2
    while True:
        z = pow(g, e, p)
        if z != 1 and pow(z, n, p) == 1 and all(pow(z, n//q, p) != 1 for q in prime_factors(n)):
            return z
        g += 1

# ---------------- prediction ----------------
def divisors(n): return [d for d in range(1, n+1) if n % d == 0]

def min_allowed(n, t):
    """divisibility-minimal divisors d of n with d > t (d > 1)."""
    allowed = [d for d in divisors(n) if d > t and d > 1]
    return tuple(sorted(d for d in allowed
                        if not any(e != d and d % e == 0 for e in allowed)))

def coset_blocks(n, ds):
    bl = set()
    for d in ds:
        step = n // d
        for r in range(step):
            m = 0
            for i in range(d):
                m |= 1 << ((r + i*step) % n)
            bl.add(m)
    return sorted(bl)

def family_from_blocks(blocks):
    """All distinct unions of pairwise-disjoint blocks (DFS over block subsets)."""
    out = {0}
    L = len(blocks)
    sys.setrecursionlimit(100000)
    def dfs(mask, start):
        for i in range(start, L):
            b = blocks[i]
            if mask & b: continue
            nm = mask | b
            out.add(nm)
            dfs(nm, i + 1)
    dfs(0, 0)
    return out

_fam_cache = {}
def predicted_family(n, t):
    key = (n, min_allowed(n, t))
    if key not in _fam_cache:
        _fam_cache[key] = family_from_blocks(coset_blocks(n, key[1]))
    return _fam_cache[key]

# sanity: family generated by minimal divisors == family by ALL allowed divisors
def predicted_family_allblocks(n, t):
    allowed = tuple(d for d in divisors(n) if d > t and d > 1)
    return family_from_blocks(coset_blocks(n, allowed))

# ---------------- actual fibers ----------------
def e1_fiber_exhaustive(n, p, z):
    N = 1 << n
    arr = np.zeros(N, dtype=np.int64)
    for b in range(n):
        c = pow(z, b % n, p)
        arr.reshape(-1, 1 << (b+1))[:, (1 << b):] += c
    arr %= p
    return np.nonzero(arr == 0)[0].astype(np.int64)

def e1_fiber_mitm(n, p, z):
    h = n // 2
    H = 1 << h
    def col(offset):
        a = np.zeros(H, dtype=np.int64)
        for b in range(h):
            c = pow(z, (offset + b) % n, p)
            a.reshape(-1, 1 << (b+1))[:, (1 << b):] += c
        return a % p
    L = col(0); R = col(h)
    dL = defaultdict(list)
    for m, v in enumerate(L.tolist()):
        dL[v].append(m)
    members = []
    for m, v in enumerate(((-R) % p).tolist()):
        if v in dL:
            base = m << h
            for l in dL[v]:
                members.append(l | base)
    members.sort()
    return np.array(members, dtype=np.int64)

def power_matrix(n, p, z, members):
    """P[m, j-1] = p_j(S_m) mod p for j = 1..n-1, via exact float64 matmul."""
    mem = np.asarray(members, dtype=np.int64)
    M = len(mem)
    B = np.zeros((M, n), dtype=np.float64)
    for b in range(n):
        B[:, b] = ((mem >> b) & 1).astype(np.float64)
    Z = np.zeros((n, n-1), dtype=np.float64)
    for i in range(n):
        for j in range(1, n):
            Z[i, j-1] = float(pow(z, (i*j) % n, p))
    # entries < p ~ 1e9, sums of <= 36 of them < 4e10 < 2^53: float64 exact
    P = B @ Z
    assert P.max() < 2**53
    return (P.astype(np.int64)) % p

def fibers_all_t(n, p, z, members):
    P = power_matrix(n, p, z, members)
    ok = np.ones(len(members), dtype=bool)
    fib = {}
    for t in range(1, n):
        ok &= (P[:, t-1] == 0)
        fib[t] = members[ok]
    return fib

# ---------------- esymm direct check (small n) ----------------
def esymm_fibers_direct(n, p, z):
    """e-window fibers for ALL subsets, by direct polynomial DP. n <= 12ish."""
    pows = [pow(z, i, p) for i in range(n)]
    fib = {t: [] for t in range(1, n)}
    for mask in range(1 << n):
        e = [1]
        mm, i = mask, 0
        while mm:
            if mm & 1:
                x = pows[i]
                ne = e + [0]
                for k in range(len(e), 0, -1):
                    ne[k] = (ne[k] + x * e[k-1]) % p
                e = ne
            mm >>= 1; i += 1
        # e_j = e[j] for j < len(e), and e_j = 0 for j >= len(e) (= |S|+1).
        tmax = 0
        for j in range(1, n):
            if j >= len(e) or e[j] % p == 0: tmax += 1
            else: break
        for t in range(1, min(tmax, n-1) + 1):
            fib[t].append(mask)
    return {t: set(v) for t, v in fib.items()}

# ---------------- reporting ----------------
def weight_table(members):
    d = defaultdict(int)
    for m in members:
        d[int(m).bit_count()] += 1
    return dict(sorted(d.items()))

def run_n(n, p, z, out):
    log(f"=== n = {n}, p = {p}, zeta = {z} ===")
    if n <= 24:
        mem = e1_fiber_exhaustive(n, p, z)
    else:
        mem = e1_fiber_mitm(n, p, z)
    log(f"  |e1-fiber| (incl empty set) = {len(mem)}")
    fib = fibers_all_t(n, p, z, mem)
    res = {"n": n, "p": p, "zeta": z, "t": {}}
    for t in range(1, n):
        actual = set(int(x) for x in fib[t])
        pred = predicted_family(n, t)
        match = (actual == pred)
        extra = sorted(actual - pred)[:5]
        missing = sorted(pred - actual)[:5]
        res["t"][t] = {
            "min_allowed_divisors": list(min_allowed(n, t)),
            "actual_count": len(actual),
            "predicted_count": len(pred),
            "set_equal": match,
            "weights": weight_table(actual),
            "extra_examples": [hex(x) for x in extra],
            "missing_examples": [hex(x) for x in missing],
        }
        if not match:
            log(f"  *** VIOLATION at (n={n}, t={t}): |actual|={len(actual)} "
                f"|pred|={len(pred)} extra={extra[:3]} missing={missing[:3]}")
    out[n] = res
    return fib, mem

def main():
    p1 = find_prime_1mod(72, 10**9)
    p2 = find_prime_1mod(72, 2 * 10**9)
    log(f"primes: p1 = {p1}, p2 = {p2} (both = 1 mod 72)")
    out = {"p1": p1, "p2": p2, "runs": {}}

    fibs = {}
    for n in (12, 18, 24, 36):
        z = primitive_root_of_unity(n, p1)
        fibs[n], _ = run_n(n, p1, z, out["runs"])

    # ---- minimal-vs-all-blocks generation sanity (n=12, 18, all t) ----
    gen_ok = True
    for n in (12, 18):
        for t in range(1, n):
            if predicted_family(n, t) != predicted_family_allblocks(n, t):
                gen_ok = False
                log(f"  *** generator mismatch at n={n}, t={t}")
    out["min_blocks_generate_all_blocks_n12_n18"] = gen_ok
    log(f"min-divisor blocks generate the full allowed-coset family (n=12,18): {gen_ok}")

    # ---- esymm vs psum window (Newton bridge) direct check at n=12, 18 ----
    for nn in (12, 18):
        znn = primitive_root_of_unity(nn, p1)
        efib = esymm_fibers_direct(nn, p1, znn)
        newton_ok = all(efib[t] == set(int(x) for x in fibs[nn][t])
                        for t in range(1, nn))
        out[f"newton_esymm_eq_psum_n{nn}"] = newton_ok
        log(f"e-window fiber == p-window fiber for all t (n={nn}, direct): {newton_ok}")

    # ---- count-factorization law: F_n(t) ~ F_l(t)^{n/l}, l = lcm(Dmin) ----
    from math import lcm
    def wenum(fam):
        d = defaultdict(int)
        for m in fam: d[int(m).bit_count()] += 1
        return dict(d)
    def conv_pow(d, k):
        cur = {0: 1}
        for _ in range(k):
            nxt = defaultdict(int)
            for a, ca in cur.items():
                for b, cb in d.items():
                    nxt[a+b] += ca*cb
            cur = dict(nxt)
        return cur
    fact_results = {}
    fact_all_ok = True
    for n in (12, 18, 24, 36):
        for t in range(1, n):
            dmin = min_allowed(n, t)
            l = lcm(*dmin) if dmin else 1
            if l < n and dmin:
                sub = predicted_family(l, t)   # window-t fiber of mu_l (verified = actual)
                pred_we = conv_pow(wenum(sub), n // l)
                act_we = wenum(set(int(x) for x in fibs[n][t]))
                ok = (pred_we == act_we)
                fact_results[f"n={n},t={t}"] = {"l": l, "copies": n//l, "ok": ok}
                fact_all_ok &= ok
                if not ok:
                    log(f"  *** factorization law FAILS at n={n}, t={t} (l={l})")
    out["count_factorization_law"] = {"all_ok": fact_all_ok, "cases": fact_results}
    log(f"count-factorization law F_n(t) ~= F_lcm(Dmin)(t)^(n/lcm) "
        f"holds in all {len(fact_results)} applicable cases: {fact_all_ok}")

    # ---- cross-prime check (full repeat with p2) ----
    log("cross-prime check with p2 ...")
    cross_ok = True
    for n in (12, 18, 24, 36):
        z2 = primitive_root_of_unity(n, p2)
        mem2 = e1_fiber_exhaustive(n, p2, z2) if n <= 24 else e1_fiber_mitm(n, p2, z2)
        fib2 = fibers_all_t(n, p2, z2, mem2)
        for t in range(1, n):
            a1 = set(int(x) for x in fibs[n][t])
            a2 = set(int(x) for x in fib2[t])
            # fibers live on exponent sets; zeta choice is a group automorphism
            # of mu_n, so compare counts per weight (sets need not be equal masks
            # if z2 corresponds to a different generator labeling)
            if weight_table(a1) != weight_table(a2) or len(a1) != len(a2):
                cross_ok = False
                log(f"  *** cross-prime weight-table mismatch n={n}, t={t}")
    out["cross_prime_weight_tables_match"] = cross_ok
    log(f"cross-prime (p2) weight tables match: {cross_ok}")

    # ---- factorization consistency (CRT class independence at t=1) ----
    def wpoly(fam):
        d = defaultdict(int)
        for m in fam: d[int(m).bit_count()] += 1
        return d
    def cube(d):
        out_ = defaultdict(int)
        for a, ca in d.items():
            for b, cb in d.items():
                for c, cc in d.items():
                    out_[a+b+c] += ca*cb*cc
        return dict(out_)
    f6 = wpoly(predicted_family(6, 1))
    f12 = wpoly(predicted_family(12, 1))
    chk18 = (cube(f6) == {k: v for k, v in wpoly(predicted_family(18, 1)).items()})
    chk36 = (cube(f12) == {k: v for k, v in wpoly(predicted_family(36, 1)).items()})
    out["class_factorization_N18_eq_N6cubed"] = chk18
    out["class_factorization_N36_eq_N12cubed"] = chk36
    log(f"N_18(.,1) == N_6(.,1)^3 (CRT classes): {chk18};  "
        f"N_36(.,1) == N_12(.,1)^3: {chk36}")

    # ---- small-prime threshold probe (O49): n=12 over F_13 ----
    z13 = primitive_root_of_unity(12, 13)
    mem13 = e1_fiber_exhaustive(12, 13, z13)
    pred1 = predicted_family(12, 1)
    extra13 = len(set(int(x) for x in mem13) - pred1)
    out["threshold_probe_F13_n12"] = {
        "e1_fiber_count": int(len(mem13)),
        "char0_count": len(pred1),
        "extra_members_mod_13": extra13,
    }
    log(f"threshold probe n=12 over F_13: |e1 fiber| = {len(mem13)} "
        f"(char-0: {len(pred1)}; {extra13} extra members mod 13)")

    with open("/tmp/mixed_tower_tables.json", "w") as f:
        json.dump(out, f, indent=1, default=int)
    log("wrote /tmp/mixed_tower_tables.json")

    # ---- human-readable report ----
    with open("/tmp/mixed_tower_results.txt", "w") as f:
        f.write(f"Mixed-radix tower fiber probe, p = {p1} (= 1 mod 72)\n")
        f.write("Fiber F_n(t) = {S subset mu_n : p_1=..=p_t=0} (== e-window, char >> t)\n")
        f.write("Prediction P_n(t) = disjoint unions of rotated mu_d-cosets, d|n, d>t\n\n")
        for n in (12, 18, 24, 36):
            r = out["runs"][n]
            f.write(f"### n = {n}\n")
            prev = None
            for t in range(1, n):
                e = r["t"][t]
                row = (tuple(e["min_allowed_divisors"]), e["actual_count"],
                       tuple(sorted(e["weights"].items())))
                tag = "MATCH" if e["set_equal"] else "*** MISMATCH ***"
                f.write(f" t={t:2d} Dmin={e['min_allowed_divisors']!s:14s} "
                        f"|F|={e['actual_count']:8d} |P|={e['predicted_count']:8d} {tag}\n")
                if row != prev:
                    f.write(f"       weights: {e['weights']}\n")
                prev = row
            f.write("\n")
    log("wrote /tmp/mixed_tower_results.txt")

if __name__ == "__main__":
    main()
