// wf-G5: Does the DYADIC (2-power) structure of mu_n LOWER the additive energy E(H)
// vs a GENERIC multiplicative subgroup of the SAME size in the SAME field?
// Heath-Brown-Konyagin (Stepanov): E(H) << |H|^{5/2} for |H| << p^{2/3}, STRUCTURE-BLIND.
// di Benedetto delta=31/2880 depends ONLY on |H|. G5 question: dyadic lacunarity (gaps 2^j)
// is the STRONGEST possible mult. lacunarity -- does it beat |H|^{5/2}?
//
// We need a prime p where (p-1) has a 2-power AND a coprime-order subgroup of the SAME size n.
// Strategy: find primes p with p-1 = 2^a * (other) AND p-1 = m1 * 3^b with 3^b ~ a comparable size,
// OR simpler: pick size n, find prime p s.t. n | (p-1); take dyadic H2 = order-n 2-group (needs n=2^a | p-1)
// and a GENERIC H_g = SOME order-n subgroup that is NOT the 2-group (needs another order-n subgroup,
// i.e. n | (p-1)/n possible, take subgroup of an odd-prime-power part). We instead compare:
//   (A) dyadic: n=2^a, H = order-n subgroup (the 2-power roots)  [the prize object]
//   (B) generic same |H|=n: order-n subgroup generated by g^((p-1)/n) -- SAME subgroup actually.
// KEY: in F_p* (cyclic) there is a UNIQUE subgroup of each order n|p-1. So "dyadic vs generic of
// same size in same field" is VACUOUS -- the order-n subgroup IS unique. The 2-power-ness is about
// the AMBIENT cyclic structure (whether n itself is 2^a), NOT a choice. So the real comparison is:
//   compare E(H_n) across primes where n is a 2-POWER vs where n is NOT a 2-power (e.g. n=3^a, n=p0),
//   at matched size n and matched beta = log p / log n. If dyadic helps, E exponent should be LOWER
//   for 2-power n than for odd/composite n of comparable size.
use std::collections::HashMap;
fn mpow(a:u64,mut e:u64,p:u64)->u64{let mut r=1u128;let mut a2=a as u128;let pp=p as u128;while e>0{if e&1==1{r=r*a2%pp;}a2=a2*a2%pp;e>>=1;}r as u64}
fn isp(n:u64)->bool{if n<2{return false}let mut d=2;while d*d<=n{if n%d==0{return false}d+=1}true}
// first prime p>lo with n|(p-1)
fn fp(n:u64,lo:u64)->u64{let mut p=lo+((1+n-lo%n)%n);if p<=2{p+=n}loop{if p>2&&p%n==1&&isp(p){return p}p+=n}}
fn proot(p:u64)->u64{let mut m=p-1;let mut fs=vec![];let mut d=2;while d*d<=m{if m%d==0{fs.push(d);while m%d==0{m/=d}}d+=1}if m>1{fs.push(m)}let mut g=2;loop{if fs.iter().all(|&f|mpow(g,(p-1)/f,p)!=1){return g}g+=1}}
// E_2(H) = #{(a,b,c,d) in H^4 : a+b=c+d} = sum over t of rep_2(t)^2 where rep_2(t)=#{(a,b):a+b=t}
fn energy2(mu:&[u64], p:u64)->u128{
    let mut cnt:HashMap<u64,u64>=HashMap::with_capacity(mu.len()*mu.len());
    for &a in mu { for &b in mu { let t=((a as u128 + b as u128)%p as u128)as u64; *cnt.entry(t).or_insert(0)+=1; } }
    let mut e:u128=0; for(_,&c) in &cnt { e += (c as u128)*(c as u128); } e
}
fn report(label:&str, n:u64, p:u64){
    let g=proot(p); let h=mpow(g,(p-1)/n,p);
    let mu:Vec<u64>=(0..n).map(|j|mpow(h,j,p)).collect();
    let e2 = energy2(&mu,p) as f64;
    let beta=(p as f64).ln()/(n as f64).ln();
    let exp_e = e2.ln()/(n as f64).ln(); // E ~ n^exp_e ; HBK ceiling 5/2; trivial 3 (random); 2 (Sidon)
    // is n a 2-power?
    let dyadic = (n & (n.wrapping_sub(1)))==0;
    println!("{:8} n={:5} p={:10} beta={:.2} dyadic={:5}  E2={:.4e}  exp=logE/logn={:.4}  (HBK 2.5, rand 3.0, Sidon 2.0)",
        label, n, p, beta, dyadic, e2, exp_e);
}
fn main(){
    println!("=== DYADIC vs NON-DYADIC additive energy E2(H) at matched size & beta ===");
    // matched sizes: pick n values that are 2-power and nearby non-2-power of similar magnitude
    // group by approximate size; same beta target ~4
    let target_beta=4.0_f64;
    let groups: Vec<Vec<u64>> = vec![
        vec![64, 63, 65, 81],        // 2^6 vs 63=9*7, 65=5*13, 81=3^4
        vec![128, 121, 125, 126],    // 2^7 vs 121=11^2, 125=5^3, 126=2*63
        vec![256, 243, 250, 255],    // 2^8 vs 243=3^5, 250, 255
        vec![512, 486, 500, 513],    // 2^9 vs others
    ];
    for grp in &groups {
        for &n in grp {
            let lo = ((n as f64).powf(target_beta)) as u64;
            let p = fp(n, lo.max(10));
            report("", n, p);
        }
        println!();
    }
    // Also: pure 2-power tower at fixed beta to read the dyadic exponent trend
    println!("=== Dyadic-only size sweep (prize trajectory) ===");
    for a in 5..=10u32 { let n=1u64<<a; let lo=((n as f64).powf(4.0))as u64; let p=fp(n,lo); report("DYAD",n,p); }
}
