// A14: Terwilliger-algebra route to M(n) = lambda_2(Cay(F_p, mu_n)).
//
// THE TEST: does the Terwilliger algebra T(x) of the cyclotomic graph confine
// the eigenvalue M to a SMALL (bounded) irreducible T-module, so that the
// operator norm of the adjacency matrix A on that module beats sqrt(q)?
//
// Terwilliger algebra T = T(x0) for base vertex x0 = subalgebra of M_p(C)
// generated by:
//   - the Bose-Mesner algebra M (adjacency matrices A_R of each relation R = coset of mu_n)
//   - the dual idempotents E*_i = diag projections onto "shell i" = the i-th relation class
//     from x0  (i.e. (E*_i)_{yy} = 1 iff y is in relation i with x0).
//
// We compute:
//   (1) dim of the Bose-Mesner algebra = number of relations = m+1 = (p-1)/n + 1.
//   (2) dim of T (= span of all words E*_{i1} A_{R1} E*_{i2} A_{R2} ... ) by
//       repeated multiplication closure over the generating set, as matrices over a
//       prime field F_l (l large random prime) to get the EXACT rank fast (dim over C
//       equals dim over a generic F_l).
//   (3) For comparison: the Hamming scheme H(d,2) on the SAME vertex count has
//       Terwilliger dim = (d+1)(d+2)(d+3)/6 ~ d^3/6 (thin, bounded by diameter) --
//       that is the regime where a Terwilliger/Krawtchouk operator-norm bound WORKS.
//
// If dim T grows ~ p (linearly in #vertices), the modules are NOT thin/bounded:
// there is no fixed low-dim block to bound M, so the route is dead.
//
// We work with base vertex x0 = 0 (translation scheme): relations are by difference,
// y ~_R z iff (y - z) in coset R. From x0=0, shell i = coset_i. The adjacency
// matrix of the GRAPH is A = A_{mu_n} (the coset of mu_n itself), eigenvalues = periods.

use std::collections::HashSet;

fn mpow(mut _a:u64, mut e:u64, p:u64)->u64{let mut r=1u128;let mut a2=_a as u128;let pp=p as u128;while e>0{if e&1==1{r=r*a2%pp;}a2=a2*a2%pp;e>>=1;}r as u64}
fn is_prime(n:u64)->bool{if n<2{return false;}let mut d=2;while d*d<=n{if n%d==0{return false;}d+=1;}true}
fn find_prime_cong1(n:u64,lo:u64)->u64{let mut p=lo+((1+n-lo%n)%n);if p<=2{p+=n;}loop{if p>2&&p%n==1&&is_prime(p){return p;}p+=n;}}
fn primitive_root(p:u64)->u64{let mut m=p-1;let mut fs=vec![];let mut d=2;while d*d<=m{if m%d==0{fs.push(d);while m%d==0{m/=d;}}d+=1;}if m>1{fs.push(m);}let mut g=2;loop{if fs.iter().all(|&f|mpow(g,(p-1)/f,p)!=1){return g;}g+=1;}}

// modular matrix rank over F_l for an l in {large prime}
const L: u64 = 2_000_000_011; // prime modulus for exact rank

fn minv(a:u64)->u64{ mpow(a, L-2, L) }

// rank of a set of length-D row vectors over F_L, via Gaussian elimination.
fn rank_rows(mut rows: Vec<Vec<u64>>, dim: usize) -> usize {
    let mut r = 0usize;
    let mut col = 0usize;
    let nrows = rows.len();
    while col < dim && r < nrows {
        // find pivot
        let mut piv = None;
        for i in r..nrows { if rows[i][col]!=0 { piv=Some(i); break; } }
        if let Some(pi)=piv {
            rows.swap(r, pi);
            let inv = minv(rows[r][col]);
            for c in col..dim { rows[r][c] = (rows[r][c] as u128 * inv as u128 % L as u128) as u64; }
            for i in 0..nrows {
                if i!=r && rows[i][col]!=0 {
                    let f = rows[i][col];
                    for c in col..dim {
                        let sub = (rows[r][c] as u128 * f as u128 % L as u128) as u64;
                        rows[i][c] = (rows[i][c] + L - sub) % L;
                    }
                }
            }
            r += 1;
        }
        col += 1;
    }
    r
}

// flatten a p x p matrix (Vec<Vec<u64>>) to a length p*p row
fn flat(m:&Vec<Vec<u64>>, p:usize)->Vec<u64>{
    let mut v=vec![0u64; p*p];
    for i in 0..p { for j in 0..p { v[i*p+j]=m[i][j]; } }
    v
}
fn matmul(a:&Vec<Vec<u64>>, b:&Vec<Vec<u64>>, p:usize)->Vec<Vec<u64>>{
    let mut c=vec![vec![0u64;p];p];
    for i in 0..p {
        for k in 0..p {
            let aik=a[i][k]; if aik==0 {continue;}
            for j in 0..p {
                if b[k][j]!=0 {
                    c[i][j]=( (c[i][j] as u128 + aik as u128 * b[k][j] as u128) % L as u128) as u64;
                }
            }
        }
    }
    c
}

fn terwilliger_dim(n:u64, p:u64)->(usize, usize){
    let pu = p as usize;
    let g = primitive_root(p);
    let h = mpow(g, (p-1)/n, p); // generator of mu_n
    // mu_n elements
    let mu:Vec<u64>=(0..n).map(|j|mpow(h,j,p)).collect();
    let m = ((p-1)/n) as usize; // number of nonidentity relations (cosets)
    // For each coset R_t = g^t * mu_n, t=0..m-1, the adjacency matrix A_{R_t}:
    //   (A_{R_t})_{y,z} = 1 iff (y - z) mod p in R_t.
    // Generators of Bose-Mesner: identity I + the m coset adjacency matrices.
    // Relation index of a nonzero difference d: which coset of mu_n contains d.
    // Precompute discrete log base g to assign coset index = (dlog(d)) mod m.
    // dlog table:
    let mut dlog = vec![0usize; pu];
    let mut x = 1u64;
    for e in 0..(p-1) {
        dlog[x as usize] = e as usize;
        x = (x as u128 * g as u128 % p as u128) as u64;
    }
    let coset_of = |d:u64| -> usize { dlog[d as usize] % m }; // 0..m-1

    // Build adjacency matrices A_{R_t} for t = 0..m-1.
    let mut a_rel: Vec<Vec<Vec<u64>>> = vec![vec![vec![0u64;pu];pu]; m];
    for y in 0..pu {
        for z in 0..pu {
            if y==z { continue; }
            let d = (y as u64 + p - z as u64) % p;
            let t = coset_of(d);
            a_rel[t][y][z] = 1;
        }
    }
    // Dual idempotents from base x0=0: E*_i = diag, (E*_i)_{yy}=1 iff y in relation i with 0
    //   i.e. y in coset i  (y nonzero, dlog(y)%m == i), and E*_{-1} = diag at y=0 (the base).
    // We include the base-point projector E*_0base (just vertex 0) and m coset projectors.
    let mut estar: Vec<Vec<Vec<u64>>> = Vec::new();
    // base point projector
    {
        let mut d=vec![vec![0u64;pu];pu]; d[0][0]=1; estar.push(d);
    }
    for i in 0..m {
        let mut d=vec![vec![0u64;pu];pu];
        for y in 1..pu {
            if dlog[y]%m == i { d[y][y]=1; }
        }
        estar.push(d);
    }

    // Bose-Mesner dim = m+1 (I + m cosets); we report m+1.
    let bm_dim = m+1;

    // Generators of T: I, all a_rel, all estar.
    let mut gens: Vec<Vec<Vec<u64>>> = Vec::new();
    {
        let mut id=vec![vec![0u64;pu];pu]; for i in 0..pu { id[i][i]=1; } gens.push(id);
    }
    for a in &a_rel { gens.push(a.clone()); }
    for e in &estar { gens.push(e.clone()); }

    // Closure under multiplication, tracking the linear span via rank of flattened matrices.
    // Start basis = gens, then repeatedly multiply current basis by generators and keep
    // only those that increase the rank. Bounded iteration.
    let mut basis: Vec<Vec<Vec<u64>>> = Vec::new();
    let mut basis_flat: Vec<Vec<u64>> = Vec::new();
    let mut cur_rank = 0usize;

    let mut try_add = |mtx:&Vec<Vec<u64>>, basis:&mut Vec<Vec<Vec<u64>>>, basis_flat:&mut Vec<Vec<u64>>, cur_rank:&mut usize| -> bool {
        let f = flat(mtx, pu);
        let mut trial = basis_flat.clone();
        trial.push(f.clone());
        let r = rank_rows(trial, pu*pu);
        if r > *cur_rank {
            basis.push(mtx.clone());
            basis_flat.push(f);
            *cur_rank = r;
            true
        } else { false }
    };

    for gm in &gens { try_add(gm, &mut basis, &mut basis_flat, &mut cur_rank); }

    // iterate products
    let mut changed = true;
    let mut iters = 0;
    while changed && iters < 12 {
        changed = false;
        iters += 1;
        let snapshot: Vec<Vec<Vec<u64>>> = basis.clone();
        for b in &snapshot {
            for gm in &gens {
                let prod = matmul(b, gm, pu);
                if try_add(&prod, &mut basis, &mut basis_flat, &mut cur_rank) { changed = true; }
                let prod2 = matmul(gm, b, pu);
                if try_add(&prod2, &mut basis, &mut basis_flat, &mut cur_rank) { changed = true; }
            }
        }
    }

    (bm_dim, cur_rank)
}

fn main(){
    // small primes p = 1 mod n, prime, beta = log_n p as close to 4 as memory permits.
    // p must be small enough that p x p matrices over F_L fit (p <= ~120 keeps it fast).
    eprintln!("# n  p  beta=log_n(p)  m=(p-1)/n  BoseMesner_dim(=m+1)  Terwilliger_dim  T/p");
    let cases: Vec<(u64,u64)> = vec![
        (2, 5), (2, 13), (2, 29), (2, 53), (2, 101),
        (4, 13), (4, 29), (4, 41), (4, 53), (4, 101),
        (8, 17), (8, 41), (8, 73), (8, 89), (8, 113),
        (16, 17), (16, 97), (16, 113),
    ];
    for &(n,p) in &cases {
        if !is_prime(p) || (p-1)%n!=0 { eprintln!("skip n={} p={} (bad)",n,p); continue; }
        if p > 130 { eprintln!("skip n={} p={} (too big)",n,p); continue; }
        let (bm, tdim) = terwilliger_dim(n,p);
        let beta = (p as f64).ln()/(n as f64).ln();
        eprintln!("{:3} {:5}  {:5.2}      {:4}        {:5}             {:6}        {:.3}",
            n, p, beta, (p-1)/n, bm, tdim, tdim as f64 / p as f64);
    }
    // Hamming H(d,2) reference dim for same vertex count 2^d:
    eprintln!("# REF Hamming H(d,2): #vertices=2^d, Terwilliger dim = (d+1)(d+2)(d+3)/6 (thin):");
    for d in 2..=7u64 {
        let v = 1u64<<d;
        let td = (d+1)*(d+2)*(d+3)/6;
        eprintln!("#   d={} vertices={} T_dim={} T/v={:.3}", d, v, td, td as f64/v as f64);
    }
}
