// wf-S9 (extension): the GLOBAL v_p CAP and Galois-orbit structure of the annihilating set.
//
// Prior wfS9_vp_valuation showed: at prize prime p ~ n^4, NO bounded-weight (w<=7) config is
// spurious (v_p>=1) for n=16,32; and across the whole prime sweep maxv@wmin was ALWAYS 1.
//
// This probe HARDENS that into the sharp p-adic statement.  Two questions:
//  (Q1) GLOBAL CAP.  Over EVERY prime p == 1 mod n (small..bound) and EVERY antipodal-free
//       config of weight <= wcap, what is the MAXIMUM v_p(N(sigma_T)) ever observed?
//       v_p(N) = #{omega primitive n-th root in F_p : T(omega) = 0 mod p}.
//       If this global max is 1 (for bounded weight), then "p | N" <=> EXACTLY ONE prime above p
//       divides, and v_p in {0,1}: the spurious mass is p-adically SQUAREFREE / perfectly spread.
//       That is the p-adic analogue of "M small despite E_r large": no concentration on one config.
//  (Q2) GALOIS ORBIT.  The decomposition group (Z/n)^* permutes the d=phi(n) primes above p by
//       omega_a -> omega_a^b = omega_{ab mod n}.  Since (Z/n)^* acts on the primitive roots and
//       sigma_b(T(omega_a)) = T_b(omega_{ab}) where T_b applies sigma_b to the (rational integer)
//       coefficients -- but coefficients are in {-1,0,1} (rational!), so sigma_b fixes them, giving
//       T(omega_a)=0  <=>  sigma_b annihilates  <=>  T(omega_{ab})=0  for the SAME T only if the
//       config is itself Galois-fixed.  In general A_T = {a : T(omega_a)=0} is an ARBITRARY subset.
//       We DIRECTLY enumerate A_T for every spur config and test: is A_T a union of <H>-cosets for
//       any nontrivial subgroup H<=(Z/n)^* ?  A genuinely-spurious config has A_T NOT closed under
//       any nontrivial Galois symmetry -> it is an "accidental" mod-p vanishing, the true extra mass.
//
// HEADLINE: global max v_p over the sweep (per weight) + count of configs whose A_T is Galois-stable
//           vs not, at the FIRST prime where spur appears and at prize scale.
//
// build: rustc -O probe_wfS9_vp_cap.rs -o /tmp/s9cap ; run: /tmp/s9cap <n> <wcap> [nprimes]

fn mpow(a: u64, mut e: u64, p: u64) -> u64 {
    let mut r: u128 = 1; let mut a2 = a as u128; let pp = p as u128;
    while e > 0 { if e & 1 == 1 { r = r * a2 % pp; } a2 = a2 * a2 % pp; e >>= 1; }
    r as u64
}
fn isp(n: u64) -> bool { if n < 2 { return false } let mut d = 2; while d*d <= n { if n%d==0 { return false } d+=1 } true }
fn fp(n: u64, lo: u64) -> u64 {
    let mut p = lo + ((n + 1 - lo % n) % n);
    if p % n != 1 { p += (n + 1 - p % n) % n; }
    loop { if p % n == 1 && p > 2 && isp(p) { return p } p += n; }
}
fn proot(p: u64) -> u64 {
    let mut m = p - 1; let mut fs = vec![]; let mut d = 2;
    while d*d <= m { if m%d==0 { fs.push(d); while m%d==0 { m/=d } } d+=1 }
    if m > 1 { fs.push(m) }
    let mut g = 2u64;
    loop { if fs.iter().all(|&f| mpow(g, (p-1)/f, p) != 1) { return g } g += 1 }
}
fn prim_roots(p: u64, n: u64) -> (Vec<u64>, Vec<u64>) {
    let g0 = proot(p);
    let zeta = mpow(g0, (p-1)/n, p);
    let mut roots = Vec::new(); let mut exps = Vec::new();
    for a in (1..n).step_by(2) { roots.push(mpow(zeta, a, p)); exps.push(a); }
    (roots, exps)
}
// subgroups of (Z/n)^* (n=2^mu): generated by all single odd elements; we test stability under
// each cyclic subgroup <b>. A_T (as a set of odd residues) is Galois-stable under <b> iff closed
// under mult by b mod n.
fn coset_closed(annset: &Vec<u64>, b: u64, n: u64) -> bool {
    use std::collections::HashSet;
    let s: HashSet<u64> = annset.iter().cloned().collect();
    annset.iter().all(|&a| s.contains(&(a * b % n)))
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let n: u64 = if args.len() > 1 { args[1].parse().unwrap() } else { 16 };
    let wcap: usize = if args.len() > 2 { args[2].parse().unwrap() } else { 8 };
    let nprimes: usize = if args.len() > 3 { args[3].parse().unwrap() } else { 60 };
    let d = (n/2) as usize;
    // odd residues mod n (the Galois group elements), excluding 1 (identity)
    let odds: Vec<u64> = (1..n).step_by(2).collect();

    println!("== wf-S9 GLOBAL v_p CAP + Galois-orbit structure: n={} phi={} wcap={} ==", n, d, wcap);

    // Q1: GLOBAL CAP over the prime sweep.
    let mut global_maxv = vec![0u32; wcap+1];        // max v_p per weight over ALL primes swept
    let mut global_maxv_prime = vec![0u64; wcap+1];  // witness prime
    let mut ever_v2 = 0u64;                           // # (prime,config) pairs with v_p>=2
    let mut ever_v2_witness = (0u64, 0u32);

    // Q2: at the FIRST spur prime and at prize-scale, count Galois-stable vs genuine A_T.
    let prize_p = fp(n, (n as f64).powf(4.0) as u64);

    let mut pp = fp(n, n);
    for _ in 0..nprimes {
        let (roots, exps) = prim_roots(pp, n);
        let mut pw = vec![vec![0u64; d]; d];
        for k in 0..d { let mut cur = 1u64; for j in 0..d { pw[k][j] = cur; cur = ((cur as u128 * roots[k] as u128) % pp as u128) as u64; } }

        let mut a = vec![0i64; d]; a[0] = 1;
        // closure capturing references via function pointer is awkward; inline recursion with a stack.
        // We do explicit recursion through a helper that takes everything.
        fn rec(a: &mut Vec<i64>, pos: usize, d: usize, used: usize, wcap: usize, p: u64,
               pw: &Vec<Vec<u64>>, exps: &Vec<u64>, n: u64, odds: &Vec<u64>,
               gmax: &mut Vec<u32>, gmaxp: &mut Vec<u64>, ever_v2: &mut u64, ev2w: &mut (u64,u32),
               stable_cnt: &mut u64, genuine_cnt: &mut u64, count_galois: bool) {
            if pos == d {
                if used == 0 { return; }
                let mut annset: Vec<u64> = Vec::new();
                for k in 0..d {
                    let mut s: u128 = 0;
                    for j in 0..d { if a[j] != 0 {
                        if a[j] > 0 { s += pw[k][j] as u128; } else { s += (p - pw[k][j]) as u128; }
                    }}
                    if s % p as u128 == 0 { annset.push(exps[k]); }
                }
                let v = annset.len() as u32;
                if v > gmax[used] { gmax[used] = v; gmaxp[used] = p; }
                if v >= 2 { *ever_v2 += 1; if v > ev2w.1 { *ev2w = (p, v); } }
                if v >= 1 && count_galois {
                    // is A_T closed under SOME nontrivial cyclic Galois subgroup <b>?
                    let mut stable = false;
                    if (v as usize) == d { stable = true; } // all roots = honest Z-vanishing
                    else {
                        for &b in odds { if b != 1 && coset_closed(&annset, b, n) { stable = true; break; } }
                    }
                    if stable { *stable_cnt += 1; } else { *genuine_cnt += 1; }
                }
                return;
            }
            a[pos] = 0;
            rec(a, pos+1, d, used, wcap, p, pw, exps, n, odds, gmax, gmaxp, ever_v2, ev2w, stable_cnt, genuine_cnt, count_galois);
            if used < wcap {
                a[pos] = 1;  rec(a, pos+1, d, used+1, wcap, p, pw, exps, n, odds, gmax, gmaxp, ever_v2, ev2w, stable_cnt, genuine_cnt, count_galois);
                a[pos] = -1; rec(a, pos+1, d, used+1, wcap, p, pw, exps, n, odds, gmax, gmaxp, ever_v2, ev2w, stable_cnt, genuine_cnt, count_galois);
                a[pos] = 0;
            }
        }

        let do_galois = pp == prize_p || _first_spur_check(pp, n);
        let mut stable_cnt = 0u64; let mut genuine_cnt = 0u64;
        rec(&mut a, 1, d, 1, wcap, pp, &pw, &exps, n, &odds,
            &mut global_maxv, &mut global_maxv_prime, &mut ever_v2, &mut ever_v2_witness,
            &mut stable_cnt, &mut genuine_cnt, do_galois);
        if do_galois && (stable_cnt + genuine_cnt) > 0 {
            let beta_p = (pp as f64).ln() / (n as f64).ln();
            println!("   [GALOIS @ p={} (n^{:.2})] spur configs: Galois-stable A_T = {}, GENUINE (no nontrivial symmetry) = {}",
                     pp, beta_p, stable_cnt, genuine_cnt);
        }
        pp = fp(n, pp + 1);
    }

    println!("\n   (Q1) GLOBAL v_p CAP per weight over {} primes (p=1 mod {}):", nprimes, n);
    let mut overall = 0u32;
    for w in 1..=wcap {
        println!("     w={:2}: global max v_p = {}  (witness prime p={})", w, global_maxv[w], global_maxv_prime[w]);
        if global_maxv[w] > overall { overall = global_maxv[w]; }
    }
    println!("   => OVERALL global max v_p over all weights<={} and all swept primes = {}", wcap, overall);
    println!("      #(config,prime) pairs with v_p>=2 = {}  {}", ever_v2,
             if ever_v2 == 0 { "=> v_p in {0,1} ALWAYS: spurious mass p-adically SQUAREFREE (perfectly spread, no concentration)" }
             else { "=> some multi-prime concentration exists" });
    if ever_v2 > 0 { println!("      max v_p>=2 witness: p={} v={}", ever_v2_witness.0, ever_v2_witness.1); }

    let beta_pr = (prize_p as f64).ln() / (n as f64).ln();
    println!("\n   prize prime p={} = n^{:.2}", prize_p, beta_pr);
}

// helper: is pp the first prime (in the 1-mod-n progression from n) -- we trigger galois count on a
// few early primes to see structure. Mark the first 3 primes as "interesting".
fn _first_spur_check(pp: u64, n: u64) -> bool {
    let p1 = fp(n, n);
    let p2 = fp(n, p1 + 1);
    let p3 = fp(n, p2 + 1);
    pp == p1 || pp == p2 || pp == p3
}
