// wf-S4 (#444): GALOIS-ORBIT decomposition of the CONCENTRATED energy inflation at structured primes.
//
// SETUP. n=2^mu, p=1 mod n, q=p. eta_b = sum_{x in mu_n} e_p(b x). |eta_b|^2 is coset-constant
//   (eta_{ux}=eta_x for u in mu_n), so it is a function on the m=(p-1)/n cosets G_coset = F_p^*/mu_n.
//   E_r = (1/q)[ n^{2r} + n * sum_{coset reps b!=0} |eta_b|^{2r} ].  M = max_{b!=0}|eta_b|.
//
// THE S4 GALOIS GROUP. Gal(Q(zeta_n)/Q) = (Z/n)^* acts on the picture. For n=2^mu it is
//   Z/2 x Z/2^{mu-2} (generated by -1 and 5). The Galois action sigma_a: zeta -> zeta^a permutes
//   the FREQUENCIES b (since e_p(b x) <-> the additive character, and the multiplicative-subgroup
//   structure is Galois-stable). Concretely on the coset index: b is a multiplicative coset rep;
//   a in (Z/n)^* acts by b -> b * (h^{(a-1)/?}) ... we use the CLEAN realization: |eta_b| depends
//   only on the n-th-power-residue class, and the relevant symmetry on |eta_b|^2 is the map
//   b -> b^a for a coprime to (p-1)/n's structure that fixes mu_n setwise. The honest, exact
//   symmetry we test: the DUAL-multiplicative action  b -> g^j * b  (j a transversal step) already
//   spans the m cosets; the GALOIS-ON-FREQUENCIES symmetry is the subgroup of these that comes
//   from sigma_a (zeta->zeta^a) on the n-th roots, i.e. multiplication by h^{(a-1)} is trivial on
//   mu_n but the FROBENIUS-FREE p=1 mod n case means Gal acts on the SPLITTING primes, equivalently
//   on the eta_b via the n/2 "spectral orbits".
//
// WHAT WE ACTUALLY MEASURE (exact, no heuristic):
//   (A) The CONCENTRATION of the inflated energy at the structured (Fermat / max-v2) prime vs a
//       generic prime: effective #freqs = sum|eta|^{2r}/max|eta|^{2r}, top-K mass, M and C.
//   (B) Whether the TOP frequencies (the ones carrying the spurious inflation) are exactly the
//       GAUSS-PERIOD / S-SYMMETRIC frequencies: b such that b lies in a proper subgroup-coset
//       structure -- i.e. b^{2^k} = b for small k, equivalently b is fixed by a nontrivial part of
//       the cyclic 2-group. We test: are the high-|eta_b| frequencies the ones where b generates a
//       SMALL subgroup mod the n-structure (low "order index")? Stickelberger predicts the spurious
//       (highly-vanishing / high-norm) configs are the S-symmetric ones = Gauss periods.
//   (C) The Galois-2-group orbit of each frequency under b -> b^5 (the order-2^{mu-2} generator of
//       (Z/n)^* mod {+-1}) lifted to F_p^* via the Teichmuller-like map, and whether |eta_b| is
//       constant on these orbits (Galois-invariance of |eta|) -- if YES, the inflation lives on
//       SHORT Galois orbits (=> concentrated => M can grow), if it were spread on full orbits M small.

use std::f64::consts::PI;
fn mpow(a:u64,mut e:u64,p:u64)->u64{let mut r=1u128;let mut a2=a as u128;let pp=p as u128;while e>0{if e&1==1{r=r*a2%pp;}a2=a2*a2%pp;e>>=1;}r as u64}
fn isp(n:u64)->bool{if n<2{return false}if n%2==0{return n==2}let mut d=3;while d*d<=n{if n%d==0{return false}d+=2}true}
fn proot(p:u64)->u64{let mut m=p-1;let mut fs=vec![];let mut d=2;while d*d<=m{if m%d==0{fs.push(d);while m%d==0{m/=d}}d+=1}if m>1{fs.push(m)}let mut g=2;loop{if fs.iter().all(|&f|mpow(g,(p-1)/f,p)!=1){return g}g+=1}}
fn v2(mut x:u64)->u32{let mut v=0;while x&1==0{v+=1;x>>=1}v}

// |eta_b|^2 over a transversal of mu_n in F_p^*, indexed by the coset exponent j (b = g^j).
fn eta2(n:u64,p:u64)->(Vec<f64>,u64){
    let g=proot(p); let h=mpow(g,(p-1)/n,p);
    let mu:Vec<u64>=(0..n).map(|j|mpow(h,j,p)).collect();
    let m=(p-1)/n;
    let mut out=Vec::with_capacity(m as usize);
    let mut b=1u64;
    for _ in 0..m {
        let mut re=0.0; let mut im=0.0;
        for &x in &mu { let t=((b as u128*x as u128)%p as u128) as u64; let a=2.0*PI*(t as f64)/(p as f64); re+=a.cos(); im+=a.sin(); }
        out.push(re*re+im*im);
        b=((b as u128*g as u128)%p as u128) as u64;
    }
    (out,g)
}

// Galois-on-frequencies orbits. (Z/n)^* acts via sigma_a: the additive char e_p(b x) is sent by the
// field automorphism that fixes F_p (none, p=1 mod n => trivial Frobenius) -- so the relevant action
// on the |eta_b| is the MULTIPLICATIVE one b -> b^a for a in (Z/(p-1)) that preserves mu_n setwise,
// i.e. a in the subgroup that fixes <g^m>=mu_n, which is all of (Z/(p-1))^* acting on cosets as the
// induced perm of F_p^*/mu_n. The CYCLOTOMIC Galois group (Z/n)^* embeds as b -> b * t where t runs
// over mu_n-coset reps fixed by the n-power map: precisely the n/2 SPLITTING-PRIME orbits.
//
// We compute the orbit of coset j (b=g^j) under b -> b^a for a = the powers of 5 mod n lifted: the
// honest invariant we test is |eta_{b}| vs |eta_{b^a}| for a in (Z/n)^* realized as exponent maps on
// the n-th root structure. Equivalently: c-th power map on cosets, c in {odd residues mod n}.
fn galois_orbit_concentration(n:u64,p:u64,r:u32)->(f64,f64,f64,f64,f64,usize){
    let (d,_g)=eta2(n,p);
    let m=d.len();
    let nn=n as f64; let q=p as f64;
    // energy pieces
    let sumr:f64=d.iter().map(|&x|x.powi(r as i32)).sum();
    let er=(nn.powi(2*r as i32) + nn*sumr)/q;
    let erc0=match r {1=>nn, 2=>3.0*nn*nn-3.0*nn, 3=>15.0*nn*nn*nn, _=>{
        // (2r-1)!! n^r exact for the leading char-0 term
        let mut dd=1.0; let mut k=2*r as i64-1; while k>=1 {dd*=k as f64; k-=2;} dd*nn.powi(r as i32)}};
    let mut mx=0.0; for &x in &d {if x>mx{mx=x;}}
    let mmax=mx.sqrt();
    let cprize=mmax/(nn*(q/nn).ln()).sqrt();
    let eff=sumr/(mx.powi(r as i32));
    (er, erc0, mmax, cprize, eff, m)
}

// (B)/(C): classify the TOP frequencies. For each coset rep b=g^j, compute its "subgroup-symmetry
// index" = the size of the orbit of b under the cyclotomic-Galois power maps b -> b^c, c in odd
// residues mod n, RESTRICTED to staying in the same mu_n-coset-quotient class. A Gauss-period
// (S-symmetric) frequency has a SHORT such orbit. We test correlation of |eta_b| with orbit length.
fn top_freq_symmetry(n:u64,p:u64,topk:usize){
    let (d,g)=eta2(n,p);
    let m=d.len();
    // sort coset indices by |eta_b| desc
    let mut idx:Vec<usize>=(0..m).collect();
    idx.sort_by(|&a,&b|d[b].partial_cmp(&d[a]).unwrap());
    // For each coset index j (b=g^j), the n/2 cyclotomic Galois elements act on the additive char
    // e_p(b.) by b -> b * h^? ... the clean Galois-on-eta orbit: |eta_b| is invariant under b -> b^c
    // for c with c == 1 mod (p-1)/n? No. The exact invariance proven in-tree (galois norm) is
    // |eta_b| = |eta_{b'}| when b' = b^a, a in (Z/n)^* acting on n-th roots, realized as multiplying
    // the coset exponent j by a unit mod m's n-part. We test the SIMPLE, EXACT invariance:
    //   sigma_{-1}: b -> -b  (complex conj, n even => |eta_{-b}|=|eta_b| always). orbit halves.
    // and the 5-power generator b -> b * (g^{m * s}) gives coset shift. We REPORT, for the top-k
    // freqs, the value h^{...}; concretely we report: is the top freq's coset index j a multiple of
    // a large power of 2 (=> b in a deep subgroup => Gauss period)?
    let g_ord=p-1;
    // factor p-1 once for fast order computation: ord(b) = (p-1) / (largest divisor d|p-1 with b^{(p-1)/d}... )
    // ord = (p-1) / k where k = product over prime factors we can strip. compute ord by reducing.
    let mut m1=g_ord; let mut pf=vec![]; let mut dd=2u64;
    while dd*dd<=m1 { if m1%dd==0 { pf.push(dd); while m1%dd==0 {m1/=dd;} } dd+=1; }
    if m1>1 { pf.push(m1); }
    let order_of=|b:u64|->u64{
        let mut o=g_ord;
        for &pp in &pf { while o%pp==0 && mpow(b,o/pp,p)==1 { o/=pp; } }
        o
    };
    println!("    top-{} freqs at p={} (coset exp j=log_g b, |eta_b|, ord(b), depth=(p-1)/ord, v2(j)):",topk,p);
    println!("    (Stickelberger/Gauss-period prediction: inflating freqs are LOW-ORDER b => large depth)");
    for &j in idx.iter().take(topk) {
        let b=mpow(g,j as u64,p);
        let ord=order_of(b);
        let depth=g_ord/ord;
        println!("        j={:>7} |eta_b|={:>7.3} ord(b)={:>8} depth={:>6} v2(j)={}",
            j, d[j].sqrt(), ord, depth, v2(j as u64));
    }
    // summary: median order of top-k vs median order over ALL freqs (is top set unusually low-order?)
    let mut all_ord:Vec<u64>=(0..m).map(|j|order_of(mpow(g,j as u64,p))).collect();
    let top_ord:Vec<u64>=idx.iter().take(topk).map(|&j|order_of(mpow(g,j as u64,p))).collect();
    all_ord.sort(); let med_all=all_ord[m/2];
    let mut to=top_ord.clone(); to.sort(); let med_top=to[to.len()/2];
    println!("    => median ord(b): TOP-{}={} vs ALL={}  (ratio {:.3}; <1 => inflating freqs are lower-order)",
        topk, med_top, med_all, med_top as f64/med_all as f64);
}

fn good_prime(n:u64,beta:f64)->u64{
    let target=(n as f64).powf(beta) as u64;
    let mut p=target+((n - target%n)%n)+1; if p%n!=1 {p=p-(p%n)+1;}
    loop { if p%n==1 && isp(p){return p;} p+=n; }
}
// structured = maximize v2(p-1) in a band; generic = minimize.
fn band_primes(n:u64,beta:f64)->(u64,u64){
    let lo=(n as f64).powf(beta) as u64;
    let mut p=lo+((n-lo%n)%n)+1; if p%n!=1 {p=p-(p%n)+1;}
    let mut bs=(0u64,0u32); let mut bg=(0u64,99u32); let mut c=0;
    while c<300 { if p%n==1 && isp(p){let vv=v2(p-1); if vv>bs.1{bs=(p,vv);} if vv<bg.1{bg=(p,vv);} c+=1;} p+=n; }
    (bs.0,bg.0)
}

fn main(){
    println!("# wf-S4: Galois-orbit concentration of the spurious energy inflation at structured primes.");
    println!("# CLAIM under test: at a structured prime E_r inflates AND the inflation is CONCENTRATED");
    println!("#   on a SMALL Gauss-period (S-symmetric/low-order) frequency set => M grows there too.");
    println!("#   If C=M/sqrt(n log(p/n)) stays bounded across n even at structured primes => prize-safe.\n");

    // C across n at the WORST (max v2) prime per band, beta~4, r=2 and r=3.
    println!("## (A) C and concentration at structured(max v2) vs generic(min v2), beta~4:");
    for &n in &[16u64,32,64] {
        let (ps,pg)=band_primes(n,4.0);
        for r in [2u32,3] {
            let (er,erc0,m_s,c_s,eff_s,_)=galois_orbit_concentration(n,ps,r);
            let (_,_,m_g,c_g,eff_g,mm)=galois_orbit_concentration(n,pg,r);
            println!("  n={:>3} r={} STRUCT p={} v2={}: E{}/c0={:.3} M={:.2} C={:.4} eff#freq={:.1}({:.2}%) | GENERIC C={:.4} eff#freq={:.1}",
                n,r,ps,v2(ps-1),r,er/erc0,m_s,c_s,eff_s,100.0*eff_s/(mm as f64),c_g,eff_g);
        }
    }
    // The hard Fermat cases (max possible v2): n=32 p=65537, n=64 p=? (Fermat-like), small-beta worst.
    println!("\n## (B) WORST-CASE structured primes (max v2, smaller beta = where SHORT relations live):");
    for &(n,p) in &[(16u64,40961u64),(32,65537),(64,786433),(16,12289),(32,40961)] {
        if isp(p) && (p-1)%n==0 {
            for r in [2u32,3,4] {
                let (er,erc0,mm,cp,eff,m)=galois_orbit_concentration(n,p,r);
                println!("  n={:>3} p={:>8} v2={} beta={:.2} r={}: E/c0={:.3} M={:.2} C={:.4} eff#freq={:.1} (of m={})",
                    n,p,v2(p-1),(p as f64).ln()/(n as f64).ln(),r,er/erc0,mm,cp,eff,m);
            }
            println!();
        }
    }
    // (C) top-freq symmetry structure at the Fermat n=32 p=65537 (where inflation is concentrated).
    println!("## (C) ARE the top (inflating) freqs the low-order/Gauss-period ones? n=32 p=65537:");
    top_freq_symmetry(32,65537,12);
    println!("\n## (C') generic comparison n=32 generic prime top freqs:");
    let (_,pg)=band_primes(32,3.2);
    top_freq_symmetry(32,pg,12);
}
