/-
Copyright (c) 2025 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/

import VCVio.OracleComp.SimSemantics.Append
import ArkLib.Data.GroupTheory.PrimeOrder
import ArkLib.Data.Classes.Serde

/-! # The Algebraic Group Model (with Oblivious Sampling)

This module formalizes the Algebraic Group Model (AGM) equipped with oblivious sampling,
drawing on the foundations laid by Jaeger and Mohan [JM24] as well as Lipmaa, Parisella,
and Siim [LPS24]. In the AGM, adversaries are modeled as algebraic: any group element
output by the adversary must be accompanied by an explicit representation (a vector of
exponents) expressing it as a linear combination of previously received group elements.
This formalization supports group operations, exponentiation, equality testing, and
serialized encoding/decoding, tracking the adversary's state as a dynamic valuation table.

## References

* [Jaeger, J. and Mohan, D.I., *Generic and algebraic computation models: When AGM proofs transfer
    to the GGM*][JM24]
* [Lipmaa, H., Parisella, R., and Siim, J., *On Knowledge-Soundness of Plonk in ROM from
    Falsifiable Assumptions*][LPS24]
-/

open OracleComp OracleSpec

namespace AGM

@[ext]
structure GroupRepresentation {G : Type*} [Group G] {p : ℕ} (prev : List G) (target : G) where
  exponents : List (ZMod p)
  hEq : (prev.zipWith (fun g a => g ^ a.val) exponents).prod = target

namespace GroupRepresentation

variable {G : Type*} [Group G] {p : ℕ}

/-- The product encoded by a representation is always in the subgroup generated by its basis. -/
theorem zipWith_pow_prod_mem_closure (prev : List G) (exponents : List (ZMod p)) :
    (prev.zipWith (fun g a => g ^ a.val) exponents).prod ∈
      Subgroup.closure {g | g ∈ prev} := by
  induction prev generalizing exponents with
  | nil =>
      simp
  | cons g prev ih =>
      cases exponents with
      | nil =>
          simp
      | cons a exponents =>
          simp only [List.mem_cons, List.zipWith_cons_cons, List.prod_cons]
          let H := Subgroup.closure {x : G | x = g ∨ x ∈ prev}
          have hg : g ∈ H := Subgroup.subset_closure (by simp)
          have hrest_small :
              (prev.zipWith (fun g a => g ^ a.val) exponents).prod ∈
                Subgroup.closure {x : G | x ∈ prev} :=
            ih exponents
          have hmono :
              Subgroup.closure {x : G | x ∈ prev} ≤ H :=
            Subgroup.closure_mono (by
              intro x hx
              exact Or.inr hx)
          exact H.mul_mem (H.pow_mem hg a.val) (hmono hrest_small)

/-- **AGM representation soundness, membership form.** A represented target lies in the subgroup
generated by the group elements that were available to the algebraic adversary. -/
theorem target_mem_closure {prev : List G} {target : G}
    (repr : GroupRepresentation (p := p) prev target) :
    target ∈ Subgroup.closure {g | g ∈ prev} := by
  rw [← repr.hEq]
  exact zipWith_pow_prod_mem_closure prev repr.exponents

/-- The identity has a representation over every basis. The current representation format permits
short exponent lists because `zipWith` truncates, so the empty exponent vector represents `1`. -/
def one (prev : List G) : GroupRepresentation (p := p) prev 1 where
  exponents := []
  hEq := by simp

/-- Over the empty basis, every representation targets the identity. -/
theorem target_eq_one_of_nil {target : G}
    (repr : GroupRepresentation (p := p) ([] : List G) target) :
    target = 1 := by
  simpa using repr.hEq.symm

#print axioms GroupRepresentation.zipWith_pow_prod_mem_closure
#print axioms GroupRepresentation.target_mem_closure
#print axioms GroupRepresentation.one
#print axioms GroupRepresentation.target_eq_one_of_nil

end GroupRepresentation

local instance {α : Type*} : Zero (Option α) where
  zero := none

/-- A partially defined table of group elements, indexed by `ι`. The table represents the
  adversary's knowledge state, mapping currently accessible group elements to their algebraic
  values. Finiteness of the support is enforced via `DFinsupp` (which provides a computable
  representation of finitely supported functions). -/
@[reducible]
def GroupValTable (ι : Type*) (G : Type*) := Π₀ _ : ι, Option G

section OracleSpec

variable (ι : Type) (p : ℕ)

/-- The group operation oracle allows an adversary to perform the group operation on group elements
  stored at the indices `i` and `j` (if they are both defined), storing the result at index `k`. -/
@[reducible]
def GroupOpOracle : OracleSpec (ι × ι × ι) := fun _ => Unit

/-- The group exponent oracle allows an adversary to compute the group element at the index `i`
  raised to the power `a`, storing the result at index `j`.

  Technically, this oracle can be implemented with just the group operation oracle, but we allow
  this for faster implementation. -/
@[reducible]
def GroupExpOracle : OracleSpec (ι × ZMod p × ι) := fun _ => Unit

/-- The group equality oracle allows an adversary to check if the group elements stored at the
  indices `i` and `j` are equal. -/
@[reducible]
def GroupEqOracle : OracleSpec (ι × ι) := fun _ => Bool

variable (bitLength : ℕ)

/-- The group encoding oracle allows an adversary to get the bit encoding of a group element. -/
@[reducible]
def GroupEncodeOracle : OracleSpec ι := fun _ => BitVec bitLength

/-- The group decoding oracle allows an adversary to insert a group element corresponding to a
  bit encoding into the table, if the bit encoding is valid. -/
@[reducible]
def GroupDecodeOracle : OracleSpec (BitVec bitLength × ι) := fun _ => Unit

end OracleSpec

section impl

variable {ι : Type} [DecidableEq ι] {G : Type} [Group G] {p : ℕ}

/-- Implementation of the group operation oracle, which changes some underlying table of group
  elements, using the group operation `op`. If the indices `i` and `j` does not contain group
  elements yet, the oracle will fail. -/
def implGroupOpOracle : QueryImpl (GroupOpOracle ι) (StateT (GroupValTable ι G) Option) :=
  fun | ⟨i, j, k⟩ => fun table =>
    match table i, table j with
    | some g₁, some g₂ => some ((), table.update k (some (g₁ * g₂)))
    | _, _ => none

/-- Implementation of the group exponent oracle, which computes the group element at the index `i`
  raised to the power `a`, storing the result at index `j`. This will fail if the index `i` does
  not contain a group element yet. -/
def implGroupExpOracle : QueryImpl (GroupExpOracle ι p) (StateT (GroupValTable ι G) Option) :=
  fun | ⟨i, a, j⟩ => fun table =>
    match table i with
    | some g => some ((), table.update j (some (g ^ a.val)))
    | none => none

/-- Implementation of the group equality oracle, which checks if the group elements at the indices
  `i` and `j` are equal, and leave the table unchanged. -/
def implGroupEqOracle [BEq G] :
    QueryImpl (GroupEqOracle ι) (StateT (GroupValTable ι G) Option) :=
  fun | ⟨i, j⟩ => fun table =>
    match table i, table j with
    | some g₁, some g₂ => some (g₁ == g₂, table)
    | _, _ => none

variable {bitLength : ℕ}

/-- Implementation of the group encoding oracle, which returns the bit encoding of the group element
  at the index `i`, leaving the table unchanged. This will fail if the index `i` does not contain
  a group element yet. -/
def implGroupEncodeOracle [Serialize G (BitVec bitLength)] :
    QueryImpl (GroupEncodeOracle ι bitLength) (StateT (GroupValTable ι G) Option) :=
  fun | i => fun table =>
    match table i with
    | some g => some (serialize g, table)
    | none => none

/-- Implementation of the group decoding oracle, which inserts a group element corresponding to a
  bit encoding into the table, if the bit encoding is valid. This will fail if the bit encoding
  is invalid. -/
def implGroupDecodeOracle [DeserializeOption G (BitVec bitLength)] :
    QueryImpl (GroupDecodeOracle ι bitLength) (StateT (GroupValTable ι G) Option) :=
  fun | (b, i) => fun table =>
    match DeserializeOption.deserialize b with
    | some g => some ((), table.update i (some g))
    | none => none

end impl

/-- An adversary in the Algebraic Group Model (AGM) is defined as follows:

- It is given knowledge of the initial configuration of the group table
- It may use any of the group oracles, including for group operation, group exponentiation, group
  equality testing, and returning group encoding (no decoding of group elements allowed)
- It returns a list of handles specifying the group elements it is supposed to output, and a
  non-group-element result of type `α`

Note: even if the adversary knows the initial group table, it can only output group elements
implicitly, via indices in the table. This means the group element outputs can only be computed via
utilizing the oracles.

Note: this definition models adversary output through table handles.
-/
def Adversary (ι : Type) (G : Type) (p : ℕ) (bitLength : ℕ) (α : Type) : Type _ :=
  ReaderT (GroupValTable ι G)
    (OracleComp (GroupOpOracle ι + GroupExpOracle ι p +
      GroupEqOracle ι + GroupEncodeOracle ι bitLength))
    (List ι × α)

namespace Adversary

variable {ι : Type} [DecidableEq ι] {G : Type} [Group G] [DecidableEq G]
    {p : ℕ} {bitLength : ℕ}
    [Serialize G (BitVec bitLength)] [DeserializeOption G (BitVec bitLength)]
    (α : Type)

/-- Running the adversary on a given table, returning the list of group elements it is supposed to
  output, and the non-group-element result. The run can fail if an oracle query fails or if the
  adversary returns a handle that is not defined in the final table. -/
def run (adversary : Adversary ι G p bitLength α) (table : GroupValTable ι G) :
    Option (List G × α) := do
  let opImpl : QueryImpl (GroupOpOracle ι) (StateT (GroupValTable ι G) Option) :=
    implGroupOpOracle
  let expImpl : QueryImpl (GroupExpOracle ι p) (StateT (GroupValTable ι G) Option) :=
    implGroupExpOracle
  let eqImpl : QueryImpl (GroupEqOracle ι) (StateT (GroupValTable ι G) Option) :=
    implGroupEqOracle
  let encImpl : QueryImpl (GroupEncodeOracle ι bitLength) (StateT (GroupValTable ι G) Option) :=
    implGroupEncodeOracle
  let impl :
      QueryImpl
        (GroupOpOracle ι + GroupExpOracle ι p + GroupEqOracle ι +
          GroupEncodeOracle ι bitLength)
        (StateT (GroupValTable ι G) Option) :=
    opImpl + expImpl + eqImpl + encImpl
  let ⟨⟨handles, result⟩, finalTable⟩ ← (simulateQ impl (adversary table)).run table
  let outputs ← handles.mapM fun i => finalTable i
  pure (outputs, result)

end Adversary

end AGM
