/-
Copyright (c) 2025 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/

import VCVio.OracleComp.SimSemantics.Append
import ArkLib.Data.GroupTheory.PrimeOrder
import ArkLib.Data.Classes.Serde

/-! # The Algebraic Group Model (with Oblivious Sampling)

This module formalizes the Algebraic Group Model (AGM) equipped with oblivious sampling,
drawing on the foundations laid by Jaeger and Mohan [JM24] as well as Lipmaa, Parisella,
and Siim [LPS24]. In the AGM, adversaries are modeled as algebraic: any group element
output by the adversary must be accompanied by an explicit representation (a vector of
exponents) expressing it as a linear combination of previously received group elements.
This formalization supports group operations, exponentiation, equality testing, and
serialized encoding/decoding, tracking the adversary's state as a dynamic valuation table.

## References

* [Jaeger, J. and Mohan, D.I., *Generic and algebraic computation models: When AGM proofs transfer
    to the GGM*][JM24]
* [Lipmaa, H., Parisella, R., and Siim, J., *On Knowledge-Soundness of Plonk in ROM from
    Falsifiable Assumptions*][LPS24]
-/

open OracleComp OracleSpec

namespace AGM

@[ext]
structure GroupRepresentation {G : Type*} [Group G] {p : ℕ} (prev : List G) (target : G) where
  exponents : List (ZMod p)
  hEq : (prev.zipWith (fun g a => g ^ a.val) exponents).prod = target

namespace GroupRepresentation

variable {G : Type*} [Group G] {p : ℕ}

/-- The product encoded by a representation is always in the subgroup generated by its basis. -/
theorem zipWith_pow_prod_mem_closure (prev : List G) (exponents : List (ZMod p)) :
    (prev.zipWith (fun g a => g ^ a.val) exponents).prod ∈
      Subgroup.closure {g | g ∈ prev} := by
  induction prev generalizing exponents with
  | nil =>
      simp
  | cons g prev ih =>
      cases exponents with
      | nil =>
          simp
      | cons a exponents =>
          simp only [List.mem_cons, List.zipWith_cons_cons, List.prod_cons]
          let H := Subgroup.closure {x : G | x = g ∨ x ∈ prev}
          have hg : g ∈ H := Subgroup.subset_closure (by simp)
          have hrest_small :
              (prev.zipWith (fun g a => g ^ a.val) exponents).prod ∈
                Subgroup.closure {x : G | x ∈ prev} :=
            ih exponents
          have hmono :
              Subgroup.closure {x : G | x ∈ prev} ≤ H :=
            Subgroup.closure_mono (by
              intro x hx
              exact Or.inr hx)
          exact H.mul_mem (H.pow_mem hg a.val) (hmono hrest_small)

/-- **AGM representation soundness, membership form.** A represented target lies in the subgroup
generated by the group elements that were available to the algebraic adversary. -/
theorem target_mem_closure {prev : List G} {target : G}
    (repr : GroupRepresentation (p := p) prev target) :
    target ∈ Subgroup.closure {g | g ∈ prev} := by
  rw [← repr.hEq]
  exact zipWith_pow_prod_mem_closure prev repr.exponents

/-- The identity has a representation over every basis. The current representation format permits
short exponent lists because `zipWith` truncates, so the empty exponent vector represents `1`. -/
def one (prev : List G) : GroupRepresentation (p := p) prev 1 where
  exponents := []
  hEq := by simp

/-- Over the empty basis, every representation targets the identity. -/
theorem target_eq_one_of_nil {target : G}
    (repr : GroupRepresentation (p := p) ([] : List G) target) :
    target = 1 := by
  simpa using repr.hEq.symm

/-- A group hom commutes with the `zipWith`-power product over a basis: applying `f` pointwise to
  the basis and reusing the same exponents equals `f` of the original product. -/
theorem zipWith_pow_map {H : Type*} [Group H] (f : G →* H)
    (prev : List G) (exponents : List (ZMod p)) :
    ((prev.map f).zipWith (fun g a => g ^ a.val) exponents).prod
      = f ((prev.zipWith (fun g a => g ^ a.val) exponents).prod) := by
  induction prev generalizing exponents with
  | nil => simp
  | cons g prev ih =>
    cases exponents with
    | nil => simp
    | cons a exponents =>
      simp only [List.map_cons, List.zipWith_cons_cons, List.prod_cons, map_mul, map_pow]
      rw [ih exponents]

/-- **Functoriality of representations under group homomorphisms.** A group hom `f : G →* H`
  transports an algebraic representation of `target` over basis `prev` to one of `f target` over
  the image basis `prev.map f`, with the *same* exponent vector. This is the structural core of the
  AGM ⇒ GGM transfer ([JM24]): an algebraic representation is preserved by any group
  homomorphism, so the exponents an algebraic adversary commits to in `G` certify the image
  element in `H`. -/
def map {H : Type*} [Group H] (f : G →* H) {prev : List G} {target : G}
    (repr : GroupRepresentation (p := p) prev target) :
    GroupRepresentation (p := p) (prev.map f) (f target) where
  exponents := repr.exponents
  hEq := by rw [zipWith_pow_map, repr.hEq]

/-- **Rank-1 representation.** Over a singleton basis `[g]`, any power `g ^ a.val` of the generator
is representable (the single-generator building block of representation completeness). -/
def singleton (g : G) (a : ZMod p) : GroupRepresentation (p := p) [g] (g ^ a.val) where
  exponents := [a]
  hEq := by simp

/-- **Basis weakening.** An algebraically-represented target stays representable when the basis is
extended on the left by extra generators: pad the exponent vector with zeros for the new
generators (each contributes `g ^ 0 = 1`). The constructive complement to `target_mem_closure`. -/
def prependBasis {prev : List G} {target : G}
    (repr : GroupRepresentation (p := p) prev target) (extra : List G) :
    GroupRepresentation (p := p) (extra ++ prev) target where
  exponents := List.replicate extra.length 0 ++ repr.exponents
  hEq := by
    rcases repr with ⟨exps, hEq⟩
    induction extra with
    | nil => simpa using hEq
    | cons g gs ih =>
        simp only [List.length_cons, List.replicate_succ, List.cons_append,
          List.zipWith_cons_cons, List.prod_cons]
        rw [show ((0 : ZMod p).val) = 0 from by simp, pow_zero, one_mul]
        exact ih

private theorem zipWith_replicate_zero_prod (xs : List G) (n : ℕ) :
    (xs.zipWith (fun g a => g ^ a.val) (List.replicate n (0 : ZMod p))).prod = 1 := by
  induction xs generalizing n with
  | nil => simp
  | cons g xs ih =>
      cases n with
      | zero => simp
      | succ n =>
          simp only [List.replicate_succ, List.zipWith_cons_cons, List.prod_cons]
          rw [show ((0 : ZMod p).val) = 0 from by simp, pow_zero, one_mul, ih n]

private theorem zipWith_take_length_prod (prev : List G) (exponents : List (ZMod p)) :
    (prev.zipWith (fun g a => g ^ a.val) (exponents.take prev.length)).prod
      = (prev.zipWith (fun g a => g ^ a.val) exponents).prod := by
  induction prev generalizing exponents with
  | nil => simp
  | cons g prev ih =>
      cases exponents with
      | nil => simp
      | cons a exponents =>
          simp only [List.length_cons, List.take_succ_cons, List.zipWith_cons_cons,
            List.prod_cons]
          rw [ih exponents]

private theorem zipWith_append_replicate_zero_prod {prev extra : List G}
    (exponents : List (ZMod p)) :
    ((prev ++ extra).zipWith (fun g a => g ^ a.val)
        (exponents.take prev.length ++ List.replicate extra.length 0)).prod
      = (prev.zipWith (fun g a => g ^ a.val) exponents).prod := by
  induction prev generalizing exponents with
  | nil =>
      simpa using zipWith_replicate_zero_prod (p := p) extra extra.length
  | cons g prev ih =>
      cases exponents with
      | nil =>
          simpa using zipWith_replicate_zero_prod (p := p) (g :: (prev ++ extra)) extra.length
      | cons a exponents =>
          simp only [List.length_cons, List.take_succ_cons, List.cons_append,
            List.zipWith_cons_cons, List.prod_cons]
          rw [ih exponents]

/-- **Exponent normalization.** A representation can discard any exponent-vector tail past the
current basis length without changing its target, because `zipWith` never consumes those entries. -/
def trimExponents {prev : List G} {target : G}
    (repr : GroupRepresentation (p := p) prev target) :
    GroupRepresentation (p := p) prev target where
  exponents := repr.exponents.take prev.length
  hEq := by
    rw [zipWith_take_length_prod, repr.hEq]

/-- The normalized exponent vector has no entries past the basis length. -/
theorem trimExponents_length_le {prev : List G} {target : G}
    (repr : GroupRepresentation (p := p) prev target) :
    (repr.trimExponents).exponents.length ≤ prev.length := by
  simp [trimExponents]

/-- Trimming is identity for representations whose exponent vectors are already short enough. -/
theorem trimExponents_eq_self_of_length_le {prev : List G} {target : G}
    (repr : GroupRepresentation (p := p) prev target)
    (h : repr.exponents.length ≤ prev.length) :
    repr.trimExponents = repr := by
  ext
  simp [trimExponents, (List.take_eq_self_iff repr.exponents).2 h]

/-- Trimming exponent vectors is idempotent. -/
theorem trimExponents_idem {prev : List G} {target : G}
    (repr : GroupRepresentation (p := p) prev target) :
    repr.trimExponents.trimExponents = repr.trimExponents := by
  exact trimExponents_eq_self_of_length_le repr.trimExponents (trimExponents_length_le repr)

/-- **Right-side basis weakening.** An algebraically-represented target stays representable when
the basis is extended on the right by extra generators. Because the representation format permits
overlong exponent vectors and `zipWith` truncates, we first truncate to the original basis length,
then pad by zeros for the appended generators. -/
def appendBasis {prev : List G} {target : G}
    (repr : GroupRepresentation (p := p) prev target) (extra : List G) :
    GroupRepresentation (p := p) (prev ++ extra) target where
  exponents := repr.exponents.take prev.length ++ List.replicate extra.length 0
  hEq := by
    rw [zipWith_append_replicate_zero_prod, repr.hEq]

/-- Right-side basis weakening produces an exponent vector no longer than the extended basis. -/
theorem appendBasis_exponents_length_le {prev : List G} {target : G}
    (repr : GroupRepresentation (p := p) prev target) (extra : List G) :
    (repr.appendBasis extra).exponents.length ≤ (prev ++ extra).length := by
  simp [appendBasis]

/-- Right-side basis weakening is already normalized with respect to the extended basis. -/
theorem appendBasis_trimExponents_eq_self {prev : List G} {target : G}
    (repr : GroupRepresentation (p := p) prev target) (extra : List G) :
    (repr.appendBasis extra).trimExponents = repr.appendBasis extra := by
  exact trimExponents_eq_self_of_length_le (repr.appendBasis extra)
    (appendBasis_exponents_length_le repr extra)

/-- Right-side basis weakening ignores stale exponent tails in the input representation. -/
theorem appendBasis_eq_trimExponents_appendBasis {prev : List G} {target : G}
    (repr : GroupRepresentation (p := p) prev target) (extra : List G) :
    repr.appendBasis extra = repr.trimExponents.appendBasis extra := by
  ext
  simp [appendBasis, trimExponents, List.take_take]
private theorem zipWith_append_prod (xs ys : List G) (as bs : List (ZMod p))
    (hlen : xs.length = as.length) :
    ((xs ++ ys).zipWith (fun g a => g ^ a.val) (as ++ bs)).prod
      = (xs.zipWith (fun g a => g ^ a.val) as).prod *
        (ys.zipWith (fun g a => g ^ a.val) bs).prod := by
  induction xs generalizing as with
  | nil =>
      cases as with
      | nil => simp
      | cons a as => simp at hlen
  | cons x xs ih =>
      cases as with
      | nil => simp at hlen
      | cons a as =>
          simp only [List.cons_append, List.zipWith_cons_cons, List.prod_cons]
          rw [ih as (by simpa using hlen), mul_assoc]

/-- **Representation concatenation / composition.** Given representations of `t₁` over basis `prev₁`
and `t₂` over basis `prev₂`, their concatenation represents the product `t₁ * t₂` over the
concatenated basis `prev₁ ++ prev₂`. We require the first exponent vector to have exactly the length
of its basis so the truncating `zipWith` does not consume the second block; this is precisely the
length-discipline needed to glue two algebraic outputs into a representation of their product. -/
def mul {prev₁ prev₂ : List G} {t₁ t₂ : G}
    (r₁ : GroupRepresentation (p := p) prev₁ t₁) (r₂ : GroupRepresentation (p := p) prev₂ t₂)
    (hlen : prev₁.length = r₁.exponents.length) :
    GroupRepresentation (p := p) (prev₁ ++ prev₂) (t₁ * t₂) where
  exponents := r₁.exponents ++ r₂.exponents
  hEq := by
    rw [zipWith_append_prod prev₁ prev₂ r₁.exponents r₂.exponents hlen, r₁.hEq, r₂.hEq]

/-- The exponent vector produced by `mul` is the concatenation of the two component vectors. This is
the bookkeeping fact that lets `mul` chain: the length-discipline hypothesis of an outer `mul`
reduces to the component disciplines via `List.length_append`. -/
@[simp] theorem mul_exponents {prev₁ prev₂ : List G} {t₁ t₂ : G}
    (r₁ : GroupRepresentation (p := p) prev₁ t₁) (r₂ : GroupRepresentation (p := p) prev₂ t₂)
    (hlen : prev₁.length = r₁.exponents.length) :
    (r₁.mul r₂ hlen).exponents = r₁.exponents ++ r₂.exponents := rfl

private theorem map_inv_zipWith_pow (prev : List G) (exps : List (ZMod p)) :
    (prev.zipWith (fun g a => g ^ a.val) exps).map (·⁻¹)
      = (prev.map (·⁻¹)).zipWith (fun g a => g ^ a.val) exps := by
  induction prev generalizing exps with
  | nil => simp
  | cons g prev ih =>
      cases exps with
      | nil => simp
      | cons a exps =>
          simp only [List.map_cons, List.zipWith_cons_cons]
          rw [ih exps, inv_pow]

/-- **Inverse representation.** The inverse `target⁻¹` of a represented target is itself
representable: over the reversed list of inverted basis generators `(prev.map (·⁻¹)).reverse`, using
the reversed exponent vector. In a general (possibly non-abelian) group, inversion reverses the
order of the product, hence the reversal of both basis and exponents; for an abelian group this
collapses to negating the exponents in place. Requires the exponent vector to match the basis length
so the two reversals line up. The group-inverse counterpart to `mul`. -/
def inv {prev : List G} {target : G}
    (repr : GroupRepresentation (p := p) prev target)
    (hlen : prev.length = repr.exponents.length) :
    GroupRepresentation (p := p) ((prev.map (·⁻¹)).reverse) target⁻¹ where
  exponents := repr.exponents.reverse
  hEq := by
    have hlen' : (prev.map (·⁻¹)).length = repr.exponents.length := by simpa using hlen
    rw [← List.reverse_zipWith hlen', ← map_inv_zipWith_pow, ← List.prod_inv_reverse, repr.hEq]

/-- The exponent vector produced by `inv` is the reversed input exponent vector. -/
@[simp] theorem inv_exponents {prev : List G} {target : G}
    (repr : GroupRepresentation (p := p) prev target)
    (hlen : prev.length = repr.exponents.length) :
    (repr.inv hlen).exponents = repr.exponents.reverse := rfl

#print axioms GroupRepresentation.zipWith_pow_prod_mem_closure
#print axioms GroupRepresentation.target_mem_closure
#print axioms GroupRepresentation.one
#print axioms GroupRepresentation.target_eq_one_of_nil
#print axioms GroupRepresentation.zipWith_pow_map
#print axioms GroupRepresentation.map
#print axioms GroupRepresentation.singleton
#print axioms GroupRepresentation.prependBasis
#print axioms GroupRepresentation.trimExponents
#print axioms GroupRepresentation.trimExponents_length_le
#print axioms GroupRepresentation.trimExponents_eq_self_of_length_le
#print axioms GroupRepresentation.trimExponents_idem
#print axioms GroupRepresentation.appendBasis
#print axioms GroupRepresentation.appendBasis_exponents_length_le
#print axioms GroupRepresentation.appendBasis_trimExponents_eq_self
#print axioms GroupRepresentation.appendBasis_eq_trimExponents_appendBasis
#print axioms GroupRepresentation.mul
#print axioms GroupRepresentation.mul_exponents
#print axioms GroupRepresentation.inv
#print axioms GroupRepresentation.inv_exponents

end GroupRepresentation

local instance {α : Type*} : Zero (Option α) where
  zero := none

/-- A partially defined table of group elements, indexed by `ι`. The table represents the
  adversary's knowledge state, mapping currently accessible group elements to their algebraic
  values. Finiteness of the support is enforced via `DFinsupp` (which provides a computable
  representation of finitely supported functions). -/
@[reducible]
def GroupValTable (ι : Type*) (G : Type*) := Π₀ _ : ι, Option G

namespace GroupValTable

variable {ι : Type*} [DecidableEq ι] {G : Type*}

/-- **Read-after-write at the written index.** Reading the index just written by `update` returns
the written value. This is the table-level invariant underlying every successful oracle
implementation (`implGroupOpOracle`, `implGroupExpOracle`, `implGroupDecodeOracle`): after a store
at index `k`, a subsequent read at `k` observes the stored group element. -/
@[simp] theorem update_self (t : GroupValTable ι G) (k : ι) (g : Option G) :
    (t.update k g) k = g := by simp

/-- **Read-after-write at a different index.** Writing index `k` leaves any other index `k' ≠ k`
unchanged, so oracle stores are local: an `update` at one handle does not disturb the group elements
recorded at other handles. -/
@[simp] theorem update_ne (t : GroupValTable ι G) {k k' : ι} (g : Option G) (h : k' ≠ k) :
    (t.update k g) k' = t k' := by simp [h]

end GroupValTable

#print axioms GroupValTable.update_self
#print axioms GroupValTable.update_ne

section OracleSpec

variable (ι : Type) (p : ℕ)

/-- The group operation oracle allows an adversary to perform the group operation on group elements
  stored at the indices `i` and `j` (if they are both defined), storing the result at index `k`. -/
@[reducible]
def GroupOpOracle : OracleSpec (ι × ι × ι) := fun _ => Unit

/-- The group exponent oracle allows an adversary to compute the group element at the index `i`
  raised to the power `a`, storing the result at index `j`.

  Technically, this oracle can be implemented with just the group operation oracle, but we allow
  this for faster implementation. -/
@[reducible]
def GroupExpOracle : OracleSpec (ι × ZMod p × ι) := fun _ => Unit

/-- The group equality oracle allows an adversary to check if the group elements stored at the
  indices `i` and `j` are equal. -/
@[reducible]
def GroupEqOracle : OracleSpec (ι × ι) := fun _ => Bool

variable (bitLength : ℕ)

/-- The group encoding oracle allows an adversary to get the bit encoding of a group element. -/
@[reducible]
def GroupEncodeOracle : OracleSpec ι := fun _ => BitVec bitLength

/-- The group decoding oracle allows an adversary to insert a group element corresponding to a
  bit encoding into the table, if the bit encoding is valid. -/
@[reducible]
def GroupDecodeOracle : OracleSpec (BitVec bitLength × ι) := fun _ => Unit

end OracleSpec

section impl

variable {ι : Type} [DecidableEq ι] {G : Type} [Group G] {p : ℕ}

/-- Implementation of the group operation oracle, which changes some underlying table of group
  elements, using the group operation `op`. If the indices `i` and `j` does not contain group
  elements yet, the oracle will fail. -/
def implGroupOpOracle : QueryImpl (GroupOpOracle ι) (StateT (GroupValTable ι G) Option) :=
  fun | ⟨i, j, k⟩ => fun table =>
    match table i, table j with
    | some g₁, some g₂ => some ((), table.update k (some (g₁ * g₂)))
    | _, _ => none

/-- Implementation of the group exponent oracle, which computes the group element at the index `i`
  raised to the power `a`, storing the result at index `j`. This will fail if the index `i` does
  not contain a group element yet. -/
def implGroupExpOracle : QueryImpl (GroupExpOracle ι p) (StateT (GroupValTable ι G) Option) :=
  fun | ⟨i, a, j⟩ => fun table =>
    match table i with
    | some g => some ((), table.update j (some (g ^ a.val)))
    | none => none

/-- Implementation of the group equality oracle, which checks if the group elements at the indices
  `i` and `j` are equal, and leave the table unchanged. -/
def implGroupEqOracle [BEq G] :
    QueryImpl (GroupEqOracle ι) (StateT (GroupValTable ι G) Option) :=
  fun | ⟨i, j⟩ => fun table =>
    match table i, table j with
    | some g₁, some g₂ => some (g₁ == g₂, table)
    | _, _ => none

variable {bitLength : ℕ}

/-- Implementation of the group encoding oracle, which returns the bit encoding of the group element
  at the index `i`, leaving the table unchanged. This will fail if the index `i` does not contain
  a group element yet. -/
def implGroupEncodeOracle [Serialize G (BitVec bitLength)] :
    QueryImpl (GroupEncodeOracle ι bitLength) (StateT (GroupValTable ι G) Option) :=
  fun | i => fun table =>
    match table i with
    | some g => some (serialize g, table)
    | none => none

/-- Implementation of the group decoding oracle, which inserts a group element corresponding to a
  bit encoding into the table, if the bit encoding is valid. This will fail if the bit encoding
  is invalid. -/
def implGroupDecodeOracle [DeserializeOption G (BitVec bitLength)] :
    QueryImpl (GroupDecodeOracle ι bitLength) (StateT (GroupValTable ι G) Option) :=
  fun | (b, i) => fun table =>
    match DeserializeOption.deserialize b with
    | some g => some ((), table.update i (some g))
    | none => none

end impl

/-- An adversary in the Algebraic Group Model (AGM) is defined as follows:

- It is given knowledge of the initial configuration of the group table
- It may use any of the group oracles, including for group operation, group exponentiation, group
  equality testing, and returning group encoding (no decoding of group elements allowed)
- It returns a list of handles specifying the group elements it is supposed to output, and a
  non-group-element result of type `α`

Note: even if the adversary knows the initial group table, it can only output group elements
implicitly, via indices in the table. This means the group element outputs can only be computed via
utilizing the oracles.

Note: this definition models adversary output through table handles.
-/
def Adversary (ι : Type) (G : Type) (p : ℕ) (bitLength : ℕ) (α : Type) : Type _ :=
  ReaderT (GroupValTable ι G)
    (OracleComp (GroupOpOracle ι + GroupExpOracle ι p +
      GroupEqOracle ι + GroupEncodeOracle ι bitLength))
    (List ι × α)

namespace Adversary

variable {ι : Type} [DecidableEq ι] {G : Type} [Group G] [DecidableEq G]
    {p : ℕ} {bitLength : ℕ}
    [Serialize G (BitVec bitLength)] [DeserializeOption G (BitVec bitLength)]
    (α : Type)

/-- Running the adversary on a given table, returning the list of group elements it is supposed to
  output, and the non-group-element result. The run can fail if an oracle query fails or if the
  adversary returns a handle that is not defined in the final table. -/
def run (adversary : Adversary ι G p bitLength α) (table : GroupValTable ι G) :
    Option (List G × α) := do
  let opImpl : QueryImpl (GroupOpOracle ι) (StateT (GroupValTable ι G) Option) :=
    implGroupOpOracle
  let expImpl : QueryImpl (GroupExpOracle ι p) (StateT (GroupValTable ι G) Option) :=
    implGroupExpOracle
  let eqImpl : QueryImpl (GroupEqOracle ι) (StateT (GroupValTable ι G) Option) :=
    implGroupEqOracle
  let encImpl : QueryImpl (GroupEncodeOracle ι bitLength) (StateT (GroupValTable ι G) Option) :=
    implGroupEncodeOracle
  let impl :
      QueryImpl
        (GroupOpOracle ι + GroupExpOracle ι p + GroupEqOracle ι +
          GroupEncodeOracle ι bitLength)
        (StateT (GroupValTable ι G) Option) :=
    opImpl + expImpl + eqImpl + encImpl
  let ⟨⟨handles, result⟩, finalTable⟩ ← (simulateQ impl (adversary table)).run table
  let outputs ← handles.mapM fun i => finalTable i
  pure (outputs, result)

end Adversary

end AGM
