/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ArkLib Contributors
-/

import ArkLib.AGM.Basic

/-!
# Foundational lemmas on AGM group representations

Companion lemmas to `ArkLib/AGM/Basic.lean`'s `GroupRepresentation` (the algebraic-adversary
representation: a target group element together with an exponent vector over a basis of
previously-seen elements).  `Basic.lean` proves *soundness* (`target_mem_closure`: a represented
target lies in the subgroup generated by the basis) and *functoriality* (`map`: a group hom
transports a representation, preserving exponents).  This file adds the matching structural facts:

* `target_eq_of_exponents_eq` — **determinism**: the target is fully determined by the basis and
  the exponent vector (the functional converse of soundness).
* `target_mem_of_forall_mem` — **relative soundness**: if the basis lies in any subgroup `H`, the
  represented target lies in `H`.
* `target_mem_closure_of_forall_mem` — closure monotonicity for changing to a basis list that
  contains the original basis elements.
* `target_mem_closure_prepend` / `target_mem_closure_append` — closure soundness after extending
  the basis on either side.
* `map_target_mem_of_forall_mem` — functorial relative soundness: if a homomorphic image of the
  basis lies in a subgroup, then the image target lies there too.
* `map_target_mem_closure` — the image target lies in the closure of the mapped basis.
* `map_exponents` — functoriality acts only on the basis, leaving the exponent vector fixed.
* `singleton_target_mem_zpowers` — the rank-1 target `g ^ a.val` lies in `Subgroup.zpowers g`.
* `mul_target_mem_closure` — **composition soundness**: the product of two represented targets lies
  in the closure of the union of their bases (the soundness complement to
  `GroupRepresentation.mul`).
* `mul_target_mem_of_forall_mem` — subgroup-relative composition soundness against a fixed `H`.
* `map_mul_target_mem_of_forall_mem` — functorial composition soundness: the homomorphic image of a
  composed target lands in `K` whenever the mapped bases do (AGM ⇒ GGM transfer brick).
-/

namespace AGM.GroupRepresentation

variable {G : Type*} [Group G] {p : ℕ}

/-- **Representation determinism.** The target of an algebraic representation is fully determined
by its basis and exponent vector: two representations over the same basis carrying the same
exponents represent the same group element. The functional counterpart to `target_mem_closure`
(soundness): basis + exponents determine a unique target. -/
theorem target_eq_of_exponents_eq {prev : List G} {t₁ t₂ : G}
    (r₁ : GroupRepresentation (p := p) prev t₁) (r₂ : GroupRepresentation (p := p) prev t₂)
    (h : r₁.exponents = r₂.exponents) : t₁ = t₂ := by
  rw [← r₁.hEq, ← r₂.hEq, h]

/-- **Subgroup-relative representation soundness.** If every basis element available to the
algebraic adversary lies in a subgroup `H`, then any target represented over that basis lies in
`H`. This packages `target_mem_closure` through closure monotonicity, so downstream reductions can
instantiate the soundness invariant with a concrete subgroup rather than the generated closure. -/
theorem target_mem_of_forall_mem {prev : List G} {target : G}
    (repr : GroupRepresentation (p := p) prev target) (H : Subgroup G)
    (hprev : ∀ g ∈ prev, g ∈ H) : target ∈ H := by
  exact ((Subgroup.closure_le H).2 (by
    intro g hg
    exact hprev g hg)) repr.target_mem_closure

/-- If the original basis is contained in another basis list, then any target represented over the
original basis lies in the subgroup generated by the larger list. This is the closure-specialized
form of `target_mem_of_forall_mem`. -/
theorem target_mem_closure_of_forall_mem {prev prev' : List G} {target : G}
    (repr : GroupRepresentation (p := p) prev target)
    (hprev : ∀ g ∈ prev, g ∈ prev') :
    target ∈ Subgroup.closure {g | g ∈ prev'} := by
  exact repr.target_mem_of_forall_mem (Subgroup.closure {g | g ∈ prev'}) (by
    intro g hg
    exact Subgroup.subset_closure (hprev g hg))

/-- If a represented target is viewed over a basis extended on the left, it lies in the subgroup
generated by that extended basis. This packages `prependBasis` with representation soundness. -/
theorem target_mem_closure_prepend {prev : List G} {target : G}
    (repr : GroupRepresentation (p := p) prev target) (extra : List G) :
    target ∈ Subgroup.closure {g | g ∈ extra ++ prev} :=
  (repr.prependBasis extra).target_mem_closure

/-- If a represented target is viewed over a basis extended on the right, it lies in the subgroup
generated by that extended basis. This packages `appendBasis` with representation soundness. -/
theorem target_mem_closure_append {prev : List G} {target : G}
    (repr : GroupRepresentation (p := p) prev target) (extra : List G) :
    target ∈ Subgroup.closure {g | g ∈ prev ++ extra} :=
  (repr.appendBasis extra).target_mem_closure

/-- **Functorial subgroup-relative soundness.** If a homomorphic image of every basis element lies
in a subgroup `K`, then the image of any represented target lies in `K`. This composes
`GroupRepresentation.map` with `target_mem_of_forall_mem`, packaging the subgroup form needed by
downstream AGM-to-GGM reductions. -/
theorem map_target_mem_of_forall_mem {H : Type*} [Group H] (f : G →* H)
    {prev : List G} {target : G} (repr : GroupRepresentation (p := p) prev target)
    (K : Subgroup H) (hprev : ∀ g ∈ prev, f g ∈ K) : f target ∈ K := by
  exact (repr.map f).target_mem_of_forall_mem K (by
    intro h hh
    rw [List.mem_map] at hh
    obtain ⟨g, hg, rfl⟩ := hh
    exact hprev g hg)

/-- The image of a represented target under a group hom lies in the subgroup generated by the mapped
basis. This is the closure-specialized form of `GroupRepresentation.map` plus
`target_mem_closure`. -/
theorem map_target_mem_closure {H : Type*} [Group H] (f : G →* H)
    {prev : List G} {target : G} (repr : GroupRepresentation (p := p) prev target) :
    f target ∈ Subgroup.closure {h | h ∈ prev.map f} :=
  (repr.map f).target_mem_closure

/-- Functoriality acts only on the basis: transporting a representation along a group hom `f`
(`GroupRepresentation.map`) leaves the exponent vector unchanged. -/
@[simp] theorem map_exponents {H : Type*} [Group H] (f : G →* H) {prev : List G} {target : G}
    (repr : GroupRepresentation (p := p) prev target) :
    (repr.map f).exponents = repr.exponents := rfl

/-- The rank-1 target `g ^ a.val` lies in the cyclic subgroup generated by `g`. -/
theorem singleton_target_mem_zpowers (g : G) (a : ZMod p) :
    g ^ a.val ∈ Subgroup.zpowers g :=
  pow_mem (Subgroup.mem_zpowers g) a.val

/-- **Representation completeness.** Every exponent vector over a basis yields a representation —
of the product it encodes. The existence converse to `target_eq_of_exponents_eq` (determinism):
together they show a representation over `prev` is *exactly* an exponent vector, with the target
determined by it. -/
def ofExponents (prev : List G) (exps : List (ZMod p)) :
    GroupRepresentation (p := p) prev ((prev.zipWith (fun g a => g ^ a.val) exps).prod) where
  exponents := exps
  hEq := rfl

/-- The empty exponent vector represents the identity over *any* basis (since `zipWith` truncates
to the empty list). Generalises `target_eq_one_of_nil`, which fixes the basis to `[]`. -/
theorem target_eq_one_of_exponents_nil {prev : List G} {target : G}
    (repr : GroupRepresentation (p := p) prev target) (h : repr.exponents = []) :
    target = 1 := by
  rw [← repr.hEq, h]; simp

/-- **Multiplicativity of the representation product over basis concatenation.** Splitting the
`zipWith`-power product along a basis/exponent concatenation factors as the product of the two
sub-products, provided the first basis is fully exponent-covered. The algebraic core of
representation composition. -/
theorem zipWith_pow_prod_append (prev₁ prev₂ : List G) (e₁ e₂ : List (ZMod p))
    (h : prev₁.length = e₁.length) :
    ((prev₁ ++ prev₂).zipWith (fun g a => g ^ a.val) (e₁ ++ e₂)).prod
      = (prev₁.zipWith (fun g a => g ^ a.val) e₁).prod
        * (prev₂.zipWith (fun g a => g ^ a.val) e₂).prod := by
  induction prev₁ generalizing e₁ with
  | nil =>
    cases e₁ with
    | nil => simp
    | cons a e₁ => simp at h
  | cons g prev₁ ih =>
    cases e₁ with
    | nil => simp at h
    | cons a e₁ =>
      simp only [List.cons_append, List.zipWith_cons_cons, List.prod_cons]
      rw [ih e₁ (by simpa using h), mul_assoc]

/-- **Representations compose multiplicatively.** Concatenating the bases and exponent vectors of
two algebraic representations represents the product of their targets: the AGM analogue of "the
product of two algebraically-represented elements is itself algebraically represented over the
combined basis." Requires the first basis to be fully exponent-covered (always arrangeable by
padding via `prependBasis`/`appendBasis`). -/
def append {prev₁ prev₂ : List G} {t₁ t₂ : G}
    (r₁ : GroupRepresentation (p := p) prev₁ t₁) (r₂ : GroupRepresentation (p := p) prev₂ t₂)
    (h : prev₁.length = r₁.exponents.length) :
    GroupRepresentation (p := p) (prev₁ ++ prev₂) (t₁ * t₂) where
  exponents := r₁.exponents ++ r₂.exponents
  hEq := by
    rw [zipWith_pow_prod_append prev₁ prev₂ r₁.exponents r₂.exponents h, r₁.hEq, r₂.hEq]
/-- **Soundness of a composed representation.** If `t₁` is represented over basis `prev₁` and `t₂`
over basis `prev₂`, then their product `t₁ * t₂` lies in the subgroup generated by the union of the
two bases. This is the soundness complement to `GroupRepresentation.mul` (which produces the
concrete composed representation): gluing two algebraic outputs keeps the result inside the closure
of the available generators, regardless of the exponent-length discipline `mul` needs. -/
theorem mul_target_mem_closure {prev₁ prev₂ : List G} {t₁ t₂ : G}
    (r₁ : GroupRepresentation (p := p) prev₁ t₁) (r₂ : GroupRepresentation (p := p) prev₂ t₂) :
    t₁ * t₂ ∈ Subgroup.closure {g | g ∈ prev₁ ++ prev₂} := by
  have h₁ : t₁ ∈ Subgroup.closure {g | g ∈ prev₁ ++ prev₂} :=
    r₁.target_mem_of_forall_mem _ (fun g hg => Subgroup.subset_closure (by simp [hg]))
  have h₂ : t₂ ∈ Subgroup.closure {g | g ∈ prev₁ ++ prev₂} :=
    r₂.target_mem_of_forall_mem _ (fun g hg => Subgroup.subset_closure (by simp [hg]))
  exact Subgroup.mul_mem _ h₁ h₂

/-- **Subgroup-relative composition soundness.** If every element of both bases lies in a subgroup
`H`, then the product of the two represented targets lies in `H`. This is the concrete-subgroup
form of `mul_target_mem_closure`, letting reductions discharge composition soundness against a
fixed `H` (e.g. the image of a commitment key) without going through the generated closure. -/
theorem mul_target_mem_of_forall_mem {prev₁ prev₂ : List G} {t₁ t₂ : G}
    (r₁ : GroupRepresentation (p := p) prev₁ t₁) (r₂ : GroupRepresentation (p := p) prev₂ t₂)
    (H : Subgroup G) (h₁ : ∀ g ∈ prev₁, g ∈ H) (h₂ : ∀ g ∈ prev₂, g ∈ H) :
    t₁ * t₂ ∈ H :=
  Subgroup.mul_mem _ (r₁.target_mem_of_forall_mem H h₁) (r₂.target_mem_of_forall_mem H h₂)

/-- **Functorial composition soundness (AGM ⇒ GGM transfer).** If a group hom `f` sends every basis
element of both representations into a subgroup `K`, then the image `f (t₁ * t₂)` of the composed
target lies in `K`. This is the multiplicative-composition form of `map_target_mem_of_forall_mem`,
the structural fact a transfer reduction uses to push a composed algebraic output through `f` while
staying inside the target-group subgroup. -/
theorem map_mul_target_mem_of_forall_mem {H : Type*} [Group H] (f : G →* H)
    {prev₁ prev₂ : List G} {t₁ t₂ : G}
    (r₁ : GroupRepresentation (p := p) prev₁ t₁) (r₂ : GroupRepresentation (p := p) prev₂ t₂)
    (K : Subgroup H) (h₁ : ∀ g ∈ prev₁, f g ∈ K) (h₂ : ∀ g ∈ prev₂, f g ∈ K) :
    f (t₁ * t₂) ∈ K := by
  rw [map_mul]
  exact Subgroup.mul_mem _
    (r₁.map_target_mem_of_forall_mem f K h₁) (r₂.map_target_mem_of_forall_mem f K h₂)

end AGM.GroupRepresentation

/-! ### Axiom audit (issue #118 representation companion lemmas) -/

#print axioms AGM.GroupRepresentation.target_eq_of_exponents_eq
#print axioms AGM.GroupRepresentation.target_mem_of_forall_mem
#print axioms AGM.GroupRepresentation.target_mem_closure_of_forall_mem
#print axioms AGM.GroupRepresentation.target_mem_closure_prepend
#print axioms AGM.GroupRepresentation.target_mem_closure_append
#print axioms AGM.GroupRepresentation.map_target_mem_of_forall_mem
#print axioms AGM.GroupRepresentation.map_target_mem_closure
#print axioms AGM.GroupRepresentation.map_exponents
#print axioms AGM.GroupRepresentation.singleton_target_mem_zpowers
#print axioms AGM.GroupRepresentation.ofExponents
#print axioms AGM.GroupRepresentation.target_eq_one_of_exponents_nil
#print axioms AGM.GroupRepresentation.zipWith_pow_prod_append
#print axioms AGM.GroupRepresentation.append
#print axioms AGM.GroupRepresentation.mul_target_mem_closure
#print axioms AGM.GroupRepresentation.mul_target_mem_of_forall_mem
#print axioms AGM.GroupRepresentation.map_mul_target_mem_of_forall_mem
