/- 
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/
import ArkLib.Interaction.Concurrent.Independence

/-!
# Interleaving equivalence of concurrent traces

This file adds the first quotient-style refinement on top of finite concurrent
traces.

`Concurrent.Trace` records one concrete scheduler linearization of frontier
events. `Concurrent.Independent` then identifies pairs of frontier events that
come from independent concurrent components and commute at the residual-spec
level.

The present file packages that commuting behavior into an equivalence relation
on traces:

* `Trace.cast` transports a trace along equality of residual specs;
* `Trace.Equiv` is the equivalence relation generated by:
  * reflexivity, symmetry, and transitivity;
  * congruence under a common leading step;
  * one local `swap` rule for adjacent independent frontier events.

This is still intentionally minimal. It does not yet construct quotient types,
normal forms, or more elaborate partial-order objects; it only records the
standard commuting conversion at the trace level.
-/

universe u

namespace Interaction
namespace Concurrent

namespace Trace

/--
Transport a concurrent trace along equality of residual concurrent specs.

This is the trace-level cast operation needed when two independent frontier
events commute and therefore produce definitionally different but propositionally
equal residual specs.
-/
def cast {S T : Spec} (h : S = T) : Trace S → Trace T := by
  cases h
  exact id

@[simp, grind =]
theorem cast_rfl {S : Spec} (trace : Trace S) :
    cast rfl trace = trace := rfl

@[simp, grind =]
theorem length_cast {S T : Spec} (h : S = T) (trace : Trace S) :
    (cast h trace).length = trace.length := by
  cases h
  rfl

/--
`Equiv trace₁ trace₂` says that the concurrent traces `trace₁` and `trace₂`
represent the same execution up to commuting adjacent independent frontier
events.

This relation is generated by:

* `refl`, `symm`, and `trans`, making it an equivalence relation;
* `step`, which preserves equivalence under a common leading event;
* `swap`, which performs one adjacent interchange of two independent frontier
  events.
-/
inductive Equiv : {S : Spec} → Trace S → Trace S → Prop where
  | /-- Every trace is interleaving-equivalent to itself. -/
    refl {S : Spec} (trace : Trace S) : Equiv trace trace
  | /-- Equivalence is preserved under a common leading frontier event. -/
    step {S : Spec} {event : Front S} {tail₁ tail₂ : Trace (residual event)}
      (h : Equiv tail₁ tail₂) :
      Equiv (.step event tail₁) (.step event tail₂)
  | /-- Adjacent independent frontier events may be swapped, with the tail
    transported across the commuting residual equality from `Independent.diamond`. -/
    swap {S : Spec} {event₁ event₂ : Front S}
      (h : Independent event₁ event₂)
      (tail : Trace (residual (Independent.afterLeft h))) :
      Equiv
        (.step event₁ (.step (Independent.afterLeft h) tail))
        (.step event₂
          (.step (Independent.afterRight h)
            (cast (Independent.diamond h) tail)))
  | /-- Equivalence is symmetric. -/
    symm {S : Spec} {trace₁ trace₂ : Trace S}
      (h : Equiv trace₁ trace₂) :
      Equiv trace₂ trace₁
  | /-- Equivalence is transitive. -/
    trans {S : Spec} {trace₁ trace₂ trace₃ : Trace S}
      (h₁ : Equiv trace₁ trace₂) (h₂ : Equiv trace₂ trace₃) :
      Equiv trace₁ trace₃

namespace Equiv

/--
Interleaving-equivalent traces have the same length.
-/
theorem length_eq {S : Spec} {trace₁ trace₂ : Trace S} :
    Equiv trace₁ trace₂ → trace₁.length = trace₂.length
  | .refl _ => rfl
  | .step h => by simpa [Trace.length] using congrArg Nat.succ (length_eq h)
  | .swap _ tail => by simp [Trace.length, Trace.length_cast]
  | .symm h => (length_eq h).symm
  | .trans h₁ h₂ => (length_eq h₁).trans (length_eq h₂)

end Equiv
end Trace

end Concurrent
end Interaction
