/- 
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/
import ArkLib.Interaction.Concurrent.OpenTheory

/-!
# A free lawful model of open composition

This module provides the first concrete realization of `Concurrent.OpenTheory`.

The design choice is deliberately *final-tagless* rather than quoted.

`OpenTheory` was introduced as an operations-first interface because we wanted
to avoid prematurely committing to a single representation of open systems.
That same design pressure applies to the first concrete model: rather than
starting with a raw syntax tree plus a quotient by laws, this file defines
open expressions by their **universal interpretation principle**.

Concretely, an `Expr Atom Δ` is something that:

* can be interpreted in any lawful `OpenTheory`,
* given an interpretation of primitive atoms `Atom`, and
* produces an object of boundary `Δ` in that target theory.

This is the familiar "tagless final" or Church-style free construction. It is
still a genuine concrete model:

* it validates that the current `OpenTheory` API is coherent;
* it gives an explicit carrier supporting `map`, `par`, `wire`, and `plug`;
* and its lawfulness follows by interpreting those expressions into an
  arbitrary lawful target theory.

The main tradeoff is intentional. This module is excellent for validating the
algebraic surface and proving the first universal laws, but it is *not* the
representation we would use later for runtime execution or graph-like
inspection. Those future semantic models can still be added independently.
-/

universe u uA uB

namespace Interaction
namespace Concurrent
namespace OpenSyntax

/--
The ambient boundary type used by this first free model of open composition.

Unlike the fully polymorphic `PortBoundary` definition, this local alias fixes
one shared pair of port/message universes, matching the current `OpenTheory`
regime.
-/
abbrev Boundary : Type (max (uA + 1) (uB + 1)) :=
  PortBoundary.{uA, uB, uA, uB}

/--
The empty boundary in the ambient universe regime of this free model.
-/
abbrev empty : Boundary :=
  PortBoundary.empty.{uA, uB, uA, uB}

/--
Swap the direction of an ambient-universe boundary.
-/
abbrev swap (Δ : Boundary) : Boundary :=
  PortBoundary.swap Δ

/--
Tensor of two ambient-universe boundaries.

This is the specialized same-universe version used internally by the free
model.
-/
def tensor (Δ₁ Δ₂ : Boundary) : Boundary :=
  ⟨Interface.sum Δ₁.In Δ₂.In, Interface.sum Δ₁.Out Δ₂.Out⟩

/--
`Expr Atom Δ` is the free lawful open-system expression of boundary `Δ`
generated by primitive atoms `Atom`.

An element of `Expr Atom Δ` does not store one particular syntax tree. Instead
it stores its universal elimination principle:

* for every lawful target open theory `T`,
* and every interpretation of primitive atoms into `T`,
* it produces an object of boundary `Δ` in `T`.

So this is the tagless-final companion to an initial syntax/quotient model.
It validates the `OpenTheory` surface without forcing a raw syntax
representation at this stage.
-/
structure Expr
    (Atom : PortBoundary.{uA, uB, uA, uB} → Type u)
    (Δ : PortBoundary.{uA, uB, uA, uB}) where
  /--
  Interpret the free expression in an arbitrary lawful target open theory.

  The argument `interp` tells us how primitive atoms should be interpreted in
  the target theory. The result is then the corresponding composite open
  system of boundary `Δ`.
  -/
  run :
    (T : OpenTheory.{max (u + 1) (uA + 2) (uB + 2), uA, uB}) →
    OpenTheory.IsLawful T →
    (∀ {Δ : PortBoundary.{uA, uB, uA, uB}}, Atom Δ → T.Obj Δ) →
    T.Obj Δ

namespace Expr

/--
Interpret a free open-system expression in a lawful target open theory.

This is just the `run` field restated as a named eliminator. The extra name is
useful because it makes the universal property of `Expr` read directly in
client code: a free expression is something that can be *interpreted* once an
atom interpretation has been chosen.
-/
abbrev interpret
    {Atom : PortBoundary.{uA, uB, uA, uB} → Type u}
    {Δ : PortBoundary.{uA, uB, uA, uB}}
    (W : Expr Atom Δ)
    (T : OpenTheory.{max (u + 1) (uA + 2) (uB + 2), uA, uB})
    (hT : OpenTheory.IsLawful T)
    (interp : ∀ {Δ : PortBoundary.{uA, uB, uA, uB}}, Atom Δ → T.Obj Δ) :
    T.Obj Δ :=
  W.run T hT interp

/--
Two free expressions are equal when they have the same interpretation in every
lawful target theory.
-/
@[ext]
theorem ext
    {Atom : PortBoundary.{uA, uB, uA, uB} → Type u}
    {Δ : PortBoundary.{uA, uB, uA, uB}}
    {W₁ W₂ : Expr Atom Δ}
    (h :
      ∀ (T : OpenTheory.{max (u + 1) (uA + 2) (uB + 2), uA, uB})
        (hT : OpenTheory.IsLawful T)
        (interp : ∀ {Δ : PortBoundary.{uA, uB, uA, uB}}, Atom Δ → T.Obj Δ),
          W₁.run T hT interp = W₂.run T hT interp) :
    W₁ = W₂ := by
  cases W₁
  cases W₂
  simp only at h
  congr
  funext T hT interp
  exact h T hT interp

/--
Inject a primitive open component into the free lawful syntax.
-/
def atom
    {Atom : PortBoundary.{uA, uB, uA, uB} → Type u}
    {Δ : PortBoundary.{uA, uB, uA, uB}} :
    Atom Δ → Expr Atom Δ
  | a => ⟨fun _ _ interp => interp a⟩

@[simp]
theorem interpret_atom
    {Atom : PortBoundary.{uA, uB, uA, uB} → Type u}
    {Δ : PortBoundary.{uA, uB, uA, uB}}
    (a : Atom Δ)
    (T : OpenTheory.{max (u + 1) (uA + 2) (uB + 2), uA, uB})
    (hT : OpenTheory.IsLawful T)
    (interp : ∀ {Δ : PortBoundary.{uA, uB, uA, uB}}, Atom Δ → T.Obj Δ) :
    (atom a).interpret T hT interp = interp a :=
  rfl

/--
Adapt the exposed boundary of a free open-system expression.
-/
def map
    {Atom : PortBoundary.{uA, uB, uA, uB} → Type u}
    {Δ₁ Δ₂ : PortBoundary.{uA, uB, uA, uB}}
    (f : PortBoundary.Hom Δ₁ Δ₂) :
    Expr Atom Δ₁ → Expr Atom Δ₂
  | W => ⟨fun T hT interp => T.map f (W.run T hT interp)⟩

@[simp]
theorem interpret_map
    {Atom : PortBoundary.{uA, uB, uA, uB} → Type u}
    {Δ₁ Δ₂ : PortBoundary.{uA, uB, uA, uB}}
    (f : PortBoundary.Hom Δ₁ Δ₂)
    (W : Expr Atom Δ₁)
    (T : OpenTheory.{max (u + 1) (uA + 2) (uB + 2), uA, uB})
    (hT : OpenTheory.IsLawful T)
    (interp : ∀ {Δ : PortBoundary.{uA, uB, uA, uB}}, Atom Δ → T.Obj Δ) :
    (map f W).interpret T hT interp = T.map f (W.interpret T hT interp) :=
  rfl

/--
Place two free open-system expressions side by side.
-/
def par
    {Atom : PortBoundary.{uA, uB, uA, uB} → Type u}
    {Δ₁ Δ₂ : PortBoundary.{uA, uB, uA, uB}} :
    Expr Atom Δ₁ →
    Expr Atom Δ₂ →
    Expr Atom (PortBoundary.tensor Δ₁ Δ₂)
  | W₁, W₂ => ⟨fun T hT interp => T.par (W₁.run T hT interp) (W₂.run T hT interp)⟩

@[simp]
theorem interpret_par
    {Atom : PortBoundary.{uA, uB, uA, uB} → Type u}
    {Δ₁ Δ₂ : PortBoundary.{uA, uB, uA, uB}}
    (W₁ : Expr Atom Δ₁)
    (W₂ : Expr Atom Δ₂)
    (T : OpenTheory.{max (u + 1) (uA + 2) (uB + 2), uA, uB})
    (hT : OpenTheory.IsLawful T)
    (interp : ∀ {Δ : PortBoundary.{uA, uB, uA, uB}}, Atom Δ → T.Obj Δ) :
    (par W₁ W₂).interpret T hT interp =
      T.par (W₁.interpret T hT interp) (W₂.interpret T hT interp) :=
  rfl

/--
Connect one shared boundary between two free open-system expressions.
-/
def wire
    {Atom : PortBoundary.{uA, uB, uA, uB} → Type u}
    {Δ₁ Γ Δ₂ : PortBoundary.{uA, uB, uA, uB}} :
    Expr Atom (PortBoundary.tensor Δ₁ Γ) →
    Expr Atom (PortBoundary.tensor (PortBoundary.swap Γ) Δ₂) →
    Expr Atom (PortBoundary.tensor Δ₁ Δ₂)
  | W₁, W₂ => ⟨fun T hT interp => T.wire (W₁.run T hT interp) (W₂.run T hT interp)⟩

@[simp]
theorem interpret_wire
    {Atom : PortBoundary.{uA, uB, uA, uB} → Type u}
    {Δ₁ Γ Δ₂ : PortBoundary.{uA, uB, uA, uB}}
    (W₁ : Expr Atom (PortBoundary.tensor Δ₁ Γ))
    (W₂ : Expr Atom (PortBoundary.tensor (PortBoundary.swap Γ) Δ₂))
    (T : OpenTheory.{max (u + 1) (uA + 2) (uB + 2), uA, uB})
    (hT : OpenTheory.IsLawful T)
    (interp : ∀ {Δ : PortBoundary.{uA, uB, uA, uB}}, Atom Δ → T.Obj Δ) :
    (wire W₁ W₂).interpret T hT interp =
      T.wire (W₁.interpret T hT interp) (W₂.interpret T hT interp) :=
  rfl

/--
Close a free open-system expression against a matching context.
-/
def plug
    {Atom : PortBoundary.{uA, uB, uA, uB} → Type u}
    {Δ : PortBoundary.{uA, uB, uA, uB}} :
    Expr Atom Δ →
    Expr Atom (PortBoundary.swap Δ) →
    Expr Atom (PortBoundary.empty.{uA, uB, uA, uB})
  | W, K => ⟨fun T hT interp => T.plug (W.run T hT interp) (K.run T hT interp)⟩

@[simp]
theorem interpret_plug
    {Atom : PortBoundary.{uA, uB, uA, uB} → Type u}
    {Δ : PortBoundary.{uA, uB, uA, uB}}
    (W : Expr Atom Δ)
    (K : Expr Atom (PortBoundary.swap Δ))
    (T : OpenTheory.{max (u + 1) (uA + 2) (uB + 2), uA, uB})
    (hT : OpenTheory.IsLawful T)
    (interp : ∀ {Δ : PortBoundary.{uA, uB, uA, uB}}, Atom Δ → T.Obj Δ) :
    (plug W K).interpret T hT interp =
      T.plug (W.interpret T hT interp) (K.interpret T hT interp) :=
  rfl

/--
The free lawful `OpenTheory` generated by primitive components `Atom`.
-/
abbrev theory
    (Atom : PortBoundary.{uA, uB, uA, uB} → Type u) :
    OpenTheory.{max (u + 2) (uA + 3) (uB + 3), uA, uB} where
  Obj := Expr Atom
  map := Expr.map
  par := Expr.par
  wire := Expr.wire
  plug := Expr.plug

instance lawfulMap
    (Atom : PortBoundary.{uA, uB, uA, uB} → Type u) :
    OpenTheory.IsLawfulMap (theory Atom) where
  map_id := by
    intro Δ W
    change Expr Atom Δ at W
    change Expr.map (PortBoundary.Hom.id Δ) W = W
    refine Expr.ext ?_
    intro T hT interp
    let _ : OpenTheory.IsLawful T := hT
    simpa [Expr.map] using
      OpenTheory.map_id (T := T) (W := W.run T hT interp)
  map_comp := by
    intro Δ₁ Δ₂ Δ₃ g f W
    change Expr Atom Δ₁ at W
    change Expr.map (PortBoundary.Hom.comp g f) W = Expr.map g (Expr.map f W)
    refine Expr.ext ?_
    intro T hT interp
    let _ : OpenTheory.IsLawful T := hT
    simpa [Expr.map] using
      OpenTheory.map_comp (T := T) g f (W.run T hT interp)

instance lawfulPar
    (Atom : PortBoundary.{uA, uB, uA, uB} → Type u) :
    OpenTheory.IsLawfulPar (theory Atom) where
  map_id := OpenTheory.IsLawfulMap.map_id (T := theory Atom)
  map_comp := OpenTheory.IsLawfulMap.map_comp (T := theory Atom)
  map_par := by
    intro Δ₁ Δ₁' Δ₂ Δ₂' f₁ f₂ W₁ W₂
    change Expr Atom Δ₁ at W₁
    change Expr Atom Δ₂ at W₂
    change
      Expr.map (PortBoundary.Hom.tensor f₁ f₂) (Expr.par W₁ W₂) =
        Expr.par (Expr.map f₁ W₁) (Expr.map f₂ W₂)
    refine Expr.ext ?_
    intro T hT interp
    let _ : OpenTheory.IsLawful T := hT
    simpa [Expr.map, Expr.par] using
      OpenTheory.map_par (T := T) f₁ f₂ (W₁.run T hT interp) (W₂.run T hT interp)

instance lawfulWire
    (Atom : PortBoundary.{uA, uB, uA, uB} → Type u) :
    OpenTheory.IsLawfulWire (theory Atom) where
  map_id := OpenTheory.IsLawfulMap.map_id (T := theory Atom)
  map_comp := OpenTheory.IsLawfulMap.map_comp (T := theory Atom)
  map_wire := by
    intro Δ₁ Δ₁' Γ Δ₂ Δ₂' f₁ f₂ W₁ W₂
    change Expr Atom (PortBoundary.tensor Δ₁ Γ) at W₁
    change Expr Atom (PortBoundary.tensor (PortBoundary.swap Γ) Δ₂) at W₂
    change
      Expr.map (PortBoundary.Hom.tensor f₁ f₂) (Expr.wire W₁ W₂) =
        Expr.wire
          (Expr.map (PortBoundary.Hom.tensor f₁ (PortBoundary.Hom.id Γ)) W₁)
          (Expr.map
            (PortBoundary.Hom.tensor
              (PortBoundary.Hom.id (PortBoundary.swap Γ))
              f₂)
            W₂)
    refine Expr.ext ?_
    intro T hT interp
    let _ : OpenTheory.IsLawful T := hT
    simpa [Expr.map, Expr.wire] using
      OpenTheory.map_wire (T := T) f₁ f₂ (W₁.run T hT interp) (W₂.run T hT interp)

instance lawfulPlug
    (Atom : PortBoundary.{uA, uB, uA, uB} → Type u) :
    OpenTheory.IsLawfulPlug (theory Atom) where
  map_id := OpenTheory.IsLawfulMap.map_id (T := theory Atom)
  map_comp := OpenTheory.IsLawfulMap.map_comp (T := theory Atom)
  map_plug := by
    intro Δ₁ Δ₂ f W K
    change Expr Atom Δ₁ at W
    change Expr Atom (PortBoundary.swap Δ₂) at K
    change
      Expr.plug (Expr.map f W) K =
        Expr.plug W (Expr.map (PortBoundary.Hom.swap f) K)
    refine Expr.ext ?_
    intro T hT interp
    let _ : OpenTheory.IsLawful T := hT
    simpa [Expr.map, Expr.plug] using
      OpenTheory.map_plug (T := T) f (W.run T hT interp) (K.run T hT interp)

instance lawful
    (Atom : PortBoundary.{uA, uB, uA, uB} → Type u) :
    OpenTheory.IsLawful (theory Atom) where

end Expr

end OpenSyntax
end Concurrent
end Interaction
