#!/usr/bin/env python3
"""
C034 crux probe: the catch behind the clean resonance formula.

Two distinct questions the earlier probes glossed:

(Q1) STRUCTURE OF THE VARIETY (char-0 combinatorics):
   Is vanishingVariety(mu_n, a, t) literally "a-subsets that are a union of cosets of mu_{2^L}"?
   i.e. is the formula C(n/2^L, a/2^L) just COUNTING unions-of-cosets-of-mu_{2^L} of total size a?
   If YES, then the count is a CHAR-0 COMBINATORIAL identity (cosets of a 2-group), and the
   "char-p transfer" is trivial (cosets vanish identically). That would make the floor genuinely
   structural. We test: do the actual vanishing subsets coincide EXACTLY with unions of
   mu_{2^L}-cosets? And does e_1..e_{t-1}=0 hold for such unions in char 0 (over C / exact)?

(Q2) THE REAL OBJECT: I(delta) = #lacBad = #IMAGE of e_t over the variety, NOT #variety.
   The floor proven structurally bounds #variety (>= #lacBad). But the GENUINE delta* quantity
   is #lacBad. Does #lacBad ALSO stay small, or does the image collapse drastically / not at all?
   More importantly: is #lacBad even the right object, or does the TRUE far-line incidence
   require t to range over ALL gaps including small t (t<t0) where the variety EXPLODES?

We answer Q1 with an EXACT char-0 (rational, using primitive root of unity symbolic via Python
fractions on the cyclotomic integer ring is heavy; instead we test over a LARGE prime with
n | q-1 and verify the union-of-cosets characterization combinatorially + check e_j vanish).
"""

import itertools, math
from math import comb, log2

def is_prime(m):
    if m < 2: return False
    if m % 2 == 0: return m == 2
    i = 3
    while i*i <= m:
        if m % i == 0: return False
        i += 2
    return True

def first_prime(n, beta=4):
    lo = int(n**beta)
    q = lo + (n - lo % n) % n + 1
    while not (q % n == 1 and is_prime(q)):
        q += n
    return q

def mu_n_elements(q, n):
    def order(a, q):
        o = 1; x = a % q
        while x != 1:
            x = (x*a) % q; o += 1
        return o
    g = None
    for cand in range(2, q):
        if order(cand, q) == q-1:
            g = cand; break
    e = (q-1)//n
    base = pow(g, e, q)
    elts = []; x = 1
    for _ in range(n):
        elts.append(x); x = (x*base) % q
    return elts, base  # elts ordered as base^0..base^{n-1}

def esymm_mod(subset, t, q):
    if t == 0: return 1 % q
    if t > len(subset): return 0
    s = 0
    for combo in itertools.combinations(subset, t):
        p = 1
        for x in combo: p = (p*x) % q
        s = (s + p) % q
    return s

def L_of(t):
    return 0 if t <= 1 else math.ceil(math.log2(t))

def is_union_of_cosets(S_idx, n, twoL):
    """S given as set of EXPONENT indices (0..n-1). mu_{2^L} = {base^{j*n/2^L}}, i.e. the
    subgroup of order 2^L is generated by index-step n/2^L. A coset of mu_{2^L} in mu_n
    is an arithmetic-progression-of-step (n/2^L) in Z/n? NO: mu_{2^L} (order 2^L) = elements
    whose index is multiple of n/2^L. Coset of that subgroup = index-class mod (n/2^L).
    So 'union of cosets of mu_{2^L}' = union of residue classes mod (n/2^L) in the index group.
    Wait: subgroup of order 2^L inside cyclic group of order n=2^mu is { x : x^{2^L}=... }
    Actually order-2^L subgroup = <base^{n/2^L}> = indices multiple of n/2^L. Its cosets are
    indices == r mod (n/2^L). Union of cosets <=> S_idx is a union of residue classes mod (n/2^L).
    """
    m = n // twoL  # = n/2^L = number of cosets; each coset has size twoL? No.
    # subgroup order = twoL, index = n/twoL = m. coset = fixed residue mod m?
    # subgroup H = <g^m> has order n/gcd(m,n)=n/m=twoL. H = {0, m, 2m, ...}=multiples of m.
    # cosets = {r, r+m, r+2m,...} = residue r mod m. There are m cosets each size twoL.
    classes = {}
    for idx in S_idx:
        classes.setdefault(idx % m, []).append(idx)
    for r, lst in classes.items():
        if len(lst) != twoL:  # full coset has twoL elements
            return False
    return True

def run():
    print("="*95)
    print("C034 crux: is the vanishing variety EXACTLY unions of mu_{2^L}-cosets? (Q1)")
    print("="*95)
    for n in [8, 16]:
        q = first_prime(n, 4)
        mu_elts, base = mu_n_elements(q, n)
        # index map: value -> exponent
        idx_of = {mu_elts[i]: i for i in range(n)}
        print(f"\nn={n}, q={q}")
        for a in range(2, n+1):
            for t in range(2, a+1):
                L = L_of(t); twoL = 2**L
                vv = []
                for S in itertools.combinations(range(n), a):
                    Svals = [mu_elts[i] for i in S]
                    ok = all(esymm_mod(Svals, j, q) == 0 for j in range(1, t))
                    if ok:
                        vv.append(set(S))
                if not vv:
                    continue
                # check every variety member is a union of mu_{2^L}-cosets
                all_cosets = all(is_union_of_cosets(S, n, twoL) for S in vv)
                pred = comb(n//twoL, a//twoL) if (a % twoL == 0 and n % twoL == 0) else 0
                print(f"  a={a} t={t} L={L} 2^L={twoL}: #vv={len(vv)} pred={pred} "
                      f"all-unions-of-mu_2^L-cosets={all_cosets}")
                if len(vv) != pred or not all_cosets:
                    print("     <-- DEVIATION")

    print("\n"+"="*95)
    print("Q2: #lacBad (image of e_t) vs #variety, and whether image collapses")
    print("="*95)
    for n in [8, 16]:
        q = first_prime(n, 4)
        mu_elts, base = mu_n_elements(q, n)
        print(f"\nn={n}, q={q}")
        for a in range(2, n+1):
            for t in range(2, a+1):
                L = L_of(t); twoL = 2**L
                vals = set()
                nvv = 0
                for S in itertools.combinations(range(n), a):
                    Svals = [mu_elts[i] for i in S]
                    ok = all(esymm_mod(Svals, j, q) == 0 for j in range(1, t))
                    if ok:
                        nvv += 1
                        vals.add(esymm_mod(Svals, t, q))
                if nvv:
                    print(f"  a={a} t={t}: #variety={nvv}  #lacBad(image e_t)={len(vals)}  "
                          f"collapse={nvv}->{len(vals)}")

if __name__ == "__main__":
    run()
