#!/usr/bin/env python3
"""
C059 attack: Autocorrelation-at-origin x resultant-threshold bounds the char-p energy ANOMALY.

Claim under test (from conn/C059.json):
  E_r^{Fp} - E_r^{char0} = Sum_{z != 0, p|z in 2r-box} R_r(z)
                         <= ( #{z != 0 : p|z, z in 2r-box} ) * R_r(0)
  where R_r(z) = #{ (x_1..x_r, y_1..y_r) in mu_n^{2r} : sum x - sum y = z }  (autocorrelation of r-fold sumset count)
  and the autocorr brick gives R_r(z) <= R_r(0) per point (Cauchy-Schwarz, AutocorrelationMax.lean).

We test, at PROPER-subgroup prize-shaped primes (n=2^mu | q-1, q ~ n^beta, n << sqrt(q)):
  (A) IDENTITY: anomaly E_r^{Fp} - E_r^{char0} == Sum_{z!=0, p|z} R_r(z) exactly.
  (B) PER-POINT CAP: R_r(z) <= R_r(0) for all z (the autocorr brick), incl signed z=g(zeta).
  (C) USEFULNESS: compare the C059 upper bound R_r(0) * (#contributing cosets)
      against the ACTUAL anomaly. Ratio = how loose. Also compare against E_r^{char0} itself
      (is the "bound on the anomaly" smaller or larger than the whole char-0 energy?).
  (D) BOX-DENSITY: contributing-count vs (2r)^{phi(n)}/p box-density prediction.

Exact integer arithmetic throughout.  z lives in F_p = ZMod p (we work additively in F_p,
which is the correct "2r-box mod p" object: R_r counts r-tuples whose signed sum equals z in F_p).
"""

import itertools, math, sys
from collections import Counter

def is_prime(m):
    if m < 2: return False
    if m % 2 == 0: return m == 2
    i = 3
    while i*i <= m:
        if m % i == 0: return False
        i += 2
    return True

def find_prize_prime(n, beta, tries=200000):
    """smallest prime q ~ n^beta with q == 1 mod n (so mu_n exists), n << sqrt(q)."""
    target = int(round(n**beta))
    # walk to q = 1 mod n above target
    base = target - (target % n) + 1
    if base <= target: base += n
    q = base
    for _ in range(tries):
        if is_prime(q):
            return q
        q += n
    return None

def subgroup_mu_n(q, n):
    """the order-n multiplicative subgroup mu_n of F_q^*  (q prime). returns sorted list of ints in [1,q-1]."""
    # find a generator-power: pick any g, raise to (q-1)/n
    e = (q-1)//n
    # find primitive-ish: just collect powers of some element of order n
    for cand in range(2, q):
        h = pow(cand, e, q)
        if h == 1:
            continue
        # order of h divides n; check it's exactly n
        S = set()
        x = 1
        for _ in range(n):
            x = (x*h) % q
            S.add(x)
        if len(S) == n:
            return sorted(S)
    raise RuntimeError("no mu_n found")

def Rr_charp(mu, q, r):
    """R_r(z) for all z in F_q : number of (x_1..x_r,y_1..y_r) in mu^{2r} with sum x - sum y = z mod q.
       Computed via DFT-free convolution of the r-fold signed-sum distribution.
       Returns Counter z -> count.  E_r^{Fp} = R_r(0)."""
    # r-fold sum distribution of mu (additive in F_q)
    # f1 = distribution of single element
    f = Counter()
    for a in mu: f[a % q] += 1
    # convolve r times to get sum of r elements
    def conv(a, b):
        c = Counter()
        for x, ax in a.items():
            for y, by in b.items():
                c[(x+y) % q] += ax*by
        return c
    sumr = Counter({0:1})
    for _ in range(r):
        sumr = conv(sumr, f)
    # negated sum distribution
    negr = Counter()
    for s, cnt in sumr.items():
        negr[(-s) % q] += cnt
    # R_r = sumr (*) negr  : R_r(z) = sum_s sumr(s) negr(z-s)
    R = conv(sumr, negr)
    return R

def Rr_char0(mu_complex_exact, r):
    """E_r^{char0}: number of r-tuple-sum collisions over the integers/complex (no wraparound).
       We compute it as the central coefficient of the autocorrelation of the r-fold sum
       distribution over Z (the free abelian group generated by exponents), i.e. using
       exact additive sums of the cyclotomic integers represented as exponent vectors.
       For mu_n = n-th roots of unity, a clean exact proxy: count tuples with EQUAL multiset
       of exponents-balance, i.e. sum_{e-tuple} = sum_{e'-tuple} as cyclotomic integers.
       We compute this by working in Z[x]/(x^n - 1) is WRONG (that's char p of the group ring);
       the correct char-0 object uses Z[zeta_n] = Z[x]/Phi_n(x).
       Simplest exact: represent each root as its complex value to high precision and bucket sums
       by rounded value -- but that's lossy. Instead use the group-ring over Z[x]/(x^n-1)?? No.
       PRACTICAL exact route: E_r^{char0} = R_r over the LATTICE Z^n (exponent multiplicities),
       i.e. #{ (multiplicities a_e, b_e) : a balanced } -- equals #{ tuples with same exponent
       multiset on each side AFTER the cyclotomic relation }. To stay rigorous we instead compute
       char0 energy as the count with z=0 over Z[zeta_n] via exact integer linear algebra below.
    """
    raise NotImplementedError

def Er_char0_via_Zzeta(mu_exponents, n, r):
    """E_r^{char0} = R_r(0) over Z[zeta_n]: number of (x,y) in mu_n^{2r} with sum x = sum y
       as elements of Z[zeta_n] = Z[x]/Phi_n(x).  We compute the r-fold sum distribution
       as a Counter over the canonical Z[zeta_n] coordinate vector (reduced mod Phi_n), then
       R_r(0) = sum over states of (count_in_sumr)^2  (the diagonal autocorrelation).
       mu_exponents: list of exponents e (0..n-1) so that root = zeta_n^e ; here mu_n = ALL n-th
       roots so exponents = range(n)."""
    import numpy as np
    # cyclotomic Phi_n for n = 2^mu (mu>=1): Phi_n(x) = x^{n/2} + 1 ; basis = {1,x,...,x^{n/2 -1}}
    # zeta_n^e reduces: for e < n/2 -> +x^e ; for n/2 <= e < n -> -x^{e-n/2}
    half = n//2
    def coord(e):
        e %= n
        v = [0]*half
        if e < half:
            v[e] += 1
        else:
            v[e-half] -= 1
        return tuple(v)
    # single-element distribution over coordinate vectors
    f = Counter()
    for e in mu_exponents:
        f[coord(e)] += 1
    def add_coord(a, b):
        return tuple(x+y for x,y in zip(a,b))
    def conv(a, b):
        c = Counter()
        for x, ax in a.items():
            for y, by in b.items():
                c[add_coord(x,y)] += ax*by
        return c
    sumr = Counter({tuple([0]*half):1})
    for _ in range(r):
        sumr = conv(sumr, f)
    # R_r(0) over Z[zeta_n] = sum_s sumr(s)^2  (number of (x,y) with sum x = sum y)
    E0 = sum(cnt*cnt for cnt in sumr.values())
    return E0, sumr

def run(n, beta, r):
    q = find_prize_prime(n, beta)
    if q is None:
        print(f"  n={n} beta={beta}: no prime found"); return
    mu = subgroup_mu_n(q, n)
    assert len(mu) == n
    # char-p energy and full R_r over F_q
    R = Rr_charp(mu, q, r)
    Erp = R[0]                       # E_r^{Fp} = R_r(0) in char p
    # char-0 energy over Z[zeta_n]  (mu_n = ALL n-th roots: exponents range(n))
    E0, sumr0 = Er_char0_via_Zzeta(list(range(n)), n, r)
    anomaly = Erp - E0
    R0 = Erp                         # autocorr at origin in char p
    # (A) IDENTITY: anomaly == sum_{z != 0} R_r(z)  ... but careful: in F_q the "char0" energy
    # is the z=0 mass MINUS the wraparound collisions that ALSO land at z=0. The proper anomaly
    # decomposition (C059) is: extra char-p collisions at z=0 come from nonzero cyclotomic-integer
    # differences alpha with p | N(alpha), i.e. alpha != 0 in Z[zeta_n] but ==0 in F_q.
    # So: anomaly = #{(x,y): sum x - sum y = 0 in F_q  AND  != 0 in Z[zeta_n]}.
    # That equals sum over nonzero cyclotomic states s of [count of (x,y) pairs giving difference s
    # whose F_q-image is 0].  We compute it DIRECTLY for cross-check.
    # difference distribution over Z[zeta_n]:
    # diff = sumr0 (*) (-sumr0)
    half = n//2
    def neg(v): return tuple(-x for x in v)
    diff = Counter()
    for s, cs in sumr0.items():
        for t, ct in sumr0.items():
            d = tuple(a-b for a,b in zip(s,t))
            diff[d] += cs*ct
    # map each cyclotomic state to its F_q value, using a primitive n-th root zeta in F_q
    # find primitive n-th root in F_q: an element of mu of exact order n
    def order(a):
        x=1
        for k in range(1,n+1):
            x=(x*a)%q
            if x==1: return k
        return None
    zeta=None
    for a in mu:
        if order(a)==n: zeta=a; break
    assert zeta is not None
    zpow=[pow(zeta,j,q) for j in range(half)]   # x^j -> zeta^j
    def to_Fq(v):
        return sum((c%q)*zpow[j] for j,c in enumerate(v)) % q
    anomaly_direct = 0
    contributing_states = 0
    contributing_mass_states = Counter()
    Rr_z_max_ratio = 0.0
    for s, cnt in diff.items():
        if all(c==0 for c in s):    # genuine char-0 collision (alpha = 0)
            continue
        if to_Fq(s) == 0:           # spurious: alpha != 0 but p | N(alpha)
            anomaly_direct += cnt
            contributing_states += 1
            contributing_mass_states[s] = cnt
        # (B) per-point cap check: in char p, R_r(z=image) ... use the char-p R already
    # (B) PER-POINT CAP over F_q (the autocorr brick): R[z] <= R[0] for all z
    cap_ok = all(v <= R0 for v in R.values())
    cap_max_offdiag = max((v for z,v in R.items() if z!=0), default=0)
    # (C) USEFULNESS: C059 upper bound = R0 * (#contributing cosets).
    # contributing cosets = distinct nonzero F_q-values among diff states that are p|z... but
    # the anomaly lands at z=0 in F_q. The "contributing sublattice points" are the cyclotomic
    # states s != 0 with to_Fq(s)=0. Their count:
    num_contrib_states = contributing_states
    # The bound as literally stated in C059 (#{z!=0,p|z in 2r-box} * R_r(0)) -- the count of
    # nonzero F_q residues z that are "p|z" is ZERO mod a prime (only z=0 is divisible by p in F_q!).
    # So the literal F_q reading is degenerate. The MEANINGFUL reading is the cyclotomic one above:
    # bound = R0 * (#nonzero cyclotomic states alpha with p|N(alpha)).
    c059_bound = R0 * num_contrib_states
    print(f"  n={n:>3} q={q} (~n^{beta}, q/n^{beta}={q/n**beta:.3f})  r={r}")
    print(f"    E_r^char0 (Z[zeta_n]) = {E0}")
    print(f"    E_r^Fp    (R_r(0))    = {Erp}")
    print(f"    anomaly (Fp - char0)  = {anomaly}   direct(spurious p|N(a)) = {anomaly_direct}  MATCH={anomaly==anomaly_direct}")
    print(f"    (B) per-point cap R_r(z)<=R_r(0): {cap_ok}  max off-diag R_r(z)={cap_max_offdiag} (R0={R0})")
    print(f"    (C) #contributing cyclotomic states (alpha!=0, p|N(alpha)) = {num_contrib_states}")
    print(f"        C059 bound R0 * #contrib = {c059_bound}")
    if anomaly>0:
        print(f"        looseness  bound/anomaly = {c059_bound/anomaly:.3e}")
    print(f"        bound / E_r^char0 (whole energy) = {c059_bound/E0:.3e}   (>1 => bound exceeds the whole energy it sits inside)")
    # (D) box-density: predicted contributing count ~ (2r)^{phi(n)}/p
    phi = n//2
    pred = (2*r)**phi / q
    print(f"    (D) box-density pred (2r)^phi/q = {pred:.3e}  vs actual #contrib={num_contrib_states}")
    print()
    return dict(n=n,q=q,r=r,E0=E0,Erp=Erp,anomaly=anomaly,anomaly_direct=anomaly_direct,
                cap_ok=cap_ok,contrib=num_contrib_states,bound=c059_bound)

if __name__=="__main__":
    print("=== C059: anomaly decomposition + autocorr-cap usefulness, proper-subgroup prize primes ===")
    cases = [
        (8,4,2),(8,4,3),(8,4,4),
        (16,4,2),(16,4,3),
        (8,5,3),(16,5,2),
    ]
    results=[]
    for (n,beta,r) in cases:
        try:
            res=run(n,beta,r)
            if res: results.append(res)
        except Exception as ex:
            print(f"  n={n} beta={beta} r={r}: ERROR {ex}")
    print("=== SUMMARY ===")
    print("All per-point caps hold:", all(x['cap_ok'] for x in results))
    print("All identity anomaly==direct:", all(x['anomaly']==x['anomaly_direct'] for x in results))
    # is the C059 bound ever near-tight?
    looses=[ (x['bound']/x['anomaly']) for x in results if x['anomaly']>0 ]
    if looses:
        print("looseness bound/anomaly: min=%.2e max=%.2e"%(min(looses),max(looses)))
    print("bound exceeds whole char0 energy in cases:",
          sum(1 for x in results if x['bound']>x['E0']),"/",len(results))
