#!/usr/bin/env python3
"""
C083 probe: "Group-action divisibility — does the residual orbit count K stay O(1)?"

C083 attack plan's closure hope:
  enumerate the FULL symmetry group acting jointly on the BGK kernel
    M = #{u in mu_n : -(1+u) in mu_n},
  quotient by ALL proven symmetries (S3 from AdditiveEnergyThreeDvd:
    iota:u->u^-1, sigma:u->-(1+u), tau=iota.sigma order 3;
    plus negation u->-u; plus Frobenius u->u^p over a subfield),
  and ask: does the RESIDUAL ORBIT COUNT K = (#orbits) stay O(1) above delta*?
  If yes => non-analytic closure of the depth-1 floor.

This probe computes, at DYADIC PROPER-SUBGROUP primes (prize regime: n=2^mu a
PROPER subgroup of F_q*, q prime = 1 mod n, q ~ n^beta, n << sqrt q):
  - M = bgkCount n   (the F5 energy kernel = the magnitude C083 says it does NOT control)
  - the number of S3-orbits on the kernel  N_S3 = M/3  (proven 3 | M when 3 ndvd n)
  - the number of <S3, negation>-orbits     N_full
  - whether N (= residual orbit count) is O(1) or GROWS with n.

The S3 group acts WITHIN mu_n (q-prime, base field F_q, no proper subfield to give
Frobenius over F_q itself), so the joint group here is generated by the field
automorphisms of the kernel: iota, sigma (the two BGK involutions), negation.
Frobenius x->x^p is trivial over the prime field F_p=F_q, so it adds nothing for
prime q (the prize regime uses q PRIME). We include negation explicitly.

EXACT integer arithmetic only. Multiple proper-subgroup primes per n.
"""

import sys

def is_prime(n):
    if n < 2: return False
    if n % 2 == 0: return n == 2
    i = 3
    while i*i <= n:
        if n % i == 0: return False
        i += 2
    return True

def find_dyadic_primes(n, beta_lo, beta_hi, count):
    """primes q = 1 mod n with n^beta_lo <= q <= n^beta_hi (proper subgroup mu_n)."""
    lo = n**beta_lo
    hi = n**beta_hi
    out = []
    # q = 1 + k*n
    k = max(1, (lo - 1)//n)
    q = 1 + k*n
    if q < lo: q += n
    while q <= hi and len(out) < count:
        if is_prime(q):
            out.append(q)
        q += n
    return out

def subgroup_mu(n, q):
    """the unique order-n subgroup of F_q^* (q = 1 mod n), as a set of ints."""
    # find a generator g of F_q^*, then mu_n = { g^(j*(q-1)/n) }
    # cheaper: an element of order exactly n = h^((q-1)/n) for a primitive root h.
    # find primitive root
    def order(a):
        # order of a mod q
        o = 1
        x = a % q
        while x != 1:
            x = (x*a) % q
            o += 1
            if o > q: return -1
        return o
    # find primitive root by trial
    h = None
    for cand in range(2, q):
        if pow(cand, (q-1)//2, q) != 1:
            # quick filter; check full order for small set
            if order(cand) == q-1:
                h = cand
                break
    if h is None:
        # fallback full scan
        for cand in range(2, q):
            if order(cand) == q-1:
                h = cand; break
    g = pow(h, (q-1)//n, q)  # element of order n
    mu = set()
    x = 1
    for _ in range(n):
        mu.add(x)
        x = (x*g) % q
    assert len(mu) == n, (n, len(mu))
    return mu

def bgk_kernel(n, q, mu):
    """{ u in mu : -(1+u) in mu }."""
    return set(u for u in mu if ((-(1+u)) % q) in mu)

def count_orbits(elts, maps, q):
    """number of orbits of the group generated by `maps` (each a closure-preserving
    self-map elts->elts) acting on the set `elts`."""
    elts = set(elts)
    seen = set()
    norbits = 0
    for s in elts:
        if s in seen: continue
        norbits += 1
        # BFS the orbit
        stack = [s]
        seen.add(s)
        while stack:
            x = stack.pop()
            for f in maps:
                y = f(x)
                if y in elts and y not in seen:
                    seen.add(y); stack.append(y)
    return norbits

def main():
    print("="*78)
    print("C083 residual-orbit-count probe  (BGK kernel M, dyadic proper-subgroup primes)")
    print("="*78)
    print("n=2^mu PROPER subgroup; q=1 mod n prime, n^beta_lo<=q<=n^beta_hi")
    print()
    header = f"{'n':>5} {'q':>10} {'beta=lg_n q':>11} {'M':>5} {'3|M':>4} {'2|M':>4} {'N_S3':>6} {'N_full':>7}"
    print(header)
    print("-"*len(header))
    # prize regime: beta in [4,5]; n proper subgroup so n << sqrt(q) i.e. beta>2.
    import math
    rows = []
    for mu in (3,4,5,6):     # n = 8,16,32,64
        n = 2**mu
        primes = find_dyadic_primes(n, 4, 5, 3)
        if not primes:
            primes = find_dyadic_primes(n, 3, 5, 3)
        for q in primes:
            muset = subgroup_mu(n, q)
            K = bgk_kernel(n, q, muset)
            M = len(K)
            # S3 maps restricted to the kernel
            inv = {u: pow(u, n-1, q) for u in muset}  # u^-1 in mu_n
            iota = lambda u: inv[u]
            sigma = lambda u: ((-(1+u)) % q)
            neg   = lambda u: ((-u) % q)
            N_S3   = count_orbits(K, [iota, sigma], q)
            N_full = count_orbits(K, [iota, sigma, neg], q)
            beta = math.log(q)/math.log(n)
            three = "Y" if M % 3 == 0 else "N"
            two   = "Y" if M % 2 == 0 else "N"
            print(f"{n:>5} {q:>10} {beta:>11.3f} {M:>5} {three:>4} {two:>4} {N_S3:>6} {N_full:>7}")
            rows.append((n, q, M, N_S3, N_full))
    print()
    print("VERDICT INPUTS:")
    # For each n, does M (hence orbit count N) grow with n?
    bym = {}
    for (n,q,M,Ns,Nf) in rows:
        bym.setdefault(n, []).append((M, Ns, Nf))
    print("  n -> (min M, max M) over the dyadic primes; min/max N_S3 ; min/max N_full")
    for n in sorted(bym):
        Ms = [x[0] for x in bym[n]]
        Nss= [x[1] for x in bym[n]]
        Nfs= [x[2] for x in bym[n]]
        print(f"   n={n:3d}: M in [{min(Ms)},{max(Ms)}]  N_S3 in [{min(Nss)},{max(Nss)}]  N_full in [{min(Nfs)},{max(Nfs)}]")
    print()
    print("If N (orbit count) GROWS with n -> the C083 'K=O(1) closure' hope is FALSE;")
    print("the magnitude M = 3*N_S3 is exactly the open BGK count, untouched by the symmetries.")

if __name__ == "__main__":
    main()
