"""
Subtlety check for C016: the _wf407_nvm.lean countermodel uses points {1, -1, zeta^2}
which all lie in mu_4 (a SUBGROUP of mu_8), and degrees {0,1,4}. There 4 == 0 mod 4 (NOT mod 8).
So that countermodel really exhibits the d -> d mod 4 collapse on a 3-element SUBSET, which the
connection slightly mislabels as "x^4=1 sends mu_8 -> mu_2". We confirm:
  - On the FULL n-element generating set (M i j = zeta^(e j * i), i over ALL of Fin n), the correct
    quotient is exactly mod n (CLAIM1, other probe).
  - On a PROPER SUBSET S of mu_n of size r that happens to span only mu_{n'} (n'|n), the relevant
    quotient is mod n' = mod (order of the subgroup the points generate), NOT mod n.
This is the genuine refinement: the gap map is d -> d mod (order of subgroup generated by the points),
which equals mod n only when the points generate all of mu_n. The connection's headline "d -> d mod n"
is correct for the full-domain Lovett union family (which uses the full evaluation set), and the
_wf407_nvm subset case is the same phenomenon at the sub-subgroup. Either way: distinct-as-naturals
is the WRONG quotient.
"""
import math

def is_prime(m):
    if m<2: return False
    for p in (2,3,5,7,11,13,17,19,23,29,31,37):
        if m%p==0: return m==p
    d=m-1;r=0
    while d%2==0: d//=2;r+=1
    for a in (2,3,5,7,11,13,17,19,23,29,31,37):
        x=pow(a,d,m)
        if x==1 or x==m-1: continue
        for _ in range(r-1):
            x=x*x%m
            if x==m-1: break
        else: return False
    return True

def prime_factors(n):
    fs=set();d=2
    while d*d<=n:
        while n%d==0: fs.add(d);n//=d
        d+=1
    if n>1: fs.add(n)
    return fs

def prim_root(q,n):
    cof=(q-1)//n
    for g in range(2,q):
        z=pow(g,cof,q)
        if z==1: continue
        if all(pow(z,n//p,q)!=1 for p in prime_factors(n)): return z
    raise RuntimeError

def det_mod(M,q):
    M=[r[:] for r in M];n=len(M);det=1
    for c in range(n):
        piv=next((r for r in range(c,n) if M[r][c]%q),None)
        if piv is None: return 0
        if piv!=c: M[c],M[piv]=M[piv],M[c];det=(-det)%q
        inv=pow(M[c][c],q-2,q);det=det*M[c][c]%q
        for r in range(c+1,n):
            f=M[r][c]*inv%q
            if f:
                for cc in range(c,n): M[r][cc]=(M[r][cc]-f*M[c][cc])%q
    return det%q

# Reproduce the EXACT _wf407_nvm.lean setup over ZMod 73 to confirm what it actually shows.
q=73; n=8
zeta=prim_root(q,n)  # primitive 8th root
# the file says zeta=10; ours may differ but generates same group; use a primitive 8th root with zeta^4=-1
# pick the one matching: find z with z^4 == 72 (=-1) and z^8==1
z8=None
for cand in range(2,q):
    if pow(cand,8,q)==1 and pow(cand,4,q)==q-1 and pow(cand,2,q)!=q-1:
        z8=cand;break
pts=[1,q-1,pow(z8,2,q)]  # {1,-1,zeta^2}
print(f"ZMod {q}: zeta8={z8}, points {pts} (=1,-1,zeta^2)")
print(f"  orders of points: {[next(o for o in range(1,n+1) if pow(p,o,q)==1) for p in pts]}")
# these points generate mu_? : zeta^2 has order 4, so they all lie in mu_4
print(f"  point powers ^4: {[pow(p,4,q) for p in pts]}  (all 1 => all in mu_4, NOT generic mu_8)")
# degrees {0,1,4}: 4 mod 8 = 4 (distinct from 0 mod 8) BUT 4 mod 4 = 0 (collapses mod 4)
print(f"  degrees {{0,1,4}}: mod 8 = {[d%8 for d in [0,1,4]]} (distinct!) ; mod 4 = {[d%4 for d in [0,1,4]]} (4==0 collapses)")
# build the 3x3 minor M[i][j] = pts[i]^degs[j]
degs=[0,1,4]
M=[[pow(pts[i],degs[j],q) for j in range(3)] for i in range(3)]
print(f"  M = {M}, det = {det_mod(M,q)} (singular, matches Mbad_det_eq_zero)")
print(f"  => the _wf407_nvm collapse is mod 4 (=order of subgroup the 3 points generate), not mod 8.")
print(f"     The 'd->d mod n' headline is precise for the FULL n-pt domain; for an r-pt subset it is")
print(f"     d->d mod (order of <pts>). Same phenomenon, distinct-as-naturals is still the wrong quotient.")
