/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alexander Hicks
-/

import ArkLib.Data.CodingTheory.ListDecoding.Bounds.General

/-!
# List-decoding bounds from ABF26 §3 — large-alphabet barrier, random codes, RS

The large-alphabet barrier, the random generator-matrix bounds, and the Reed-Solomon
list-decoding bounds. Part 2 of the `Bounds` split; see the `Bounds.lean` umbrella.
-/

set_option linter.unusedFintypeInType false
set_option linter.unusedDecidableInType false
set_option linter.unusedSectionVars false

namespace CodingTheory

open scoped NNReal ProbabilityTheory
open ListDecodable

section LargeAlphabetBarrier

/-- **ABF26 Theorem 3.10 [BDG24, AGL23].** Large-alphabet barrier for generalized
Singleton attainment. For every `ℓ ≥ 2` and `ρ ∈ (0, 1)` there exists a constant
`α_ℓρ > 0` such that for every `η > 0` and every sufficiently large `n`, every linear
error-correcting code `C ⊆ F^n` of rate at least `ρ` with `|Λ(C, ℓ/(ℓ+1) · (1-ρ-η))| ≤ ℓ`
satisfies:

  `|F| ≥ 2^{α_ℓρ / η}`

i.e. attaining the generalized Singleton bound up to `η` slack requires alphabet size
exponential in `1/η`. We existentially package the "sufficiently large" threshold as
an explicit `n₀` parameter rather than relying on Lean's `eventually` API.

**Rate hypothesis.** Phrased as `Module.finrank F C ≥ ρ · n` (a lower bound; matches
the paper's "rate at least ρ" reading and avoids the impossible real-equality
`finrank/n = ρ` for irrational `ρ`). The rate-≥-ρ form is what the proof actually
uses (the conclusion is a *lower* bound on `|F|`, monotone in the rate hypothesis).

Admitted as an external result.

**STATUS: HONEST REDUCTION AVAILABLE.** The descent from the combinatorial counting inequality
`2^(c·n) ≤ q^(4·η·n)` to the threshold `q ≥ 2^((c/4)/η)` is fully proven, `sorry`-free and
axiom-clean, in `AGL23.large_alphabet_barrier_of_counting`. The residual gap is isolated precisely
to `AGL23CountingExtraction` (the AGL23 §4 subcode extraction + pigeonhole phase), taken
here as an explicit hypothesis.
See `research/formal/arklib-proof-research-2026-06.md`. -/
theorem large_alphabet_barrier_bdg24_agl23
    (ℓ : ℕ) (hℓ_ge : 2 ≤ ℓ) (ρ : ℝ) (hρ_pos : 0 < ρ) (hρ_lt : ρ < 1)
    (hext : AGL23.AGL23CountingExtraction ℓ ρ) :
    ∃ α : ℝ, 0 < α ∧
      ∀ (η : ℝ), 0 < η →
        ∃ n₀ : ℕ,
          ∀ {ι : Type} [Fintype ι] [Nonempty ι] [DecidableEq ι]
            {F : Type} [Field F] [Fintype F] [DecidableEq F]
            (C : Submodule F (ι → F)),
            n₀ ≤ Fintype.card ι →
            (Module.finrank F C : ℝ) ≥ ρ * Fintype.card ι →
            Lambda ((C : Set (ι → F))) ((ℓ : ℝ) / (ℓ + 1) * (1 - ρ - η)) ≤ (ℓ : ℕ∞) →
            (Fintype.card F : ℝ) ≥ (2 : ℝ) ^ (α / η) :=
  AGL23.large_alphabet_barrier_of_counting ℓ hℓ_ge ρ hρ_pos hρ_lt hext

end LargeAlphabetBarrier

section RandomLinear

/-! ### Random generator matrices

GLMRSW22 samples linear codes through random generator matrices.  The definitions below expose
that finite probability space and its pushforward to `LinearCode.fromRowGenMat`; the paper's
first-moment lower-bound estimate remains the external ingredient. -/

/-- Uniform sampling of `k × |ι|` generator matrices over a finite alphabet. -/
noncomputable def uniformRandomLinearGeneratorMatrix
    (F : Type) [Fintype F] [Nonempty F] (k : ℕ) (ι : Type) [Fintype ι] :
    PMF (Matrix (Fin k) ι F) := by
  classical
  letI : Fintype (Matrix (Fin k) ι F) := by
    change Fintype (Fin k → ι → F)
    infer_instance
  letI : Nonempty (Matrix (Fin k) ι F) := by
    change Nonempty (Fin k → ι → F)
    infer_instance
  exact PMF.uniformOfFintype (Matrix (Fin k) ι F)

@[simp]
theorem support_uniformRandomLinearGeneratorMatrix
    {F : Type} [Fintype F] [Nonempty F] {k : ℕ} {ι : Type} [Fintype ι] :
    (uniformRandomLinearGeneratorMatrix F k ι).support = ⊤ := by
  classical
  simp [uniformRandomLinearGeneratorMatrix]

/-- Every generator matrix lies in the support of the uniform generator-matrix distribution. -/
theorem mem_support_uniformRandomLinearGeneratorMatrix
    {F : Type} [Fintype F] [Nonempty F] {k : ℕ} {ι : Type} [Fintype ι]
    (G : Matrix (Fin k) ι F) :
    G ∈ (uniformRandomLinearGeneratorMatrix F k ι).support := by
  rw [support_uniformRandomLinearGeneratorMatrix]
  trivial

/-- The linear code generated by the rows of a sampled generator matrix. -/
noncomputable def randomLinearCodeOfGeneratorMatrix
    {F : Type} [Semiring F] {k : ℕ} {ι : Type} [Fintype ι]
    (G : Matrix (Fin k) ι F) : LinearCode ι F :=
  LinearCode.fromRowGenMat G

/-- The pushforward distribution on linear codes induced by uniform generator matrices. -/
noncomputable def uniformRandomLinearCode
    (F : Type) [Field F] [Fintype F] [DecidableEq F] (k : ℕ)
    (ι : Type) [Fintype ι] :
    PMF (LinearCode ι F) :=
  (uniformRandomLinearGeneratorMatrix F k ι).map randomLinearCodeOfGeneratorMatrix

/-- The GLMRSW22 list-size lower-bound event for one sampled generator matrix. -/
noncomputable def randomLinearLambdaLowerEvent
    {F : Type} [Field F] [Fintype F] [DecidableEq F]
    {ι : Type} [Fintype ι] (q k : ℕ) (δ ε ρ : ℝ)
    (G : Matrix (Fin k) ι F) : Prop :=
  (LinearCode.dim (randomLinearCodeOfGeneratorMatrix G) : ℝ) / Fintype.card ι ≥ ρ ∧
    (Lambda (((randomLinearCodeOfGeneratorMatrix G : LinearCode ι F) : Set (ι → F))) δ :
        ENNReal) >
      ((Nat.floor (qEntropy q δ / (1 - qEntropy q δ - ρ) - ε) : ℕ) : ENNReal)

/-- Success probability of the GLMRSW22 lower-bound event under uniform generator matrices. -/
noncomputable def randomLinearLambdaLowerProbability
    (F : Type) [Field F] [Fintype F] [DecidableEq F]
    (ι : Type) [Fintype ι] (q k : ℕ) (δ ε ρ : ℝ) : ENNReal := by
  classical
  exact
    Pr_{let G ← uniformRandomLinearGeneratorMatrix F k ι}[
      randomLinearLambdaLowerEvent (F := F) (ι := ι) q k δ ε ρ G]

/-- Pointwise GLMRSW22 first-moment residual at fixed field, blocklength, generator dimension,
and rate target: the random-generator-matrix success probability is positive.

The paper proves a stronger high-probability estimate.  This residual names the exact positivity
input needed by ArkLib's existential-code front door. -/
noncomputable def randomLinearLambdaLowerFirstMomentResidual
    (F : Type) [Field F] [Fintype F] [DecidableEq F]
    (ι : Type) [Fintype ι] (q k : ℕ) (δ ε ρ : ℝ) : Prop :=
  0 < randomLinearLambdaLowerProbability F ι q k δ ε ρ

/-- A positive success probability supplies a concrete good generator matrix. -/
theorem exists_randomLinearLambdaLowerEvent_of_probability_pos
    {F : Type} [Field F] [Fintype F] [DecidableEq F]
    {ι : Type} [Fintype ι] {q k : ℕ} {δ ε ρ : ℝ}
    (hprob : 0 < randomLinearLambdaLowerProbability F ι q k δ ε ρ) :
    ∃ G : Matrix (Fin k) ι F,
      randomLinearLambdaLowerEvent (F := F) (ι := ι) q k δ ε ρ G := by
  classical
  by_contra hnone
  push Not at hnone
  have hEventFalse :
      (fun G : Matrix (Fin k) ι F =>
        randomLinearLambdaLowerEvent (F := F) (ι := ι) q k δ ε ρ G) =
        fun _ => False := by
    funext G
    exact propext (iff_false_intro (hnone G))
  have hzero : randomLinearLambdaLowerProbability F ι q k δ ε ρ = 0 := by
    unfold randomLinearLambdaLowerProbability
    change
      (PMF.map
          (fun G : Matrix (Fin k) ι F =>
            randomLinearLambdaLowerEvent (F := F) (ι := ι) q k δ ε ρ G)
          (uniformRandomLinearGeneratorMatrix F k ι)) True = 0
    rw [hEventFalse]
    change (PMF.map (Function.const (Matrix (Fin k) ι F) False)
        (uniformRandomLinearGeneratorMatrix F k ι)) True = 0
    rw [PMF.map_const]
    simp [PMF.pure_apply]
  rw [hzero] at hprob
  exact (lt_irrefl (0 : ENNReal)) hprob

/-- Conversely, one good generator matrix gives positive success probability.

This uses only the full support of the uniform generator-matrix distribution; it is the
existence-to-probability direction complementary to
`exists_randomLinearLambdaLowerEvent_of_probability_pos`. -/
theorem randomLinearLambdaLowerProbability_pos_of_exists_event
    {F : Type} [Field F] [Fintype F] [DecidableEq F]
    {ι : Type} [Fintype ι] {q k : ℕ} {δ ε ρ : ℝ}
    {G : Matrix (Fin k) ι F}
    (hG : randomLinearLambdaLowerEvent (F := F) (ι := ι) q k δ ε ρ G) :
    0 < randomLinearLambdaLowerProbability F ι q k δ ε ρ := by
  classical
  unfold randomLinearLambdaLowerProbability
  change 0 <
    (PMF.map
      (fun G : Matrix (Fin k) ι F =>
        randomLinearLambdaLowerEvent (F := F) (ι := ι) q k δ ε ρ G)
      (uniformRandomLinearGeneratorMatrix F k ι)) True
  rw [PMF.apply_pos_iff, PMF.support_map]
  exact ⟨G, mem_support_uniformRandomLinearGeneratorMatrix G, propext (iff_true_intro hG)⟩

/-- A concrete successful generator matrix supplies the named first-moment residual. -/
theorem randomLinearLambdaLowerFirstMomentResidual_of_exists_event
    {F : Type} [Field F] [Fintype F] [DecidableEq F]
    {ι : Type} [Fintype ι] {q k : ℕ} {δ ε ρ : ℝ}
    {G : Matrix (Fin k) ι F}
    (hG : randomLinearLambdaLowerEvent (F := F) (ι := ι) q k δ ε ρ G) :
    randomLinearLambdaLowerFirstMomentResidual F ι q k δ ε ρ :=
  randomLinearLambdaLowerProbability_pos_of_exists_event
    (F := F) (ι := ι) (q := q) (k := k) (δ := δ) (ε := ε) (ρ := ρ) hG

/-- A good generator matrix gives the existential code witness used by the legacy front door. -/
theorem exists_code_of_randomLinearLambdaLowerEvent
    {F : Type} [Field F] [Fintype F] [DecidableEq F]
    {ι : Type} [Fintype ι] {q k : ℕ} {δ ε ρ : ℝ}
    {G : Matrix (Fin k) ι F}
    (hG : randomLinearLambdaLowerEvent (F := F) (ι := ι) q k δ ε ρ G) :
    ∃ C : Submodule F (ι → F),
      (Module.finrank F C : ℝ) / Fintype.card ι ≥ ρ ∧
        (Lambda ((C : Set (ι → F))) δ : ENNReal) >
          ((Nat.floor (qEntropy q δ / (1 - qEntropy q δ - ρ) - ε) : ℕ) : ENNReal) := by
  refine ⟨randomLinearCodeOfGeneratorMatrix G, ?_, ?_⟩
  · simpa [LinearCode.dim] using hG.1
  · simpa using hG.2

/-- The pointwise first-moment residual supplies the legacy existential-code witness. -/
theorem exists_code_of_randomLinearLambdaLowerFirstMomentResidual
    {F : Type} [Field F] [Fintype F] [DecidableEq F]
    {ι : Type} [Fintype ι] {q k : ℕ} {δ ε ρ : ℝ}
    (hprob : randomLinearLambdaLowerFirstMomentResidual F ι q k δ ε ρ) :
    ∃ C : Submodule F (ι → F),
      (Module.finrank F C : ℝ) / Fintype.card ι ≥ ρ ∧
        (Lambda ((C : Set (ι → F))) δ : ENNReal) >
          ((Nat.floor (qEntropy q δ / (1 - qEntropy q δ - ρ) - ε) : ℕ) : ENNReal) := by
  rcases exists_randomLinearLambdaLowerEvent_of_probability_pos
      (F := F) (ι := ι) (q := q) (k := k) (δ := δ) (ε := ε) (ρ := ρ)
      hprob with
    ⟨G, hG⟩
  exact exists_code_of_randomLinearLambdaLowerEvent
    (F := F) (ι := ι) (q := q) (k := k) (δ := δ) (ε := ε) (ρ := ρ) hG

/-- **ABF26 Theorem 3.11 [GLMRSW22 Thm 4.1].** Random linear code lower bound. Fix a
prime `q`, `δ ∈ (0, 1 - 1/q)`, and `ε ∈ (0, 1)`. There exists `γ > 0` such that for all
`1 - H_q(δ) - γ < ρ < 1 - H_q(δ)` and all sufficiently large `n`, some linear code
`C ⊆ F^n` of rate `ρ` satisfies:

  `|Λ(C, δ)| > ⌊H_q(δ) / (1 - H_q(δ) - ρ) - ε⌋`

The paper's full statement gives a `1 - q^{-Ω(n)}` probability over the choice of a random
generator matrix.  ArkLib now has that probability space (`uniformRandomLinearGeneratorMatrix`
and `randomLinearLambdaLowerProbability`), while this legacy front door remains the existential
code statement consumed by downstream bounds.

**STATUS: NEEDS_CLASSICAL.** The [GLMRSW22 Thm 4.1] random-linear-code lower bound is
settled classical coding theory but unformalized anywhere; mathlib lacks the
list-decoding / entropy-rate API the proof needs. Discharging the `sorry` is a ground-up
formalization, not a port. (Secondary DESIGN_OBSTRUCTION: the paper's `1 - q^{-Ω(n)}`
probabilistic guarantee is downgraded here to a bare existential witness; the faithful
random-generator-matrix surface is `random_linear_lambda_lower_glmrsw22_random_generator_matrix`
below.) See `research/formal/arklib-proof-research-2026-06.md`. -/
def random_linear_lambda_lower_glmrsw22
    (q : ℕ) (_hq_pp : IsPrimePow q)
    (δ : ℝ) (_hδ_pos : 0 < δ) (_hδ_lt : δ < 1 - 1 / q)
    (ε : ℝ) (_hε_pos : 0 < ε) (_hε_lt : ε < 1) :
    Prop :=
    ∃ γ : ℝ, 0 < γ ∧
      ∀ ρ : ℝ, 1 - qEntropy q δ - γ < ρ → ρ < 1 - qEntropy q δ →
        ∃ n₀ : ℕ,
          ∀ {ι : Type} [Fintype ι] [Nonempty ι] [DecidableEq ι]
            {F : Type} [Field F] [Fintype F] [DecidableEq F],
            Fintype.card F = q → n₀ ≤ Fintype.card ι →
            -- Rate `≥ ρ` (not `= ρ`) so the statement is provable for *any* real
            -- `ρ` in the interval, including irrationals where the rational
            -- `finrank/|ι|` cannot exactly equal `ρ`. The conclusion's bound is
            -- monotone in `ρ`, so a code of rate strictly above `ρ` still
            -- witnesses the `ρ`-indexed bound.
            ∃ C : Submodule F (ι → F),
              (Module.finrank F C : ℝ) / Fintype.card ι ≥ ρ ∧
              (Lambda ((C : Set (ι → F))) δ : ENNReal) >
                ((Nat.floor (qEntropy q δ / (1 - qEntropy q δ - ρ) - ε) : ℕ) : ENNReal)
  -- ABF26-T3.11; external statement [GLMRSW22 Thm 4.1].
  -- Missing ingredient: GLMRSW22's random-linear-code list-size lower bound. Needs a
  -- probabilistic-existence argument: a random rate-ρ linear code has |Λ(C,δ)| >
  -- ⌊H_q(δ)/(1-H_q(δ)-ρ)-ε⌋ with probability 1-q^{-Ω(n)}. ArkLib now has the finite
  -- generator-matrix probability space; the missing theorem is the GLMRSW22 first-moment
  -- count showing this success probability is positive (indeed high). Genuinely external.

/-- Faithful random-generator-matrix form of the GLMRSW22 lower bound, with the high-probability
estimate weakened to the positive-probability assertion sufficient for an existential code
witness.  The full paper theorem should strengthen the final conjunct to `1 - q^{-Ω(n)}`. -/
noncomputable def random_linear_lambda_lower_glmrsw22_random_generator_matrix
    (q : ℕ) (_hq_pp : IsPrimePow q)
    (δ : ℝ) (_hδ_pos : 0 < δ) (_hδ_lt : δ < 1 - 1 / q)
    (ε : ℝ) (_hε_pos : 0 < ε) (_hε_lt : ε < 1) :
    Prop :=
    ∃ γ : ℝ, 0 < γ ∧
      ∀ ρ : ℝ, 1 - qEntropy q δ - γ < ρ → ρ < 1 - qEntropy q δ →
        ∃ n₀ : ℕ,
          ∀ {ι : Type} [Fintype ι] [Nonempty ι] [DecidableEq ι]
            {F : Type} [Field F] [Fintype F] [DecidableEq F],
            Fintype.card F = q → n₀ ≤ Fintype.card ι →
            ∃ k : ℕ,
              0 < randomLinearLambdaLowerProbability F ι q k δ ε ρ

/-- Positive probability in the random-generator-matrix form reassembles the legacy existential
GLMRSW22 front door. -/
theorem random_linear_lambda_lower_glmrsw22_of_random_generator_matrix
    (q : ℕ) (hq_pp : IsPrimePow q)
    (δ : ℝ) (hδ_pos : 0 < δ) (hδ_lt : δ < 1 - 1 / q)
    (ε : ℝ) (hε_pos : 0 < ε) (hε_lt : ε < 1)
    (h :
      random_linear_lambda_lower_glmrsw22_random_generator_matrix
        q hq_pp δ hδ_pos hδ_lt ε hε_pos hε_lt) :
    random_linear_lambda_lower_glmrsw22 q hq_pp δ hδ_pos hδ_lt ε hε_pos hε_lt := by
  rcases h with ⟨γ, hγ_pos, hγ⟩
  refine ⟨γ, hγ_pos, ?_⟩
  intro ρ hρ_low hρ_high
  rcases hγ ρ hρ_low hρ_high with ⟨n₀, hn₀⟩
  refine ⟨n₀, ?_⟩
  intro ι hιFintype hιNonempty hιDecidable F hField hFFintype hFDecidable hFq hn
  letI : Fintype ι := hιFintype
  letI : Nonempty ι := hιNonempty
  letI : DecidableEq ι := hιDecidable
  letI : Field F := hField
  letI : Fintype F := hFFintype
  letI : DecidableEq F := hFDecidable
  rcases hn₀ (ι := ι) (F := F) hFq hn with ⟨k, hprob⟩
  rcases exists_randomLinearLambdaLowerEvent_of_probability_pos
      (F := F) (ι := ι) (q := q) (k := k) (δ := δ) (ε := ε) (ρ := ρ) hprob with
    ⟨G, hG⟩
  exact exists_code_of_randomLinearLambdaLowerEvent
    (F := F) (ι := ι) (q := q) (k := k) (δ := δ) (ε := ε) (ρ := ρ) hG

/-- A named first-moment residual family supplies the faithful random-generator-matrix
GLMRSW22 surface.  The theorem only unfolds
`randomLinearLambdaLowerFirstMomentResidual`; the actual first-moment estimate remains the
explicit hypothesis. -/
theorem random_linear_lambda_lower_glmrsw22_random_generator_matrix_of_first_moment_residual
    (q : ℕ) (hq_pp : IsPrimePow q)
    (δ : ℝ) (hδ_pos : 0 < δ) (hδ_lt : δ < 1 - 1 / q)
    (ε : ℝ) (hε_pos : 0 < ε) (hε_lt : ε < 1)
    (h :
      ∃ γ : ℝ, 0 < γ ∧
        ∀ ρ : ℝ, 1 - qEntropy q δ - γ < ρ → ρ < 1 - qEntropy q δ →
          ∃ n₀ : ℕ,
            ∀ {ι : Type} [Fintype ι] [Nonempty ι] [DecidableEq ι]
              {F : Type} [Field F] [Fintype F] [DecidableEq F],
              Fintype.card F = q → n₀ ≤ Fintype.card ι →
              ∃ k : ℕ,
                randomLinearLambdaLowerFirstMomentResidual F ι q k δ ε ρ) :
    random_linear_lambda_lower_glmrsw22_random_generator_matrix
      q hq_pp δ hδ_pos hδ_lt ε hε_pos hε_lt := by
  simpa [random_linear_lambda_lower_glmrsw22_random_generator_matrix,
    randomLinearLambdaLowerFirstMomentResidual] using h

/-- A named first-moment residual family supplies the legacy existential GLMRSW22 front door. -/
theorem random_linear_lambda_lower_glmrsw22_of_first_moment_residual
    (q : ℕ) (hq_pp : IsPrimePow q)
    (δ : ℝ) (hδ_pos : 0 < δ) (hδ_lt : δ < 1 - 1 / q)
    (ε : ℝ) (hε_pos : 0 < ε) (hε_lt : ε < 1)
    (h :
      ∃ γ : ℝ, 0 < γ ∧
        ∀ ρ : ℝ, 1 - qEntropy q δ - γ < ρ → ρ < 1 - qEntropy q δ →
          ∃ n₀ : ℕ,
            ∀ {ι : Type} [Fintype ι] [Nonempty ι] [DecidableEq ι]
              {F : Type} [Field F] [Fintype F] [DecidableEq F],
              Fintype.card F = q → n₀ ≤ Fintype.card ι →
              ∃ k : ℕ,
                randomLinearLambdaLowerFirstMomentResidual F ι q k δ ε ρ) :
    random_linear_lambda_lower_glmrsw22 q hq_pp δ hδ_pos hδ_lt ε hε_pos hε_lt :=
  random_linear_lambda_lower_glmrsw22_of_random_generator_matrix q hq_pp δ hδ_pos hδ_lt ε
    hε_pos hε_lt
    (random_linear_lambda_lower_glmrsw22_random_generator_matrix_of_first_moment_residual
      q hq_pp δ hδ_pos hδ_lt ε hε_pos hε_lt h)

/-! ### The combinatorial-witness layer: the residual without its probability space

`randomLinearLambdaLowerFirstMomentResidual` is a probability statement (`Pr > 0` over uniform
generator matrices), but in-tree it is *equivalent* to a purely combinatorial existence: one
generator matrix `G`, one centre `y`, and one finite set `S` of codewords of `C(G)` within
relative radius `δ` of `y` with `|S| > ⌊H_q(δ)/(1 − H_q(δ) − ρ) − ε⌋`, alongside the rate bound.
The two theorems below prove both directions, so the genuinely external GLMRSW22 content is
re-surfaced one layer deeper: a finite counting construction with **no probability left in the
statement** (the paper's §4 construction produces exactly such `(G, y, S)`). -/

/-- **Combinatorial witness for the GLMRSW22 first-moment residual.**  A generator matrix `G`
meeting the rate target together with an explicit centre `y` and a finite codeword set `S` inside
the relative-`δ` ball at `y` beating the floor bound.  Equivalent to the probabilistic residual
(`randomLinearLambdaLowerFirstMomentResidual`) by the two theorems below — but stated with no
probability space. -/
def RandomLinearLambdaLowerCombinatorialWitness
    (F : Type) [Field F] [Fintype F] [DecidableEq F]
    (ι : Type) [Fintype ι] (q k : ℕ) (δ ε ρ : ℝ) : Prop :=
  ∃ (G : Matrix (Fin k) ι F) (y : ι → F) (S : Finset (ι → F)),
    (LinearCode.dim (randomLinearCodeOfGeneratorMatrix G) : ℝ) / Fintype.card ι ≥ ρ ∧
    (∀ c ∈ S, c ∈ closeCodewordsRel
        (((randomLinearCodeOfGeneratorMatrix G : LinearCode ι F) : Set (ι → F))) y δ) ∧
    Nat.floor (qEntropy q δ / (1 - qEntropy q δ - ρ) - ε) < S.card

/-- A combinatorial witness yields the per-matrix event: the explicit ball population forces
`Λ(C(G), δ)` above the floor bound. -/
theorem randomLinearLambdaLowerEvent_of_combinatorial
    {F : Type} [Field F] [Fintype F] [DecidableEq F]
    {ι : Type} [Fintype ι] {q k : ℕ} {δ ε ρ : ℝ}
    {G : Matrix (Fin k) ι F} {y : ι → F} {S : Finset (ι → F)}
    (hrate : (LinearCode.dim (randomLinearCodeOfGeneratorMatrix G) : ℝ) / Fintype.card ι ≥ ρ)
    (hclose : ∀ c ∈ S, c ∈ closeCodewordsRel
        (((randomLinearCodeOfGeneratorMatrix G : LinearCode ι F) : Set (ι → F))) y δ)
    (hcard : Nat.floor (qEntropy q δ / (1 - qEntropy q δ - ρ) - ε) < S.card) :
    randomLinearLambdaLowerEvent (F := F) (ι := ι) q k δ ε ρ G := by
  classical
  refine ⟨hrate, ?_⟩
  set C : Set (ι → F) :=
    ((randomLinearCodeOfGeneratorMatrix G : LinearCode ι F) : Set (ι → F)) with hC
  -- `S` populates the point list at `y`, so `|S| ≤ |Λ(C, δ, y)| ≤ Λ(C, δ)`.
  have hsub : (S : Set (ι → F)) ⊆ closeCodewordsRel C y δ := fun c hc =>
    hclose c (by exact_mod_cast hc)
  have hScard : (S.card : ℕ) ≤ (closeCodewordsRel C y δ).ncard := by
    calc S.card = (S : Set (ι → F)).ncard := (Set.ncard_coe_finset S).symm
      _ ≤ (closeCodewordsRel C y δ).ncard := Set.ncard_le_ncard hsub (Set.toFinite _)
  have hpoint : ((closeCodewordsRel C y δ).ncard : ℕ∞) ≤ Lambda C δ :=
    le_iSup (fun f : ι → F => ((closeCodewordsRel C f δ).ncard : ℕ∞)) y
  have hENat : ((Nat.floor (qEntropy q δ / (1 - qEntropy q δ - ρ) - ε) : ℕ) : ℕ∞)
      < Lambda C δ :=
    lt_of_lt_of_le (by exact_mod_cast lt_of_lt_of_le hcard hScard) hpoint
  calc ((Nat.floor (qEntropy q δ / (1 - qEntropy q δ - ρ) - ε) : ℕ) : ENNReal)
      = (((Nat.floor (qEntropy q δ / (1 - qEntropy q δ - ρ) - ε) : ℕ) : ℕ∞) : ENNReal) := by
        simp
    _ < (Lambda C δ : ENNReal) := by exact_mod_cast hENat

/-- **The residual from the combinatorial witness.**  The probabilistic first-moment residual
follows from the purely combinatorial `(G, y, S)` existence — no probability estimate needed
beyond full support of the uniform generator-matrix distribution. -/
theorem randomLinearLambdaLowerFirstMomentResidual_of_combinatorialWitness
    {F : Type} [Field F] [Fintype F] [DecidableEq F]
    {ι : Type} [Fintype ι] {q k : ℕ} {δ ε ρ : ℝ}
    (h : RandomLinearLambdaLowerCombinatorialWitness F ι q k δ ε ρ) :
    randomLinearLambdaLowerFirstMomentResidual F ι q k δ ε ρ := by
  obtain ⟨G, y, S, hrate, hclose, hcard⟩ := h
  exact randomLinearLambdaLowerFirstMomentResidual_of_exists_event
    (randomLinearLambdaLowerEvent_of_combinatorial hrate hclose hcard)

/-- **Converse: the residual yields a combinatorial witness.**  Hence the witness is a faithful
(equivalent) re-surfacing of the residual, not a strengthening: positive probability extracts a
good matrix, and `Λ(C, δ) > ⌊…⌋` extracts a centre and a finite list beating the floor. -/
theorem combinatorialWitness_of_randomLinearLambdaLowerFirstMomentResidual
    {F : Type} [Field F] [Fintype F] [DecidableEq F]
    {ι : Type} [Fintype ι] {q k : ℕ} {δ ε ρ : ℝ}
    (h : randomLinearLambdaLowerFirstMomentResidual F ι q k δ ε ρ) :
    RandomLinearLambdaLowerCombinatorialWitness F ι q k δ ε ρ := by
  classical
  obtain ⟨G, hrate, hLam⟩ := exists_randomLinearLambdaLowerEvent_of_probability_pos h
  set C : Set (ι → F) :=
    ((randomLinearCodeOfGeneratorMatrix G : LinearCode ι F) : Set (ι → F)) with hC
  -- transport the strict bound from `ENNReal` back to `ℕ∞`
  have hENat : ((Nat.floor (qEntropy q δ / (1 - qEntropy q δ - ρ) - ε) : ℕ) : ℕ∞)
      < Lambda C δ := by
    by_contra hle
    push Not at hle
    exact absurd (lt_of_lt_of_le hLam (by exact_mod_cast hle)) (lt_irrefl _)
  -- the supremum beats the floor, so some centre's point list does
  obtain ⟨y, hy⟩ := lt_iSup_iff.mp hENat
  refine ⟨G, y, (Set.toFinite (closeCodewordsRel C y δ)).toFinset, hrate, ?_, ?_⟩
  · intro c hc
    exact (Set.Finite.mem_toFinset _).mp hc
  · have hcard : (Set.toFinite (closeCodewordsRel C y δ)).toFinset.card
        = (closeCodewordsRel C y δ).ncard :=
      (Set.ncard_eq_toFinset_card _ (Set.toFinite _)).symm
    exact_mod_cast hcard ▸ (by exact_mod_cast hy :
      Nat.floor (qEntropy q δ / (1 - qEntropy q δ - ρ) - ε)
        < (closeCodewordsRel C y δ).ncard)

end RandomLinear

section ReedSolomonBounds

/-- **ABF26 Theorem 3.12 [BKR06 Cor 2.2] — honest reduction form (per-instance).**

The *in-tree-provable arithmetic content* of the BKR06 superpolynomial RS bound, with the
single genuinely-external ingredient surfaced as an explicit hypothesis (never faked).

BKR06's construction (Lemma 3.5) exhibits, for the RS code `RS[F_q, F_q, ⌊q^α⌋]`, a word
`w` whose close-codeword set is at least as large as the root count of the subspace
polynomial `P_W` of an `𝔽_q`-subspace `W ⊆ F_q` of dimension `d`.  That count equals
`(BKR06.subspacePoly (BKR06.subFinset W)).natDegree = q^d` (proven, axiom-clean, in
`BKR06SubspacePoly.lean`).  The residual `hcount` is exactly the BKR06 roots→close-codewords
conversion; the dimension threshold `hdim : (α - β²)·log q ≤ d` is BKR06's parameter choice.

Given those two, the target bound `q^{(α-β²)·log q} ≤ ncard` follows by the proven
`BKR06.subspacePoly_natDegree_ge_target` arithmetic bridge.  This pins the genuine residual
precisely inside `hcount`/`hdim` and discharges the corollary's own arithmetic honestly. -/
theorem rs_lambda_superpoly_extension_bkr06_of_residuals
    {ι : Type} [Fintype ι] [Nonempty ι] [DecidableEq ι]
    {F : Type} [Field F] [Fintype F] [DecidableEq F]
    (α β : ℝ) (q : ℕ) (hq : Fintype.card F = q) (hq1 : (1 : ℝ) ≤ q)
    (domain : ι ↪ F) (w : ι → F) (δ : ℝ)
    (W : Submodule F F) [Fintype W]
    -- BKR06's parameter choice: the subspace dimension meets the T3.12 threshold.
    (hdim : (α - β ^ 2) * Real.log q ≤ (Module.finrank F W : ℝ))
    -- BKR06 Lemma 3.5 (roots → close-codewords), the genuine external count: the
    -- close-codeword set is at least as large as the subspace polynomial's root count.
    (hcount :
        ((BKR06.subspacePoly (BKR06.subFinset W)).natDegree : ℝ) ≤
          ((closeCodewordsRel
              ((ReedSolomon.code domain (Nat.floor ((q : ℝ) ^ α)) : Set (ι → F))) w δ).ncard : ℝ)) :
    ((closeCodewordsRel
        ((ReedSolomon.code domain (Nat.floor ((q : ℝ) ^ α)) : Set (ι → F))) w δ).ncard : ℝ) ≥
      (q : ℝ) ^ ((α - β ^ 2) * Real.log q) := by
  have hbridge :=
    BKR06.subspacePoly_natDegree_ge_target (F := F) (K := F) W q hq hq1
      ((α - β ^ 2) * Real.log q) hdim
  exact le_trans hbridge hcount

/-- **ABF26 Theorem 3.12 [BKR06 Cor 2.2] — narrowed-residual form (fiber-count consuming).**

A strictly *smaller* residual than `rs_lambda_superpoly_extension_bkr06_of_residuals`'s
`hcount`.  Rather than assuming the close-codeword *count* `≥ q^d` outright, this form
assumes only the genuine *geometric* step of BKR06 Lemma 3.5: an **injection**
`encode : F → (ι → F)` that sends the `q^d` roots of the subspace polynomial (the carrier
of the subspace `W`) to *distinct close codewords* (`hmaps` + `hinj`).  The cardinality
arithmetic — that such an injection forces `≥ q^d = (subspacePoly W).natDegree` close
codewords — is then discharged here, axiom-clean, via `Set.ncard_le_ncard_of_injOn` and
the proven value-fiber count engine in `ArkLib.ToMathlib.BKR06FiberCount`
(`BKR06.subspacePoly_natDegree`, the zero-fiber `= subFinset W` identity).

This pins the genuine external residual to its irreducible geometric core: the *existence*
of the BKR06 roots→distinct-close-codewords encoding.  Everything counting-theoretic is
now proven in-tree.

**PARAMETER DEFECT (do not discharge this form by BKR06; use the corrected form below).**
This statement is parameterized by `W : Submodule F F` — an `F`-submodule of the *alphabet
field itself*.  Such a submodule has `Module.finrank F W ∈ {0, 1}` (only `⊥` and `⊤`), so
its "`q^d`" collapses to `q^0 = 1` or `q^1 = q`, and the dimension threshold `hdim`
together with the geometric encoding *cannot be discharged by the BKR06 construction at any
meaningful dimension*.  BKR06 genuinely lives at the *extension* parameters: base field
`F_q`, extension `K = F_{q^m}` (`m ≥ 2`), `W` an `F_q`-subspace of `K` of dimension
`2 ≤ d ≤ m`, evaluation domain inside `K`.  Over `K = F = F_q` the subspace-polynomial
structure is degenerate.  Moreover the list size in BKR06 comes from *varying* the subspace
`L` over a pigeonhole *family* `𝓛` (the `|𝓛| ≥ q^{(u+1)m − v²}` distinct subspaces), not
from the `q^d` agreements of one fixed `W`.  The form is *not unsound* (it merely *takes*
`encode` as a hypothesis), it simply cannot be discharged at its own parameters.  Use the
corrected extension/family form `rs_lambda_superpoly_extension_bkr06_of_family` below, which
is stated where the construction actually applies and consumes exactly the output of
`BKR06.bkr06_family_close_codewords_card_ge`.  (Campaign convention: never delete, document.)
-/
theorem rs_lambda_superpoly_extension_bkr06_of_injection
    {ι : Type} [Fintype ι] [Nonempty ι] [DecidableEq ι]
    {F : Type} [Field F] [Fintype F] [DecidableEq F]
    (α β : ℝ) (q : ℕ) (hq : Fintype.card F = q) (hq1 : (1 : ℝ) ≤ q)
    (domain : ι ↪ F) (w : ι → F) (δ : ℝ)
    (W : Submodule F F) [Fintype W]
    (hdim : (α - β ^ 2) * Real.log q ≤ (Module.finrank F W : ℝ))
    -- The genuine BKR06 Lemma-3.5 geometric residual: an encoding of the roots of the
    -- subspace polynomial (= carrier of `W`) into the close-codeword set …
    (encode : F → (ι → F))
    (hmaps : ∀ v ∈ W,
        encode v ∈
          closeCodewordsRel
            ((ReedSolomon.code domain (Nat.floor ((q : ℝ) ^ α)) : Set (ι → F))) w δ)
    -- … and that this encoding is injective on `W` (distinct roots ↦ distinct codewords).
    (hinj : Set.InjOn encode (W : Set F)) :
    ((closeCodewordsRel
        ((ReedSolomon.code domain (Nat.floor ((q : ℝ) ^ α)) : Set (ι → F))) w δ).ncard : ℝ) ≥
      (q : ℝ) ^ ((α - β ^ 2) * Real.log q) := by
  -- The injection gives `|W| ≤ |closeCodewords|` …
  have hncard_le :
      (W : Set F).ncard ≤
        (closeCodewordsRel
          ((ReedSolomon.code domain (Nat.floor ((q : ℝ) ^ α)) : Set (ι → F))) w δ).ncard :=
    Set.ncard_le_ncard_of_injOn encode hmaps hinj (Set.toFinite _)
  -- … and `|W| = |subFinset W| = (subspacePoly W).natDegree = q^{finrank}` via the proven brick.
  have hWcard : (W : Set F).ncard = (BKR06.subspacePoly (BKR06.subFinset W)).natDegree := by
    rw [BKR06.subspacePoly_natDegree]
    have hcard : (BKR06.subFinset W).card = Fintype.card W := by
      rw [BKR06.subFinset]; simp [Set.toFinset_card]
    rw [hcard, Set.ncard_eq_toFinset_card' (W : Set F)]
    simp [Set.toFinset_card]
  -- Convert to the `hcount`-shaped inequality and reuse the proven arithmetic bridge.
  have hcount :
      ((BKR06.subspacePoly (BKR06.subFinset W)).natDegree : ℝ) ≤
        ((closeCodewordsRel
            ((ReedSolomon.code domain (Nat.floor ((q : ℝ) ^ α)) : Set (ι → F))) w δ).ncard : ℝ) := by
    rw [← hWcard]; exact_mod_cast hncard_le
  exact rs_lambda_superpoly_extension_bkr06_of_residuals α β q hq hq1 domain w δ W hdim hcount

/-- **ABF26 Theorem 3.12 [BKR06 Cor 2.2] — corrected extension/family reduction form.**

The genuine, dischargeable shape of the BKR06 superpolynomial RS bound, stated at the
parameters where the construction actually lives (cf. the PARAMETER DEFECT note on
`rs_lambda_superpoly_extension_bkr06_of_injection`): a base field `F` (the `𝔽_q`), a
*proper extension* `K = 𝔽_{q^m}` carrying an `F`-module structure, the full evaluation
domain `K ↪ K` (BKR06's `domain = id`, surjective), and a *family* `𝓛 : ι → Submodule F K`
of `F_q`-subspaces of `K` whose subspace polynomials all agree with a common pivot above
degree `k` and are pairwise distinct.

This consumes **exactly** the hypotheses of (and routes through) the proven construction
`BKR06.bkr06_family_close_codewords_card_ge`:
* `hsmall`   — each `pivot − P_{𝓛 i}` has degree `< |K|` (so the agreement-on-all-points
  injectivity applies);
* `hdistinct`— the subspace polynomials are pairwise distinct (the pigeonhole family is
  genuinely a family of distinct codewords);
* `hclose`   — each constructed codeword lies in the close-codeword set of the received word
  `w = evalOnPoints domain pivot` (the only numeric residual: BKR06 discharges this from
  `agree ≥ q^v`, turning the agreement count into the relative-distance bound `δ`).

The list-size lower bound then chains:
  `q^{(α − β²)·log q}  ≤  |ι|  ≤  ncard (close codewords)`,
where the left inequality is the **pigeonhole family-size residual** `hfamily` (BKR06
Lemma 3.5: there are `|ι| = |𝓛| ≥ q^{(u+1)m − v²}` distinct subspaces sharing top
coefficients — the genuinely external combinatorial input, see below), and the right
inequality is `BKR06.bkr06_family_close_codewords_card_ge`, fully proven in-tree.

**Residual surface after this reduction** (each a named, honest hypothesis of a *proven*
reduction — no `sorry`, no silent weakening):
* `(a)` `hclose` — agreement-count `≥ q^v` → relative-distance `δ` conversion;
* `(b)` `hfamily` — the pigeonhole family existence/size `q^{(α−β²)log q} ≤ |ι|`
  (subspaces of `K` of fixed dimension `v` sharing the top coefficients of their subspace
  polynomials; counted via Gaussian binomials against the number of top-coefficient
  patterns — left as a named residual here, see the module/PARAMETER-DEFECT note);
* the "infinitely many prime powers" sequence still lives only in the bare external `Prop`
  `rs_lambda_superpoly_extension_bkr06`.

Compared to `_of_residuals`/`_of_injection`, this is the *first* form that can actually be
fed by BKR06: the subspace lives in a real extension `K`, so `Module.finrank F (𝓛 i)` is
no longer pinned to `{0,1}`, and the list size comes from the *family cardinality* `|ι|`,
not from one fixed subspace. -/
theorem rs_lambda_superpoly_extension_bkr06_of_family
    {ι : Type} [Fintype ι] [DecidableEq ι]
    {K : Type} [Field K] [Fintype K] [DecidableEq K]
    {F : Type} [Field F] [Fintype F] [DecidableEq F] [Module F K]
    (α β : ℝ) (q : ℕ) (_hq : Fintype.card F = q)
    (domain : K ↪ K) (hsurj : Function.Surjective domain)
    (pivot : Polynomial K) (k : ℕ) (δ : ℝ)
    (𝓛 : ι → Submodule F K) [∀ i, Fintype (𝓛 i)]
    (hsmall : ∀ i,
        (pivot - BKR06.subspacePoly (BKR06.subFinset (𝓛 i))).natDegree < Fintype.card K)
    (hdistinct : Function.Injective (fun i => BKR06.subspacePoly (BKR06.subFinset (𝓛 i))))
    -- BKR06 Lemma 3.5 numeric closeness residual (agreement count → relative distance `δ`).
    (hclose : ∀ i,
        ReedSolomon.evalOnPoints domain
            (pivot - BKR06.subspacePoly (BKR06.subFinset (𝓛 i)))
          ∈ closeCodewordsRel
              ((ReedSolomon.code domain k : Set (K → K)))
              (ReedSolomon.evalOnPoints domain pivot) δ)
    -- BKR06 Lemma 3.5 pigeonhole family-size residual: there are at least
    -- `q^{(α−β²)·log q}` distinct subspaces in the family `𝓛`.
    (hfamily : (q : ℝ) ^ ((α - β ^ 2) * Real.log q) ≤ (Fintype.card ι : ℝ)) :
    ((closeCodewordsRel
        ((ReedSolomon.code domain k : Set (K → K)))
        (ReedSolomon.evalOnPoints domain pivot) δ).ncard : ℝ) ≥
      (q : ℝ) ^ ((α - β ^ 2) * Real.log q) := by
  -- The proven construction supplies `|ι| ≤ ncard (close codewords)` directly.
  have hcard_le :
      (Fintype.card ι : ℕ) ≤
        (closeCodewordsRel
            ((ReedSolomon.code domain k : Set (K → K)))
            (ReedSolomon.evalOnPoints domain pivot) δ).ncard :=
    BKR06.bkr06_family_close_codewords_card_ge domain hsurj pivot k δ 𝓛 hsmall hdistinct hclose
  -- Chain `q^{(α−β²)log q} ≤ |ι| ≤ ncard`.
  calc (q : ℝ) ^ ((α - β ^ 2) * Real.log q)
      ≤ (Fintype.card ι : ℝ) := hfamily
    _ ≤ _ := by exact_mod_cast hcard_le

/-- **ABF26 Theorem 3.12 [BKR06 Cor 2.2].** Reed-Solomon superpolynomial list-size over
extension fields. Fix `0 < α < β < 1`. For infinitely many prime powers `q` there exists
a Reed-Solomon code `C := RS[F_q, F_q, ⌊q^α⌋]` and a word `w : F_q → F_q` such that:

  `|Λ(C, 1 - q^{β-1}, w)| ≥ q^{(α - β²) · log q}`

**STATUS: PROVEN.** This front door is discharged as an in-tree, axiom-clean theorem:
`BKR06.rs_lambda_superpoly_extension_bkr06_proven` in
`ArkLib/ToMathlib/BKR06BareT312.lean` (witness sequence `qs i = 2^{i+N+1}` past the
Archimedean band threshold; per-instance assembly = ZMod-2 base-field glue +
log-2-widened band cutoffs + the tight pigeonhole close-codeword count +
floor-window/index transport, all from `ArkLib/ToMathlib/BKR06EndToEnd.lean`).  The
`def : Prop` below is retained as the statement surface; the narrowed `_of_residuals`/
injection/family forms remain as intermediate API.  Historical context:
`research/formal/arklib-proof-research-2026-06.md`.

**HONEST REDUCTION AVAILABLE.** The arithmetic core (the subspace-polynomial root count
`q^d` dominating the target `q^{(α-β²)log q}` under BKR06's dimension threshold) is fully
proven, `sorry`-free and axiom-clean, in `rs_lambda_superpoly_extension_bkr06_of_residuals`
(above), which derives the per-instance bound from the BKR06 Lemma-3.5 roots→close-codewords
count (`hcount`) and the dimension threshold (`hdim`) as explicit hypotheses. The subspace
polynomial's additivity and degree `q^d` are proven in `BKR06SubspacePoly.lean`.

**RESIDUAL NARROWED.** `rs_lambda_superpoly_extension_bkr06_of_injection` (above) shrinks the
residual further: it assumes only the genuine *geometric* step — an injective encoding of the
`q^d` roots of the subspace polynomial into the close-codeword set — and discharges *all* of
the counting arithmetic in-tree via `Set.ncard_le_ncard_of_injOn` together with the proven
value-fiber engine in `ArkLib.ToMathlib.BKR06FiberCount`
(`BKR06.card_subspacePolyHom_fiber_eq_natDegree`: a degree-`q^d` linearized polynomial takes
each value in its image exactly `q^d` times). The statement below remains an external `Prop`
only because the *unhypothesized* in-tree statement cannot supply that geometric encoding nor
the "infinitely many `q`" prime-power witness sequence. -/
def rs_lambda_superpoly_extension_bkr06
    (α β : ℝ) (_hα_pos : 0 < α) (_hα_lt : α < β) (_hβ_lt : β < 1) :
    Prop :=
    -- `qs` carries the prime-power requirement as a *conjunct* alongside
    -- `StrictMono`. The previous shape `∀ i, IsPrimePow (qs i) → P i` was
    -- vacuously satisfied by any non-prime-power sequence; we now require
    -- *every* `qs i` to be a prime power up front.
    ∃ qs : ℕ → ℕ, StrictMono qs ∧ (∀ i, IsPrimePow (qs i)) ∧
      ∀ i : ℕ,
        ∀ {ι : Type} [Fintype ι] [Nonempty ι] [DecidableEq ι]
          {F : Type} [Field F] [Fintype F] [DecidableEq F],
          Fintype.card F = qs i → Fintype.card ι = qs i →
          ∃ (domain : ι ↪ F) (w : ι → F),
            let q : ℕ := qs i
            let k : ℕ := Nat.floor ((q : ℝ) ^ α)
            let δ : ℝ := 1 - (q : ℝ) ^ (β - 1)
            let C := ReedSolomon.code domain k
            ((closeCodewordsRel ((C : Set (ι → F))) w δ).ncard : ℝ) ≥
              (q : ℝ) ^ ((α - β ^ 2) * Real.log q)
  -- ABF26-T3.12; external statement [BKR06 Cor 2.2].
  -- Missing ingredient: BKR06's superpolynomial RS list-size CONSTRUCTION over extension
  -- fields. Must exhibit, for infinitely many prime powers q, an RS code RS[F_q,F_q,⌊q^α⌋]
  -- and a word w with ≥ q^{(α-β²)log q} close codewords. The construction uses BKR06's
  -- subfield/trace structure; ExtensionCodes.lean L2.21 transports list sizes but does not
  -- manufacture the BKR06 large-list word. LOWER bound — genuinely external.

/-- **ABF26 Theorem 3.13 [GHSZ02 Cor 20] — honest reduction form (per-instance).**

The *in-tree-provable content* of the GHSZ02 prime-field RS bound, with the single
genuinely-external ingredient surfaced as an explicit hypothesis (never faked).

GHSZ02's construction builds, for a large prime `p`, a word `w` whose close-codeword set has
*at least* `p^{p^α·β/2}` elements (the high-multiplicity polynomial-family count, `hcount`).
The Ω-form target `> c · p^{p^α·β/2}` (with the `Ω`-constant existentially bound as `0 < c`)
then follows with the explicit witness `c = 1/2`, since `(1/2)·X < X ≤ ncard` for the
strictly-positive `X = p^{p^α·β/2}`.  This pins the genuine residual precisely inside
`hcount` and discharges the Ω-constant + strict-inequality bookkeeping honestly. -/
theorem rs_lambda_large_prime_ghsz02_of_residuals
    {ι : Type} [Fintype ι] [Nonempty ι] [DecidableEq ι]
    {F : Type} [Field F] [Fintype F] [DecidableEq F]
    (α β : ℝ) (p : ℕ) (hp1 : (1 : ℝ) ≤ p)
    (domain : ι ↪ F) (w : ι → F) (δ : ℝ)
    -- GHSZ02 high-multiplicity count (the genuine external lower bound):
    (hcount :
        (p : ℝ) ^ ((p : ℝ) ^ α * β / 2) ≤
          ((closeCodewordsRel
              ((ReedSolomon.code domain (Nat.floor ((p : ℝ) ^ α)) : Set (ι → F))) w δ).ncard : ℝ)) :
    ∃ c : ℝ, 0 < c ∧
      ((closeCodewordsRel
          ((ReedSolomon.code domain (Nat.floor ((p : ℝ) ^ α)) : Set (ι → F))) w δ).ncard : ℝ) >
        c * (p : ℝ) ^ ((p : ℝ) ^ α * β / 2) := by
  refine ⟨1 / 2, by norm_num, ?_⟩
  have hpow_pos : (0 : ℝ) < (p : ℝ) ^ ((p : ℝ) ^ α * β / 2) :=
    Real.rpow_pos_of_pos (by linarith) _
  calc (1 / 2 : ℝ) * (p : ℝ) ^ ((p : ℝ) ^ α * β / 2)
      < (p : ℝ) ^ ((p : ℝ) ^ α * β / 2) := by linarith
    _ ≤ _ := hcount

/-- **ABF26 Theorem 3.13 [GHSZ02 Cor 20] — narrowed-residual (injection) form.**

A strictly *smaller* residual than `rs_lambda_large_prime_ghsz02_of_residuals`'s `hcount`.
Rather than assuming the close-codeword *count* `≥ p^{p^α·β/2}` outright, this form assumes
only the genuine GHSZ02 Cor-20 *geometric* step: an index type `S` of the right size
(`hS : (Fintype.card S : ℝ) = p^{p^α·β/2}`, the high-multiplicity polynomial-family index)
together with an **injection** `encode : S → (ι → F)` placing each member of the family at a
*distinct close codeword* (`hmaps` + `hinj`).  The cardinality arithmetic — that this forces
`≥ p^{p^α·β/2}` close codewords, hence the Ω-bound — is discharged here, axiom-clean, via
`Set.ncard_le_ncard_of_injOn`.  This pins the residual to its irreducible core: the
*existence* of the GHSZ02 high-multiplicity family as distinct close codewords. -/
theorem rs_lambda_large_prime_ghsz02_of_injection
    {ι : Type} [Fintype ι] [Nonempty ι] [DecidableEq ι]
    {F : Type} [Field F] [Fintype F] [DecidableEq F]
    (α β : ℝ) (p : ℕ) (hp1 : (1 : ℝ) ≤ p)
    (domain : ι ↪ F) (w : ι → F) (δ : ℝ)
    -- The GHSZ02 high-multiplicity family index, of the target cardinality.
    {S : Type} [Fintype S]
    (hS : (Fintype.card S : ℝ) = (p : ℝ) ^ ((p : ℝ) ^ α * β / 2))
    -- The genuine GHSZ02 Cor-20 geometric residual: the family lands injectively in the
    -- close-codeword set.
    (encode : S → (ι → F))
    (hmaps : ∀ s : S,
        encode s ∈
          closeCodewordsRel
            ((ReedSolomon.code domain (Nat.floor ((p : ℝ) ^ α)) : Set (ι → F))) w δ)
    (hinj : Function.Injective encode) :
    ∃ c : ℝ, 0 < c ∧
      ((closeCodewordsRel
          ((ReedSolomon.code domain (Nat.floor ((p : ℝ) ^ α)) : Set (ι → F))) w δ).ncard : ℝ) >
        c * (p : ℝ) ^ ((p : ℝ) ^ α * β / 2) := by
  -- `|S| ≤ |closeCodewords|` from the injection on the (finite) universe of `S`.
  have hncard_le :
      (Set.univ : Set S).ncard ≤
        (closeCodewordsRel
          ((ReedSolomon.code domain (Nat.floor ((p : ℝ) ^ α)) : Set (ι → F))) w δ).ncard :=
    Set.ncard_le_ncard_of_injOn encode (fun s _ => hmaps s)
      (fun a _ b _ h => hinj h) (Set.toFinite _)
  have hcount :
      (p : ℝ) ^ ((p : ℝ) ^ α * β / 2) ≤
        ((closeCodewordsRel
            ((ReedSolomon.code domain (Nat.floor ((p : ℝ) ^ α)) : Set (ι → F)))
              w δ).ncard : ℝ) := by
    rw [← hS]
    have huniv : (Set.univ : Set S).ncard = Fintype.card S := by
      rw [Set.ncard_univ, Nat.card_eq_fintype_card]
    rw [← huniv]; exact_mod_cast hncard_le
  exact rs_lambda_large_prime_ghsz02_of_residuals α β p hp1 domain w δ hcount

/-- **ABF26 Theorem 3.13 [GHSZ02 Cor 20].** Reed-Solomon large list-size over prime
fields. Fix `0 < α, β < 1`. For all sufficiently large primes `p`, there exists
`C := RS[F_p, F_p, ⌊p^α⌋]` and a word `w : F_p → F_p` such that:

  `|Λ(C, 1 - ((1-β)/α) · p^{α-1}, w)| > Ω(p^{p^α · β/2})`

**STATUS: PROVEN.** This front door is discharged as an in-tree, axiom-clean theorem:
`GHSZ02LargeNProof.rs_lambda_large_prime_ghsz02_proven` in
`ArkLib/ToMathlib/GHSZ02LargeNProof.lean` (the `GHSZ02LargeN` asymptotic ledger proven
from explicit thresholds via choose-symmetry + `Nat.pow_le_choose` + the `(1−1/p)^p`
brick; thresholds eventually satisfied by filter/tendsto compositions; uniform
Ω-constant `c = 1/2` through the in-tree `hcount_of_largeN` reduction).  The
`def : Prop` below is retained as the statement surface; the `_of_residuals`/injection
forms remain as intermediate API.  Historical context:
`research/formal/arklib-proof-research-2026-06.md`.

**HONEST REDUCTION AVAILABLE.** The Ω-constant + strict-inequality bookkeeping is fully
proven, `sorry`-free and axiom-clean, in `rs_lambda_large_prime_ghsz02_of_residuals`
(above), which derives the per-instance `> c · p^{p^α·β/2}` bound from the GHSZ02
high-multiplicity count `hcount` as an explicit hypothesis.

**RESIDUAL NARROWED.** `rs_lambda_large_prime_ghsz02_of_injection` (above) shrinks the
residual to its geometric core: it assumes only an index type `S` of cardinality
`p^{p^α·β/2}` (the high-multiplicity polynomial-family index) and an injection placing the
family at distinct close codewords, discharging *all* of the counting/Ω arithmetic in-tree
via `Set.ncard_le_ncard_of_injOn`. The statement below remains an external `Prop` only
because the *unhypothesized* in-tree statement cannot supply that high-multiplicity
construction nor the `p₀` threshold. -/
def rs_lambda_large_prime_ghsz02
    (α β : ℝ) (_hα_pos : 0 < α) (_hα_lt : α < 1) (_hβ_pos : 0 < β) (_hβ_lt : β < 1) :
    Prop :=
    ∃ (c : ℝ) (_ : 0 < c) (p₀ : ℕ),
      ∀ p : ℕ, Nat.Prime p → p₀ ≤ p →
        ∀ {ι : Type} [Fintype ι] [Nonempty ι] [DecidableEq ι]
          {F : Type} [Field F] [Fintype F] [DecidableEq F],
          Fintype.card F = p → Fintype.card ι = p →
          ∃ (domain : ι ↪ F) (w : ι → F),
            let k : ℕ := Nat.floor ((p : ℝ) ^ α)
            let δ : ℝ := 1 - ((1 - β) / α) * (p : ℝ) ^ (α - 1)
            let C := ReedSolomon.code domain k
            ((closeCodewordsRel ((C : Set (ι → F))) w δ).ncard : ℝ) >
              c * (p : ℝ) ^ ((p : ℝ) ^ α * β / 2)
  -- ABF26-T3.13; external statement [GHSZ02 Cor 20].
  -- Missing ingredient: GHSZ02's large RS list-size CONSTRUCTION over prime fields. Must
  -- exhibit, for all large primes p, an RS[F_p,F_p,⌊p^α⌋] and word w with > Ω(p^{p^α·β/2})
  -- close codewords. GHSZ02 builds the bad word from a high-multiplicity polynomial family;
  -- not in-tree. LOWER bound — genuinely external.

/-- **ABF26 Theorem 3.14 [JH01 Thm 2], repaired list-size form.** Large-rate
Reed-Solomon lower bound. Fix an integer `j ≥ 2`. For infinitely many prime-power
field sizes `q`, every field/domain pair with `|L| = j + 1` and `|F| = q` admits
`C := RS[F, L, j]` together with a word `w : L → F` such that:

  `|Λ(C, 1/(j+1), w)| > j`

Witnesses that high-rate RS codes cannot be list-decoded beyond `1/(j+1)` with list

**Statement repair.** The earlier formalization included the false conjunct
`Set.ncard C = j + 1`, confusing the size of the close list with the size of the entire
Reed-Solomon code. The theorem below records the actual JH01/ABF26 list-size separation
and is proved by the interpolation construction in `ListDecoding.JH01`. -/
theorem rs_lambda_high_rate_jh01
    (j : ℕ) (_hj_ge : 2 ≤ j) :
    ∃ qs : ℕ → ℕ, StrictMono qs ∧ (∀ i, IsPrimePow (qs i)) ∧
      ∀ i : ℕ,
        ∀ {ι : Type} [Fintype ι] [Nonempty ι] [DecidableEq ι]
          {F : Type} [Field F] [Fintype F] [DecidableEq F],
          Fintype.card F = qs i → Fintype.card ι = j + 1 →
          ∃ (domain : ι ↪ F) (w : ι → F),
            let C := ReedSolomon.code domain j
            (j : ℕ∞) < (closeCodewordsRel ((C : Set (ι → F))) w (1 / (j + 1 : ℝ))).ncard := by
  exact ReedSolomon.rs_lambda_high_rate_jh01 j _hj_ge

end ReedSolomonBounds

end CodingTheory

/-! ## Axiom audit (combinatorial-witness layer) -/
#print axioms CodingTheory.randomLinearLambdaLowerEvent_of_combinatorial
#print axioms CodingTheory.randomLinearLambdaLowerFirstMomentResidual_of_combinatorialWitness
#print axioms CodingTheory.combinatorialWitness_of_randomLinearLambdaLowerFirstMomentResidual
