/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import Mathlib
import ArkLib.Data.CodingTheory.ProximityGap.AdditiveEnergyResultant

/-!
# Divisibility-by-3 of the BGK prize kernel via an S₃ action (#232)

A second structural constraint on the open additive-energy intersection count
`M = bgkCount n = #{u ∈ μ_n : -(1+u) ∈ μ_n}`, complementing the parity of `AdditiveEnergyParity`.

The kernel carries an action of the symmetric group `S₃` generated by the two involutions
`ι(u) = u⁻¹` and `σ(u) = -(1+u)` (both preserve the kernel). Their product
`τ = ι ∘ σ : u ↦ -(1+u)⁻¹` has order 3 (a direct field computation `τ³ = id`), and its fixed points
are exactly the roots of `u² + u + 1 = 0` — the primitive cube roots of unity. When `char F ≠ 3` and
`3 ∤ n`, such a root would have order `3 ∣ gcd(3, n) = 1`, impossible, so `τ` is **fixed-point-free**
on the kernel. A fixed-point-free order-3 self-map partitions the kernel into 3-orbits, whence:

* `three_dvd_card_of_orderThree_free` — the general counting principle: a fixed-point-free `τ` with
  `τ³ = id` on a finite set `s` forces `3 ∣ |s|`.
* `three_dvd_bgkCount` — for `0 < n`, `3 ∤ n`, and `char F ≠ 3`, `3 ∣ bgkCount n`.
* `three_dvd_bgkCount_two_pow` — in particular `3 ∣ bgkCount (2^k)` whenever `char F ≠ 3`.

**Consequence (sharpens the cartography).** Combined with the parity result
(`AdditiveEnergyParity.odd_bgkCount_iff`: `M` is even unless `char F ∣ 2^n − 1`), for the smooth
domain `n = 2^k` and any `char F ∉ {3} ∪ {Fermat-bad primes}` we get `6 ∣ M`. So away from the
finitely many Fermat/`3` exceptional characteristics the kernel count is a multiple of 6 — a strong
constraint, though it still does not pin the *magnitude* of `M` (the open BGK/Bourgain core).
Axiom-clean.

## References
- [ABF26] Arnon, Boneh, Fenzi. *Open Problems in List Decoding and Correlated Agreement*. 2026.
  Tracking issue #232.
-/

open Finset Polynomial

namespace ArkLib.ProximityGap.AdditiveEnergyKernel

variable {F : Type*} [Field F] [DecidableEq F]

/-- **A fixed-point-free order-3 self-map forces `3 ∣ |s|`.** If `τ` maps `s` into itself, satisfies
`τ³ = id` on `s`, and has no fixed point in `s`, then `s` is partitioned into 3-orbits
`{x, τ x, τ² x}`, so `3 ∣ |s|`. -/
theorem three_dvd_card_of_orderThree_free {α : Type*} [DecidableEq α] (τ : α → α) :
    ∀ s : Finset α, (∀ x ∈ s, τ x ∈ s) → (∀ x ∈ s, τ (τ (τ x)) = x) →
      (∀ x ∈ s, τ x ≠ x) → 3 ∣ s.card := by
  intro s
  induction s using Finset.strongInductionOn with
  | _ s ih =>
    intro hmem hcube hfree
    rcases s.eq_empty_or_nonempty with rfl | ⟨x, hx⟩
    · simp
    have hinj : ∀ a ∈ s, ∀ b ∈ s, τ a = τ b → a = b := by
      intro a ha b hb hab
      have h : τ (τ (τ a)) = τ (τ (τ b)) := by rw [hab]
      rwa [hcube a ha, hcube b hb] at h
    have hτx : τ x ∈ s := hmem x hx
    have hττx : τ (τ x) ∈ s := hmem _ hτx
    have hne1 : τ x ≠ x := hfree x hx
    have hne2 : τ (τ x) ≠ x := fun h => hne1 (by have hc := hcube x hx; rw [h] at hc; exact hc)
    have hne3 : τ (τ x) ≠ τ x := fun h => hne1 (hinj (τ x) hτx x hx h)
    set s' := ((s.erase x).erase (τ x)).erase (τ (τ x)) with hs'
    have hsub : s' ⊂ s := by
      refine Finset.ssubset_of_subset_of_ssubset (Finset.erase_subset _ _) ?_
      exact Finset.ssubset_of_subset_of_ssubset (Finset.erase_subset _ _) (Finset.erase_ssubset hx)
    have hmem' : ∀ y ∈ s', τ y ∈ s' := by
      intro y hy
      rw [hs', Finset.mem_erase, Finset.mem_erase, Finset.mem_erase] at hy ⊢
      obtain ⟨hyττ, hyτ, hyx, hys⟩ := hy
      refine ⟨?_, ?_, ?_, hmem y hys⟩
      · intro h; exact hyτ (hinj y hys (τ x) hτx h)
      · intro h; exact hyx (hinj y hys x hx h)
      · intro h; exact hyττ (by have hc := hcube y hys; rw [h] at hc; exact hc.symm)
    have hmemS : ∀ y ∈ s', y ∈ s := fun y hy => by
      rw [hs'] at hy
      exact Finset.mem_of_mem_erase (Finset.mem_of_mem_erase (Finset.mem_of_mem_erase hy))
    have IH := ih s' hsub hmem' (fun y hy => hcube y (hmemS y hy)) (fun y hy => hfree y (hmemS y hy))
    have h3le : 3 ≤ s.card := by
      have hsub3 : ({x, τ x, τ (τ x)} : Finset α) ⊆ s := by
        intro z hz; simp only [Finset.mem_insert, Finset.mem_singleton] at hz
        rcases hz with rfl | rfl | rfl
        exacts [hx, hτx, hττx]
      have hc3 : ({x, τ x, τ (τ x)} : Finset α).card = 3 :=
        Finset.card_eq_three.mpr ⟨x, τ x, τ (τ x), hne1.symm, hne2.symm, hne3.symm, rfl⟩
      calc (3 : ℕ) = _ := hc3.symm
        _ ≤ s.card := Finset.card_le_card hsub3
    have hcard : s.card = s'.card + 3 := by
      rw [hs',
        Finset.card_erase_of_mem (Finset.mem_erase.mpr ⟨hne3, Finset.mem_erase.mpr ⟨hne2, hττx⟩⟩),
        Finset.card_erase_of_mem (Finset.mem_erase.mpr ⟨hne1, hτx⟩), Finset.card_erase_of_mem hx]
      omega
    rw [hcard]; omega

/-- **The kernel count is divisible by 3** (away from characteristic 3, when `3 ∤ n`). The order-3
map `τ(u) = -(1+u)⁻¹` (the product of the inversion and `u ↦ -(1+u)` involutions) is a
fixed-point-free self-map of the kernel, so the kernel splits into 3-orbits. -/
theorem three_dvd_bgkCount {n : ℕ} (hn : 0 < n) (hn3 : ¬ 3 ∣ n) (h3 : (3 : F) ≠ 0) :
    3 ∣ bgkCount (F := F) n := by
  set S := (nthRootsFinset n (1:F)).filter (fun u => -(1+u) ∈ nthRootsFinset n (1:F)) with hS
  have hbgk : bgkCount (F := F) n = S.card := rfl
  set τ : F → F := fun u => -(1 + u)⁻¹ with hτ
  -- extract the pointwise facts available on the kernel
  have hfacts : ∀ u ∈ S, u ^ n = 1 ∧ (-(1+u)) ^ n = 1 ∧ u ≠ 0 ∧ (1 + u) ≠ 0 := by
    intro u hu
    rw [hS, Finset.mem_filter] at hu
    obtain ⟨hu1, hu2⟩ := hu
    rw [mem_nthRootsFinset hn] at hu1 hu2
    have hune : u ≠ 0 := fun h => by rw [h, zero_pow hn.ne'] at hu1; exact zero_ne_one hu1
    have h1u : (1 + u) ≠ 0 := fun h => by
      rw [h, neg_zero, zero_pow hn.ne'] at hu2; exact zero_ne_one hu2
    exact ⟨hu1, hu2, hune, h1u⟩
  rw [hbgk]
  refine three_dvd_card_of_orderThree_free τ S ?_ ?_ ?_
  · -- closure
    intro u hu
    obtain ⟨hu1, hu2, hune, h1u⟩ := hfacts u hu
    rw [hS, Finset.mem_filter]
    have hτpow : (τ u) ^ n = 1 := by simp only [hτ]; rw [neg_inv, inv_pow, hu2, inv_one]
    have hid : -(1 + τ u) = u * τ u := by simp only [hτ]; field_simp; ring
    refine ⟨?_, ?_⟩
    · rw [mem_nthRootsFinset hn]; exact hτpow
    · rw [mem_nthRootsFinset hn, hid, mul_pow, hu1, hτpow, mul_one]
  · -- τ³ = id
    intro u hu
    obtain ⟨_, _, hune, h1u⟩ := hfacts u hu
    simp only [hτ]
    have hv : (1 : F) + (-(1 + u)⁻¹) = u / (1 + u) := by field_simp; ring
    rw [hv]
    have h2 : (u / (1 + u)) ≠ 0 := div_ne_zero hune h1u
    have hw : (1 : F) + (-(u / (1 + u))⁻¹) = -(1 / u) := by field_simp; ring
    rw [hw]; field_simp
  · -- fixed-point free
    intro u hu hcontra
    obtain ⟨hu1, _, hune, h1u⟩ := hfacts u hu
    simp only [hτ] at hcontra
    have huu : u ^ 2 + u + 1 = 0 := by
      have e1 : -(1 + u)⁻¹ * (1 + u) = u * (1 + u) := by rw [hcontra]
      rw [neg_mul, inv_mul_cancel₀ h1u] at e1
      linear_combination -e1
    have hu3 : u ^ 3 = 1 := by linear_combination (u - 1) * huu
    have hune1 : u ≠ 1 := by intro h; rw [h] at huu; apply h3; linear_combination huu
    have ho3 : orderOf u ∣ 3 := orderOf_dvd_of_pow_eq_one hu3
    have hon : orderOf u ∣ n := orderOf_dvd_of_pow_eq_one hu1
    have hco : Nat.Coprime 3 n := (Nat.prime_three.coprime_iff_not_dvd).mpr hn3
    have hord1 : orderOf u = 1 := Nat.dvd_one.mp (hco ▸ Nat.dvd_gcd ho3 hon)
    exact hune1 (orderOf_eq_one_iff.mp hord1)

/-- **The kernel count for the smooth domain `μ_{2^k}` is divisible by 3** (away from char 3). -/
theorem three_dvd_bgkCount_two_pow {k : ℕ} (h3 : (3 : F) ≠ 0) :
    3 ∣ bgkCount (F := F) (2 ^ k) := by
  refine three_dvd_bgkCount (Nat.two_pow_pos k) (fun hdvd => ?_) h3
  have h32 : (3 : ℕ) ∣ 2 := Nat.Prime.dvd_of_dvd_pow Nat.prime_three hdvd
  norm_num at h32

end ArkLib.ProximityGap.AdditiveEnergyKernel

#print axioms ArkLib.ProximityGap.AdditiveEnergyKernel.three_dvd_bgkCount
#print axioms ArkLib.ProximityGap.AdditiveEnergyKernel.three_dvd_bgkCount_two_pow
