/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import Mathlib.Algebra.Polynomial.Roots
import Mathlib.InformationTheory.Hamming
import Mathlib.Data.Finset.Card

/-!
# Explicit Reed–Solomon list lower bound on a codeword *line*, and where it lands (ABF26 #232)

This file attacks the **lower-bound** side of the open proximity-gap core (Issue #232): can one
*construct*, explicitly and verifiably, a received word `w` and a large family `L` of distinct
degree-`< k` Reed–Solomon codewords all within a fixed relative distance `δ` of `w`, with `δ`
**strictly inside** the open gap `(1 − √ρ, 1 − ρ)` at bounded field size?

We carry out the cleanest fully-explicit construction — the **codeword line**
`L = { lam · g : lam ∈ Λ }` for a fixed nonzero `g : F[X]` of degree `< k` with exactly `z` roots in
the evaluation domain `D` — and we **compute every relevant count exactly** in Lean:

* `line_codewords_card` — the list has size **exactly `|Λ|`** (distinct codewords): the map
  `lam ↦ (i ↦ (lam·g)(D i))` is injective on `Λ` once `g` is nonzero at some domain point. So with
  `Λ = F` the list can have size up to `|F|` (≈ `2^256`) — a genuine, NOT field-size-*capped*,
  super-polynomial-in-`n` list (it is in fact linear in `|F|`, the maximum conceivable list size).
* `line_member_dist_to_zero` — **every nonzero member is at Hamming distance exactly `n − z`** from
  the zero word `w = 0`, where `z = #{i : g(D i) = 0} ≤ k − 1`. So the *relative distance is exactly
  `δ = 1 − z/n`*.
* `line_member_pairwise_dist` — distinct members are pairwise at Hamming distance exactly `n − z`.

**Honest verdict (the obstruction, stated precisely and proven non-vacuously).**
Since `g` has degree `< k`, its domain-zero count satisfies `z ≤ k − 1`, hence the achieved relative
distance is `δ = 1 − z/n ≥ 1 − (k−1)/n`, which is **at or above the capacity edge `1 − ρ`** — the
*upper* boundary of the open gap — never strictly inside it (`line_agreement_le`). **Entering the
strict interior `δ < 1 − ρ` provably requires the target `w` to be a non-codeword on which each list
codeword agrees on `> k − 1` coordinates** — exactly the quantity that two distinct codewords can
never share, and for which no explicit smooth-domain construction is known. This file makes that
boundary fully explicit and verified: the line construction is a *maximal* (`|F|`-size) list, but it
saturates the **capacity edge**, not the interior.

All results are `sorry`-free and axiom-clean.
-/

namespace ArkLib.CodingTheory.GapLowerBound

open Finset Polynomial

variable {ι : Type*} [Fintype ι] [DecidableEq ι]
variable {F : Type*} [Field F] [Fintype F] [DecidableEq F]

/-- The Reed–Solomon codeword of `p` on domain `D : ι → F`. -/
def rsWord (D : ι → F) (p : F[X]) : ι → F := fun i => p.eval (D i)

/-- The **codeword line** generated by a fixed `g`, indexed by a scalar set `Λ`:
`L = { i ↦ (lam · g)(D i) : lam ∈ Λ }`. -/
noncomputable def lineList (D : ι → F) (g : F[X]) (Λ : Finset F) : Finset (ι → F) :=
  Λ.image (fun lam => rsWord D (Polynomial.C lam * g))

/-- The domain-zero set of `g`: coordinates `i` where `g(D i) = 0`. -/
def domainZeros (D : ι → F) (g : F[X]) : Finset ι :=
  Finset.univ.filter (fun i => g.eval (D i) = 0)

omit [Fintype ι] [DecidableEq ι] [Fintype F] [DecidableEq F] in
/-- **Evaluation of a scaled polynomial.** `(lam · g)(D i) = lam · g(D i)`. -/
lemma rsWord_C_mul (D : ι → F) (g : F[X]) (lam : F) (i : ι) :
    rsWord D (Polynomial.C lam * g) i = lam * g.eval (D i) := by
  simp [rsWord, Polynomial.eval_mul, Polynomial.eval_C]

omit [Fintype ι] [DecidableEq ι] [Fintype F] [DecidableEq F] in
/-- **Pointwise equality of two line members reduces to scalar agreement on the support of `g`.**
For a coordinate `i` with `g(D i) ≠ 0`, `(lam·g)(D i) = (mu·g)(D i) ↔ lam = mu`. -/
lemma line_eq_iff_scalar_eq (D : ι → F) (g : F[X]) {lam mu : F} (i : ι)
    (hg : g.eval (D i) ≠ 0) :
    rsWord D (Polynomial.C lam * g) i = rsWord D (Polynomial.C mu * g) i ↔ lam = mu := by
  rw [rsWord_C_mul, rsWord_C_mul]
  constructor
  · intro h; exact mul_right_cancel₀ hg h
  · intro h; rw [h]

omit [DecidableEq ι] [Fintype F] in
/-- **List size is exactly `|Λ|`.** As long as `g` is nonzero at some domain point `i₀`, the line
`{ lam·g : lam ∈ Λ }` has exactly `|Λ|` distinct codewords. With `Λ = F` this is `|F|` — a maximal,
*not field-size-capped*, list. -/
theorem line_codewords_card (D : ι → F) (g : F[X]) (Λ : Finset F)
    {i₀ : ι} (hg : g.eval (D i₀) ≠ 0) :
    (lineList D g Λ).card = Λ.card := by
  rw [lineList, Finset.card_image_of_injOn]
  intro lam _ mu _ h
  have := congrFun h i₀
  exact (line_eq_iff_scalar_eq D g i₀ hg).mp this

omit [DecidableEq ι] [Fintype F] in
/-- **Exact agreement of a nonzero line member with the zero word.** For `lam ≠ 0`, the codeword
`lam·g` agrees with `w = 0` *exactly* on the domain-zero set of `g`. Hence its agreement count with
the zero word is exactly `z = #{i : g(D i) = 0}`. -/
theorem line_member_agree_zero (D : ι → F) (g : F[X]) {lam : F} (hlam : lam ≠ 0) :
    (Finset.univ.filter
        (fun i => rsWord D (Polynomial.C lam * g) i = (fun _ => (0 : F)) i)).card
      = (domainZeros D g).card := by
  congr 1
  ext i
  simp only [domainZeros, Finset.mem_filter, Finset.mem_univ, true_and, rsWord_C_mul,
    mul_eq_zero]
  constructor
  · rintro (h | h)
    · exact absurd h hlam
    · exact h
  · intro h; exact Or.inr h

omit [Fintype F] in
/-- **Exact Hamming distance of a nonzero line member to the zero word.** For `lam ≠ 0`,
`hammingDist (lam·g) 0 = n − z`, where `n = |ι|` and `z = #{i : g(D i) = 0}`. So the *relative
distance is exactly `δ = 1 − z/n`*. -/
theorem line_member_dist_to_zero (D : ι → F) (g : F[X]) {lam : F} (hlam : lam ≠ 0) :
    hammingDist (rsWord D (Polynomial.C lam * g)) (fun _ => (0 : F))
      = Fintype.card ι - (domainZeros D g).card := by
  classical
  have hagree := line_member_agree_zero D g hlam
  have hsplit :
      (Finset.univ.filter
          (fun i => ¬ rsWord D (Polynomial.C lam * g) i = (fun _ => (0 : F)) i)).card
        = Fintype.card ι
          - (Finset.univ.filter
              (fun i => rsWord D (Polynomial.C lam * g) i = (fun _ => (0 : F)) i)).card := by
    rw [Finset.filter_not, Finset.card_sdiff_of_subset (Finset.filter_subset _ _),
      Finset.card_univ]
  simp only [hammingDist, ne_eq]
  rw [hsplit, hagree]

omit [Fintype F] in
/-- **Exact pairwise distance between distinct line members.** For `lam ≠ mu`, the codewords
`lam·g` and `mu·g` agree exactly on the domain zeros of `g`, hence are at Hamming distance
exactly `n − z`. -/
theorem line_member_pairwise_dist (D : ι → F) (g : F[X]) {lam mu : F} (hne : lam ≠ mu) :
    hammingDist (rsWord D (Polynomial.C lam * g)) (rsWord D (Polynomial.C mu * g))
      = Fintype.card ι - (domainZeros D g).card := by
  classical
  have hagree :
      (Finset.univ.filter
          (fun i => rsWord D (Polynomial.C lam * g) i = rsWord D (Polynomial.C mu * g) i)).card
        = (domainZeros D g).card := by
    congr 1
    ext i
    simp only [domainZeros, Finset.mem_filter, Finset.mem_univ, true_and, rsWord_C_mul]
    constructor
    · intro h
      by_contra hg
      exact hne (mul_right_cancel₀ hg h)
    · intro h; rw [h, mul_zero, mul_zero]
  have hsplit :
      (Finset.univ.filter
          (fun i => ¬ rsWord D (Polynomial.C lam * g) i
            = rsWord D (Polynomial.C mu * g) i)).card
        = Fintype.card ι
          - (Finset.univ.filter
              (fun i => rsWord D (Polynomial.C lam * g) i
                = rsWord D (Polynomial.C mu * g) i)).card := by
    rw [Finset.filter_not, Finset.card_sdiff_of_subset (Finset.filter_subset _ _),
      Finset.card_univ]
  simp only [hammingDist, ne_eq]
  rw [hsplit, hagree]

omit [DecidableEq ι] [Fintype F] in
/-- **The capacity-edge obstruction (root-count bound on the achievable agreement).** The
domain-zero count of any nonzero `g : F[X]` of degree `< k` evaluated on an injective domain is at
most `k − 1`. Therefore every line member is at Hamming distance `≥ n − (k − 1)` from the zero word,
i.e. relative distance `δ ≥ 1 − (k−1)/n ≥ 1 − ρ`: the line construction **saturates the capacity
edge, never the strict interior `δ < 1 − ρ`** of the open gap. -/
theorem line_agreement_le (D : ι ↪ F) {g : F[X]} {k : ℕ} (hg : g ≠ 0) (hdeg : g.natDegree < k) :
    (domainZeros (fun i => D i) g).card ≤ k - 1 := by
  classical
  set s := domainZeros (fun i => D i) g with hs
  have hmap : ∀ i ∈ s, D i ∈ g.roots.toFinset := by
    intro i hi
    rw [hs, domainZeros, Finset.mem_filter] at hi
    rw [Multiset.mem_toFinset, mem_roots hg, IsRoot.def]
    exact hi.2
  have hcard : s.card ≤ g.roots.toFinset.card :=
    Finset.card_le_card_of_injOn (fun i => D i) hmap (fun a _ b _ h => D.injective h)
  have hroots : g.roots.toFinset.card ≤ g.natDegree :=
    le_trans (Multiset.toFinset_card_le _) (card_roots' g)
  omega

/-- **Capstone: an explicit, maximal (`|F|`-size) RS codeword list at the *capacity edge*, fully
counted.** For any nonzero `g` of degree `< k` that is nonzero at some domain point `i₀` with `z`
domain-zeros, the line `{ lam·g : lam ∈ F }` is a set of **exactly `|F|` distinct codewords**, each
at Hamming distance **exactly `n − z`** from the zero word, with `z ≤ k − 1` (so
`n − z ≥ n − (k−1)`, the capacity-edge radius). This is a *genuine, non-field-size-capped* lower
bound — the list is as large as the field — but it lands at the capacity boundary `1 − ρ`, **not**
strictly inside the open gap. The strict-interior bound (`δ < 1 − ρ`, super-`ε*·|F|` list) is open;
no line / linear construction reaches it, because line members can only agree with the (codeword)
target on `g`'s `≤ k − 1` zeros. -/
theorem explicit_capacity_edge_list (D : ι ↪ F) {g : F[X]} {k : ℕ}
    (hg0 : g ≠ 0) (hdeg : g.natDegree < k) {i₀ : ι} (hi₀ : g.eval (D i₀) ≠ 0) :
    (lineList (fun i => D i) g Finset.univ).card = Fintype.card F ∧
    (∀ lam : F, lam ≠ 0 →
        hammingDist (rsWord (fun i => D i) (Polynomial.C lam * g)) (fun _ => (0 : F))
          = Fintype.card ι - (domainZeros (fun i => D i) g).card) ∧
    (domainZeros (fun i => D i) g).card ≤ k - 1 := by
  refine ⟨?_, ?_, line_agreement_le D hg0 hdeg⟩
  · rw [line_codewords_card (fun i => D i) g Finset.univ hi₀, Finset.card_univ]
  · intro lam hlam
    exact line_member_dist_to_zero (fun i => D i) g hlam

end ArkLib.CodingTheory.GapLowerBound

/-! ## Axiom audit -/
#print axioms ArkLib.CodingTheory.GapLowerBound.line_codewords_card
#print axioms ArkLib.CodingTheory.GapLowerBound.line_member_dist_to_zero
#print axioms ArkLib.CodingTheory.GapLowerBound.line_member_pairwise_dist
#print axioms ArkLib.CodingTheory.GapLowerBound.line_agreement_le
#print axioms ArkLib.CodingTheory.GapLowerBound.explicit_capacity_edge_list
