/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import ArkLib.Data.CodingTheory.ProximityGap.BoundarySupExactness

set_option maxHeartbeats 2000000

/-!
# An exact boundary-band MCA value over `F_19` (#389)

A new concrete instance of the boundary-band exactness law `rs_boundary_epsMCA_eq`
(`epsMCA = n/q` for `3 ∣ n`, `6 < n`, `k = n−4`, `2 ≤ δ·n < 3`), at the previously-untouched field
`q = 19`.  For the smooth Reed–Solomon code `RS[F_19, μ_9, 5]` (`μ_9` generated by the order-9
element `4 ∈ F_19`, `4^9 = 1`) at the boundary radius `δ = 2/9`:

> **`epsMCA_boundary_F19_n9`** — `epsMCA(RS[F_19, μ_9, 5], 2/9) = 9/19`.

This pins the first exact `n/q` boundary value at `q = 19`, a fresh field for the explosion-band law
(prior exact boundary/explosion values sit at `q ∈ {5, 13, 17}`).  Obtained by specializing the
proven generic sandwich `rs_boundary_epsMCA_eq` — **not** by an explicit bad-scalar enumeration
(the `C(9,5)² = 15876 > 19` regime makes the generic-far route inapplicable); the value is the MCA
*equality*, not a witness count.  Axiom-clean.
-/

open scoped NNReal ENNReal
open ProximityGap Code ProximityGap.CensusLowerBound ProximityGap.SmoothLadderInstance
  ProximityGap.MCAThresholdLedger ProximityGap.BoundarySupExactness

namespace ProximityGap.BoundaryExactEpsF19

instance : Fact (Nat.Prime 19) := ⟨by norm_num⟩

/-- **Exact boundary MCA value over `F_19`.**  For `RS[F_19, μ_9, 5]` (`μ_9 = ⟨4⟩`, `orderOf 4 = 9`)
at the boundary radius `δ = 2/9` (so `δ·n = 2 ∈ [2, 3)`), the boundary-band law gives
`epsMCA = n/q = 9/19`. -/
theorem epsMCA_boundary_F19_n9 :
    epsMCA (F := ZMod 19) (A := ZMod 19)
      (evalCode (smoothDom (4 : ZMod 19) 9) 5 : Set (Fin 9 → ZMod 19)) (2 / 9 : ℝ≥0)
      = (9 : ℝ≥0∞) / (19 : ℝ≥0∞) := by
  have hord : orderOf (4 : ZMod 19) = 9 := by
    rw [orderOf_eq_iff (by norm_num)]
    refine ⟨by decide, fun m hm hm0 => ?_⟩
    interval_cases m <;> decide
  have hval : (2 / 9 : ℝ≥0) * ((9 : ℕ) : ℝ≥0) = 2 := by
    rw [show ((9 : ℕ) : ℝ≥0) = 9 from by norm_num, div_mul_cancel₀]; norm_num
  have h := rs_boundary_epsMCA_eq (F := ZMod 19) (n := 9) (k := 5) (4 : ZMod 19) hord
    (by decide) (by norm_num) rfl (le_of_eq hval.symm) (by rw [hval]; norm_num)
  rw [h, ZMod.card]
  norm_num

end ProximityGap.BoundaryExactEpsF19
