/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import ArkLib.Data.CodingTheory.ProximityGap.CubicOrchardIdentity
import Mathlib.Tactic.NormNum.Prime

/-!
# A second deep-band supply zero: the cubic word on `μ_8 ⊂ F₇₃` (#389)

`CubicSupplyZeroNTT.lean` exhibits `x³` on `μ_16 ⊂ F₂₅₇` with exactly `0` explainable
`3`-cores — the deepest pre-capacity (agreement-`3`, sub-Johnson) supply hitting its floor,
because the char-`0` no-cube-root rigidity (`ThreeRootsSumZeroCharZero`, `3 ∤ n`) survives to
that prime.  This file lands the **second** such witness, at a different scale/prime:

> **`cubicSupply_mu8_F73_eq_zero`** — `x³` on `μ_8 ⊂ F₇₃` has **exactly `0`** explainable
> `3`-cores: no degree-`<2` codeword of `rsCode dom8 2` agrees with it on `3` points.  Via
> the cubic orchard identity this is the zero-sum-triple count, which is `0` — the char-`0`
> Mann rigidity (no three `8`-th roots of unity sum to zero, `3 ∤ 8`) lifts to `F₇₃`.

This is **sub-Johnson** content (agreement `3 < √(2·8) ≈ 4`, the Johnson radius for `k = 2`,
`n = 8`): at radius `5/8`, one step below the capacity radius `6/8`, the tower-shaped word
`x³` contributes *no* bad scalars over `F₇₃`.  The lift is prime-dependent — over `F₁₇` the
same subgroup has `24` zero-sum triples (the rigidity fails), the Mann–Conway–Jones height
phenomenon, matching the additive-energy contrast in `EnergyMinimalF73.lean`.  Issue #389.
-/

open Finset

namespace ProximityGap.PairRank

open ProximityGap.SpikeFloor ProximityGap ProximityGap.Ownership Code

local instance : Fact (Nat.Prime 73) := ⟨by norm_num⟩

/-- The eight `8`-th roots of unity in `F₇₃` (the order-8 subgroup, generated by `10`). -/
def mu8vals : Fin 8 → ZMod 73 := ![1, 10, 22, 27, 46, 51, 63, 72]

/-- The NTT evaluation domain `μ_8 ⊂ F₇₃` as an embedding (injective by `decide`). -/
def dom8 : Fin 8 ↪ ZMod 73 := ⟨mu8vals, by decide⟩

set_option maxHeartbeats 1000000 in
set_option maxRecDepth 100000 in
/-- The zero-sum-triple count of `μ_8 ⊂ F₇₃` is exactly `0`: no three of the eight `8`-th
roots of unity sum to zero in `F₇₃` (the char-`0` no-cube-root rigidity survives). -/
theorem mu8_F73_zeroSum_triples_eq_zero :
    (((Finset.univ : Finset (Fin 8)).powersetCard 3).filter
        (fun T => ∑ i ∈ T, dom8 i = 0)).card = 0 := by
  decide

open Classical in
/-- **A SECOND EXACT IN-WINDOW SUPPLY ZERO**: the cubic word `x³` on `μ_8 ⊂ F₇₃` has exactly
`0` explainable `3`-cores.  Via the cubic orchard identity, the zero-sum-triple count `= 0`. -/
theorem cubicSupply_mu8_F73_eq_zero :
    ((Finset.univ : Finset (Fin 8 → ZMod 73)).filter (fun c =>
        c ∈ (rsCode dom8 2 : Submodule (ZMod 73) (Fin 8 → ZMod 73))
          ∧ 3 ≤ (agreeSet c (fun i => (dom8 i) ^ 3)).card)).card = 0 := by
  rw [cubic_list_eq_zeroSum dom8]
  exact mu8_F73_zeroSum_triples_eq_zero

end ProximityGap.PairRank

-- Axiom audit (expected: propext, Classical.choice, Quot.sound only)
#print axioms ProximityGap.PairRank.mu8_F73_zeroSum_triples_eq_zero
#print axioms ProximityGap.PairRank.cubicSupply_mu8_F73_eq_zero
