/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import ArkLib.Data.CodingTheory.ProximityGap.MCABandTwoExact
import ArkLib.Data.CodingTheory.ProximityGap.MCADeltaStarExactPoint
import ArkLib.Data.CodingTheory.ProximityGap.MCAWitnessSpread
import Mathlib.LinearAlgebra.Lagrange

/-!
# The second exact δ* pin: `RS[F₁₇, ⟨2⟩, 4]` at a deployed rate (#357, C2-R)

The second machine-checked exact MCA-threshold value, for the smooth-domain
Reed–Solomon code `C = RS[F₁₇, ⟨2⟩, k = 4]` (domain = the order-8 subgroup of
`F₁₇ˣ` generated by 2, `n = 8 = 2³`, **rate ρ = 1/2 — a deployed rate**):

  `mcaDeltaStar C ε* = 1/4 = (1−ρ)/2`  for every `ε* ∈ [2/17, 3/17)`.

**Good side** (every `δ < 1/4`): covered entirely by the two universal staircase
theorems — `ε_mca = 1/17` on the first granularity band (`δ·n < 1`,
`epsMCA_eq_inv_card_of_small_radius`) and `= 2/17` on the second (`1 ≤ δ·n < 2`,
`epsMCA_eq_two_div_card_of_dist4`; the distance hypothesis holds since nonzero
cubics have at most 3 roots).  Both values are `≤ 2/17 ≤ ε*`.

**Bad side** (`δ = 1/4`): the explicit deviation stack
`u₀ = e₅`, `u₁ = (1,3,0,…,0)` (found by the exhaustive deviation-restricted probe
`probe_c2r_second_pin.py`, justified by `rows_close_of_two_bad`) has the three bad
scalars `γ ∈ {0, 5, 7}`, each certified by an explicit witness set and an explicit
cubic line-codeword; the joint clause fails because the would-be explanation of
`u₁` vanishes at four distinct domain points — forcing it to be the zero codeword,
contradicting `u₁(x₀) = 1`.  So `ε_mca(C, 1/4) ≥ 3/17 > ε*`.

Everything reduces to one root-counting lemma
(`Polynomial.eq_zero_of_degree_lt_of_eval_finset_eq_zero`); there is no `decide`
over coefficient tuples anywhere.  The staircase law C2-R (δ* = the unique-decoding
radius on the granularity window) is hereby confirmed at a second instance — second
field, second size, deployed rate.
-/

open Finset Polynomial
open scoped NNReal ENNReal ProbabilityTheory
open ProximityGap Code
open ProximityGap.MCAThresholdLedger
open ProximityGap.MCABandTwoCollapse

namespace ProximityGap.DeltaStarSecondPin

abbrev F17 := ZMod 17

instance : Fact (Nat.Prime 17) := ⟨by decide⟩

/-- The smooth domain: the order-8 subgroup `⟨2⟩ ≤ F₁₇ˣ`, enumerated as powers. -/
def dom : Fin 8 → F17 := ![1, 2, 4, 8, 16, 15, 13, 9]

/-- `dom` is injective (eight distinct field elements). -/
theorem dom_injective : Function.Injective dom := by decide

/-- `RS[F₁₇, dom, 4]`: evaluations of polynomials of degree `< 4`. -/
def C84 : Submodule F17 (Fin 8 → F17) where
  carrier := {w | ∃ P : Polynomial F17, P.degree < 4 ∧ w = fun i => P.eval (dom i)}
  zero_mem' := ⟨0, by rw [Polynomial.degree_zero]; decide, by funext i; simp⟩
  add_mem' := by
    rintro w w' ⟨P, hP, rfl⟩ ⟨Q, hQ, rfl⟩
    exact ⟨P + Q, lt_of_le_of_lt (Polynomial.degree_add_le P Q) (max_lt hP hQ),
      by funext i; simp⟩
  smul_mem' := by
    rintro c w ⟨P, hP, rfl⟩
    exact ⟨c • P, lt_of_le_of_lt (Polynomial.degree_smul_le c P) hP,
      by funext i; simp⟩

/-- **The root-counting kill.**  A codeword vanishing on a 4-element set of domain
values is zero (a nonzero cubic has at most 3 roots). -/
theorem codeword_eq_zero_of_vanishing (w : Fin 8 → F17) (hw : w ∈ C84)
    (s : Finset F17) (hs : 4 ≤ s.card) (hsub : ∀ x ∈ s, ∃ i, dom i = x ∧ w i = 0) :
    w = 0 := by
  obtain ⟨P, hP, rfl⟩ := hw
  have hPz : P = 0 := by
    refine Polynomial.eq_zero_of_degree_lt_of_eval_finset_eq_zero
      (f := P) (s := s) (lt_of_lt_of_le hP (by exact_mod_cast hs)) ?_
    intro x hx
    obtain ⟨i, hdi, hwi⟩ := hsub x hx
    rw [← hdi]
    exact hwi
  funext i
  simp [hPz]

/-- Cubic-by-coefficients membership helper. -/
theorem cubic_mem (a b c d : F17) :
    (fun i => a + b * dom i + c * dom i ^ 2 + d * dom i ^ 3) ∈ C84 := by
  refine ⟨C d * X ^ 3 + C c * X ^ 2 + C b * X + C a,
    lt_of_le_of_lt (Polynomial.degree_cubic_le) (by decide), ?_⟩
  funext i
  simp only [Polynomial.eval_add, Polynomial.eval_mul, Polynomial.eval_pow,
    Polynomial.eval_C, Polynomial.eval_X]
  ring

/-! ## The bad stack and its three certificates -/

/-- The deviation stack's first row: the spike at position 5. -/
def u₀ : Fin 8 → F17 := ![0, 0, 0, 0, 0, 1, 0, 0]

/-- The second row: weight-2 deviation `(1, 3, 0, …, 0)`. -/
def u₁ : Fin 8 → F17 := ![1, 3, 0, 0, 0, 0, 0, 0]

/-- The joint-failure engine: any explanation of `u₁` on a witness containing four
of its zero positions is the zero codeword — contradicting `u₁ 0 = 1` when the
witness also contains position `0`. -/
theorem no_joint_on (T : Finset (Fin 8)) (h0 : (0 : Fin 8) ∈ T)
    (i1 i2 i3 i4 : Fin 8) (hz : u₁ i1 = 0 ∧ u₁ i2 = 0 ∧ u₁ i3 = 0 ∧ u₁ i4 = 0)
    (hmem : i1 ∈ T ∧ i2 ∈ T ∧ i3 ∈ T ∧ i4 ∈ T)
    (hcard : ({dom i1, dom i2, dom i3, dom i4} : Finset F17).card = 4) :
    ¬ pairJointAgreesOn (C84 : Set (Fin 8 → F17)) T u₀ u₁ := by
  rintro ⟨v₀, hv₀, v₁, hv₁, hag⟩
  have hvz : v₁ = 0 := by
    refine codeword_eq_zero_of_vanishing v₁ hv₁ {dom i1, dom i2, dom i3, dom i4}
      (le_of_eq hcard.symm) ?_
    intro x hx
    simp only [Finset.mem_insert, Finset.mem_singleton] at hx
    rcases hx with rfl | rfl | rfl | rfl
    · exact ⟨i1, rfl, by rw [(hag i1 hmem.1).2, hz.1]⟩
    · exact ⟨i2, rfl, by rw [(hag i2 hmem.2.1).2, hz.2.1]⟩
    · exact ⟨i3, rfl, by rw [(hag i3 hmem.2.2.1).2, hz.2.2.1]⟩
    · exact ⟨i4, rfl, by rw [(hag i4 hmem.2.2.2).2, hz.2.2.2]⟩
  have h1 := (hag 0 h0).2
  rw [hvz] at h1
  exact absurd h1.symm (by decide)

/-- The size clause at `δ = 1/4`, `n = 8`: a 6-element witness suffices. -/
theorem card_clause {T : Finset (Fin 8)} (hT : T.card = 6) :
    (T.card : ℝ≥0) ≥ (1 - (1/4 : ℝ≥0)) * (Fintype.card (Fin 8) : ℝ≥0) := by
  have h14 : (1/4 : ℝ≥0) ≤ 1 := by
    rw [div_le_one (by norm_num : (0:ℝ≥0) < 4)]
    norm_num
  have h34 : (1 : ℝ≥0) - 1/4 = 3/4 := by
    rw [tsub_eq_iff_eq_add_of_le h14]
    rw [← NNReal.coe_inj]
    push_cast
    norm_num
  rw [hT, h34, Fintype.card_fin]
  norm_num

/-- **Certificate γ = 0**: witness `{0,1,2,3,4,6}`, line codeword `0`. -/
theorem cert0 : mcaEvent (F := F17) (C84 : Set (Fin 8 → F17)) (1/4) u₀ u₁ 0 := by
  refine ⟨{0, 1, 2, 3, 4, 6}, card_clause (by decide), ⟨0, C84.zero_mem, ?_⟩, ?_⟩
  · intro i hi
    fin_cases hi <;> decide
  · exact no_joint_on _ (by decide) 2 3 4 6 (by decide)
      ⟨by decide, by decide, by decide, by decide⟩ (by decide)

/-- **Certificate γ = 5**: witness `{0,1,3,4,5,6}`, line codeword the cubic
`12 + 5x + 16x² + 6x³`. -/
theorem cert5 : mcaEvent (F := F17) (C84 : Set (Fin 8 → F17)) (1/4) u₀ u₁ 5 := by
  refine ⟨{0, 1, 3, 4, 5, 6}, card_clause (by decide),
    ⟨_, cubic_mem 12 5 16 6, ?_⟩, ?_⟩
  · intro i hi
    fin_cases hi <;> decide
  · exact no_joint_on _ (by decide) 3 4 5 6 (by decide)
      ⟨by decide, by decide, by decide, by decide⟩ (by decide)

/-- **Certificate γ = 7**: witness `{0,1,2,4,5,7}`, line codeword the cubic
`1 + 3x + 11x² + 9x³`. -/
theorem cert7 : mcaEvent (F := F17) (C84 : Set (Fin 8 → F17)) (1/4) u₀ u₁ 7 := by
  refine ⟨{0, 1, 2, 4, 5, 7}, card_clause (by decide),
    ⟨_, cubic_mem 1 3 11 9, ?_⟩, ?_⟩
  · intro i hi
    fin_cases hi <;> decide
  · exact no_joint_on _ (by decide) 2 4 5 7 (by decide)
      ⟨by decide, by decide, by decide, by decide⟩ (by decide)

/-- **Bad side:** `ε_mca(C, 1/4) ≥ 3/17`. -/
theorem epsMCA_quarter_ge :
    (3 / 17 : ℝ≥0∞) ≤ epsMCA (F := F17) (A := F17) (C84 : Set (Fin 8 → F17)) (1/4) := by
  have h := ProximityGap.MCAWitnessSpread.epsMCA_ge_card_div_of_mcaEvent_set
    (C84 : Set (Fin 8 → F17)) (1/4) ![u₀, u₁] ({0, 5, 7} : Finset F17) ?_
  · have hcard : ({0, 5, 7} : Finset F17).card = 3 := by decide
    have hF : (Fintype.card F17 : ℝ≥0∞) = 17 := by
      rw [show Fintype.card F17 = 17 from by simp [ZMod.card]]
      norm_num
    rwa [hcard, hF] at h
  · intro γ hγ
    fin_cases hγ
    · simpa using cert0
    · simpa using cert5
    · simpa using cert7

/-! ## The good side: the two staircase bands -/

/-- `C84` is not the whole space: `u₁` is not a codeword (it vanishes at four
domain points yet is nonzero). -/
theorem C84_ne_univ : (C84 : Set (Fin 8 → F17)) ≠ Set.univ := by
  intro h
  have hu : u₁ ∈ C84 := by
    have hmem : u₁ ∈ (C84 : Set (Fin 8 → F17)) := by
      rw [h]
      trivial
    exact hmem
  have := codeword_eq_zero_of_vanishing u₁ hu {dom 2, dom 3, dom 4, dom 6}
    (by decide) ?_
  · exact absurd (congrFun this 0) (by decide)
  · intro x hx
    simp only [Finset.mem_insert, Finset.mem_singleton] at hx
    rcases hx with rfl | rfl | rfl | rfl
    exacts [⟨2, rfl, by decide⟩, ⟨3, rfl, by decide⟩, ⟨4, rfl, by decide⟩,
      ⟨6, rfl, by decide⟩]

/-- `C84` has no nonzero codeword supported on `≤ 3` positions (distance `≥ 5 > 4`). -/
theorem C84_noLowWeight : NoLowWeight C84 := by
  intro w hw ⟨T, hT, hvan⟩
  -- w vanishes off T; pick four positions outside T
  have hcompl : 5 ≤ (Finset.univ \ T).card := by
    have := Finset.card_sdiff_add_card_inter Finset.univ T
    have hTuniv : (Finset.univ ∩ T).card ≤ 3 :=
      le_trans (Finset.card_le_card (Finset.inter_subset_right)) hT
    have huniv : (Finset.univ : Finset (Fin 8)).card = 8 := by decide
    omega
  refine codeword_eq_zero_of_vanishing w hw ((Finset.univ \ T).image dom) ?_ ?_
  · rw [Finset.card_image_of_injective _ dom_injective]
    omega
  · intro x hx
    obtain ⟨i, hi, rfl⟩ := Finset.mem_image.mp hx
    exact ⟨i, rfl, hvan i (Finset.mem_sdiff.mp hi).2⟩

/-- **Good side:** `ε_mca(C, δ) ≤ 2/17` for every `δ < 1/4` (bands 1 and 2 of the
universal staircase). -/
theorem epsMCA_le_of_lt_quarter {δ : ℝ≥0} (hδ : δ < 1/4) :
    epsMCA (F := F17) (A := F17) (C84 : Set (Fin 8 → F17)) δ ≤ 2 / 17 := by
  have hcard8 : (Fintype.card (Fin 8) : ℝ≥0) = 8 := by
    rw [Fintype.card_fin]
    norm_num
  have hF : (Fintype.card F17 : ℝ≥0∞) = 17 := by
    rw [show Fintype.card F17 = 17 from by simp [ZMod.card]]
    norm_num
  have hδ2 : δ * (Fintype.card (Fin 8) : ℝ≥0) < 2 := by
    rw [hcard8]
    calc δ * 8 < (1/4) * 8 := by gcongr
      _ = 2 := by norm_num
  by_cases h1 : δ * (Fintype.card (Fin 8) : ℝ≥0) < 1
  · rw [ProximityGap.MCADeltaStarExactPoint.epsMCA_eq_inv_card_of_small_radius
      C84 h1 C84_ne_univ, hF]
    exact ENNReal.div_le_div_right (by norm_num : (1:ℝ≥0∞) ≤ 2) 17
  · push Not at h1
    rw [ProximityGap.MCABandTwoExact.epsMCA_eq_two_div_card_of_dist4 C84
      C84_noLowWeight (by rw [Fintype.card_fin]; norm_num) h1 hδ2
      (show (0 : Fin 8) ≠ 1 by decide) (show (1 : F17) ≠ 0 by decide), hF]

/-! ## The pin -/

/-- **THE SECOND PIN.**  For `C = RS[F₁₇, ⟨2⟩, 4]` (smooth domain `n = 8 = 2³`,
rate `ρ = 1/2`) and every `ε* ∈ [2/17, 3/17)`:

  `mcaDeltaStar C ε* = 1/4 = (1 − ρ)/2`.

Confirms the granularity-ladder law (C2-R) at a second instance, deployed rate. -/
theorem mcaDeltaStar_C84_eq_quarter {εstar : ℝ≥0∞}
    (hlo : 2/17 ≤ εstar) (hhi : εstar < 3/17) :
    MCAThresholdLedger.mcaDeltaStar (F := F17) (A := F17)
      (C84 : Set (Fin 8 → F17)) εstar = 1/4 := by
  refine le_antisymm
    (MCAThresholdLedger.mcaDeltaStar_le_of_bad _ _
      (lt_of_lt_of_le hhi epsMCA_quarter_ge)) ?_
  by_contra h
  push Not at h
  obtain ⟨c, hc1, hc2⟩ := exists_between h
  have hmem : c ∈ MCAThresholdLedger.mcaGoodRadii (F := F17) (A := F17)
      (C84 : Set (Fin 8 → F17)) εstar := by
    have hq1 : (1/4 : ℝ≥0) ≤ 1 := by
      rw [div_le_one (by norm_num : (0:ℝ≥0) < 4)]
      norm_num
    refine ⟨le_of_lt (lt_of_lt_of_le hc2 hq1), ?_⟩
    exact le_trans (epsMCA_le_of_lt_quarter hc2) hlo
  have hle := MCAThresholdLedger.le_mcaDeltaStar_of_good (F := F17) (A := F17)
    (C84 : Set (Fin 8 → F17)) εstar hmem.1 hmem.2
  exact absurd hle (not_le.mpr hc1)

end ProximityGap.DeltaStarSecondPin

-- Axiom audit (expected: propext, Classical.choice, Quot.sound only)
#print axioms ProximityGap.DeltaStarSecondPin.epsMCA_quarter_ge
#print axioms ProximityGap.DeltaStarSecondPin.epsMCA_le_of_lt_quarter
#print axioms ProximityGap.DeltaStarSecondPin.mcaDeltaStar_C84_eq_quarter
