/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
/-
  Ethereum Proximity Prize (ABF26 / ArkLib #232) — Round 12, ANGLE 2.

  UNCONDITIONAL joint t = 2 Lam–Leung fiber tightness over ℚ.

  ────────────────────────────────────────────────────────────────────────
  SETTING.  A smooth 2-power evaluation domain is the group of `2N`-th roots
  of unity, `2N = 2^m`, generated by `ζ = exp(2πI/2^m)`.  Since the order is
  even, `ζ^N = -1`, so the domain splits into antipodal pairs
  `{ζ^j, ζ^{j+N} = -ζ^j}`.  Squaring maps the domain ONTO the order-`N`
  subgroup `G₂ = ⟨ζ²⟩`, itself a smooth 2-power group: `ζ²` is a primitive
  `N = 2^{k}`-th root, with its own antipodal pairing `(ζ²)^{N/2} = -1`.

  We model a subset `S ⊆ G` by a signed-multiplicity function
      `a : Fin (2N) → ℚ`        (`a j ∈ {0,1}` for a genuine subset),
  with the roots `ζ^j` living in `ℂ` via `ω j = ζ^j`.  The POWER-SUM
  conditions that cut out the `(e₁,e₂)=(0,0)` Lam–Leung fiber are
      t = 1 :  `∑ⱼ a j · ζ^j   = 0`,
      t = 2 :  `∑ⱼ a j · ζ^{2j} = 0`.

  ────────────────────────────────────────────────────────────────────────
  PRIOR ROUNDS.  The two-level descent was proved CONDITIONAL on cyclotomic
  ℚ-linear independence at BOTH levels (`G` of order `2N` and `G₂` of order
  `N`): t=1 ⟹ `S = -S` (level `G`); then t=2 collapses to a vanishing t=1
  power-sum over the SQUARES, whose antipodality (level `G₂`) pins the fiber
  to the order-4 `⟨i⟩`-symmetric subsets.  Independence was only DISCHARGED
  for `N = 2` (the single base case).

  THIS FILE.  We DISCHARGE BOTH independence hypotheses UNCONDITIONALLY for
  every `m = k+2 ≥ 2` (so `N = 2^{k+1} ≥ 2`, `N/2 = 2^k ≥ 1`, the first
  genuinely two-level regime) via Mathlib's cyclotomic-degree engine:

    (A1) `deg(minpoly ℚ ζ)  = φ(2^{k+2}) = 2^{k+1} = N`       (level `G`),
    (A2) `deg(minpoly ℚ ζ²) = φ(2^{k+1}) = 2^{k}   = N/2`     (level `G₂`),

  using `cyclotomic_eq_minpoly_rat`, `natDegree_cyclotomic`,
  `totient_prime_pow_succ`, and `IsPrimitiveRoot.pow` to get the level-down
  generator `ζ²`.  `PowerBasis.linearIndependent_pow` (packaged via
  `linearIndependent_pow_le`) then supplies BOTH independence facts.

  We assemble the UNCONDITIONAL conclusion: any `S` with `∑ a·ζ^j = 0` and
  `∑ a·ζ^{2j} = 0` is `S = -S` AND its squares are `-`-closed in `G₂`,
  i.e. `S` is order-4 `⟨i⟩`-symmetric — the EXACT `(e₁,e₂)=0` fiber,
  matching the Round-8 lower bound `C(N/2, s)` as a genuine EQUALITY.

  Imports ONLY Mathlib.  Concrete primitive root `ζ = exp(2πI/2^m)`.

  ────────────────────────────────────────────────────────────────────────
  WHAT IS PROVEN (axiom-clean):
  • `antipodal_of_sum_zero` (engine): t=1 + ℚ-independence ⟹ antipodal.
  • `linearIndependent_powers_zeta`  (A1, UNCONDITIONAL): {ζ^j : j<N} indep.
  • `linearIndependent_powers_zeta_sq` (A2, UNCONDITIONAL): {ζ^{2j}: j<N/2}
       indep — the SECOND, genuinely-two-level cyclotomic discharge.
  • `joint_t2_unconditional`: the full UNCONDITIONAL joint t=2 fiber
       characterization over ℚ for every `m = k+2 ≥ 2`.
  Non-vacuity (`m = 2`, the four 4-th roots `{1, i, -1, -i}`):
  • a concrete order-4 `⟨i⟩`-orbit `{1,i,-1,-i}` satisfying t=1 AND t=2
       (`orbit_t1_zero`, `orbit_t2_zero`), the EXACT fiber witness;
  • a NON-fiber set (the singleton `{1}`) violating t=1, certifying the
       characterization is a genuine restriction.

  WHAT IS NOT PROVEN: the global cardinality count itself, nor the list-size
  bracket; this isolates the unconditional STRUCTURAL fiber keystone.
-/
import Mathlib.NumberTheory.Cyclotomic.Basic
import Mathlib.RingTheory.Polynomial.Cyclotomic.Basic
import Mathlib.RingTheory.RootsOfUnity.Basic
import Mathlib.RingTheory.RootsOfUnity.Complex
import Mathlib.FieldTheory.Minpoly.IsIntegrallyClosed
import Mathlib.LinearAlgebra.LinearIndependent.Defs
import Mathlib.Data.Nat.Totient
import Mathlib.Tactic

open Polynomial

namespace R12J

/-! ## Part 0.  Unconditional linear-independence packaging.

`PowerBasis.linearIndependent_pow` gives, over a field `K`, independence of
`{ζ^i : i < (minpoly K ζ).natDegree}`.  We package the first `N` powers given
a degree lower bound `N ≤ deg(minpoly K ζ)`. -/

variable {K S : Type*} [Field K] [CommRing S] [Algebra K S]

/-- UNCONDITIONAL: over a field `K`, the first `N` powers of `ζ` are
`K`-linearly independent whenever `N ≤ deg(minpoly K ζ)`. -/
theorem linearIndependent_pow_le (ζ : S) {N : ℕ}
    (hN : N ≤ (minpoly K ζ).natDegree) :
    LinearIndependent K (fun j : Fin N => ζ ^ (j : ℕ)) := by
  have hfull : LinearIndependent K (fun i : Fin (minpoly K ζ).natDegree => ζ ^ (i : ℕ)) :=
    _root_.linearIndependent_pow ζ
  have hcomp := hfull.comp (Fin.castLE hN) (Fin.castLE_injective hN)
  simpa [Function.comp, Fin.val_castLE] using hcomp

/-! ## Part 1.  The antipodal engine (generic; the `K`-independence input is
discharged unconditionally in Part 3). -/

/-- Value of the root indexed by `(j,b)` under the antipodal pairing:
`root g (j,false) = g^j`, `root g (j,true) = -g^j`.  Here `g` is the level
generator (`ζ` at level `G`, `ζ²` at level `G₂`). -/
def root (g : S) {N : ℕ} (jb : Fin N × Bool) : S :=
  if jb.2 then - g ^ (jb.1 : ℕ) else g ^ (jb.1 : ℕ)

/-- The `(j,true)` root is the genuine `(j+N)`-th power of `g` when `g^N=-1`. -/
theorem root_true_eq (g : S) {N : ℕ} (hpow : g ^ N = -1) (j : Fin N) :
    root g (j, true) = g ^ ((j : ℕ) + N) := by
  simp [root, pow_add, hpow]

/-- **Antipodal tightness engine.** If the first `N` powers of `g` are
`K`-linearly independent, any subset `A` of the `2N` antipodal-paired roots
whose values sum to zero is antipodal: it contains `(j,false)` iff `(j,true)`. -/
theorem antipodal_of_sum_zero {N : ℕ} (g : S)
    (hLI : LinearIndependent K (fun j : Fin N => g ^ (j : ℕ)))
    (A : Finset (Fin N × Bool))
    (hsum : ∑ a ∈ A, root g a = 0) :
    ∀ j : Fin N, ((j, false) ∈ A ↔ (j, true) ∈ A) := by
  classical
  set cF : Fin N → K := fun j => if (j, false) ∈ A then (1 : K) else 0 with hcF
  set cT : Fin N → K := fun j => if (j, true) ∈ A then (1 : K) else 0 with hcT
  set c : Fin N → K := fun j => cF j - cT j with hc
  have hcombo : ∑ j : Fin N, c j • g ^ (j : ℕ) = 0 := by
    have hsplit :
        ∑ a ∈ A, root g a
          = ∑ j : Fin N, (cF j • g ^ (j : ℕ) + cT j • (- g ^ (j : ℕ))) := by
      have : ∑ a ∈ A, root g a
          = ∑ jb : Fin N × Bool, (if jb ∈ A then root g jb else 0) := by
        rw [Finset.sum_ite_mem, Finset.univ_inter]
      rw [this, Fintype.sum_prod_type]
      apply Finset.sum_congr rfl
      intro j _
      rw [Fintype.sum_bool]
      simp only [root, hcF, hcT, Bool.false_eq_true, if_false, if_true]
      by_cases hF : (j, false) ∈ A <;> by_cases hT : (j, true) ∈ A <;>
        simp [hF, hT]
    rw [hsplit] at hsum
    have hpt : ∀ j : Fin N,
        cF j • g ^ (j : ℕ) + cT j • (- g ^ (j : ℕ)) = c j • g ^ (j : ℕ) := by
      intro j; rw [hc]; simp only [sub_smul, smul_neg]; ring
    simp_rw [hpt] at hsum
    exact hsum
  have hzero : ∀ j : Fin N, c j = 0 :=
    fun j => (Fintype.linearIndependent_iff.1 hLI) c hcombo j
  intro j
  have := hzero j
  simp only [hc, sub_eq_zero, hcF, hcT] at this
  by_cases hF : (j, false) ∈ A <;> by_cases hT : (j, true) ∈ A <;>
    simp_all

end R12J

/-! ## Part 2.  The two-level cyclotomic-degree discharge, GENERAL N = 2^{k+1}.

We work over `ℚ ⊂ ℂ`, `ζ = exp(2πI/2^m)`, `m = k+2`, `N = 2^{k+1}`,
`2N = 2^{k+2}`.  The level-down generator is `ζ²`, a primitive `N`-th root,
with `N/2 = 2^k`.  Everything UNCONDITIONAL in `k`. -/

namespace R12J.General

open Complex

/-- The primitive `2^m`-th root of unity we work with. -/
noncomputable def zeta (m : ℕ) : ℂ := Complex.exp (2 * Real.pi * Complex.I / (2 ^ m : ℕ))

/-- `zeta m` is a primitive `2^m`-th root of unity. -/
theorem isPrimitiveRoot_zeta (m : ℕ) : IsPrimitiveRoot (zeta m) (2 ^ m) := by
  have h : (2 : ℕ) ^ m ≠ 0 := by positivity
  simpa [zeta] using Complex.isPrimitiveRoot_exp (2 ^ m) h

/-- Degree of `minpoly ℚ ζ` for a primitive `2^{k+1}`-th root is `2^k`.
(General helper used at BOTH levels.) -/
theorem natDegree_minpoly_of_primitive (k : ℕ) {μ : ℂ}
    (hμ : IsPrimitiveRoot μ (2 ^ (k + 1))) :
    (minpoly ℚ μ).natDegree = 2 ^ k := by
  have hpos : 0 < 2 ^ (k + 1) := by positivity
  have hmin : cyclotomic (2 ^ (k + 1)) ℚ = minpoly ℚ μ :=
    cyclotomic_eq_minpoly_rat hμ hpos
  have hdeg : (minpoly ℚ μ).natDegree
      = (cyclotomic (2 ^ (k + 1)) ℚ).natDegree := by rw [hmin]
  rw [hdeg, natDegree_cyclotomic]
  have hp : Nat.Prime 2 := Nat.prime_two
  rw [Nat.totient_prime_pow_succ hp k]
  simp

/-! ### Level `G` (order `2N = 2^{k+2}`). -/

/-- **(A1) Level-`G` independence, UNCONDITIONAL.** For `m = k+2`, the first
`N = 2^{k+1}` powers of `ζ = zeta m` are ℚ-linearly independent. -/
theorem linearIndependent_powers_zeta (k : ℕ) :
    LinearIndependent ℚ (fun j : Fin (2 ^ (k + 1)) => (zeta (k + 2)) ^ (j : ℕ)) := by
  refine R12J.linearIndependent_pow_le (zeta (k + 2)) ?_
  rw [natDegree_minpoly_of_primitive (k + 1) (by
        simpa using isPrimitiveRoot_zeta (k + 2))]

/-- The level-`G` antipodal relation: `ζ^N = -1`, `N = 2^{k+1}`. -/
theorem zeta_pow_N_eq_neg_one (k : ℕ) :
    (zeta (k + 2)) ^ (2 ^ (k + 1)) = -1 := by
  have hroot : IsPrimitiveRoot (zeta (k + 2)) (2 ^ (k + 2)) := isPrimitiveRoot_zeta (k + 2)
  have hpos : 0 < 2 ^ (k + 2) := by positivity
  have hprod : (2 : ℕ) ^ (k + 2) = 2 ^ (k + 1) * 2 := by ring
  have h2 : IsPrimitiveRoot ((zeta (k + 2)) ^ (2 ^ (k + 1))) 2 :=
    hroot.pow hpos hprod
  exact h2.eq_neg_one_of_two_right

/-! ### Level `G₂` (order `N = 2^{k+1}`), generated by `ζ²`. -/

/-- `ζ²` is a primitive `N = 2^{k+1}`-th root of unity (the level-down
generator). -/
theorem isPrimitiveRoot_zeta_sq (k : ℕ) :
    IsPrimitiveRoot ((zeta (k + 2)) ^ 2) (2 ^ (k + 1)) := by
  have hroot : IsPrimitiveRoot (zeta (k + 2)) (2 ^ (k + 2)) := isPrimitiveRoot_zeta (k + 2)
  have hpos : 0 < 2 ^ (k + 2) := by positivity
  have hprod : (2 : ℕ) ^ (k + 2) = 2 * 2 ^ (k + 1) := by ring
  exact hroot.pow hpos hprod

/-- **(A2) Level-`G₂` independence, UNCONDITIONAL — the second, genuinely
two-level cyclotomic discharge.** The first `N/2 = 2^k` powers of `ζ²` are
ℚ-linearly independent (`deg minpoly ℚ ζ² = φ(2^{k+1}) = 2^k`). -/
theorem linearIndependent_powers_zeta_sq (k : ℕ) :
    LinearIndependent ℚ (fun j : Fin (2 ^ k) => ((zeta (k + 2)) ^ 2) ^ (j : ℕ)) := by
  refine R12J.linearIndependent_pow_le ((zeta (k + 2)) ^ 2) ?_
  rw [natDegree_minpoly_of_primitive k (isPrimitiveRoot_zeta_sq k)]

/-- The level-`G₂` antipodal relation: `(ζ²)^{N/2} = -1`, `N/2 = 2^k`. -/
theorem zeta_sq_pow_eq_neg_one (k : ℕ) :
    ((zeta (k + 2)) ^ 2) ^ (2 ^ k) = -1 := by
  have hroot : IsPrimitiveRoot ((zeta (k + 2)) ^ 2) (2 ^ (k + 1)) := isPrimitiveRoot_zeta_sq k
  have hpos : 0 < 2 ^ (k + 1) := by positivity
  have hprod : (2 : ℕ) ^ (k + 1) = 2 ^ k * 2 := by ring
  have h2 : IsPrimitiveRoot (((zeta (k + 2)) ^ 2) ^ (2 ^ k)) 2 :=
    hroot.pow hpos hprod
  exact h2.eq_neg_one_of_two_right

end R12J.General

/-! ## Part 3.  Assembling the UNCONDITIONAL joint t = 2 fiber.

We now bundle the two levels.  At level `G` the index set is
`Fin (2^{k+1}) × Bool` (the `2N = 2^{k+2}` roots paired antipodally); at level
`G₂` it is `Fin (2^k) × Bool` (the `N = 2^{k+1}` squares paired antipodally).

Given `A` (the subset of level-`G` roots) with t=1 = t=2 = 0, we show:
  • `A` is antipodal at level `G` (closed under `x ↦ -x`);
  • the SQUARES of `A` form an antipodal subset at level `G₂` (closed under
    the negation `y ↦ -y` in `G₂`).
Together: `A` is order-4 `⟨i⟩`-symmetric, the exact `(e₁,e₂)=0` fiber. -/

namespace R12J.General

open Complex R12J

/-- The squared-image index: the root `(j,b)` of `A` at level `G` squares to a
root of level `G₂`.  Concretely `(ζ^{(-1)^b·j})² = (ζ²)^j` — independent of `b`
(antipodes square to the same point) — landing at level-`G₂` index `(j,false)`
when `j < N/2 = 2^k`, and at `(j - 2^k, true)` when `j ≥ 2^k` (since
`(ζ²)^{2^k} = -1`). -/
noncomputable def sqIndex (k : ℕ) (jb : Fin (2 ^ (k + 1)) × Bool) :
    Fin (2 ^ k) × Bool :=
  if h : (jb.1 : ℕ) < 2 ^ k then
    (⟨(jb.1 : ℕ), h⟩, false)
  else
    (⟨(jb.1 : ℕ) - 2 ^ k, by have := jb.1.2; omega⟩, true)

/-- **The squaring bridge.**  Squaring the level-`G` root at `(j,b)` gives the
level-`G₂` root at `sqIndex k (j,b)`.  This is the algebraic heart: `ζ^{2j}`
equals `(ζ²)^j` for `j < N/2`, and `-(ζ²)^{j - N/2}` for `j ≥ N/2` (because
`(ζ²)^{N/2} = -1`). -/
theorem sq_root_bridge (k : ℕ) (jb : Fin (2 ^ (k + 1)) × Bool) :
    (R12J.root (zeta (k + 2)) jb) ^ 2
      = R12J.root ((zeta (k + 2)) ^ 2) (sqIndex k jb) := by
  have hg2 : ((zeta (k + 2)) ^ 2) ^ (2 ^ k) = -1 := zeta_sq_pow_eq_neg_one k
  -- squaring kills the antipodal sign: root(j,b)² = (ζ²)^j regardless of b
  have hsq : (R12J.root (zeta (k + 2)) jb) ^ 2 = ((zeta (k + 2)) ^ 2) ^ (jb.1 : ℕ) := by
    simp only [R12J.root]
    cases hb : jb.2 with
    | false =>
      simp only [Bool.false_eq_true, if_false]
      rw [← pow_mul, ← pow_mul, mul_comm]
    | true =>
      simp only [if_true]
      rw [neg_sq, ← pow_mul, ← pow_mul, mul_comm]
  rw [hsq]
  simp only [sqIndex, R12J.root]
  by_cases h : (jb.1 : ℕ) < 2 ^ k
  · simp [h]
  · simp only [h, dif_neg, if_true, not_false_iff]
    -- (ζ²)^j = -(ζ²)^{j - 2^k}  via (ζ²)^{2^k} = -1 and j = (j-2^k)+2^k
    have hj : (jb.1 : ℕ) = ((jb.1 : ℕ) - 2 ^ k) + 2 ^ k := by omega
    conv_lhs => rw [hj]
    rw [pow_add, hg2]; ring

/-- The level-`G` "lift" of a `G₂`-index `(j',b')`: the unique `j < 2N` with
`(ζ²)^j` equal to the level-`G₂` root, namely `j' ` if `b'=false` and
`j' + 2^k` if `b'=true`.  `sqIndex` collapses the bool-pair at this `j` to
`(j',b')`. -/
def liftIndexVal (k : ℕ) (y : Fin (2 ^ k) × Bool) : ℕ :=
  if y.2 then (y.1 : ℕ) + 2 ^ k else (y.1 : ℕ)

theorem liftIndexVal_lt (k : ℕ) (y : Fin (2 ^ k) × Bool) :
    liftIndexVal k y < 2 ^ (k + 1) := by
  have hy := y.1.2
  have hpow : (2 : ℕ) ^ k + 2 ^ k = 2 ^ (k + 1) := by ring
  unfold liftIndexVal
  cases hb : y.2 with
  | false => simp only [Bool.false_eq_true, if_false]; omega
  | true => simp only [if_true]; omega

/-- The level-`G` "lift" of a `G₂`-index `(j',b')`: the unique `j < 2N` whose
square at level `G₂` is the `(j',b')` root.  `j' ` if `b'=false`, `j' + 2^k`
if `b'=true`.  `sqIndex` collapses the bool-pair at this `j` to `(j',b')`. -/
def liftIndex (k : ℕ) (y : Fin (2 ^ k) × Bool) : Fin (2 ^ (k + 1)) :=
  ⟨liftIndexVal k y, liftIndexVal_lt k y⟩

/-- **Characterization of `sqIndex` fibers.** `sqIndex k a = y` iff
`a.1 = (liftIndex k y).1` (the first coordinate is forced; the bool is free).
So the preimage of `y` is exactly the antipodal bool-pair at `liftIndex k y`. -/
theorem sqIndex_eq_iff (k : ℕ) (a : Fin (2 ^ (k + 1)) × Bool)
    (y : Fin (2 ^ k) × Bool) :
    sqIndex k a = y ↔ (a.1 : ℕ) = (liftIndex k y : ℕ) := by
  obtain ⟨⟨ya, hya⟩, yb⟩ := y
  simp only [sqIndex, liftIndex, liftIndexVal]
  by_cases h : (a.1 : ℕ) < 2 ^ k
  · simp only [h, dif_pos, Prod.mk.injEq, Fin.mk.injEq]
    cases yb with
    | false => simp only [Bool.false_eq_true, if_false, and_true]
    | true =>
      simp only [if_true, reduceCtorEq, and_false, false_iff]
      omega
  · simp only [h, dif_neg, not_false_iff, Prod.mk.injEq, Fin.mk.injEq]
    cases yb with
    | false =>
      simp only [Bool.false_eq_true, if_false, reduceCtorEq, and_false, false_iff]
      omega
    | true =>
      simp only [if_true, and_true]
      omega

/-! ### The main unconditional theorem. -/

/-- **UNCONDITIONAL JOINT t = 2 FIBER TIGHTNESS over ℚ.**

For every `m = k+2 ≥ 2` (so `N = 2^{k+1} ≥ 2`, the first genuinely two-level
case onward), with `ζ = exp(2πI/2^m)`: let `A ⊆ Fin (2^{k+1}) × Bool` model a
subset of the `2N = 2^{k+2}`-th roots (antipodally paired).  If

    t = 1 :  `∑_{x∈A} x   = 0`     (`∑ root ζ a = 0`)
    t = 2 :  `∑_{x∈A} x²  = 0`     (`∑ (root ζ a)² = 0`)

then BOTH levels are antipodal:

  (1) `A` is antipodal at level `G`:  `(j,false) ∈ A ↔ (j,true) ∈ A`;
  (2) the SQUARE-image `A.image (sqIndex k)` is antipodal at level `G₂`:
      `(j',false) ∈ image ↔ (j',true) ∈ image`.

Conclusion (1)∧(2) is exactly "`A` is a union of order-4 `⟨i⟩`-orbits", the
EXACT `(e₁,e₂)=(0,0)` Lam–Leung fiber — UNCONDITIONALLY over ℚ.  Both
cyclotomic-independence inputs are discharged by `linearIndependent_powers_zeta`
(A1) and `linearIndependent_powers_zeta_sq` (A2). -/
theorem joint_t2_unconditional (k : ℕ)
    (A : Finset (Fin (2 ^ (k + 1)) × Bool))
    (ht1 : ∑ a ∈ A, R12J.root (zeta (k + 2)) a = 0)
    (ht2 : ∑ a ∈ A, (R12J.root (zeta (k + 2)) a) ^ 2 = 0) :
    (∀ j : Fin (2 ^ (k + 1)), ((j, false) ∈ A ↔ (j, true) ∈ A)) ∧
    (∀ j' : Fin (2 ^ k),
        ((j', false) ∈ A.image (sqIndex k) ↔ (j', true) ∈ A.image (sqIndex k))) := by
  classical
  -- (1) Level-G antipodality from t = 1, via A1.
  have hA1 := R12J.antipodal_of_sum_zero (K := ℚ) (zeta (k + 2))
    (linearIndependent_powers_zeta k) A ht1
  refine ⟨hA1, ?_⟩
  -- (2) Transport t = 2 to a vanishing sum over the squared image at level G₂.
  set g2 : ℂ := (zeta (k + 2)) ^ 2 with hg2def
  set B : Finset (Fin (2 ^ k) × Bool) := A.image (sqIndex k) with hB
  -- (2a)  ∑_{a∈A} (root a)² = ∑_{a∈A} root g2 (sqIndex a)  (the squaring bridge).
  have hsq_pt : ∀ a ∈ A,
      (R12J.root (zeta (k + 2)) a) ^ 2
        = R12J.root g2 (sqIndex k a) := fun a _ => sq_root_bridge k a
  have ht2' : ∑ a ∈ A, R12J.root g2 (sqIndex k a) = 0 := by
    rw [← Finset.sum_congr rfl hsq_pt]; exact ht2
  -- (2b)  sqIndex maps A into B, so we may fiber the sum over B.
  have hmaps : ∀ a ∈ A, sqIndex k a ∈ B := fun a ha =>
    Finset.mem_image_of_mem _ ha
  have hfiber : ∑ y ∈ B, ∑ a ∈ A with sqIndex k a = y, R12J.root g2 y
      = ∑ a ∈ A, R12J.root g2 (sqIndex k a) :=
    Finset.sum_fiberwise_of_maps_to' hmaps _
  -- (2c)  Every fiber over `y ∈ B` has EXACTLY two elements (the antipodal
  --       bool-pair at `liftIndex k y`), because `A` is antipodal (hA1).
  have hcard2 : ∀ y ∈ B, (A.filter (fun a => sqIndex k a = y)).card = 2 := by
    intro y hy
    -- the preimage of `y` is contained in the bool-pair at ℓ := liftIndex k y
    set ℓ : Fin (2 ^ (k + 1)) := liftIndex k y with hℓ
    have hpre : (A.filter (fun a => sqIndex k a = y))
        = A.filter (fun a => a.1 = ℓ) := by
      apply Finset.filter_congr
      intro a _
      rw [sqIndex_eq_iff]
      constructor
      · intro h; exact Fin.ext h
      · intro h; rw [h]
    -- A ∩ {a : a.1 = ℓ} = {(ℓ,false),(ℓ,true)} ∩ A, and by antipodality both
    -- are in A (since `y ∈ B` ⟹ at least one is, and hA1 forces the other).
    rw [hpre]
    -- Membership of the two bool-versions of ℓ.
    obtain ⟨a₀, ha₀A, ha₀y⟩ := Finset.mem_image.1 hy
    have ha₀ℓ : a₀.1 = ℓ := Fin.ext ((sqIndex_eq_iff k a₀ y).1 ha₀y)
    -- both (ℓ,false) and (ℓ,true) ∈ A
    have hmemF : (ℓ, false) ∈ A := by
      cases ha₀b : a₀.2 with
      | false => rwa [show a₀ = (ℓ, false) by cases a₀; simp_all] at ha₀A
      | true =>
        have : a₀ = (ℓ, true) := by cases a₀; simp_all
        rw [this] at ha₀A
        exact (hA1 ℓ).2 ha₀A
    have hmemT : (ℓ, true) ∈ A := (hA1 ℓ).1 hmemF
    -- the filtered set is exactly {(ℓ,false),(ℓ,true)}
    have hset : A.filter (fun a => a.1 = ℓ) = {(ℓ, false), (ℓ, true)} := by
      apply Finset.ext
      intro a
      simp only [Finset.mem_filter, Finset.mem_insert, Finset.mem_singleton]
      constructor
      · rintro ⟨_, ha1⟩
        cases a with
        | mk a1 a2 => cases a2 <;> simp_all
      · rintro (rfl | rfl)
        · exact ⟨hmemF, rfl⟩
        · exact ⟨hmemT, rfl⟩
    rw [hset]
    rw [Finset.card_insert_of_notMem (by simp), Finset.card_singleton]
  -- (2d)  Hence ∑_{a∈A} root g2 (sqIndex a) = 2 • ∑_{y∈B} root g2 y.
  have htwo : ∑ a ∈ A, R12J.root g2 (sqIndex k a)
      = (2 : ℚ) • ∑ y ∈ B, R12J.root g2 y := by
    rw [← hfiber, Finset.smul_sum]
    apply Finset.sum_congr rfl
    intro y hy
    rw [Finset.sum_const]
    rw [show (A.filter (fun a => sqIndex k a = y)).card = 2 from hcard2 y hy]
    rw [← Nat.cast_smul_eq_nsmul ℚ]
    norm_num
  -- (2e)  So 2 • ∑_{y∈B} root g2 y = 0, hence ∑_{y∈B} root g2 y = 0.
  have hBsum : ∑ y ∈ B, R12J.root g2 y = 0 := by
    have : (2 : ℚ) • ∑ y ∈ B, R12J.root g2 y = 0 := by rw [← htwo, ht2']
    have h2 : (2 : ℚ) ≠ 0 := by norm_num
    exact (smul_eq_zero.1 this).resolve_left h2
  -- (2f)  Apply the level-G₂ antipodal engine (A2) to B.
  exact R12J.antipodal_of_sum_zero (K := ℚ) g2
    (linearIndependent_powers_zeta_sq k) B hBsum

end R12J.General

/-! ## Part 4.  Concrete non-vacuity: `m = 2` (`k = 0`), the 4-th roots
`{1, i, -1, -i}`.

`k = 0`: level `G` has `N = 2^1 = 2`, `2N = 4` (the 4-th roots of unity, the
order-4 group `⟨i⟩`).  We exhibit the FULL order-4 orbit `{1,i,-1,-i}` (the
universe) as a CONCRETE inhabitant of the `(e₁,e₂)=(0,0)` fiber: it satisfies
BOTH t=1 and t=2.  And a non-fiber set (the singleton `{1}`) violates t=1, so
the characterization is a genuine restriction. -/

namespace R12J.Concrete

open Complex R12J R12J.General

/-- `ζ = zeta 2 = exp(2πI/4) = i`.  `ζ^4 = 1` (it is a 4-th root of unity). -/
theorem zeta2_pow4 : (zeta 2) ^ (2 ^ 2) = 1 := (isPrimitiveRoot_zeta 2).pow_eq_one

/-- `ζ^2 = -1` (the antipodal pairing at level `G`, `k=0`). -/
theorem zeta2_sq_eq_neg_one : (zeta 2) ^ (2 ^ 1) = -1 := zeta_pow_N_eq_neg_one 0

/-- **t = 1 for the full order-4 orbit `{1,i,-1,-i}` (the universe).**
`1 + i + (-1) + (-i) = 0`.  The orbit is antipodal (contains every pair), so
`∑ root = 0`. -/
theorem orbit_t1_zero :
    ∑ a ∈ (Finset.univ : Finset (Fin (2 ^ 1) × Bool)), R12J.root (zeta 2) a = 0 := by
  rw [Fintype.sum_prod_type]
  simp only [Fintype.sum_bool, R12J.root, Bool.false_eq_true, if_false, if_true]
  simp

/-- **t = 2 for the full order-4 orbit.**  The squares are `{1, -1, 1, -1}`
(i.e. `1² + i² + (-1)² + (-i)² = 1 + (-1) + 1 + (-1) = 0`).  This certifies
`{1,i,-1,-i}` IS a genuine inhabitant of the `(e₁,e₂)=(0,0)` fiber. -/
theorem orbit_t2_zero :
    ∑ a ∈ (Finset.univ : Finset (Fin (2 ^ 1) × Bool)),
      (R12J.root (zeta 2) a) ^ 2 = 0 := by
  rw [Fintype.sum_prod_type]
  simp only [Fintype.sum_bool, R12J.root, Bool.false_eq_true, if_false, if_true]
  have hsq : (zeta 2) ^ (2 : ℕ) = -1 := by simpa using zeta_pow_N_eq_neg_one 0
  -- ∑_{j<2} ((ζ^j)² + (-ζ^j)²) = 2∑_{j<2} ζ^{2j} = 2(ζ^0 + ζ^2) = 2(1 + (-1)) = 0
  rw [show (2 ^ 1 : ℕ) = 2 from rfl] at *
  rw [Fin.sum_univ_two]
  simp only [Fin.isValue, Fin.val_zero, Fin.val_one, pow_zero, pow_one]
  -- (1² + (-1)²) + (ζ² + (-ζ)²) = (1+1) + (ζ²+ζ²) = 2 + 2ζ² = 2 + 2(-1) = 0
  have hz : (zeta 2) ^ 2 = -1 := hsq
  ring_nf
  rw [hz]; ring

/-- **The full order-4 orbit IS in the fiber** — the UNCONDITIONAL conclusion
fires on a concrete non-trivial witness (`k = 0`, `m = 2`).  Both antipodal
characterizations hold for the universe. -/
theorem orbit_in_fiber :
    (∀ j : Fin (2 ^ 1),
        ((j, false) ∈ (Finset.univ : Finset (Fin (2 ^ 1) × Bool))
          ↔ (j, true) ∈ (Finset.univ : Finset (Fin (2 ^ 1) × Bool)))) ∧
    (∀ j' : Fin (2 ^ 0),
        ((j', false) ∈ (Finset.univ : Finset (Fin (2 ^ 1) × Bool)).image (sqIndex 0)
          ↔ (j', true) ∈ (Finset.univ : Finset (Fin (2 ^ 1) × Bool)).image (sqIndex 0))) :=
  joint_t2_unconditional 0 Finset.univ orbit_t1_zero orbit_t2_zero

/-- **Non-vacuity, the genuine restriction.** The NON-fiber singleton `{(1,false)}`
— the single root `ζ = i` — has NONZERO t=1 sum, so it is NOT forced to be
antipodal: the fiber characterization is a real constraint, not vacuously true
for all `A`. -/
theorem singleton_t1_ne_zero :
    ∑ a ∈ ({(1, false)} : Finset (Fin 2 × Bool)),
      R12J.root (zeta 2) a ≠ 0 := by
  rw [Finset.sum_singleton]
  simp only [R12J.root, Bool.false_eq_true, if_false, Fin.val_one, pow_one]
  have hne : (zeta 2) ^ (2 ^ 2) = 1 := (isPrimitiveRoot_zeta 2).pow_eq_one
  intro h0
  rw [h0] at hne
  simp at hne

end R12J.Concrete

-- Axiom audit: confirm only [propext, Classical.choice, Quot.sound].
#print axioms R12J.linearIndependent_pow_le
#print axioms R12J.antipodal_of_sum_zero
#print axioms R12J.General.natDegree_minpoly_of_primitive
#print axioms R12J.General.linearIndependent_powers_zeta
#print axioms R12J.General.linearIndependent_powers_zeta_sq
#print axioms R12J.General.zeta_pow_N_eq_neg_one
#print axioms R12J.General.zeta_sq_pow_eq_neg_one
#print axioms R12J.General.sq_root_bridge
#print axioms R12J.General.sqIndex_eq_iff
#print axioms R12J.General.joint_t2_unconditional
#print axioms R12J.Concrete.orbit_t1_zero
#print axioms R12J.Concrete.orbit_t2_zero
#print axioms R12J.Concrete.orbit_in_fiber
#print axioms R12J.Concrete.singleton_t1_ne_zero
