/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import ArkLib.Data.CodingTheory.ProximityGap.GranularityLadderRS

/-!
# The first exact `δ*` pin at the LITERAL challenge error `ε* = 2⁻¹²⁸` (#357, round 2)

Every exact MCA-threshold pin landed so far evaluates `mcaDeltaStar` at a *toy*
threshold (`ε* ≈ j/q` with `q ≤ 17`).  The Proximity Prize fixes the challenge error
at the literal `ε* = 2⁻¹²⁸`.  This file produces the first exact `δ*` value at that
literal budget: for **any** Reed–Solomon code over a field of size
`q ∈ (2¹²⁸, 2¹²⁹)` — e.g. a 129-bit prime field — with `k + 2 ≤ n`,

  `mcaDeltaStar (RS[F, dom, k]) 2⁻¹²⁸ = 1/n`        (`mcaDeltaStar_eq_inv_n`).

**Why this is the decisive staircase-rung test (round-1 synthesis, #357).**  The
surviving hypothesis after the H1/H2/H3 refutations is the staircase law

  `δ*(RS[F_q, L, k], ε*) = max {e/n : Λ(n, k, e) ≤ ε*·q}`,

where `Λ(n,k,e)` is the worst-case bad-scalar count at error level `e`.  For
`q ∈ (2¹²⁸, 2¹²⁹)` the budget is `ε*·q ∈ (1, 2)`, so the law predicts `δ* = 1/n`
exactly iff its two lowest rungs hold *at the literal budget*:

* `Λ(0) = 1` — below the granularity radius at most one scalar is bad (the
  forced-`univ` uniqueness collapse), so `ε_mca ≤ 1/q ≤ 2⁻¹²⁸`: every `δ < 1/n` is
  **good**;
* `Λ(1) = 2` — at `δ = 1/n` a two-bad-scalar spike stack exists whenever the
  punctured code still has positive distance (`k + 2 ≤ n`), so
  `ε_mca ≥ 2/q > 2⁻¹²⁸`: every `δ ≥ 1/n` is **bad**.

Both rungs are delivered by the in-tree granularity ladder
(`mcaDeltaStar_rs_eq_granularity`, `GranularityLadderRS.lean`) on its `j = 1` band,
whose window `ε* ∈ [1/q, 2/q)` contains `2⁻¹²⁸` exactly when `2¹²⁸ ≤ q < 2¹²⁹` —
that is the entire content of the two field-size hypotheses below.  The brackets
meet through the ledger engine (`le_mcaDeltaStar_of_good` / `mcaDeltaStar_le_of_bad`
inside `mcaDeltaStar_eq_of_good_below_of_bad_above`), so the staircase law's rungs
`Λ(0) = 1` and `Λ(1) = 2` are now machine-checked at the literal challenge error.

Instantiations:

* `mcaDeltaStar_zmod_eq_inv_n` — prime fields `ZMod p`, `2¹²⁸ < p < 2¹²⁹` (the prime
  is abstract with the two bounds as hypotheses, the repo convention for exact pins —
  Bertrand/PNT guarantee such primes exist in abundance);
* `mcaDeltaStar_smooth_eq_inv_n` — **smooth domains**: the evaluation domain is the
  cyclic 2-power group `⟨g⟩` of order `n = 2^μ` generated by a unit `g` of order
  `2^μ` (the prize's domain shape), any `k + 2 ≤ 2^μ`;
* `mcaDeltaStar_production_shape_eq_inv_n` — production scale: `n = 2²⁵`, `k = 2²⁴`
  (rate `1/2`), i.e. the first exact `δ*` at simultaneously production-relevant
  `n`, rate, *and* the literal `ε*`.

**Honest scope.**  At this field size the literal budget `ε*·q < 2` keeps `δ*` at
the bottom rung `1/n` — far below the prize window `(1−√ρ, 1−ρ)`.  The pin therefore
does **not** touch the open core (production parameterization has `q ≥ n²·2¹²⁸`,
budget `≥ n²`, where `Λ`'s growth through the window is exactly the open problem);
what it does is verify the staircase law's base case at the literal `ε*` and refute
"`δ*` is a function of the rate `ρ` alone" at the literal budget (here `δ* = 1/n → 0`
at rate `1/2`, while `JohnsonTightnessRefuted` gives `δ* ≥ 1/2` at the same rate for
`q ≥ 70·2¹²⁸`).

All results are `sorry`-free and axiom-clean (`[propext, Classical.choice, Quot.sound]`).

## References
- Issue #357 (the δ* campaign; round-1 synthesis comment, hypothesis H4 "staircase").
- `GranularityLadderRS.lean` (the ladder closed form), `MCAThresholdLedger.lean`
  (the bracket engine), `UniversalStaircaseCollapse.lean` (good side),
  `UniversalSpikeFloor.lean` (bad side).
-/

set_option autoImplicit false
set_option linter.unusedSectionVars false

open Finset Polynomial
open scoped NNReal ENNReal

namespace ProximityGap.MCADeltaStarLiteralEps

open ProximityGap.SpikeFloor

/-! ## The band arithmetic: `2⁻¹²⁸` sits in the `j = 1` window `[1/q, 2/q)` iff
`2¹²⁸ ≤ q < 2¹²⁹` -/

/-- Lower band edge: `1/q ≤ 2⁻¹²⁸` whenever `2¹²⁸ < q`. -/
theorem band_lo {q : ℕ} (hqlo : 2 ^ 128 < q) :
    ((1 : ℕ) : ℝ≥0∞) / (q : ℝ≥0∞) ≤ 1 / 2 ^ 128 := by
  rw [Nat.cast_one]
  exact ENNReal.div_le_div le_rfl (by exact_mod_cast hqlo.le)

/-- Upper band edge: `2⁻¹²⁸ < 2/q` whenever `q < 2¹²⁹`. -/
theorem band_hi {q : ℕ} (hqhi : q < 2 ^ 129) :
    (1 / 2 ^ 128 : ℝ≥0∞) < ((1 + 1 : ℕ) : ℝ≥0∞) / (q : ℝ≥0∞) := by
  have h2 : ((1 + 1 : ℕ) : ℝ≥0∞) = 2 := by norm_num
  have key : (1 : ℝ≥0∞) / 2 ^ 128 = 2 / 2 ^ 129 := by
    rw [ENNReal.div_eq_div_iff (by norm_num) (by norm_num) (by norm_num) (by norm_num)]
    ring
  rw [h2, key]
  exact ENNReal.div_lt_div_left (by norm_num) (by norm_num) (by exact_mod_cast hqhi)

/-! ## The pin, parametrized: any field, any injective domain, any `k + 2 ≤ n` -/

section General

variable {F : Type} [Field F] [Fintype F] [DecidableEq F]
variable {n : ℕ} [NeZero n]

open Classical in
/-- **The first exact `δ*` pin at the literal challenge error `ε* = 2⁻¹²⁸`.**
For any Reed–Solomon code `RS[F, dom, k]` (any field with `2¹²⁸ < |F| < 2¹²⁹`, any
injective evaluation domain of size `n`, any dimension `k` with `k + 2 ≤ n`):

  `mcaDeltaStar (RS[F, dom, k]) 2⁻¹²⁸ = 1/n`.

Good side (`Λ(0) = 1`): every `δ < 1/n` has `ε_mca ≤ 1/|F| ≤ 2⁻¹²⁸`.  Bad side
(`Λ(1) = 2`): at `δ = 1/n` the two-bad-scalar spike forces `ε_mca ≥ 2/|F| > 2⁻¹²⁸`.
This is the `j = 1` band of the granularity ladder, whose window `[1/|F|, 2/|F|)`
contains `2⁻¹²⁸` exactly because `2¹²⁸ < |F| < 2¹²⁹`. -/
theorem mcaDeltaStar_eq_inv_n (dom : Fin n ↪ F) {k : ℕ} (hkn : k + 2 ≤ n)
    (hqlo : 2 ^ 128 < Fintype.card F) (hqhi : Fintype.card F < 2 ^ 129) :
    MCAThresholdLedger.mcaDeltaStar (F := F) (A := F)
        ((rsCode dom k : Submodule F (Fin n → F)) : Set (Fin n → F))
        (1 / 2 ^ 128 : ℝ≥0∞)
      = 1 / (n : ℝ≥0) := by
  have hjF : 1 + 1 ≤ Fintype.card F :=
    le_trans (by norm_num : 1 + 1 ≤ 2 ^ 128) hqlo.le
  have h := mcaDeltaStar_rs_eq_granularity dom (k := k) (j := 1) le_rfl
    (by omega) (by omega) hjF (band_lo hqlo) (band_hi hqhi)
  rwa [Fintype.card_fin, Nat.cast_one] at h

end General

/-! ## Prime fields: an abstract 129-bit prime -/

section Prime

variable (p : ℕ) [Fact (Nat.Prime p)]

open Classical in
/-- The literal-`ε*` pin over a prime field: any prime `2¹²⁸ < p < 2¹²⁹` (such primes
exist in abundance by Bertrand's postulate; the prime stays abstract with the two
bounds as hypotheses, the repo convention for exact pins), any injective domain of
size `n`, any `k + 2 ≤ n`:

  `mcaDeltaStar (RS[F_p, dom, k]) 2⁻¹²⁸ = 1/n`. -/
theorem mcaDeltaStar_zmod_eq_inv_n (hplo : 2 ^ 128 < p) (hphi : p < 2 ^ 129)
    {n : ℕ} [NeZero n] (dom : Fin n ↪ ZMod p) {k : ℕ} (hkn : k + 2 ≤ n) :
    MCAThresholdLedger.mcaDeltaStar (F := ZMod p) (A := ZMod p)
        ((rsCode dom k : Submodule (ZMod p) (Fin n → ZMod p)) : Set (Fin n → ZMod p))
        (1 / 2 ^ 128 : ℝ≥0∞)
      = 1 / (n : ℝ≥0) := by
  refine mcaDeltaStar_eq_inv_n dom hkn ?_ ?_ <;> rw [ZMod.card] <;> assumption

/-! ## Smooth domains: the cyclic 2-power evaluation group `⟨g⟩` -/

/-- The smooth evaluation domain of the prize's shape: the cyclic 2-power group
`⟨g⟩ ≤ F_pˣ` of order `n = 2^μ`, enumerated as successive powers of the generator. -/
def smoothDom {μ : ℕ} (g : (ZMod p)ˣ) (hg : orderOf g = 2 ^ μ) :
    Fin (2 ^ μ) ↪ ZMod p where
  toFun i := ((g ^ (i : ℕ) : (ZMod p)ˣ) : ZMod p)
  inj' := by
    intro i j hij
    have hunit : (g ^ (i : ℕ) : (ZMod p)ˣ) = g ^ (j : ℕ) := Units.ext hij
    have hi : (i : ℕ) ∈ Set.Iio (orderOf g) := by rw [hg]; exact i.isLt
    have hj : (j : ℕ) ∈ Set.Iio (orderOf g) := by rw [hg]; exact j.isLt
    exact Fin.ext (pow_injOn_Iio_orderOf hi hj hunit)

/-- The smooth domain really is `i ↦ g^i`. -/
theorem smoothDom_apply {μ : ℕ} (g : (ZMod p)ˣ) (hg : orderOf g = 2 ^ μ)
    (i : Fin (2 ^ μ)) : smoothDom p g hg i = ((g : ZMod p) ^ (i : ℕ)) := by
  simp [smoothDom]

open Classical in
/-- **The literal-`ε*` pin for smooth-domain Reed–Solomon** — the prize's code shape:
prime field `2¹²⁸ < p < 2¹²⁹`, evaluation domain the cyclic 2-power group `⟨g⟩` of
order `n = 2^μ` (a smooth domain), any dimension `k + 2 ≤ 2^μ`:

  `mcaDeltaStar (RS[F_p, ⟨g⟩, k]) 2⁻¹²⁸ = 1/2^μ`. -/
theorem mcaDeltaStar_smooth_eq_inv_n (hplo : 2 ^ 128 < p) (hphi : p < 2 ^ 129)
    {μ : ℕ} (g : (ZMod p)ˣ) (hg : orderOf g = 2 ^ μ) {k : ℕ} (hkn : k + 2 ≤ 2 ^ μ) :
    MCAThresholdLedger.mcaDeltaStar (F := ZMod p) (A := ZMod p)
        ((rsCode (smoothDom p g hg) k :
            Submodule (ZMod p) (Fin (2 ^ μ) → ZMod p)) : Set (Fin (2 ^ μ) → ZMod p))
        (1 / 2 ^ 128 : ℝ≥0∞)
      = 1 / ((2 ^ μ : ℕ) : ℝ≥0) := by
  haveI : NeZero (2 ^ μ) := ⟨pow_ne_zero μ (by norm_num)⟩
  exact mcaDeltaStar_zmod_eq_inv_n p hplo hphi (smoothDom p g hg) hkn

open Classical in
/-- **Production shape at the literal budget:** `n = 2²⁵`, `k = 2²⁴` (rate `1/2`,
the production rate), smooth domain `⟨g⟩` of order `2²⁵`, prime `2¹²⁸ < p < 2¹²⁹`:

  `mcaDeltaStar (RS[F_p, ⟨g⟩, 2²⁴]) 2⁻¹²⁸ = 2⁻²⁵`.

The first exact MCA threshold at simultaneously production-relevant block length,
rate, and the literal challenge error.  (At this field size the budget `ε*·p < 2`
pins `δ*` to the bottom staircase rung; the prize window needs `p ≥ n²·2¹²⁸`.) -/
theorem mcaDeltaStar_production_shape_eq_inv_n (hplo : 2 ^ 128 < p)
    (hphi : p < 2 ^ 129) (g : (ZMod p)ˣ) (hg : orderOf g = 2 ^ 25) :
    MCAThresholdLedger.mcaDeltaStar (F := ZMod p) (A := ZMod p)
        ((rsCode (smoothDom p g hg) (2 ^ 24) :
            Submodule (ZMod p) (Fin (2 ^ 25) → ZMod p)) : Set (Fin (2 ^ 25) → ZMod p))
        (1 / 2 ^ 128 : ℝ≥0∞)
      = 1 / ((2 ^ 25 : ℕ) : ℝ≥0) :=
  mcaDeltaStar_smooth_eq_inv_n p hplo hphi g hg (by norm_num)

end Prime

end ProximityGap.MCADeltaStarLiteralEps

-- Axiom audit (expected: propext, Classical.choice, Quot.sound only)
#print axioms ProximityGap.MCADeltaStarLiteralEps.mcaDeltaStar_eq_inv_n
#print axioms ProximityGap.MCADeltaStarLiteralEps.mcaDeltaStar_zmod_eq_inv_n
#print axioms ProximityGap.MCADeltaStarLiteralEps.mcaDeltaStar_smooth_eq_inv_n
#print axioms ProximityGap.MCADeltaStarLiteralEps.mcaDeltaStar_production_shape_eq_inv_n
