/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import ArkLib.Data.CodingTheory.ProximityGap.WBPencilWindowLaw
import ArkLib.Data.CodingTheory.ProximityGap.WBPencilLinearBudget

/-!
# The window capstone: the below-UDR law from the unanchored residual (#371)

The honest factorization after the falsification round
(`probe_wb_window_corank2.py`, `probe_wb_window_anchor_existential.py`,
`probe_wb_window_reduced_anchor.py`):

* `WindowPencilAnchored` is **NOT universal**: class-V stacks (rows that are
  rational-with-exceptions, i.e. every WB representation's denominator vanishes
  somewhere on the domain) generically have pencil corank ≥ 2 for EVERY
  representation pair (103/130 fresh class-V stacks, full WB-space enumeration),
  and common-factor reduction with shrunken caps rescues only part of the class
  (the survivors: shared reduced denominators / post-reduction polynomial rows).
  DISPROOF_LOG carries the record.

* BUT every probed unanchored stack has at most **2** mca-bad scalars (vs the
  incidence-law counts that anchored stacks can reach).  The structural reason
  (the attack route for the residual): below UDR with `gcd(ℓ₀ℓ₁, Z_D) = 1`, two
  `F(γ)`-independent kernel solutions force `Q₁Z₂ = Q₂Z₁` (degree < n) and
  `Z_D ∣ W` for the cross-difference `W` — the kernel is **cyclic**, generated by
  one primitive triple `(g, ρ, c)` with slack in all three degree caps; a bad
  scalar then needs `g(γ,·)` to split over the domain, which is the same
  incidence count run on the primitive curve.

This file names the residual in its corrected, weakest-known form —
`UnanchoredLinear`: doubly-WB-solvable stacks with NO anchored representation
have ≤ `n` bad scalars (probe record: ≤ 2; budget `n` matches the repaired
linear architecture and is robust to the `n = q−1` probe-blindness lesson of
the normalizer-family refutation) — and derives the below-UDR law from it:
`ε_mca(RS, δ) ≤ ((n+1)(w+1)+1)/q` for every `δ ≤ w/n`, hence at production
shape (`q ≥ n²·2¹²⁸`) the δ* floor moves to the unique-decoding radius
`(1−ρ)/2`.  `UnanchoredLinear` is STRICTLY weaker than the repaired
`WindowRationalLinear` (the implication is `unanchoredLinear_of_windowRationalLinear`):
the anchored bulk of the stack space is now carried by the proven window
pencil law, and only the unanchored exceptional class remains conditional.
-/

open Finset Polynomial
open scoped NNReal ENNReal ProbabilityTheory

set_option linter.unusedSectionVars false

namespace ProximityGap.WBPencil

open ProximityGap.SpikeFloor

variable {F : Type} [Field F] [Fintype F] [DecidableEq F]
variable {n : ℕ} [NeZero n]

open Classical in
/-- **The corrected named residual of the below-UDR law.**  Every
doubly-WB-solvable stack with NO anchored representation pair has at most
`n` mca-bad scalars.  Probe record: every unanchored stack found (class V and
its reductions) has ≤ 2 bad scalars; the cyclic-kernel structure of corank-≥2
pencils is the identified proof route.  Strictly weaker than the repaired
all-stacks Prop `WindowRationalLinear`. -/
def UnanchoredLinear (dom : Fin n ↪ F) (k w : ℕ) (δ : ℝ≥0) : Prop :=
  ∀ u₀ u₁ : Fin n → F, WBSolvable dom k w u₀ → WBSolvable dom k w u₁ →
    ¬ WindowPencilAnchored dom k w u₀ u₁ →
    (Finset.univ.filter (fun γ : F => mcaEvent (F := F)
      ((rsCode dom k : Submodule F (Fin n → F)) : Set (Fin n → F)) δ u₀ u₁ γ)).card
      ≤ n

open Classical in
/-- The corrected residual is strictly weaker than the repaired all-stacks
linear Prop: `WindowRationalLinear` discharges it by forgetting the
non-anchoredness hypothesis. -/
theorem unanchoredLinear_of_windowRationalLinear (dom : Fin n ↪ F) {k w : ℕ}
    {δ : ℝ≥0} (h : WindowRationalLinear dom k w δ) :
    UnanchoredLinear dom k w δ :=
  fun u₀ u₁ h₀ h₁ _ => h u₀ u₁ h₀ h₁

open Classical in
/-- **THE BELOW-UDR LAW, residual-corrected form**: under `UnanchoredLinear`
alone, every radius `δ ≤ w/n` below the unique-decoding slack has
`ε_mca(RS, δ) ≤ ((w+1) + n(w+1) + 1)/q` — anchored stacks by the window pencil
law, unanchored stacks by the residual (`w+3` is absorbed by the poly budget). -/
theorem epsMCA_le_below_udr_of_unanchoredLinear (dom : Fin n ↪ F) {k w : ℕ}
    (hk : 1 ≤ k) (hwk : w + k ≤ n) {δ : ℝ≥0}
    (hδn : δ * (Fintype.card (Fin n) : ℝ≥0) ≤ w)
    (hres : UnanchoredLinear dom k w δ) :
    epsMCA (F := F) (A := F)
        ((rsCode dom k : Submodule F (Fin n → F)) : Set (Fin n → F)) δ
      ≤ (((w + 1) + n * (w + 1) + 1 : ℕ) : ℝ≥0∞) / (Fintype.card F : ℝ≥0∞) := by
  have hn1 : 1 ≤ n := Nat.one_le_iff_ne_zero.mpr (NeZero.ne n)
  have hnw : w + 1 ≤ n * (w + 1) := Nat.le_mul_of_pos_left _ (by omega)
  rw [epsMCA]
  refine iSup_le fun u => ?_
  rw [prob_uniform_eq_card_filter_div_card]
  refine ENNReal.div_le_div_right ?_ _
  by_cases h1 : WBSolvable dom k w (u 1)
  · by_cases h0 : WBSolvable dom k w (u 0)
    · by_cases hanch : WindowPencilAnchored dom k w (u 0) (u 1)
      · -- anchored: the window pencil law
        have := badScalars_card_le_of_windowPencilAnchored dom hk hδn hanch
        exact_mod_cast this
      · -- unanchored: the residual
        have := hres (u 0) (u 1) h0 h1 hanch
        have hb : (Finset.univ.filter (fun γ : F => mcaEvent (F := F)
            ((rsCode dom k : Submodule F (Fin n → F)) : Set (Fin n → F)) δ
            (u 0) (u 1) γ)).card ≤ (w + 1) + n * (w + 1) + 1 := by
          have hnn : n ≤ n * (w + 1) := Nat.le_mul_of_pos_right _ (by omega)
          omega
        exact_mod_cast hb
    · -- offset row far: swap + pencil
      have hswap := badScalars_card_swap_le
        (rsCode dom k : Submodule F (Fin n → F)) δ (u 0) (u 1)
      have hfar := badScalars_card_le_of_far_snd dom hk hwk hδn
        (u₀ := u 1) (u₁ := u 0) h0
      have hb : (Finset.univ.filter (fun γ : F => mcaEvent (F := F)
          ((rsCode dom k : Submodule F (Fin n → F)) : Set (Fin n → F)) δ
          (u 0) (u 1) γ)).card ≤ (w + 1) + n * (w + 1) + 1 := by omega
      exact_mod_cast hb
  · -- direction row far: the pencil bound directly
    have hfar := badScalars_card_le_of_far_snd dom hk hwk hδn
      (u₀ := u 0) (u₁ := u 1) h1
    have hb : (Finset.univ.filter (fun γ : F => mcaEvent (F := F)
        ((rsCode dom k : Submodule F (Fin n → F)) : Set (Fin n → F)) δ
        (u 0) (u 1) γ)).card ≤ (w + 1) + n * (w + 1) + 1 := by omega
    exact_mod_cast hb

open Classical in
/-- The threshold form: under the corrected residual, the δ* floor clears every
below-UDR radius whose poly(n) budget fits `ε*` — at production
(`ε* = 2^{−128}`, `q ≥ ((n+1)(w+1)+1)·2^{128}`) the floor is the
unique-decoding radius. -/
theorem le_mcaDeltaStar_below_udr_of_unanchoredLinear (dom : Fin n ↪ F)
    {k w : ℕ} (hk : 1 ≤ k) (hwk : w + k ≤ n) {δ : ℝ≥0} (hδ1 : δ ≤ 1)
    (hδn : δ * (Fintype.card (Fin n) : ℝ≥0) ≤ w)
    (hres : UnanchoredLinear dom k w δ)
    {εstar : ℝ≥0∞}
    (hbudget : (((w + 1) + n * (w + 1) + 1 : ℕ) : ℝ≥0∞) / (Fintype.card F : ℝ≥0∞)
      ≤ εstar) :
    δ ≤ ProximityGap.MCAThresholdLedger.mcaDeltaStar (F := F) (A := F)
        ((rsCode dom k : Submodule F (Fin n → F)) : Set (Fin n → F)) εstar :=
  ProximityGap.MCAThresholdLedger.le_mcaDeltaStar_of_good _ _ hδ1
    (le_trans (epsMCA_le_below_udr_of_unanchoredLinear dom hk hwk hδn hres)
      hbudget)

end ProximityGap.WBPencil

-- Axiom audit (expected: propext, Classical.choice, Quot.sound only)
#print axioms ProximityGap.WBPencil.epsMCA_le_below_udr_of_unanchoredLinear
#print axioms ProximityGap.WBPencil.le_mcaDeltaStar_below_udr_of_unanchoredLinear
