#!/usr/bin/env python3
"""Generate AUDIT_LEDGER.md: a complete inventory of proof debt in ArkLib.

Categories:
  S  - `sorry` / `admit` occurrences (with enclosing declaration)
  N  - `native_decide` occurrences (compiler-trusting shortcut)
  A  - `axiom` declarations
  R  - declarations whose *name* contains Residual / CONJECTURE / Conjecture
       (named hypothesis-laundering surfaces; each needs proving or honest
       documentation as open research)

Usage: python3 scripts/audit_ledger.py   (from repo root; writes AUDIT_LEDGER.md)
"""

import os
import re
import sys
from collections import defaultdict

ROOT = "ArkLib"
OUT = "AUDIT_LEDGER.md"

DECL_RE = re.compile(
    r"^\s*(?:@\[[^\]]*\]\s*)?(?:private |protected |noncomputable |scoped |local )*"
    r"(theorem|lemma|def|abbrev|instance|class|structure|axiom|opaque)\s+([^\s({\[:]+)"
)
SORRY_RE = re.compile(r"(?<![A-Za-z0-9_'])(sorry|admit)(?![A-Za-z0-9_'])")
NATIVE_RE = re.compile(r"(?<![A-Za-z0-9_'])native_decide(?![A-Za-z0-9_'])")
AXIOM_RE = re.compile(r"^\s*(?:noncomputable\s+)?axiom\s+(\S+)")
RESIDUAL_NAME_RE = re.compile(
    r"^\s*(?:@\[[^\]]*\]\s*)?(?:private |protected |noncomputable |scoped |local )*"
    r"(def|theorem|lemma|abbrev|class|structure)\s+"
    r"([^\s({\[:]*(?:Residual|CONJECTURE|Conjecture)[^\s({\[:]*)"
)


def strip_comments(lines):
    """Yield (lineno, code) with line/block comments and docstrings blanked."""
    in_block = 0
    for i, raw in enumerate(lines, 1):
        line = raw
        out = []
        j = 0
        while j < len(line):
            if in_block:
                # Lean block comments NEST: count inner `/-` openers before the next `-/`.
                nxt_open = line.find("/-", j)
                nxt_close = line.find("-/", j)
                if nxt_close == -1 and nxt_open == -1:
                    j = len(line)
                elif nxt_open != -1 and (nxt_close == -1 or nxt_open < nxt_close):
                    in_block += 1
                    j = nxt_open + 2
                else:
                    in_block -= 1
                    j = nxt_close + 2
                continue
            if line.startswith("/-", j):
                in_block += 1
                j += 2
                continue
            if line.startswith("--", j):
                break
            out.append(line[j])
            j += 1
        yield i, "".join(out)


def subsystem(path):
    parts = path.split(os.sep)
    if len(parts) >= 3 and parts[1] in ("ProofSystem", "Data", "OracleReduction"):
        sub = parts[2] if not parts[2].endswith(".lean") else parts[1]
        return f"{parts[1]}/{sub}" if sub != parts[1] else parts[1]
    return parts[1].removesuffix(".lean") if len(parts) > 1 else parts[0]


def main():
    sorries, natives, axioms, residuals = [], [], [], []
    for dirpath, _dirs, files in os.walk(ROOT):
        for fn in sorted(files):
            if not fn.endswith(".lean"):
                continue
            path = os.path.join(dirpath, fn)
            with open(path, encoding="utf-8") as fh:
                raw_lines = fh.readlines()
            current_decl = "?"
            for lineno, code in strip_comments(raw_lines):
                mdecl = DECL_RE.match(code)
                if mdecl:
                    current_decl = mdecl.group(2)
                if SORRY_RE.search(code):
                    sorries.append((path, lineno, current_decl))
                if NATIVE_RE.search(code):
                    natives.append((path, lineno, current_decl))
                max_ = AXIOM_RE.match(code)
                if max_:
                    axioms.append((path, lineno, max_.group(1)))
                mres = RESIDUAL_NAME_RE.match(code)
                if mres:
                    residuals.append((path, lineno, mres.group(2), mres.group(1)))

    by_sub = defaultdict(lambda: defaultdict(list))
    for cat, items in (("S", sorries), ("N", natives), ("A", axioms), ("R", residuals)):
        for it in items:
            by_sub[subsystem(it[0])][cat].append(it)

    with open(OUT, "w", encoding="utf-8") as out:
        out.write("# ArkLib proof-debt ledger (generated by scripts/audit_ledger.py)\n\n")
        out.write(
            "Goal: zero `sorry`/`admit`, zero `axiom`, zero `native_decide`, and every\n"
            "Residual/CONJECTURE-named surface either **proven**, **deleted**, or honestly\n"
            "documented as open research with the paper trail.\n\n"
        )
        out.write("| subsystem | sorry/admit | native_decide | axioms | residual-named |\n")
        out.write("|---|---|---|---|---|\n")
        tot = [0, 0, 0, 0]
        for sub in sorted(by_sub, key=lambda s: -len(by_sub[s]["S"])):
            c = by_sub[sub]
            out.write(
                f"| {sub} | {len(c['S'])} | {len(c['N'])} | {len(c['A'])} | {len(c['R'])} |\n"
            )
            tot[0] += len(c["S"])
            tot[1] += len(c["N"])
            tot[2] += len(c["A"])
            tot[3] += len(c["R"])
        out.write(f"| **TOTAL** | **{tot[0]}** | **{tot[1]}** | **{tot[2]}** | **{tot[3]}** |\n\n")

        for sub in sorted(by_sub):
            c = by_sub[sub]
            out.write(f"\n## {sub}\n\n")
            if c["A"]:
                out.write("### axioms\n")
                for path, ln, name in c["A"]:
                    out.write(f"- `{path}:{ln}` axiom **{name}**\n")
            if c["S"]:
                out.write("### sorry / admit\n")
                for path, ln, decl in c["S"]:
                    out.write(f"- `{path}:{ln}` in `{decl}`\n")
            if c["N"]:
                out.write("### native_decide\n")
                for path, ln, decl in c["N"]:
                    out.write(f"- `{path}:{ln}` in `{decl}`\n")
            if c["R"]:
                out.write("### residual-named declarations\n")
                for path, ln, name, kind in c["R"]:
                    out.write(f"- `{path}:{ln}` {kind} **{name}**\n")

    print(f"wrote {OUT}: sorry={len(sorries)} native={len(natives)} "
          f"axiom={len(axioms)} residual-named={len(residuals)}")


if __name__ == "__main__":
    main()
