/-
Copyright (c) 2024-2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Julian Sutherland, Ilia Vlasov, Aristotle (Harmonic)
-/

import Mathlib.GroupTheory.SpecificGroups.Cyclic
import Mathlib.Algebra.Group.Fin.Basic
import Mathlib.Algebra.Group.TypeTags.Basic
import Mathlib.Algebra.Group.Defs
import Mathlib.Tactic.Cases
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.Field

import ArkLib.Data.Domain.FftDomain.Mem

/-!
# The unit subgroup of an FFT domain

We define `toSubgroup ω`, the subgroup of `Fˣ` generated by the image of an FFT domain `ω`, and
characterize its membership via `mem_subgroup_iff_mem_finset` and `mem_subgroup_iff_mem_domain`.
An `abbrev toSubgroup` specializes the construction to `FftDomain ι F`.
-/

namespace Domain

variable {ι : Type} [Fintype ι] [AddCommGroup ι]
variable {F : Type} [Field F] [DecidableEq F]

namespace FftDomainClass

variable {D : Type} [FunLike D ι F] [FftDomainClass D ι F]
variable {ω : D} {i j : ι}

def toSubgroup (ω : D) : Subgroup Fˣ where
  carrier := Finset.image (CosetFftDomainClass.mkSubgroupUnit ω) Finset.univ
  mul_mem' {a b} ha hb := by {
    simp_all only [Finset.coe_image, Finset.coe_univ, Set.image_univ, Set.mem_range]
    rcases ha, hb with ⟨⟨x, rfl⟩, ⟨y, rfl⟩⟩
    exists (x + y)
    ext
    simp [CosetFftDomainClass.mkSubgroupUnit,
          CosetFftDomainClass.map_add,
          FftDomainClass.generator_eq_one]
  }
  one_mem' := by {
    simp only [Finset.coe_image, CosetFftDomainClass.mkSubgroupUnit]
    exists 0
    aesop
  }
  inv_mem' {x} hx := by {
    simp_all only [Finset.coe_image, Finset.coe_univ, Set.image_univ, Set.mem_range]
    obtain ⟨a, rfl⟩ := hx
    exists (-a)
    aesop (add simp [CosetFftDomainClass.mkSubgroupUnit,
                      CosetFftDomainClass.map_neg, generator_eq_one])
  }

lemma mem_subgroup_iff_mem_finset {x : Fˣ} :
    x ∈ toSubgroup ω ↔ x.val ∈ CosetFftDomainClass.toFinset ω := by
  aesop
    (add simp [toSubgroup, CosetFftDomainClass.toFinset,
                CosetFftDomainClass.mkSubgroupUnit, generator_eq_one])

@[simp]
lemma mem_subgroup_iff_mem_domain {ω : D} {x : Fˣ} :
    x ∈ toSubgroup ω ↔ x.val ∈ ω := by simp [mem_subgroup_iff_mem_finset]

end FftDomainClass

namespace FftDomain

variable {ι : Type} [Fintype ι] [AddCommGroup ι]
variable {F : Type} [Field F] [DecidableEq F]

abbrev toSubgroup (ω : FftDomain ι F) : Subgroup Fˣ := FftDomainClass.toSubgroup ω

end FftDomain

end Domain
