import numpy as np
from itertools import combinations

# Verify the agent's claim (1): genuine ragged residues of monomial-line agreement sets
# over F_p are non-vanishing (sum != 0) and non-antipodal (Mann/Lam-Leung fails).
# And claim (2): ragged excess over coset core ~ 2k-1 (n-independent), saturating Johnson at prize rate.

# Work over C with mu_n = nth roots of unity, agreement set of x^a + gamma x^b vs deg-<k codeword c.
# An agreement set S is "realizable" if there is ONE deg-<k poly c with x^a+gamma x^b = c(x) for x in S.
# Worst-case realizable S: pick a subset T of mu_n, solve for c (deg<k) interpolating x^a+gamma x^b on T
# via least info; the realizable agreement set is all x in mu_n where x^a+gamma x^b == c(x).

def mu(n):
    return np.exp(2j*np.pi*np.arange(n)/n)

def is_coset_union(idx_set, n):
    # idx_set: indices into mu_n. Is it a union of mu_g cosets for some g>1 dividing n?
    S = set(idx_set)
    best_core = set()
    for g in range(2, n+1):
        if n % g: continue
        # cosets of mu_g in mu_n: index sets {j + (n/g)*t mod n : t}? mu_g = {exp(2pi i * (n/g)*s/n)} 
        # actually mu_g generated by exp(2pi i/g) = index n/g. coset of mu_g containing idx j: {(j + (n//g)*t) % n}
        step = n//g
        cosets = []
        seen=set()
        for j in range(n):
            if j in seen: continue
            cs = set((j+step*t)%n for t in range(g))
            seen|=cs
            cosets.append(cs)
        core=set()
        for cs in cosets:
            if cs <= S:
                core |= cs
        if len(core)>len(best_core):
            best_core=core
    return best_core

n_list=[8,16,32]
for n in n_list:
    w = mu(n)
    # genuine direction: d=gcd(a-b,n)>=2, and exclude correlated x^{n/2}=+-1 (b != n/2 etc).
    # We'll enumerate realizable agreement sets and find largest genuinely-ragged ones.
    k_list=[2,3]
    for k in k_list:
        rho=k/n
        johnson = n - int(np.floor(np.sqrt(n*(n-k))))  # min distance-ish; list-johnson agreement ~ sqrt(nk)
        sqrtnk=np.sqrt(n*k)
        maxexcess=0
        worst=None
        # enumerate directions
        for a in range(1,n):
            for b in range(a+1,n):
                d=np.gcd(np.gcd(a-b,n),n)
                if d<2: continue
                if a==n//2 or b==n//2: continue  # exclude correlated
                # choose gamma, then realizable S = {x: x^a+gamma x^b = c(x)} for some deg<k c.
                # To get a *realizable* S of given size: pick subset T (size up to ...), fit c deg<k by
                # Vandermonde on T, then S = all x agreeing. We sample subsets T of size k+? 
                # Try all subsets T of size up to min(n, k+4) is too much; sample.
                rng=np.random.default_rng(0)
                for trial in range(200):
                    gamma = np.exp(2j*np.pi*rng.random())
                    f = w**a + gamma*w**b   # values at all mu_n
                    # pick T = k points to define c (deg<k => k coeffs). 
                    Tsize=k
                    T=sorted(rng.choice(n, size=Tsize, replace=False).tolist())
                    V=np.vander(w[T], k, increasing=True)
                    try:
                        coeffs=np.linalg.solve(V, f[T])
                    except np.linalg.LinAlgError:
                        continue
                    cvals=np.vander(w, k, increasing=True)@coeffs
                    S=[j for j in range(n) if abs(f[j]-cvals[j])<1e-6]
                    if len(S)<=k+1: continue  # need genuinely large
                    core=is_coset_union(S,n)
                    excess=len(S)-len(core)
                    if excess>maxexcess and excess>0 and len(core)<len(S):
                        # check residue ragged & sum
                        R=sorted(set(S)-core)
                        ssum=sum(w[j] for j in R)
                        # antipodal? every elt has its negative in R
                        antip = all(((j+n//2)%n) in set(R) for j in R) and len(R)>0
                        maxexcess=excess
                        worst=(a,b,len(S),len(core),R,abs(ssum),antip)
        print(f"n={n} k={k} rho={rho:.3f} sqrt(nk)={sqrtnk:.2f}  max genuine ragged excess={maxexcess}", "worst=",worst)
